### ISSUE TITLE
[Bug] CPU-ONLY TORCH, NO CUDA, Running Example From Getting Started without CUDA

### ISSUE THREAD

**Issue by DerKevinRiehl** [open-mmlab/mmrotate#1009]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

Windows users.
I installed PyTorch as follows
```
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cpuonly -c pytorch
```

### Reproduces the problem - code sample

python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg

### Reproduces the problem - command or script

mim download mmrotate --config oriented_rcnn_r50_fpn_1x_dota_le90 --dest .
python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg

### Reproduces the problem - error message

(openmmlab) C:\test\mmrotate>python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg
C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
Traceback (most recent call last):
  File "demo/image_demo.py", line 45, in <module>
    main(args)
  File "demo/image_demo.py", line 30, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmdet\apis\inference.py", line 55, in init_detector
    model.to(device)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 673, in to
    return self._apply(convert)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 387, in _apply
    module._apply(fn)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 387, in _apply
    module._apply(fn)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 409, in _apply
    param_applied = fn(param)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\torch\cuda\__init__.py", line 164, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### Additional information

I follow this tutorial
https://mmrotate.readthedocs.io/en/latest/install.html#installation

I install TORCH without CUDA, as I have CPU only!
Is mmrotate working only with CUDA/GPU?
According to your documentation it is based on torch, and torch can be installed without CUDA according to official Torch documentation. ?

I install mmrotate using case a Case a: If you develop and run mmrotate directly, install it from source:

This is my conda list:
```
# packages in environment at C:\Users\kriehl\.conda\envs\openmmlab:
#
# Name                    Version                   Build  Channel
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.15.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2023.12.12           haa95532_0
certifi                   2024.2.2                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cpuonly                   2.0                           0    pytorch
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
e2cnn                     0.2.3                    pypi_0    pypi
fonttools                 4.49.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
idna                      3.6                      pypi_0    pypi
importlib-metadata        7.0.2                    pypi_0    pypi
importlib-resources       6.3.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.4.5                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_0
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.0                h8a3f274_0
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_1
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.8            py38h2bbff1b_0
mkl_random                1.2.4            py38h59b6b97_0
mmcv-full                 1.7.2                    pypi_0    pypi
mmdet                     2.28.2                   pypi_0    pypi
mmrotate                  0.3.4                     dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numpy                     1.24.3           py38h79a8e48_1
numpy-base                1.24.3           py38h8a87ada_1
opencv-python             4.9.0.80                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.13               h2bbff1b_0
openxlab                  0.0.36                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    9.0.0                    pypi_0    pypi
pip                       23.3.1           py38haa95532_0
platformdirs              4.2.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.8.18               h1aa4202_0
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   1.8.0               py3.8_cpu_0  [cpuonly]  pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2023.4                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
regex                     2023.12.25               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
terminaltables            3.1.10                   pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                  py38_cpu  [cpuonly]  pytorch
tqdm                      4.65.2                   pypi_0    pypi
typing_extensions         4.9.0            py38haa95532_1
tzdata                    2024.1                   pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2           py38haa95532_0
xz                        5.4.6                h8cc25b3_0
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0
```

This is my mim list:
```
(openmmlab) C:\test\mmrotate>mim list
Package    Version    Source
---------  ---------  -----------------------------------------
mmcv-full  1.7.2      https://github.com/open-mmlab/mmcv
mmdet      2.28.2     https://github.com/open-mmlab/mmdetection
mmrotate   0.3.4      c:\test\mmrotate
```

**Comment by DerKevinRiehl** [comment]
Btw, after installing mmdet, when trying to verify installation
```
import mmdet
print(mmdet.__version__)
```

I get this error message
```
>>> import mmdet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmdet\__init__.py", line 2, in <module>
    import mmcv
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 7, in <module>
    from .image import *
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\image\__init__.py", line 11, in <module>
    from .photometric import (adjust_brightness, adjust_color, adjust_contrast,
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\image\photometric.py", line 7, in <module>
    from PIL import Image, ImageEnhance
  File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

Therefore I installed pillow exactly at 9.0.0
```
pip install pillow==9.0.0
```

Then it worked. I think that is something you should consider mentioning in your documentation as well.

**Comment by DButkovskyi** [comment]
> Btw, after installing mmdet, when trying to verify installation
> 
> ```
> import mmdet
> print(mmdet.__version__)
> ```
> 
> I get this error message
> 
> ```
> >>> import mmdet
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmdet\__init__.py", line 2, in <module>
>     import mmcv
>   File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 7, in <module>
>     from .image import *
>   File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\image\__init__.py", line 11, in <module>
>     from .photometric import (adjust_brightness, adjust_color, adjust_contrast,
>   File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\mmcv\image\photometric.py", line 7, in <module>
>     from PIL import Image, ImageEnhance
>   File "C:\Users\kriehl\.conda\envs\openmmlab\lib\site-packages\PIL\Image.py", line 100, in <module>
>     from . import _imaging as core
> ImportError: DLL load failed while importing _imaging: The specified module could not be found.
> ```
> 
> Therefore I installed pillow exactly at 9.0.0
> 
> ```
> pip install pillow==9.0.0
> ```
> 
> Then it worked. I think that is something you should consider mentioning in your documentation as well.

Were you able to run with CPU only? I am getting 
AssertionError: Torch not compiled with CUDA enabled

**Comment by DerKevinRiehl** [comment]
No, at the end I was not able.
I found a cluster with GPUs to run it there at my university.
I feel the developers should make this great software available for CPU users as well, as not everyone has access to GPUs.
