### ISSUE TITLE
[Docs] 什么鬼文档？各种版本根本对不上！

### ISSUE THREAD

**Issue by willwang-cv** [open-mmlab/mmrotate#1026]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

![image](https://github.com/open-mmlab/mmrotate/assets/29682883/319e4d73-eba2-4d20-9b4c-ba026dd10a5a)

按照步骤安装，结果：

![image](https://github.com/open-mmlab/mmrotate/assets/29682883/ac2cb820-3029-40cb-b808-657e8f65bd6a)

然后 安装给定的mmdet

tm的：

![image](https://github.com/open-mmlab/mmrotate/assets/29682883/b3bfe7fd-2ffd-4b5f-ab99-2ba6dfafc0c4)

到底用哪个版本啊！！！！？？？

极其混乱

**Comment by Xinyi-Liang** [comment]
请问最后怎么解决的？
