### ISSUE TITLE
[Docs] 太不严谨了！！错误百出！

### ISSUE THREAD

**Issue by willwang-cv** [open-mmlab/mmrotate#1027]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

![image](https://github.com/open-mmlab/mmrotate/assets/29682883/35ea0b8e-9d45-4d6c-97e2-04f537cf0dba)

![image](https://github.com/open-mmlab/mmrotate/assets/29682883/415689c0-7953-4ff9-94f2-993948679f6a)

这么大一个公司 就出这种错误 公司没有测试吗？

**Comment by yangxue0827** [comment]
这个公司无关，MMRotate是由社区自发开发依托openmmlab开源的，主要核心团队就两个人，并且都已博士毕业。开源是需要社区共同努力的，如果发现有错误我们欢迎大家提PR或者提issue。Stay Calm.
