### ISSUE TITLE
[Need Help !!! ] how to get/debug loss with mmrotate

### ISSUE THREAD

**Issue by CrazyBrick** [open-mmlab/mmrotate#1035]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

linux+pytorch1.13.1+cuda116+mmcv1.7.0

### Reproduces the problem - code sample

`test.py`
```
import numpy as np
import torch
import torchvision.transforms as T
from PIL import Image
from mmdet.apis import inference_detector, init_detector

import mmrotate  # noqa: F401
transform = T.Compose([
    T.ToTensor(),
])

# 加载配置文件和模型权重
config_file = "configs/robustRDet/lsk_s_fpn_1x_dota_le90.py"  # 配置文件路径
checkpoint_file = "checkpoints/lsk_s_fpn_1x_dota_le90_20230116-99749191.pth"  # 预训练权重路径

# 初始化模型
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = init_detector(config_file, checkpoint_file, device=device)


image_path = "test_images_set/images/P0841__1024__824___0.png"
image = transform(Image.open(image_path).convert("RGB")).unsqueeze(0).to(device)
targets = [{
    "bboxes": torch.tensor([[451.69, 376.24, 232.91, 223.53, 1.57],
                            [724.04, 935.44, 218.13, 215.91, -0.02],
                            [963.54, 363.27, 240.56, 218.61, 1.56]], dtype=torch.float32, device=device),
    "labels": torch.tensor([0, 0, 0], dtype=torch.int64, device=device)
}]


def compute_loss(model, image, target):
    model.train()

    loss_dict = model(image, targets[0]["bboxes"], targets[0]["labels"])
    """ got error 1:RuntimeError: Boolean value of Tensor with more than one value is ambiguous"""

    # loss_dict = model(image,img_metas,targets[0]["bboxes"],targets[0]["labels"])
    """ got error 2:TypeError: forward() takes from 3 to 4 positional arguments but 5 were given"""

    # loss_dict = model(image,target)
    """ got error 3:TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'"""

    loss_dict = model(image, targets)
    losses = sum(loss for loss in loss_dict.values())
    model.eval()
    return losses

loss = compute_loss(model, image, targets)
print(loss)
```

### Reproduces the problem - command or script

`python test.py`

### Reproduces the problem - error message

```
  loss_dict = model(image, targets[0]["bboxes"], targets[0]["labels"])
    """ got error 1:RuntimeError: Boolean value of Tensor with more than one value is ambiguous"""

    # loss_dict = model(image,img_metas,targets[0]["bboxes"],targets[0]["labels"])
    """ got error 2:TypeError: forward() takes from 3 to 4 positional arguments but 5 were given"""

    # loss_dict = model(image,target)
    """ got error 3:TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'"""
```

### Additional information

Thank you very much for your wonderful work. MMrotate is a useful framework that makes it easy to add or replace commonly used components. However, due to its strong encapsulation, I don't know how to modify it when facing other requirements and where to start debugging.

I have already read most of the intro and custom documents for mmrotate. What additional documents should I read.

Q1.How to simply **calculate the loss** of **a single sample** using a model
Q2. If the loss is replaced and the **dimensions are not aligned**, which module should we start debugging from

Hope to receive a reply as soon as possible. Thank you in advance!

**Comment by CrazyBrick** [comment]
@yangxue0827 @zytx121 sorry to bother you

**Comment by gbdjxgp** [comment]
其实一个比较简单的方法是直接去pycharm开断点调试。网上关于mmrotate的资料其实比较少，建议去搜mmdet的教程，资料比较多，mmrotate和mmdet的流程什么的很像。
Actually, a relatively simple method is to directly go to the breakpoint debugging of PyCharm. There is actually relatively little information about mmrotate online. It is recommended to search for mmdet tutorials, as there are many resources available, The process of mmrotate and mmdet is very similar.

**Comment by CrazyBrick** [comment]
> 其实一个比较简单的方法是直接去pycharm开断点调试。网上关于mmrotate的资料其实比较少，建议去搜mmdet的教程，资料比较多，mmrotate和mmdet的流程什么的很像。 Actually, a relatively simple method is to directly go to the breakpoint debugging of PyCharm. There is actually relatively little information about mmrotate online. It is recommended to search for mmdet tutorials, as there are many resources available, The process of mmrotate and mmdet is very similar.

谢谢回复～其实也确实在用pycharm打断点调试，但是有些地方打上了断点就会卡住跳不出来
比如：`xxx/miniconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py`
```
    def train(self, data_loader, **kwargs):
        self.model.train()
        self.mode = 'train'
        self.data_loader = data_loader
        self._max_iters = self._max_epochs * len(self.data_loader)
        self.call_hook('before_train_epoch')
        time.sleep(2)  # Prevent possible deadlock during epoch transition
        for i, data_batch in enumerate(self.data_loader):
            self.data_batch = data_batch
            print(f"self.data_batch:{self.data_batch}")
            self._inner_iter = i
            self.call_hook('before_train_iter')
            self.run_iter(data_batch, train_mode=True, **kwargs)
            self.call_hook('after_train_iter')
            del self.data_batch
            self._iter += 1

        self.call_hook('after_train_epoch')
        self._epoch += 1
```
如果在`run_iter`和`call_hook('after_train_iter')`这里打，都没办法往下调试，只能打在其他地方，但是偏偏这里面是我想要关注的(也可能是基础库里面的就不能打？) 
后来我在`mmrotate/models/detectors/two_stage.py`文件中找到了forward_train部分，可以print当前损失，但是我的一些改动会使它报错，我目前对hook比较迷惑，不知道该从哪里进到对应的hook函数

**Comment by gbdjxgp** [comment]
> > 其实一个比较简单的方法是直接去pycharm开断点调试。网上关于mmrotate的资料其实比较少，建议去搜mmdet的教程，资料比较多，mmrotate和mmdet的流程什么的很像。 Actually, a relatively simple method is to directly go to the breakpoint debugging of PyCharm. There is actually relatively little information about mmrotate online. It is recommended to search for mmdet tutorials, as there are many resources available, The process of mmrotate and mmdet is very similar.
> 
> 谢谢回复～其实也确实在用pycharm打断点调试，但是有些地方打上了断点就会卡住跳不出来 比如：`xxx/miniconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py`
> 
> ```
>     def train(self, data_loader, **kwargs):
>         self.model.train()
>         self.mode = 'train'
>         self.data_loader = data_loader
>         self._max_iters = self._max_epochs * len(self.data_loader)
>         self.call_hook('before_train_epoch')
>         time.sleep(2)  # Prevent possible deadlock during epoch transition
>         for i, data_batch in enumerate(self.data_loader):
>             self.data_batch = data_batch
>             print(f"self.data_batch:{self.data_batch}")
>             self._inner_iter = i
>             self.call_hook('before_train_iter')
>             self.run_iter(data_batch, train_mode=True, **kwargs)
>             self.call_hook('after_train_iter')
>             del self.data_batch
>             self._iter += 1
> 
>         self.call_hook('after_train_epoch')
>         self._epoch += 1
> ```
> 
> 如果在`run_iter`和`call_hook('after_train_iter')`这里打，都没办法往下调试，只能打在其他地方，但是偏偏这里面是我想要关注的(也可能是基础库里面的就不能打？) 后来我在`mmrotate/models/detectors/two_stage.py`文件中找到了forward_train部分，可以print当前损失，但是我的一些改动会使它报错，我目前对hook比较迷惑，不知道该从哪里进到对应的hook函数

你要改哪一部分的话就直接在相应的的相应部分打断点就行（如改LSKNet主干就去相应的forward打断点、改loss就去loss函数的forward），hook函数同理，比如你自己写了一个hook，那么就直接在对应的hook的入口函数打断点。我目前调试mmrotate基本没有不能断的，只有极小部分pytorch的hook函数需要改动源文件添加两行代码才能进断点，参考（https://stackoverflow.com/questions/34299082/not-working-python-breakpoints-in-c-thread-in-pycharm-or-eclipsepydev）

**Comment by CrazyBrick** [comment]
> > > 其实一个比较简单的方法是直接去pycharm开断点调试。网上关于mmrotate的资料其实比较少，建议去搜mmdet的教程，资料比较多，mmrotate和mmdet的流程什么的很像。 Actually, a relatively simple method is to directly go to the breakpoint debugging of PyCharm. There is actually relatively little information about mmrotate online. It is recommended to search for mmdet tutorials, as there are many resources available, The process of mmrotate and mmdet is very similar.
> > 
> > 
> > 谢谢回复～其实也确实在用pycharm打断点调试，但是有些地方打上了断点就会卡住跳不出来 比如：`xxx/miniconda3/envs/lsknet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py`
> > ```
> >     def train(self, data_loader, **kwargs):
> >         self.model.train()
> >         self.mode = 'train'
> >         self.data_loader = data_loader
> >         self._max_iters = self._max_epochs * len(self.data_loader)
> >         self.call_hook('before_train_epoch')
> >         time.sleep(2)  # Prevent possible deadlock during epoch transition
> >         for i, data_batch in enumerate(self.data_loader):
> >             self.data_batch = data_batch
> >             print(f"self.data_batch:{self.data_batch}")
> >             self._inner_iter = i
> >             self.call_hook('before_train_iter')
> >             self.run_iter(data_batch, train_mode=True, **kwargs)
> >             self.call_hook('after_train_iter')
> >             del self.data_batch
> >             self._iter += 1
> > 
> >         self.call_hook('after_train_epoch')
> >         self._epoch += 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果在`run_iter`和`call_hook('after_train_iter')`这里打，都没办法往下调试，只能打在其他地方，但是偏偏这里面是我想要关注的(也可能是基础库里面的就不能打？) 后来我在`mmrotate/models/detectors/two_stage.py`文件中找到了forward_train部分，可以print当前损失，但是我的一些改动会使它报错，我目前对hook比较迷惑，不知道该从哪里进到对应的hook函数
> 
> 你要改哪一部分的话就直接在相应的的相应部分打断点就行（如改LSKNet主干就去相应的forward打断点、改loss就去loss函数的forward），hook函数同理，比如你自己写了一个hook，那么就直接在对应的hook的入口函数打断点。我目前调试mmrotate基本没有不能断的，只有极小部分pytorch的hook函数需要改动源文件添加两行代码才能进断点，参考（[https://stackoverflow.com/questions/34299082/not-working-python-breakpoints-in-c-thread-in-pycharm-or-eclipsepydev）](https://stackoverflow.com/questions/34299082/not-working-python-breakpoints-in-c-thread-in-pycharm-or-eclipsepydev%EF%BC%89)

抱歉没及时看到回复。我表达的还不够准确，目前我还没有到修改网络结构和损失函数具体实施部分的过程，只是在做一些尝试性工作，比如在里面添加一些扰动，但是确实调试到环境中mmcv包或者mmdet的runner下的hook或者epoch_based_runner文件的时候，某些函数无法跳转，找不到它的定义，在这其中某些地方打了断点调试会无法往下进行，但是以允许状态又可以正常往下执行，我感到很困扰，这方面大佬有什么建议吗

**Comment by gbdjxgp** [comment]
加一下我联系方式吧 qq2060177817 可以约个时间帮你看看

**Comment by CrazyBrick** [comment]
感谢🙏



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 4, 2024 11:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmrotate] [Need Help !!! ] how to get/debug loss withmmrotate (Issue #1035)




 
加一下我联系方式吧 qq2060177817 可以约个时间帮你看看
