### ISSUE TITLE
error about `pip install -v -e .`

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#104]
windows10  cuda 11.3  torch1.10.2 mmdet 2.22.0 mmcv 1.4.5 mmrotate 0.1.0 

PS H:\Adam\mmrotate> pip install -v -e .
Using pip 22.0.4 from D:\Anaconda3\envs\mmrotate\lib\site-packages\pip (python 3.8)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
Obtaining file:///H:/Adam/mmrotate
  Preparing metadata (setup.py) ...   Running command python setup.py egg_info
  running egg_info
  creating C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info
  writing C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\PKG-INFO
  writing dependency_links to C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\dependency_links.txt
  writing requirements to C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\requires.txt
  writing top-level names to C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\top_level.txt
  writing manifest file 'C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\DELL\AppData\Local\Temp\pip-pip-egg-info-j61c3vi1\mmrotate.egg-info\SOURCES.txt'
done
Requirement already satisfied: e2cnn in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (0.2.1)
Requirement already satisfied: matplotlib in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (3.5.1)
Requirement already satisfied: mmcv-full in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (1.4.5)
Requirement already satisfied: mmdet in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (2.22.0)
Requirement already satisfied: numpy in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (1.22.3)
Requirement already satisfied: six in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (1.16.0)
Requirement already satisfied: terminaltables in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (3.1.10)
Requirement already satisfied: torch in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (1.10.2)
Requirement already satisfied: pycocotools-windows in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmrotate==0.1.0) (2.0.0.2)
Requirement already satisfied: sympy in d:\anaconda3\envs\mmrotate\lib\site-packages (from e2cnn->mmrotate==0.1.0) (1.10)
Requirement already satisfied: scipy in d:\anaconda3\envs\mmrotate\lib\site-packages (from e2cnn->mmrotate==0.1.0) (1.8.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (4.30.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (1.3.2)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (21.3)
Requirement already satisfied: pillow>=6.2.0 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (9.0.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (3.0.7)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\envs\mmrotate\lib\site-packages (from matplotlib->mmrotate==0.1.0) (0.11.0)
Requirement already satisfied: yapf in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmcv-full->mmrotate==0.1.0) (0.32.0)
Requirement already satisfied: pyyaml in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmcv-full->mmrotate==0.1.0) (6.0)
Requirement already satisfied: regex in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmcv-full->mmrotate==0.1.0) (2022.3.2)
Requirement already satisfied: addict in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmcv-full->mmrotate==0.1.0) (2.4.0)
Requirement already satisfied: pycocotools in d:\anaconda3\envs\mmrotate\lib\site-packages (from mmdet->mmrotate==0.1.0) (2.0.4)
Requirement already satisfied: cython>=0.27.3 in d:\anaconda3\envs\mmrotate\lib\site-packages (from pycocotools-windows->mmrotate==0.1.0) (0.29.28)
Requirement already satisfied: setuptools>=18.0 in d:\anaconda3\envs\mmrotate\lib\site-packages (from pycocotools-windows->mmrotate==0.1.0) (60.9.3)
Requirement already satisfied: typing_extensions in d:\anaconda3\envs\mmrotate\lib\site-packages (from torch->mmrotate==0.1.0) (4.1.1)
Requirement already satisfied: mpmath>=0.19 in d:\anaconda3\envs\mmrotate\lib\site-packages (from sympy->e2cnn->mmrotate==0.1.0) (1.2.1)
Installing collected packages: mmrotate
  Attempting uninstall: mmrotate
    Found existing installation: mmrotate 0.1.0
    Uninstalling mmrotate-0.1.0:
      Removing file or directory d:\anaconda3\envs\mmrotate\lib\site-packages\mmrotate-0.1.0.dist-info\
      Removing file or directory d:\anaconda3\envs\mmrotate\lib\site-packages\mmrotate\
      Successfully uninstalled mmrotate-0.1.0
  Running setup.py develop for mmrotate
    Running command python setup.py develop
    running develop
    H:\Adam\mmrotate\setup.py:145: UserWarning: Failed to create a symbolic link for ..\..\tools, and it will be copied to H:\Adam\mmrotate\mmrotate\.mim\tools
      warnings.warn(
    D:\Anaconda3\envs\mmrotate\lib\site-packages\setuptools\command\easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other st
andards-based tools.
      warnings.warn(
    error: error in C:\Users\DELL\pydistutils.cfg: command 'develop' has no such option 'timeout'
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: 'D:\Anaconda3\envs\mmrotate\python.exe' -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'H:\\Adam\\mmrotate\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: H:\Adam\mmrotate\
  WARNING: No metadata found in d:\anaconda3\envs\mmrotate\lib\site-packages
  Rolling back uninstall of mmrotate
   from D:\Anaconda3\envs\mmrotate\Lib\site-packages\~mrotate-0.1.0.dist-info
  Moving to d:\anaconda3\envs\mmrotate\lib\site-packages\mmrotate\
   from D:\Anaconda3\envs\mmrotate\Lib\site-packages\~mrotate
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS H:\Adam\mmrotate> pip install -r requirements/build.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: cython in d:\anaconda3\envs\mmrotate\lib\site-packages (from -r requirements/build.txt (line 2)) (0.29.28)
Requirement already satisfied: numpy in d:\anaconda3\envs\mmrotate\lib\site-packages (from -r requirements/build.txt (line 3)) (1.22.3)

**Comment by zytx121** [comment]
Please submit the bug report according to the template.
