### ISSUE TITLE
Questions about updates and loss:nan

### ISSUE THREAD

**Issue by 231055558** [open-mmlab/mmrotate#1043]
### What's the feature?

 I would like to ask whether you continue to promote and maintain mmrotate 1.x, because recently I tried to learn to use 1.x version but encountered many difficulties.
 I am not sure whether it is my equipment problem or the use of mistakes, and whether there is a more suitable component for remote sensing aerial image detection now？
# Some questions
 For example, when I was training, all the models except RTMDet encountered errors with loss of nan or inf, as shown in the following figure.
![Snipaste_2024-07-01_14-11-24](https://github.com/open-mmlab/mmrotate/assets/145833325/ae8dafc7-98ff-4a57-bbf6-4befc71f7e88)
It will appear after a period of time
<img width="1425" alt="image" src="https://github.com/open-mmlab/mmrotate/assets/145833325/1e9b6a8f-d217-4ec4-8178-fcafc6e06a10">
 I tried rotated_fast_rcnn,s2anet,oriented_rcnn, etc. This happened at the beginning of training, but it still failed to recover to the normal value.
I have tried to modify batch_size and other parameters according to the official tips to try to stabilize the loss, but in fact RTMDet can still keep the loss stable when batch_size=2, while other models can still not solve the loss=nan or inf after batch_size=8. So I don't think this is the problem, and none of these models will have this problem on mmrotate0.3x.
I also tried to change some of the configuration files but it still didn't work out. I can't provide more information because of limited power and computing power.

**Comment by 231055558** [comment]
I have now successfully solved this problem and I am grateful that I saw some advice on it, but I forgot where I saw it. The solution is to use the official mmrotate image splitting scheme so that the loss of 0 is no longer a problem.

**Comment by 231055558** [comment]
> @231055558 hello how to fix this problem

I used the data tool in the tools folder of mmrotate:https://github.com/open-mmlab/mmrotate/blob/1.x/tools/data/dota/split/img_split.py,and then the question doesn't come up anymore, of course I haven't done a rigorous test of whether it can perfectly reproduce the results in the paper.

**Comment by Aya-shawky** [comment]
I appreciate your solution it works for me. 
but I don't know why this is work? can you give me an intuition.
