### ISSUE TITLE
[Feature]   Where is the code for COBB?

### ISSUE THREAD

**Issue by ZhenboZhao77** [open-mmlab/mmrotate#1050]
### What's the feature?

Where is the code for COBB?

### Any other context?

Where is the code for COBB?

**Comment by yangxue0827** [comment]
https://github.com/514flowey/JDet-cobb

**Comment by ZhenboZhao77** [comment]
Excuse me, does the senior have plans to implement the Cobb algorithm in MMRotate with Torch?

**Comment by yangxue0827** [comment]
No plans at this time

**Comment by yangxue0827** [comment]
You can contact the author, he may have relevant implementation.

**Comment by ZhenboZhao77** [comment]
I am extremely grateful to you!

**Comment by amomo123** [comment]
请问一下，你联系到COBB作者了吗，COBB是否有在mmrotate的工作？

> Excuse me, does the senior have plans to implement the Cobb algorithm in MMRotate with Torch?

**Comment by ZhenboZhao77** [comment]
无



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月23日 10:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [open-mmlab/mmrotate] [Feature] Where is the code for COBB? (Issue #1050) |

请问一下，你联系到COBB作者了吗，COBB是否有在mmrotate的工作？

Excuse me, does the senior have plans to implement the Cobb algorithm in MMRotate with Torch?
