### ISSUE TITLE
想问一下Rotated RetinaNet中OBB, HBB的含义

### ISSUE THREAD

**Issue by zhujingsong** [open-mmlab/mmrotate#106]
我看大多数文献对Rotated RetinaNet-OBB/HBB的命名好像指的是anchor是水平的还是有旋转的.

我仔细看了mmrotate感觉好像跟一般文献定义的RetinaNet-H, RetinaNet-R不太一样

我不知道我理解的对不对，想确认一下: 
我看这两种config采用的anchor好像都是水平的(只是加了维度theta=0). 唯一的区别在于assign_by_circumhbbox. 是不是xxx_obb_xxx.py的config用的是纯gt去和anchor匹配，而xxx_hbb_xxx.py的config用的是gt的外围水平框去和anchor匹配？ 

另外，可以增加对模型和算法的说明文档吗？

**Comment by yangxue0827** [comment]
你好，这个repo采用的都是水平anchor，assign_by_circumhbbox参数你的理解是对的。一般论文里RetinaNet-OBB/HBB分别指旋转检测器和水平框检测器；RetinaNet-H, RetinaNet-R指的是使用旋转anchor还是水平anchor。我们页已经意识到本repo中hbb和obb在retinanet中带来的歧义，也在考虑修改带来的工作量。感谢反馈。
至于增加对模型和算法的说明文档，我不清楚你指的是方法的讲解这种吗，如果是这种可能需要你自行阅读相应论文和博客了，挺多文章有相应的讲解的。如果不是我理解的这种，希望你详细说明一下需求，谢谢！

**Comment by zhujingsong** [comment]
你好大神再问一下不同角度定义下的框的编码问题：

proj_xy, edge_swap, norm_factor这些参数怎么设置搭配? 为什么le90的config中edge_swap=True，le135中就不交换边；le90中的norm_factor=None，le135中又使用了归一化系数？是大量经验这样搭配设置更好吗？

**Comment by zytx121** [comment]
proj_xy, edge_swap, norm_factor 这些参数是与各自论文中的编码设置对齐，我们并没有进行大量实验。
