### ISSUE TITLE
FileNotFoundError: torch/hub/checkpoints/swin_tiny_patch4_window7_224.pth can not be found.

### ISSUE THREAD

**Issue by echosum** [open-mmlab/mmrotate#108]
Hello. I try to run roi-transformer, but meet this problem.
FileNotFoundError: torch/hub/checkpoints/swin_tiny_patch4_window7_224.pth can not be found.

Could you please provide the file?

**Comment by jbwang1997** [comment]
You can download the pretrained model at [here](https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth).
