### ISSUE TITLE
Assigning the horizontal anchors directly rather than using assign_by_circumhbbox

### ISSUE THREAD

**Issue by canoe-Z** [open-mmlab/mmrotate#109]
I'd like to suggest assigning the horizontal anchors directly. In detail, assign_by_circumhbbox is always set as None except in the configs of RetinaNet-HBB, which seems redundant. We can use a simple AnchorGenerator and assign gt boxes in a common horizontal way for RetinaNet-HBB. In that case, a new bbox_coder similar to DeltaXYWHAOBBoxCoder needs to be adopted to add the Theta0 dim to the HBB anchors and encode rbboxes from them. It seems not necessary to keep the shape of the input bboxes consistent with output bboxes in a bbox_coder for example DistancePointBBoxCoder in mmdetection. 

Though the configs will be more complex, it would be more clear to understand the label assignment pipeline and the configs will be more flexible for modification in the future. Now the RotatedAnchorGenerator can only generate horizontal anchors with theta=0 instead of genuine rotated anchors. And it also may be confusing to use the RBboxOverlaps2D in RetinaNet-HBB configs where the overlap is calculated by a pair of HBB in fact.

**Comment by zytx121** [comment]
Hi @canoe-Z 
We are glad to receive your suggestion. The design of the `assign_by_circumhbbox` is really not elegant. It is designed to switch between RetinaNet-OBB and RetinaNet-HBB. And welcome to PR  to  MMRotate!
