### ISSUE TITLE
Support OrientedRepPoints

### ISSUE THREAD

**Issue by zytx121** [open-mmlab/mmrotate#127]
This issue describes the development requirement of a feature we wish to collaborate with the community.
In this issue, we welcome the community developers to participate in the development of Oriented RepPoints.

## Description

Support OrientedRepPoints. You can use `points_in_polygons` op in mmcv to judge whether points are inside polygons.

## Steps

- [ ] Add  `OrientedRepPointsHead` and  `SpatialBorderLoss` in MMRotate
- [ ] Benchmark the performance 
- [ ] Prepare and release the models

## Resources

- https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA
- https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/points_in_polygons.py

**Comment by LiWentomng** [comment]
Hello, I'm preparing the  codes of Oriented RepPoints for MMRotate.  
The `chamfer distance 2d`  used in Oriented RepPoints needs `cuda compile`.   I bulid a new `ops` folder like old version, then compile it in the environment of MMRotate successfully.  But the error of `error in nnd updateOutput: invalid device function`  appears during the training.  
Can you help me to make `chamfer distance 2d`  op avaliable in the **mmcv** like `points_in_polygons`. 

The  resources of `chamfer distance 2d` are here:
- [https://github.com/LiWentomng/OrientedRepPoints/tree/main/mmdet/ops/chamfer_2d](https://github.com/LiWentomng/OrientedRepPoints/tree/main/mmdet/ops/chamfer_2d)
- [https://github.com/chrdiller/pyTorchChamferDistance/tree/master/chamfer_distance](https://github.com/chrdiller/pyTorchChamferDistance/tree/master/chamfer_distance)

**Comment by yangxue0827** [comment]
@zytx121

**Comment by zytx121** [comment]
Thanks for your PR, and we will add this Cuda op ASAP.

**Comment by zytx121** [comment]
https://github.com/open-mmlab/mmcv/pull/1933

**Comment by xxmomo** [comment]
When I validate the model on DOTA，I can't figure out the range of mAP . Is it from 0-1 or 0-100? Thanks for your replay!

**Comment by yangxue0827** [comment]
@LiWentomng `chamfer distance` is merged in [mmcv](https://github.com/open-mmlab/mmcv/pull/1933) now.
