### ISSUE TITLE
r3det_refine_r50_fpn_1x_dota_oc.py

### ISSUE THREAD

**Issue by rhj0103** [open-mmlab/mmrotate#130]
The pre-trained weights and model files of this config are not found?

**Comment by yangxue0827** [comment]
Use `r3det_r50_fpn_1x_dota_oc.py` instead.

**Comment by rhj0103** [comment]
r3det_tiny.py uses a network structure of a refine stage, and r3det_refine.py uses two refine stages? Will the precision of using r3det_refine be higher?

**Comment by yangxue0827** [comment]
maybe, just try it.

**Comment by rhj0103** [comment]
And where can I find weights files for different models?

**Comment by yangxue0827** [comment]
Train from pretrain model by yourself.

**Comment by yangxue0827** [comment]
all models we have are listed in the tabel.

**Comment by rhj0103** [comment]
Yes, I saw it. Thanks for the answer.
