### ISSUE TITLE
TypeError: format_results() argument after ** must be a mapping, not bool

### ISSUE THREAD

**Issue by rhj0103** [open-mmlab/mmrotate#131]
when I did rest, no Task1_results.

**Comment by yangxue0827** [comment]
Did you solve it ?

**Comment by rhj0103** [comment]
No,I didn't.

**Comment by yangxue0827** [comment]
what's your test command?

**Comment by rhj0103** [comment]
Right click to run without command. Unable to execute submission_ dir

**Comment by yangxue0827** [comment]
try command as we provide.

**Comment by rhj0103** [comment]
Report such a mistake：

![图片](https://user-images.githubusercontent.com/86508657/158042845-03ff212f-9a36-4727-ad3b-4927e5e8638c.png)

**Comment by yangxue0827** [comment]
It looks like it didn't find your test data, please re-crop the data,

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/158042947-21c691e0-20c3-4fa8-9a23-7e09ecbbdde7.png)

**Comment by rhj0103** [comment]
Just execute this command?
`python img_split.py --base_json split_config/dota1_0/ss_test.json`

**Comment by yangxue0827** [comment]
different set use different json.
for example:
for test set, use `ss_test.json`
for trainval set, use `ss_trainval.json`

**Comment by rhj0103** [comment]
Yes, this is what I do. The same is true for the annfiles on the official website of the bboxtoolkit. Pkl files.

**Comment by yangxue0827** [comment]
official website? please use our [tookit](https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/split/img_split.py)

**Comment by rhj0103** [comment]
OK, Thanks very much!

**Comment by rhj0103** [comment]
There is such an error after detection.
![图片](https://user-images.githubusercontent.com/86508657/158043903-335c0695-30f3-491b-b3e7-12d2d2f29a52.png)

**Comment by yangxue0827** [comment]
try like
`
CUDA_VISIBLE_DEVICES=0 PORT=29807 \
       ./tools/dist_test.sh oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
        /workspace/mmrotate/work_dirs/ms/oriented_rcnn/0221/epoch_12.pth 1 --format-only \
        --eval-options submission_dir=/workspace/mmrotate/work_dirs/ms/oriented_rcnn/0221/Task1_results
`

**Comment by rhj0103** [comment]
Can PORT be the same?

**Comment by yangxue0827** [comment]
yes

**Comment by rhj0103** [comment]
Error:`bash: ./tools/dist_test.sh: 权限不够`

**Comment by yangxue0827** [comment]
chmod -R 775 mmrotate

**Comment by rhj0103** [comment]
Such Error:
![图片](https://user-images.githubusercontent.com/86508657/158050243-98e6d871-c3f5-4232-b8ad-af211e272456.png)

**Comment by yangxue0827** [comment]
what can I say. you need to learn Linux first.

**Comment by yangxue0827** [comment]
First, you use `chmod -R 775 mmrotate` to modify the permissions of mmrotate. When you run this command, your path should be one level above `mmrotate` project.
Then you run 
```
CUDA_VISIBLE_DEVICES=0 PORT=29807 \
       ./tools/dist_test.sh oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
        /workspace/mmrotate/work_dirs/ms/oriented_rcnn/0221/epoch_12.pth 1 --format-only \
        --eval-options submission_dir=/workspace/mmrotate/work_dirs/ms/oriented_rcnn/0221/Task1_results
```

**Comment by rhj0103** [comment]
But he's still wrong:
![图片](https://user-images.githubusercontent.com/86508657/158055398-0abc025b-0cdf-47e3-8d29-388b170afe58.png)

**Comment by yangxue0827** [comment]
All errors reported are clearly stated in the screenshots, please debug by yourself.

**Comment by rhj0103** [comment]
OK.

**Comment by rhj0103** [comment]
I will do it by myself.
