### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by rhj0103** [open-mmlab/mmrotate#132]
When I run the train

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/issues/35

**Comment by rhj0103** [comment]
Must we use relative path?

**Comment by rhj0103** [comment]
There is no problem with the path, because pictures can be detected during the test

**Comment by yangxue0827** [comment]
discussion at https://github.com/open-mmlab/mmrotate/issues/35
