### ISSUE TITLE
Change module.

### ISSUE THREAD

**Issue by rhj0103** [open-mmlab/mmrotate#136]
If I want to change the backbone and neck of the model r3det, where should I change it? is `mmrotate/module/backbone`? or `mmrotate/module/neck`?

**Comment by yangxue0827** [comment]
yes

**Comment by rhj0103** [comment]
But I saw ResNet in `mmrotate/models/backbone` is be named ReResNet, FPN in  `mmrotate/models/neck` is be named ReFPN. But the backbone in r3det_tiny.py is written with `type = 'ResNet'`, the neck in r3det_tiny.py is written with `type = 'FPN'`, I feel that r3det_tiny.py does not call ResNet and FPN in `mmrotate/module/backbone`  and `mmrotate/module/neck`.

**Comment by yangxue0827** [comment]
`FPN` and `ResNet` module is defined in mmdet not in mmrotate, we just import them from mmdet.

**Comment by rhj0103** [comment]
![图片](https://user-images.githubusercontent.com/86508657/158130458-2bd3abe6-bd66-456d-bfbd-71d3a63f7d9c.png)

**Comment by rhj0103** [comment]
So, I should modify `resnet` and `fpn`in mmdet.

**Comment by rhj0103** [comment]
Then,what are the functions of RESNET and FPN in mmrotate / module?

**Comment by yangxue0827** [comment]
You need to creat a new one, like `ReFPN` and `ReResNet `.

**Comment by rhj0103** [comment]
That's not what I mean, I just want to change a small part of resnet.

**Comment by yangxue0827** [comment]
I also recommend creating a new one. For example, inherit `FPN` and `ResNet` in mmdet, and then rewrite the part you want to modify.

**Comment by yangxue0827** [comment]
Of course, the more crude method is to copy the corresponding `ResNet` and `FPN` from mmdet, and then modify it. Be careful not to import them from mmdet, but replace it with mmrotate

**Comment by rhj0103** [comment]
OK, thank you. But if I want to replace it with mmrotate, what should I do?

**Comment by yangxue0827** [comment]
> Of course, the more crude method is to copy the corresponding `ResNet` and `FPN` from mmdet, and then modify it. Be careful not to import them from mmdet, but replace it with mmrotate.

This way.

**Comment by rhj0103** [comment]
I just copy the corresponding ResNet and FPN from mmdet and modify it, it's OK?

**Comment by yangxue0827** [comment]
Then, do not import `ResNet` and `FPN` from mmdet, but replace it with mmrotate.

**Comment by rhj0103** [comment]
Sorry, I don't understand how to import `ResNet` and `FPN`.

**Comment by yangxue0827** [comment]
> You need to creat a new one if you want to design new backbone or beck, like `ReFPN` and `ReResNet`.

It is recommended that you use this method, it is a better and simpler way.

**Comment by rhj0103** [comment]
But I still don't know the relationship between the code in mmrotate and the model. It seems from r3det_tiny.py that he did not call ReResNet and ReFPN in mmrotate provided by you. I don't know which step mmrotate played a role in training.

**Comment by yangxue0827** [comment]
R3Det does not use `ReResNet` and `ReFPN`.
You have to familiarize yourself with mmdet's architecture to understand how to modify it, which is beyond my scope of responsibility.

**Comment by rhj0103** [comment]
Still thanks a lot for your answer.
