### ISSUE TITLE
kld高精度检测

### ISSUE THREAD

**Issue by zjutlouis1011** [open-mmlab/mmrotate#138]
我将dota 1.0的train 作为训练集，val 作为测试集，然后训练，最后ap50在70左右，和论文上差不多，但是ap75只有34左右，和论文中相差十个点，想知道这是为什么，我用的config是：r3det_kld_r50_fpn_1x_dota_oc.py

**Comment by yangxue0827** [comment]
pytorch版本不保证所有指标都对齐，还在调试，因为挺多细节还是不一样的。如果需要做相关实验，建议用TF版本，或者如果你复现成功了，可以提PR

**Comment by zjutlouis1011** [comment]
好的，那我在这做的实验是否具有说服力呢

**Comment by yangxue0827** [comment]
我觉得只要KLD比baseline retinanet在高精度上高，你做的实验又是基于他们改的，还是有说服力的。

**Comment by yangxue0827** [comment]
另外，TF版本的训练量是mmrotate的两倍，建议可以试试2x来缩小差距。
目前retinanet-oc-2x的AP75在38的样子。

**Comment by zjutlouis1011** [comment]
我今天跑了24个epoch，ap50已经73，但ap75只有35

**Comment by yangxue0827** [comment]
最近跑了kld在hrsc高精度上的实验：
mmrotate：
|       Backbone        |  mAP | AP50 | AP75  | Angle | lr schd | Mem (GB) | Inf Time (fps) | Aug | Batch Size |                                            Configs                                            | Download |
|:---------------------:|:-----:|:-----:|:-----:|:-----------:|:-------:|:---------:|:---------:|:---------:|:---------:|:---------------------------------------------------------------------------------------------:|:-------------:|
|  ResNet50 (800,512)   | 45.09 | 79.30 | 46.90 |    oc    | 6x | 1.56 | 39.2 | RR | 2 | [rotated_retinanet_hbb_r50_fpn_6x_hrsc_rr_oc](../rotated_retinanet/rotated_retinanet_hbb_r50_fpn_6x_hrsc_rr_oc.py) |
|  ResNet50 (800,512)   | 58.19 | 86.20 | 69.80 |    oc    | 6x | 1.56 | 39.5 | RR | 2 | [rotated_retinanet_hbb_kld_stable_r50_fpn_6x_hrsc_rr_oc](./rotated_retinanet_hbb_kld_stable_r50_fpn_6x_hrsc_rr_oc.py) |

原文：
<img width="991" alt="image" src="https://user-images.githubusercontent.com/29257168/162974286-53817a58-4d99-4a5a-9286-008e51495810.png">

没有严格设置相同的配置，比如图片大小，训练次数，但结论是差不多的。

调参中有个发现，kld什么的对loss weight比较敏感，需要自己好好调一下，差别挺大的。
相关代码正在pr中，参考链接：https://github.com/open-mmlab/mmrotate/pull/183

**Comment by yangxue0827** [comment]
另外，我也在这个PR中加了新的配置文件（带`stable`关键字的），之前版本的kld训练容易出现`nan`
