### ISSUE TITLE
Can not install mmcv-full

### ISSUE THREAD

**Issue by Agito555** [open-mmlab/mmrotate#140]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Hello,I have met the problem mentioned in the link https://github.com/open-mmlab/mmcv/issues/1318, and i have tried to follow the instructions in the link,but failed. I notice that the instruction advises us to download the software Visual Studio 2019, but it can not be downloaded now. And the cuda11.0 is not  totally compatiable with the newest Visual Studio2022. I wonder whether it is the problem and how can i do to fix the problem? P.S. The system of my computer is windows 10.
**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zytx121** [comment]
HI @Agito555 
This is an error caused by a compilation failure. In fact, you don't need to compile mmcv yourself, just install the compiled mmcv. So there's no need for Visual Studio 2019.  You could refer to https://mmcv.readthedocs.io/en/latest/get_started/installation.html,
and try:
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
```
Note: change the version of `cu111` and `torch1.8.0` to your envs.

**Comment by Agito555** [comment]
> HI @Agito555 This is an error caused by a compilation failure. In fact, you don't need to compile mmcv yourself, just install the compiled mmcv. So there's no need for Visual Studio 2019. You could refer to https://mmcv.readthedocs.io/en/latest/get_started/installation.html, and try:
> 
> ```
> pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
> ```
> 
> Note: change the version of `cu111` and `torch1.8.0` to your envs.

Thanks for your immediate reply, it really helps!!!
When I want to check if the MMrotate is installed correctly or not, I follow the instruction to run the demo,  and then I find that there are folders about the model and the weights missing. I wonder how can I get these files to run the demo.
>```
>work_dirs/oriented_rcnn_r50_fpn_1x_dota_v3/oriented_rcnn_r50_fpn_1x_dota_v3.py \
>work_dirs/oriented_rcnn_r50_fpn_1x_dota_v3/epoch_12.pth \
>```

P.S. I want to know whether the cuda version within Pytorch installed by the following command,like
>
>```
>conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
>``` 
should be consistent with the cuda version in the system to make sure the package mmcv-full can be installed correctly.

P.P.S. Really appreciate your help!!

**Comment by zytx121** [comment]
You could choose anyone config in [configs](https://github.com/open-mmlab/mmrotate/tree/main/configs/oriented_rcnn) to replace these, e.g., [oriented_rcnn_r50_fpn_1x_dota_le90.py](https://github.com/open-mmlab/mmrotate/blob/main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py)

**Comment by Agito555** [comment]
> You could choose anyone config in [configs](https://github.com/open-mmlab/mmrotate/tree/main/configs/oriented_rcnn) to replace these, e.g., [oriented_rcnn_r50_fpn_1x_dota_le90.py](https://github.com/open-mmlab/mmrotate/blob/main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py)

Thank your for your instructions !! I have isntalled mmrotate successfully!!
