### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by chaoye171** [open-mmlab/mmrotate#141]
when i test the demo ,the problem is 
C:\Anaconda3\envs\mmrotate\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: weights/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth
C:\Anaconda3\envs\mmrotate\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
C:\Anaconda3\envs\mmrotate\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated,

**Comment by zytx121** [comment]
Hi @chaoye171 
The warning is caused by mmdet. We use mmdet as our upstream library.

**Comment by chaoye171** [comment]
oh,OK, Do these warnings matter me using the mmrotate to pratice my models?

**Comment by yangxue0827** [comment]
no

**Comment by chaoye171** [comment]
thanks
