### ISSUE TITLE
无法进行在线验证，验证进度条完成后训练会卡住不动

### ISSUE THREAD

**Issue by 1994su** [open-mmlab/mmrotate#142]
我们用mmrotate训练自建样本库时，在进行在线验证时，验证进度条完成后，不会出定量指标，且训练不再进行，请问是什么原因呀？

**Comment by zytx121** [comment]
Hi @1994su 
Are you using the latest version of mmrotate? v0.1.1

**Comment by houw0517** [comment]
I also  ran into this problem 
TypeError: eval_map() got an unexpected keyword argument 'version'
I use the version of mmrotate v0.1.0

**Comment by yangxue0827** [comment]
This eval bug is fixed in v0.1.1. @houw0517

**Comment by houw0517** [comment]
but when I  run the command “ pip install -v -e .”  the version of mmroate is back to v0.1.0 
if I don’t run the command ，I cannot use the new module

**Comment by zytx121** [comment]
Please download the latest version by 
`git clone https://github.com/open-mmlab/mmrotate.git` 
and run the command “ pip install -v -e .”  again.
