### ISSUE TITLE
请问官网测试的是map 0.5:0.95的嘛？

### ISSUE THREAD

**Issue by rhj0103** [open-mmlab/mmrotate#147]

**Comment by yangxue0827** [comment]
DOTA 用的AP50

**Comment by yangxue0827** [comment]
官网测试脚本：https://github.com/CAPTAIN-WHU/DOTA_devkit

**Comment by rhj0103** [comment]
OK, if I test it with the code you provided, I can submit it directly, right?

**Comment by yangxue0827** [comment]
if you have the gt, yes, you can.

**Comment by rhj0103** [comment]
不是的。我们通过您的mmrotate完成了训练，并测试了测试集，得到一个Task1_results的文件夹，我们是否可以直接提交这个文件夹到官网？

**Comment by yangxue0827** [comment]
是的，test只能提交官网评估。

**Comment by rhj0103** [comment]
好的，谢谢
