### ISSUE TITLE
在使用Oriented R-CNN进行DOTA数据集测试时报错

### ISSUE THREAD

**Issue by beixinag** [open-mmlab/mmrotate#148]
可以输出检测图像，但是mAP无法输出，下面是运行结果

运行
%cd /user-data/mmrotate
!python ./tools/test.py \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  checkpoints/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth \
  --eval mAP 

结果
/user-data/mmrotate
/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: checkpoints/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
[                                                  ] 0/11627, elapsed: 0s, ETA:/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
[>>>>>>>>>>>>>>>>>>>>>>>>] 11627/11627, 15.1 task/s, elapsed: 768s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 238, in <module>
    main()
  File "./tools/test.py", line 230, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/user-data/mmrotate/mmrotate/datasets/dota.py", line 196, in evaluate
    mean_ap, _ = eval_rbbox_map(
  File "/user-data/mmrotate/mmrotate/core/evaluation/eval_map.py", line 177, in eval_rbbox_map
    cls_dets, cls_gts, cls_gts_ignore = get_cls_results(
  File "/user-data/mmrotate/mmrotate/core/evaluation/eval_map.py", line 114, in get_cls_results
    cls_gts.append(ann['bboxes'][gt_inds, :])
TypeError: list indices must be integers or slices, not tuple

**Comment by zytx121** [comment]
Please check your data path.

**Comment by beixinag** [comment]
输出其他都行，这个就运行成功了
!python ./tools/test.py \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  checkpoints/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --format-only\
  --eval-options submission_dir=work_dirs/Task1_results

**Comment by beixinag** [comment]
/user-data/mmrotate
/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: checkpoints/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
[                                                  ] 0/11627, elapsed: 0s, ETA:/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
[>>>>>>>>>>>>>>>>>>>>>>>>] 11627/11627, 15.1 task/s, elapsed: 769s, ETA:     0s
Merging patch bboxes into full image!!!
Multiple processing
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 937/937, 92.2 task/s, elapsed: 10s, ETA:     0s
Used time: 13.0 s

**Comment by zytx121** [comment]
Hi @beixinag 
The reason is we don't have the ground truth of the DOTA test set.

**Comment by beixinag** [comment]
好的，谢谢，好像是这样的，哈哈哈

**Comment by YimingDong1999** [comment]
Same problem encountered. Thanks for your help

**Comment by 1Chengjie** [comment]
您好，我也遇到了这个问题，上面评论的ground truth of the DOTA test set我没太明白，想请问一下具体该如何解决？
