### ISSUE TITLE
Chinese Documentation Translation

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmrotate#15]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here.
Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/get_started.md @[RangeKing](https://github.com/RangeKing)
- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/model_zoo.md @[liufeinuaa](https://github.com/liufeinuaa)
- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/faq.md
- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_config.md @[RangeKing](https://github.com/RangeKing)
- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_dataset.md @[matrixgame2018](https://github.com/matrixgame2018)
- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_models.md @[Abyssaledge](https://github.com/Abyssaledge) & @[matrixgame2018](https://github.com/matrixgame2018) for review
- [x] https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_runtime.md @[SheffieldCao](https://github.com/SheffieldCao)

**Comment by Abyssaledge** [comment]
I find `customize_models.md` is somewhat interesting, and I am happy to provide a translation.

**Comment by ZwwWayne** [comment]
> I find `customize_models.md` is somewhat interesting, and I am happy to provide a translation.

Great, looking forward to your PR!

**Comment by RangeKing** [comment]
I can help  translate
https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/get_started.md
https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_config.md

**Comment by matrixgame2018** [comment]
I can help translate，I am happy to provide a translation.
https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_models.md

**Comment by SheffieldCao** [comment]
I am glad to translate 
https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_runtime.md

**Comment by liufeinuaa** [comment]
I can help translate,
 https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/model_zoo.md

**Comment by ZwwWayne** [comment]
> I can help translate，I am happy to provide a translation. https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_models.md

Hi @matrixgame2018 ,
customize_models.md has been picked up. You can review this PR if you would like to. You can also choose a new  doc if you are interested.

**Comment by matrixgame2018** [comment]
I can help 
https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/tutorials/customize_dataset.md

**Comment by BrotherHappy** [comment]
hi,it is my pleasure to translate: https://github.com/open-mmlab/mmrotate/blob/main/docs/zh_cn/faq.md

**Comment by zytx121** [comment]
Thank you all guys! All tasks have been done.
