### ISSUE TITLE
如何通过DOTA数据集的val 图像输出模型的mAP结果?

### ISSUE THREAD

**Issue by beixinag** [open-mmlab/mmrotate#150]
由于test文件没有ground truth，我尝试将分割好的val文件夹改名为test，然后运行test.py
结果还是出错，请问，如何通过DOTA数据集的val 图像输出模型的mAP结果?

运行
%cd /user-data/mmrotate
!python ./tools/test.py \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  checkpoints/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth \
  --eval mAP 
结果
/user-data/mmrotate
/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: checkpoints/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
[                                                  ] 0/5756, elapsed: 0s, ETA:/opt/conda/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
[>>>>>>>>>>>>>>>>>>>>>>>>>>] 5756/5756, 15.0 task/s, elapsed: 383s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 238, in <module>
    main()
  File "./tools/test.py", line 230, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/user-data/mmrotate/mmrotate/datasets/dota.py", line 196, in evaluate
    mean_ap, _ = eval_rbbox_map(
  File "/user-data/mmrotate/mmrotate/core/evaluation/eval_map.py", line 177, in eval_rbbox_map
    cls_dets, cls_gts, cls_gts_ignore = get_cls_results(
  File "/user-data/mmrotate/mmrotate/core/evaluation/eval_map.py", line 114, in get_cls_results
    cls_gts.append(ann['bboxes'][gt_inds, :])
TypeError: list indices must be integers or slices, not tuple

**Comment by yangxue0827** [comment]
How did you set up in
https://github.com/open-mmlab/mmrotate/blob/main/configs/_base_/datasets/dotav1.py#L30-L47

**Comment by beixinag** [comment]
我直接在文件夹将val文件名改成了test，除了文件路径我都没有修改。
那我该怎么通过val输出map呢?
是否可以修改test 的ann_file=data_root + 'test/images/' 为ann_file=data_root + 'test/annfiles/'

test=dict(
        type=dataset_type,
        #ann_file=data_root + 'test/images/',
        ann_file=data_root + 'test/annfiles/'，
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))

**Comment by beixinag** [comment]
感谢感谢，懂了其实可以直接修改

test=dict(
type=dataset_type,
#ann_file=data_root + 'test/images/',
#img_prefix=data_root + 'test/images/',
ann_file=data_root + 'val/annfiles/'，
img_prefix=data_root + 'val/images/',
pipeline=test_pipeline))

**Comment by yangxue0827** [comment]
For the DOTA dataset, I recommend generating txt result files first, and then evaluating it with the [official script](https://github.com/CAPTAIN-WHU/DOTA_devkit).

**Comment by beixinag** [comment]
嗯呀，我就想先通过val看看效果，
有个疑问val应该没有参与训练吧

**Comment by yangxue0827** [comment]
It depands on your
```
train=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
```

**Comment by beixinag** [comment]
好的好的，感谢感谢，我感觉学到了很多，哈哈哈哈

**Comment by hust-lidelong** [comment]
In configs\_base_\datasets\dotav1.py
```
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'val/images/',
        img_prefix=data_root + 'val/images/',
        pipeline=test_pipeline))
```

When I run :
```
./tools/dist_test.sh  \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  work_dirs/oriented_rcnn_r50_fpn_1x_dota_le90/epoch_12.pth 2 --eval mAP
```
or 
```
CUDA_VISIBLE_DEVICES=1 python ./tools/test.py \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  work_dirs/oriented_rcnn_r50_fpn_1x_dota_le90/epoch_12.pth --eval mAP
```
It appears:
TypeError: list indices must be integers or slices, not tuple

**Comment by hust-lidelong** [comment]
https://github.com/open-mmlab/mmrotate/blob/main/configs/_base_/datasets/dotav1.py#L45
 Is it wrong?
Should ann_file=data_root + 'test/annfiles/' ?

**Comment by lywang76** [comment]
> For the DOTA dataset, I recommend generating txt result files first, and then evaluating it with the [official script](https://github.com/CAPTAIN-WHU/DOTA_devkit).

This repo is too old. I tried it before, and its configurations files are all old format and doesn't work with latest mmrotate. I think people should use mmrotate instead of that one.
