### ISSUE TITLE
[求助] 有关旋转框定义的疑问

### ISSUE THREAD

**Issue by HsLOL** [open-mmlab/mmrotate#151]
感谢大佬们出色的工作！
我在学习`角度版本=oc`的R-RetinaNet的时候，发现预设值的水平锚框中定义的角度为0弧度。但是根据基础知识的文章中，如果opencv的版本大于4.5.1的话，角度范围是(0,90°]的。那为什么这里的锚框设置的角度是0°呢？

希望大佬可以帮忙解答一下。

**Comment by yangxue0827** [comment]
`RotatedAnchorGenerator` 这个存在bug，一个是取名有问题，这个类是用于生成五参数表示的水平框，所以我觉得命名为`FakeRotatedAnchorGenerator`更贴切。另外就是，不同角度定义下水平框的角度是不一样的，其实需要判断一下，这里统一为0是不妥的。但是有意思的是，在oc下，设置成0反而比正确的90的效果要好一些。
我们会在后面修正这些问题，希望没有误导你，十分抱歉。

**Comment by HsLOL** [comment]
> `RotatedAnchorGenerator` 这个存在bug，一个是取名有问题，这个类是用于生成五参数表示的水平框，所以我觉得命名为`FakeRotatedAnchorGenerator`更贴切。另外就是，不同角度定义下水平框的角度是不一样的，其实需要判断一下，这里统一为0是不妥的。但是有意思的是，在oc下，设置成0反而比正确的90的效果要好一些。 我们会在后面修正这些问题，希望没有误导你，十分抱歉。

感谢大佬的回复！

这两天在根据MMRotate的思路，自己尝试写下旋转的RetinaNet，结果发现检测效果很离谱，然后Debug的时候就突然发现了角度定义的问题，那根据您的说法感觉我的检测效果很差应该不是角度定义的问题，我再找找Bug.

再次感谢大佬的解答~

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/159170508-0186c493-ed46-4887-9516-babaec1c40bf.png)
这是我用了正确anchor生成器的性能，从68.79下降到了67.39，非常奇怪，所以我们在考虑要不要修改这个涨点的bug. >_<
```
mAP: 0.6739365254564681
ap of each class: plane:0.8833921626383211, baseball-diamond:0.792209017017192, bridge:0.4062754544324635, ground-track-field:0.6642251645520911, small-vehicle:0.7787324522977256, large-vehicle:0.5673172966774563, ship:0.7714356766524842, tennis-court:0.8939929457150905, basketball-court:0.7387293261468867, storage-tank:0.8130941182012215, soccer-ball-field:0.5931339874185464, roundabout:0.6597527611827078, harbor:0.5262066390281135, swimming-pool:0.6314232786560395, helicopter:0.38912760123068046
```

**Comment by yangxue0827** [comment]
【更新】
`rotated_retinanet_obb_r50_fpn_1x_dota_le135`结果：
```
mAP: 0.680392373335475
ap of each class: plane:0.8914711094516861, baseball-diamond:0.8034912925266369, bridge:0.4022653465869002, ground-track-field:0.6556297878104551, small-vehicle:0.7752625868089739, large-vehicle:0.5809677199540735, ship:0.7643732430364061, tennis-court:0.9049071080649492, basketball-court:0.7983428487686156, storage-tank:0.802368096425488, soccer-ball-field:0.5568757536515034, roundabout:0.6273661313984683, harbor:0.5361792892715711, swimming-pool:0.6496487095049853, helicopter:0.4567365767714123
```

`rotated_retinanet_hbb_r50_fpn_1x_dota_oc`结果：
```
mAP: 0.6465663890389447
ap of each class: plane:0.8738185534774865, baseball-diamond:0.7149853430757392, bridge:0.4393980048197631, ground-track-field:0.6292966782812204, small-vehicle:0.7003376853100355, large-vehicle:0.5660794830968301, ship:0.7425052423661722, tennis-court:0.9080438784700589, basketball-court:0.729757515434526, storage-tank:0.8052047945947394, soccer-ball-field:0.47713692002050184, roundabout:0.6240863024215481, harbor:0.5837486346769886, swimming-pool:0.6389940779470279, helicopter:0.26510272159153175
```

除了oc结果都有所下降，因为oc是通过水平anchor和gt的水平外接矩形进行样本分配的，所以影响小一些。

**Comment by Agito555** [comment]
I noticed that when using the config file
>rotated_retinanet_hbb_r50_fpn_1x_dota_oc
to train the model, the angles of horizontal circumscribing rectangles are not 90°, they are 1.5°。 
Maybe this is the reason why setting all the angles rudely to 0°  can lead to improvement in this config case.
@yangxue0827  @HsLOL 

> `RotatedAnchorGenerator` 这个存在bug，一个是取名有问题，这个类是用于生成五参数表示的水平框，所以我觉得命名为`FakeRotatedAnchorGenerator`更贴切。另外就是，不同角度定义下水平框的角度是不一样的，其实需要判断一下，这里统一为0是不妥的。但是有意思的是，在oc下，设置成0反而比正确的90的效果要好一些。 我们会在后面修正这些问题，希望没有误导你，十分抱歉。
