### ISSUE TITLE
redet 配置文件configs\redet\redet_re50_refpn_1x_dota_ms_rr_le90.py中有个配置名字错误

### ISSUE THREAD

**Issue by lalalagogogochong** [open-mmlab/mmrotate#156]
![image](https://user-images.githubusercontent.com/44855506/159400010-9815d236-ed14-44ea-9549-597d15adbad9.png)
应该是refpn吧
![image](https://user-images.githubusercontent.com/44855506/159400070-3dddadeb-09a5-44b1-8e8a-9846cc1712c8.png)

**Comment by yangxue0827** [comment]
thx!

**Comment by yangxue0827** [comment]
Fixed in PR https://github.com/open-mmlab/mmrotate/pull/153
