### ISSUE TITLE
[求助]opencv表示法的疑问

### ISSUE THREAD

**Issue by HsLOL** [open-mmlab/mmrotate#157]
大佬好，还是有关oc格式对旋转框表示上的一些疑问， 我用的opencv版本是**4.5.5.64** 
我在Debug的时候发现，我的真值是按照下面的方式来描述的
```
gt_bboxes = np.array([[245.24801635742188, 171.76348876953125,
                                     20.867666244506836, 68.0083236694336, 
                                     0.6351632475852966]], dtype=np.float32)
```
然后我使用如下的画图函数得到的旋转结果是正确的
```
image1 = cv2.resize(cv2.cvtColor(cv2.imread(os.path.join(image_path, image_name)), cv2.COLOR_BGR2RGB), (512, 512))
for single in gt_bboxes:
    xc, yc, w, h, angle = single
    wx, wy = w / 2 * math.cos(angle), w / 2 * math.sin(angle)
    hx, hy = -h / 2 * math.sin(angle), h / 2 * math.cos(angle)
    p1 = (xc - wx - hx, yc - wy - hy)
    p2 = (xc + wx - hx, yc + wy - hy)
    p3 = (xc + wx + hx, yc + wy + hy)
    p4 = (xc - wx + hx, yc - wy + hy)
    ps = np.int0(np.array([p1, p2, p3, p4]))
    cv2.drawContours(image1, [ps], -1, [0, 255, 255], thickness=2)
```
![旋转](https://user-images.githubusercontent.com/53011009/159414686-2d458090-869e-4021-a5c7-8e28315b908f.png)

但是根据basic里面的描述，oc表示法中的h边应该是x轴正半轴顺时针旋转过程中遇到的第一条边，那这样来看的话，我的表示方式应该是存在问题的，我的表示方式满足的是[xc, yc, h, w, angle(radian)]。

但是根据画图函数，又可以画出正确的真值框，不太明白哪里出了问题，希望大佬可以解答一下我的疑问，谢谢！

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/159415934-dc1605ee-7be2-4d45-a388-dd4824083c93.png)
没有问题啊，ni你看我画的图，对于opencv来说。wh没有具体的含义（比如h是长边什么的），这个repo种h只是代表第三个参数，w代表第四个参数。

**Comment by HsLOL** [comment]
> ![image](https://user-images.githubusercontent.com/29257168/159415934-dc1605ee-7be2-4d45-a388-dd4824083c93.png) 没有问题啊，ni你看我画的图，对于opencv来说。wh没有具体的含义（比如h是长边什么的），这个repo中h只是代表第三个参数，w代表第四个参数。

感谢您的回复。

根据您的画法，我感觉跟我真值的表示形式是一样的 (旋转框的高比宽要小)。

但是我的疑问是，在我的画图函数中
`xc, yc, w, h, angle = single`
我是按照xc, yc, w, h, angle来读取的，这和我真值的表示形式不就冲突了吗？

**Comment by yangxue0827** [comment]
这个和符号关系不大，你的转换脚本只要是把w作为第三个参数来处理的话是没有问题的。

**Comment by yangxue0827** [comment]
如果按照我的方式，我的脚本就是
```
xc, yc, h, w, angle = single
hx, hy = h / 2 * math.cos(angle), h / 2 * math.sin(angle)
hwx, wy = -w / 2 * math.sin(angle), w / 2 * math.cos(angle)
p1 = (xc - hx - wx, yc - hy - wy)
p2 = (xc + hx - wx, yc + hy - wy)
p3 = (xc + hx + wx, yc + hy + wy)
p4 = (xc - hx + wx, yc - hy + wy)
ps = np.int0(np.array([p1, p2, p3, p4]))
cv2.drawContours(image1, [ps], -1, [0, 255, 255], thickness=2)
```

刚好负负得正

**Comment by HsLOL** [comment]
> 这个和符号关系不大，你的转换脚本只要是把w作为第三个参数来处理的话是没有问题的。

大佬，不知道我现在的理解对不对，对于这个repo而言，针对oc表示法采用的是[xc, yc, h, w, angle(radin)]的格式，其中h就是x轴正半轴顺时针旋转碰到的第一条边，另一条边就是w，我的理解对吗？

您那个公式我在推一推，我之前就是直接从repo里copy过来用了，还没有仔细推过 [尴尬]
