### ISSUE TITLE
如何在无Annotation的多幅影像中可视化目标检测的结果？

### ISSUE THREAD

**Issue by LastSummer09** [open-mmlab/mmrotate#161]
我想将模型训练的结果用于遥感图像切片的目标检测中，由于没有Annotations，不知道调用test.py时customized_dataset的两个config应该怎么修改，demo.py好像只能可视化单个图像

**Comment by zytx121** [comment]
You could modify your config file like this
![image](https://user-images.githubusercontent.com/10410257/160226947-7c9a3c78-cce6-47f9-a47b-7dc52115a247.png)

**Comment by LastSummer09** [comment]
> Hi @LastSummer09 We're sorry to confuse you, and you could modify your config file like this ![image](https://user-images.githubusercontent.com/10410257/160226947-7c9a3c78-cce6-47f9-a47b-7dc52115a247.png)
> 
> We have to admit that the design here is unreasonable, and we will improve it.

Thanks for your reply! But by doing so, it gives no results. The command and output are in the screenshot below.
![image](https://user-images.githubusercontent.com/76859231/160322600-5212819e-4186-4b0d-8fc9-f3b5cb59582b.png)
My test data is made up with a series of tiff images (.tif). And the filenames are discontinuous like "a_1.tif  a_102.tif a_303.tif". I wonder if it is the matter with my datasets or something else. I'd appreciate it if you could give further tutorial about this issue.

**Comment by domin00** [comment]
hi, did you manage to solve this issue?
i also would like to use test.py on a dataset that doesnt have annotations, but cant seem to bypass the ann_file requirement.
