### ISSUE TITLE
使用test.py --format-only,出现IndexError: list index out of range

### ISSUE THREAD

**Issue by Hd-14** [open-mmlab/mmrotate#163]
我用ssdd训练了oriented rcnn网络，在检测时使用python tools/test.py configs/oriented_rcnn/oriented_rcnn_r50_fpn_6x_ssdd_le90.py work_dirs/oriented_rcnn_r50_fpn_6x_ssdd_le90/latest.pth --format-only命令
出现了IndexError: list index out of range
整体错误代码如下：
Traceback (most recent call last):
  File "tools/test.py", line 238, in <module>
    main()
  File "tools/test.py", line 220, in main
    dataset.format_results(outputs, **kwargs)
  File "e:\pycharmproject\mmrotate\mmrotate\datasets\dota.py", line 320, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
  File "e:\pycharmproject\mmrotate\mmrotate\datasets\dota.py", line 225, in merge_det
    x_y_2 = re.findall(r'\d+', x_y[0])
IndexError: list index out of range

可以使用--eval mAP命令。
有什么解决的方法吗

**Comment by zytx121** [comment]
Please follow the [doc](https://mmrotate.readthedocs.io/en/latest/get_started.html#test-a-model).

**Comment by Hd-14** [comment]
> Hi @Hd-14 Please follow the [doc](https://mmrotate.readthedocs.io/en/latest/get_started.html#test-a-model).

Thank you for your answer, I have another question, what is the specific meaning of the data in the pkl file list[list[ndarry]] obtained with the test.py --out command.

**Comment by heyun1994** [comment]
Hi @Hd-14,Have you solved this problem yet?

**Comment by lo202ng** [comment]
> Hi @Hd-14,Have you solved this problem yet?

I had the same problem too ...

**Comment by dk-liang** [comment]
I meet the same problem

**Comment by 2505928188** [comment]
> Hi @Hd-14,Have you solved this problem yet?

The dataset used by mmrotate is not the original DOTA dataset, but the dataset after splitter. you can see in https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md

mmrotate不是用的原始的DOTA数据集，而是分割后的数据集，具体可看https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md

**Comment by 2505928188** [comment]
> The dataset used by mmrotate is not the original DOTA dataset, but the dataset after splitter. you can see in https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md
> 
> mmrotate不是用的原始的DOTA数据集，而是分割后的数据集，具体可看https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md

The dataset used by mmrotate is not the original DOTA dataset, but the dataset after splitter. you can see in https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md

mmrotate不是用的原始的DOTA数据集，而是分割后的数据集，具体可看https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md

**Comment by 2505928188** [comment]
> I meet the same problem

The dataset used by mmrotate is not the original DOTA dataset, but the dataset after splitter. you can see in https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md

mmrotate不是用的原始的DOTA数据集，而是分割后的数据集，具体可看https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md
