### ISSUE TITLE
How can i implement instance segmentation with Oriented RCNN?

### ISSUE THREAD

**Issue by AOTY-szy** [open-mmlab/mmrotate#164]

**Comment by yangxue0827** [comment]
Instance segmentation is not supported by mmrotate yet, you need to implement it by yourself. We also welcome you to conduct PR to enrich mmrotate.

**Comment by AOTY-szy** [comment]
> Instance segmentation is not supported by mmrotate yet, you need to implement it by yourself. We also welcome you to conduct PR to enrich mmrotate.
Thanks for your reply.
