### ISSUE TITLE
进行多卡训练的时候会报错，请问你们自己进行过相应的测试吗

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#171]

**Comment by yangxue0827** [comment]
我的多卡命令是这样的，你可以参考一下：
```
CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29819 \
./tools/dist_train.sh configs/csl/rotated_retinanet_obb_csl_gaussian_r50_fpn_fp16_1x_dota_le90.py 4
```

**Comment by jiubie89** [comment]
> 我的多卡命令是这样的，你可以参考一下：
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29819 \
> ./tools/dist_train.sh configs/csl/rotated_retinanet_obb_csl_gaussian_r50_fpn_fp16_1x_dota_le90.py 4
> ```

您好，请问该如何进行非分布式多卡训练
