### ISSUE TITLE
Error occurs when runing the demo

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmrotate#174]
FileNotFoundError: file "/home/zgchen/PycharmProjects/mmrotate-main/work_dirs/oriented_rcnn_r50_fpn_1x_dota_v3/oriented_rcnn_r50_fpn_1x_dota_v3.py" does not exist

**Comment by yangxue0827** [comment]
The reason for the error is clearly described in the error message. Please check the file `/home/zgchen/PycharmProjects/mmrotate-main/work_dirs/oriented_rcnn_r50_fpn_1x_dota_v3/oriented_rcnn_r50_fpn_1x_dota_v3.py`.

**Comment by yangxue0827** [comment]
Download trained weight first, refer to
![image](https://user-images.githubusercontent.com/29257168/161183636-22d2d85c-faa1-498b-8825-fda9ea15d6aa.png)

**Comment by yangxue0827** [comment]
Fixed in https://github.com/open-mmlab/mmrotate/pull/137/commits/1c32e618b2bff6bb1c4ac8cc0dfc34d172a71b06
