### ISSUE TITLE
"IndexError: tuple index out of range" in mAP evaluation

### ISSUE THREAD

**Issue by Sabavid** [open-mmlab/mmrotate#178]
I used SSDD dataset to train the faster-rcnn model, and only modified the data_root in ssdd.py and _base_ in rotated_faster_rcnn_r50_fpn_1x_dota_le90.py. After training, an IndexError happened in /site-packages/mmrotate/core/evaluation/eval_map.py", line 304, in print_map_summary
    label_names[j]

Also, this error happened when i'm trying to use --eval mAP to evalutate test results.
I'm new in CV, and I've tried my best to figure it out, but I failed. It'll be really nice of you to help me, thank you!

**Comment by Sabavid** [comment]
After I delete the "label_names[j]" from that line, it can print part of the evaluation table like this:
+-------+-----+-------+--------+-------+
| class | gts | dets  | recall | ap    |
+-------+-----+-------+--------+-------+
| 401   | 785 | 0.332 | 0.120  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
| 0     | 0   | 0.000 | 0.000  |       |
+-------+-----+-------+--------+-------+
| mAP   |     |       |        | 0.120 |
+-------+-----+-------+--------+-------+
{'mAP': 0.11957745999097824}

**Comment by Sabavid** [comment]
Then I guess this is because the range of the for loop is "num_classes", but the len of label_names isn't equal to "num_classes" for some reasons. So I tried changing the for loop to "for j in range(len(label_names)):", and the outcome is quite logical:

+-------+-----+------+--------+-------+
| class | gts | dets | recall | ap    |
+-------+-----+------+--------+-------+
| ship  | 401 | 785  | 0.332  | 0.120 |
+-------+-----+------+--------+-------+
| mAP   |     |      |        | 0.120 |
+-------+-----+------+--------+-------+
{'mAP': 0.11957745999097824}

**Comment by liuyanyi** [comment]
I guess the `num_classes` of `bbox_head` is still 15 in your config. In SSDD, `num_classes` should be 1.

**Comment by Sabavid** [comment]
> I guess the `num_classes` of `bbox_head` is still 15 in your config. In SSDD, `num_classes` should be 1.

Thanks for your reply! This problem get solved, thank you again!
