### ISSUE TITLE
Demo run error

### ISSUE THREAD

**Issue by RicardioMu** [open-mmlab/mmrotate#180]
torch.nn.modules.module.ModuleAttributeError: 'RoIAlignRotated' object has no attribute 'output_size'
![image](https://user-images.githubusercontent.com/36025506/161380195-704bcafd-f96e-4a8b-8628-33e1ff2e8804.png)
![image](https://user-images.githubusercontent.com/36025506/161380216-8b4ed179-b48e-4cca-9c88-92ce248eaeb4.png)
THANKS

**Comment by yangxue0827** [comment]
refer to https://github.com/open-mmlab/mmrotate/pull/51

**Comment by zytx121** [comment]
Hi @RicardioMu 
This bug is already fixed in v0.1.1, please use the latest version.

**Comment by RicardioMu** [comment]
Hi@zytx121
I face a new issue :
![image](https://user-images.githubusercontent.com/36025506/161413667-f91bdb78-2aa1-416a-8e1d-99aab39ce39b.png)
![image](https://user-images.githubusercontent.com/36025506/161413714-ad25d914-78a3-40b4-9652-026afb68f600.png)

sys.platform: win32
Python: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1050 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
NVCC: Not Available
GCC: n/a
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.3
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.1
mmcv-full          1.4.5
mmdet              2.23.0
mmrotate           0.1.1

**Comment by RicardioMu** [comment]
> refer to #51

thx! but i face a new issue

**Comment by RicardioMu** [comment]
When I return to the original state, I can run the demo
![image](https://user-images.githubusercontent.com/36025506/161419610-6c52f7bd-f34a-4031-8ed7-5528f010765b.png)
