### ISSUE TITLE
Use KLD in horizontal object detection.

### ISSUE THREAD

**Issue by yxx-byte** [open-mmlab/mmrotate#181]
您好，博主，请问kld怎么一进去呢（水平框），我目前想把损失函数移到yolo里面，但我发现你的文件都带有旋转框。方便和我详细说说吗？2532070242@qq.com，万谢

**Comment by yangxue0827** [comment]
convert hbb to obb, then use kld. 
refer to 
https://github.com/open-mmlab/mmrotate/blob/b78bab24dc35657fe4e349d8c033e15848101eef/mmrotate/core/bbox/transforms.py#L221-L239
