### ISSUE TITLE
train models without cropping images

### ISSUE THREAD

**Issue by AllieLan** [open-mmlab/mmrotate#185]
I want to use my own data to tran GWD_hbb model, and the size of images is 1024*1024, which is not needed to crop .
I do not know how to prepare the dataset with dota format, if not crop data?
Is it right if I only revise the root in  dotav1.py?

**Comment by Anm-pinellia** [comment]
Crop image is used to better train the model, it's right to revise the root path.
It is noting that the num_classes in the config file of model also need to be set as your datasets.
The variable CLASSES in DOTA datasets also needs to be set as your datasets.

**Comment by zytx121** [comment]
If the annotation of the custom dataset is the same as DOTA‘s txt，you could revise the root in dotav1.py. Otherwise, we should convert it to DOTA‘s style first by https://github.com/ming71/toolbox/tree/master/converter/toDOTA
