### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by RicardioMu** [open-mmlab/mmrotate#186]
Hi@yangxue0827 
I face a new issue in train.py
installed cudann for cuda_v10.1
but in train.py: 
torch.backends.cudnn.benchmark = True
not found 'cudnn'  in  '__ init__. py 
![image](https://user-images.githubusercontent.com/36025506/161699595-ed2f6465-d15b-4b12-9f54-1f9b089424d8.png)

![image](https://user-images.githubusercontent.com/36025506/161699424-5a4a072b-33a2-4fd7-b23f-72f9c3460d0a.png)

**Comment by zytx121** [comment]
Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.

**Comment by RicardioMu** [comment]
sys.platform: win32
Python: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1050 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
NVCC: Not Available
GCC: n/a
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute
_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.3
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=O
N, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.8.0
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.1
MMRotate: 0.2.0+unknown
![image](https://user-images.githubusercontent.com/36025506/161719296-48c23ff7-bd61-463e-a20f-c761d95ebb07.png)

Maybe because my C disk will be full?

**Comment by yangxue0827** [comment]
Your graphics card is out of memory, you may need to use a graphics card with more memory/

**Comment by TolgaBkm** [comment]
I have solved the issue by running this before training:
`cfg["data"]["workers_per_gpu"]=0`
