### ISSUE TITLE
how to analysis .pkl file

### ISSUE THREAD

**Issue by AllieLan** [open-mmlab/mmrotate#188]
I use my own data with dota format (horizental boundding box) to train models.
I use configs/gwd/rotated_retinanet_**hbb**_gwd_r50_fpn_1x_dota_**oc**.py  as my configs.
And then I get a .pkl file through test.py.
I want to convert the .pkl file to the xml file.
I read there is a list, like  **[ 4.0548303e+02  3.3685107e+02  5.0923328e+00  6.4344110e+00  -4.5251951e-04  6.8603694e-01]**
I am not sure what is meaning of each number ? Maybe is [cx, cy, w, h, angle, conf] ? And this list is Definition of OpenCV  or Long Edge Definition90? or Long Edge Definition135?
Thanks a lot

**Comment by AllieLan** [comment]
So grateful for your reply.  By the way， I want to konw where to revise it if I save every .pth file and see val mAP 
after every epoch finished

**Comment by nijkah** [comment]
You may check [configs/\_base\_/schedules/schedule_1x.py](https://github.com/open-mmlab/mmrotate/blob/main/configs/_base_/schedules/schedule_1x.py).

Original file
```
# evaluation
evaluation = dict(interval=12, metric='mAP')
# optimizer
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=12)
```

Change
- evaluation = dict(interval=**1**, metric='mAP')
- checkpoint_config = dict(interval=**1**)

**Comment by nijkah** [comment]
@AllieLan Hi, I think we have to check this https://github.com/open-mmlab/mmrotate/issues/193.
I think the implementation uses the format of `(x_center, y_center, width, height, theta)` rather than `(x_center, y_center, height, width, theta)`.

**Comment by AllieLan** [comment]
I found that my opencv-python version is 4.5.3, according to the opencv definition, the angle should be in range [pi/2, 0), But when I print bbox, the angle seems is lower than 0°？ So what is it wrong?
![opencv](https://user-images.githubusercontent.com/94182491/162168412-d7e6bb93-9304-4e52-a8b1-194b4cc06120.png)
![image](https://user-images.githubusercontent.com/94182491/162168725-9a9e2f65-bcf6-4751-ab64-f493a3439ade.png)
![image](https://user-images.githubusercontent.com/94182491/162169342-2c4d18f6-329d-4424-a6d8-eaaf6bb17fe4.png)

I also want to format the results to submission text (standard format for DOTA evaluation), so what should I do to use test.py to get the standard format?
Thanks a lot!

**Comment by zytx121** [comment]
For the `oc` representation, we don't restrict the value range of the prediction angle like 'le'. The angles in the red box are very close to 0, so this does not affect the result. However, the submission file is in polygons format. You need to use the corresponding conversion function to convert rotated bounding boxes back to polygons format.
