### ISSUE TITLE
[Question] Which is correct  [cx, cy, w, h, angle] or [cx, cy, h, w, angle] ?

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmrotate#193]
In the implementation, it seems to have an object format such as [cx, cy, w, h, angle].
https://github.com/open-mmlab/mmrotate/blob/b78bab24dc35657fe4e349d8c033e15848101eef/mmrotate/core/bbox/transforms.py#L103.

But in the document [intro.md](https://github.com/open-mmlab/mmrotate/blob/main/docs/en/intro.md#what-is-rotated-box), it seems to explain as 
[x_center, y_center, height, width, theta].

Should the document be fixed?

**Comment by zytx121** [comment]
This is related to #157

For OpenCV height and width have no specific meaning. In this repo, h only represents the third parameter and w represents the fourth parameter.

Typo in `transforms.py`: [x_ctr,y_ctr,w,h,angle] -> [x_ctr,y_ctr,h,w,angle].

**Comment by nijkah** [comment]
@zytx121 Then, docstring in `transforms.py` should be corrected?

**Comment by zytx121** [comment]
Yes, it should be corrected. Thank you for your kind reminder.

**Comment by nijkah** [comment]
@zytx121  I am so sorry to ask again. I would like to ask if the name of the variables should also be changed.
Currently transform functions use the variable name as `[x_ctr, y_ctr, width, height, angles]`.

https://github.com/open-mmlab/mmrotate/blob/b78bab24dc35657fe4e349d8c033e15848101eef/mmrotate/core/bbox/transforms.py#L298

https://github.com/open-mmlab/mmrotate/blob/b78bab24dc35657fe4e349d8c033e15848101eef/mmrotate/core/bbox/transforms.py#L390

https://github.com/open-mmlab/mmrotate/blob/b78bab24dc35657fe4e349d8c033e15848101eef/mmrotate/core/bbox/transforms.py#L458

**Comment by kimlia545** [comment]
@zytx121 

I am trying to return the modified box coordinates back to their original values.
Where might the error occur?

```
# model box result(le90) : [x_ctr,y_ctr,w,h,angle]
# obb2xyxy_le90 : [x_ctr,y_ctr,w,h,angle] -> [x_lt,y_lt,x_rb,y_rb]
# hbb2obb_le90 : [x_lt,y_lt,x_rb,y_rb] -> [x_ctr,y_ctr,w,h,angle]

result = torch.FloatTensor([[3.7863e+02, 1.9907e+02, 
1.4659e+02, 1.3453e+01, -5.8097e-01]])
print('model result', result)
hbb = obb2xyxy_le90(result)
print('hbb', hbb)
obb = hbb2obb_le90(hbb)
print('obb', obb)
```
![Screenshot from 2022-11-02 16-49-12](https://user-images.githubusercontent.com/72369991/199430349-c0d0b293-2b61-414e-8e1d-8fbdd7fea71b.png)

**Comment by Petros626** [comment]
@kimlia545 did you succeed?
