### ISSUE TITLE
Allow extra dataloader settings in config

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmrotate#194]
## Describe the feature

Add `train_dataloader`, `val_dataloader`, and `test_dataloader` in the data field of config so that users can specify different arguments for them.

## Motivation

Originally, the data field of config only allows the following usage:

```python
data = dict(
    samples_per_gpu=64, workers_per_gpu=4,
    train=dict(type='xxx', ...),
    val=dict(type='xxx', samples_per_gpu=4, ...),
    test=dict(type='xxx', ...),
)
```

Such a design only allows to set different batch size in val and test data loader.
Adding `train_dataloader`, `val_dataloader`, and `test_dataloader` in the data field of config allows more flexible usages.
A new example looks like below:

```python
data = dict(
    train=dict(type='xxx', ...),
    val=dict(type='xxx', ...),
    test=dict(type='xxx', ...),
    # Use different batch size during inference.
    train_dataloader=dict(samples_per_gpu=64, workers_per_gpu=4),
    val_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
    test_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
)
```

To achieve that, we should:
1. allow train_dataloader/val_dataloader/test_dataloader to be set in the data filed by modifying `train_detector`.
2. deprecate `samples_per_gpu` in data.val field by raising warnings if it is set

**Related resources**
See PR https://github.com/open-mmlab/mmclassification/pull/752.

**Additional context**

**Comment by zytx121** [comment]
Get.
