### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#198]
Does mmdetection support random rotation, flipping, and graying?
How to configure it

**Comment by zytx121** [comment]
We support random rotation and flipping, you could refer to https://github.com/open-mmlab/mmrotate/blob/main/configs/roi_trans/roi_trans_r50_fpn_1x_dota_ms_rr_le90.py

**Comment by ogencoglu** [comment]
Can we incorporate our custom augmentations using `albumentations` library?
