### ISSUE TITLE
TypeError: object of type 'GeometricTensor' has no len()

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#211]
backbone=dict(
        type='ReResNet',
        depth=50,
        num_stages=4,
        in_channels=3,
        stem_channels=64,
        base_channels=64,
        expansion=None,
        strides=(1, 2, 2, 2),
        dilations=(1, 1, 1, 1),
        out_indices=(3,),
        style='pytorch',
        deep_stem=False,
        avg_down=False,
        frozen_stages=-1,
        conv_cfg=None,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        with_cp=False,
        zero_init_residual=True,
        pretrained=None,
        init_cfg=None,

This error occurs when the backbone of s2anet is modified to the reresnet that 
comes with the file

**Comment by liuyanyi** [comment]
When using ReResNet, i think you need to use ReFPN too. You can refer to ReDet config

**Comment by zytx121** [comment]
The output of ReResNet is GeometricTensor, if you want to use FPN, you need to modify the output of ReResNet or just use ReFPN.

**Comment by milamiqi** [comment]
OK, thanks, but I still have this problem when I set refpn. This is my parameter 
    neck=dict(
        type='ReFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5,

**Comment by milamiqi** [comment]
Thank you for your diagram, but I still show the same problem when I use the p
arameters you give. What I use s2anet

angle_version = 'le135'
model = dict(
    type='S2ANet',
    backbone=dict(
        type='ReResNet',
        depth=50,
        in_channels=3,
        stem_channels=64,
        base_channels=64,
        expansion=None,
        num_stages=4,
        strides=(1, 2, 2, 2),
        dilations=(1, 1, 1, 1),
        out_indices=(3,),
        style='pytorch',
        deep_stem=False,
        avg_down=False,
        frozen_stages=-1,
        conv_cfg=None,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        with_cp=False,
        zero_init_residual=True,
        pretrained=None,
        init_cfg=None),
    neck=dict(
        type='ReFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,     # don't forget!!
        add_extra_convs='on_input',
        num_outs=5),

**Comment by zytx121** [comment]
Your config about the backbone looks wrong, `Swin` and `ReResNet` are mixed up. You can try:

```
_base_ = 's2anet_r50_fpn_1x_dota_le135.py'


model = dict(
    backbone=dict(
        _delete_=True,
        type='ReResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        pretrained=None),
    neck=dict(
        _delete_=True,
        type='ReFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,     # don't forget!!
        add_extra_convs='on_input',
        num_outs=5))

```

**Comment by LyoungOVO** [comment]
> 

How can I convert the GeometricTensor to normal tensor?

**Comment by LyoungOVO** [comment]
> The output of ReResNet is GeometricTensor, if you want to use FPN, you need to modify the output of ReResNet or just use ReFPN.

How can I convert the GeometricTensor to normal tensor?

**Comment by zytx121** [comment]
Just like [this](https://github.com/open-mmlab/mmrotate/blob/df125d7121d9d4074d1ccfdec60fd65ce58ff7d8/mmrotate/models/necks/re_fpn.py#L322-323)
```
# convert GeometricTensor to Tensor
outs = [out.tensor for out in outs]
```

**Comment by LyoungOVO** [comment]
ok，thanks
