### ISSUE TITLE
关于新版本mAP评估方法与之前版本不同的问题

### ISSUE THREAD

**Issue by so-bright** [open-mmlab/mmrotate#212]
您好，我在之前版本训练好的模型，在后来的新版本进行测试的时候，相比之前版本测试的结果mAP降低了3左右，
我查看代码，发现评估方法改变了，是加入了旋转角度值吗？

**Comment by yangxue0827** [comment]
Where has the evaluation method changed? Please provide detailed information for our analysis.
Also, have you retrained the model with the new code?

**Comment by so-bright** [comment]
Thanks for your relpy.
I have trained in the new version, the same code settings but the results obtained are lower than the previous training results.
The older versions of the evaluation code are available in mmrotate/datasets/dota.py
![image](https://user-images.githubusercontent.com/67722868/162939342-83156a37-3efe-41f2-b155-095f7e26a7a4.png)
The new versions of the evaluation coda are available in mmrotate/core/evaluation/eval_map.py
![image](https://user-images.githubusercontent.com/67722868/162939635-1211d384-88ae-4e5c-bd2e-4135bd66d220.png)

**Comment by yangxue0827** [comment]
For the DOTA dataset, we recommend using the [official evaluation script](https://github.com/CAPTAIN-WHU/DOTA_devkit).
The `mAP` output during training are for reference only.

**Comment by so-bright** [comment]
Thank you. What are the changes in the current version of the mAP evaluation method compared to the old version?

**Comment by yangxue0827** [comment]
@liuyanyi 
https://github.com/open-mmlab/mmrotate/pull/73

**Comment by liuyanyi** [comment]
I compare the code, there's one difference between two version. In old version version we use voc12 metric to evaluate, after #73 we use voc07 metric by default. 
You can just modify `use_07_metric=False` and check the mAP of your model.
I think it's better to add a flag to control voc07/12, thanks for you report.

**Comment by yangxue0827** [comment]
07 metric will usually be lower than 12 metric

**Comment by so-bright** [comment]
Thank you very much for your patient responses! I understand the problem now.
