### ISSUE TITLE
About splitting images

### ISSUE THREAD

**Issue by galaxyGGG** [open-mmlab/mmrotate#214]
When splitting original images into small ones, I found that the results are different between mmrotate and official s2anet code, which are:
 1. The filenames of the images split by s2anet contain the "rate" which shows the zoom rate of the image, while the names in mmrotate don't.
 2. The images are all resized to 1024*1024 in s2anet while mmrotate not.

I'm wondering these difference will affect the process when I use the results in mmrotate to do merge & get mAP via DOTA_devkit?
Also, can I simply use the images and annotations made by official s2anet code, to train in mmrotate?

**Comment by yangxue0827** [comment]
Some details do vary, because we need to unify many methods. We're not sure what the impact of these differences will be, but we recommend using the ones we provide.

**Comment by galaxyGGG** [comment]
Very much appreciated!
