### ISSUE TITLE
Try combining swin-Transform and s2anet

### ISSUE THREAD

**Issue by juzh1998** [open-mmlab/mmrotate#217]
I trained config/oriented rcnn/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py and got a map of 76. Later, I tried to combine swin-transformer and s2anet according to the file, but the final test map was almost 0. My configuration file and results are as follows, what may be the problem.

config file(follow the oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py ):
```
_base_ = ['./s2anet_r50_fpn_1x_dota_le135.py']

pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa

model = dict(
    backbone=dict(
        _delete_=True,
        type='SwinTransformer',
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(0, 1, 2, 3),
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)),
    neck=dict(
        _delete_=True,
        type='FPN',
        in_channels=[96, 192, 384, 768],
        out_channels=256,
        num_outs=5))

optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))
```

and the val result:
[>>>>>>>>>>>>>>>>>>>>>>>>] 12800/12800, 9.9 task/s, elapsed: 1287s, ETA:     0s
+--------------------+-------+--------+--------+-------+
| class              | gts   | dets   | recall | ap    |
+--------------------+-------+--------+--------+-------+
| plane              | 18788 | 181350 | 0.148  | 0.095 |
| baseball-diamond   | 1087  | 26009  | 0.101  | 0.006 |
| bridge             | 4183  | 0      | 0.000  | 0.000 |
| ground-track-field | 733   | 4791   | 0.041  | 0.018 |
| small-vehicle      | 58868 | 274047 | 0.033  | 0.045 |
| large-vehicle      | 43075 | 275107 | 0.035  | 0.003 |
| ship               | 76153 | 246661 | 0.037  | 0.022 |
| tennis-court       | 5923  | 65863  | 0.191  | 0.097 |
| basketball-court   | 1180  | 36163  | 0.130  | 0.046 |
| storage-tank       | 13670 | 102725 | 0.059  | 0.091 |
| soccer-ball-field  | 827   | 9698   | 0.098  | 0.010 |
| roundabout         | 973   | 7898   | 0.012  | 0.018 |
| harbor             | 15468 | 177240 | 0.033  | 0.002 |
| swimming-pool      | 3836  | 26019  | 0.030  | 0.001 |
| helicopter         | 1189  | 9280   | 0.047  | 0.014 |
+--------------------+-------+--------+--------+-------+
| mAP                |       |        |        | 0.031 |
+--------------------+-------+--------+--------+-------+
{'mAP': 0.031172679737210274}

**Comment by zytx121** [comment]
Hi @juzh1998 

For the single-stage detector, the FPN config should be:
```
    neck=dict(
        type='FPN',
        in_channels=[96, 192, 384, 768],
        out_channels=256,
        start_level=1,     # don't forget!!
        add_extra_convs='on_input',
        num_outs=5),
```

And this picture may help you understand:

![image](https://user-images.githubusercontent.com/10410257/163294457-b9ab3a8c-7f67-49bf-8349-ac1ac9c082dc.png)

**Comment by juzh1998** [comment]
Thanks for your help, I will experiment soon
