### ISSUE TITLE
Inf Time (fps)

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#218]
FPS test in the retinanet configuration file is 15.7 or 16.9 while in the faster r-cnn configuration file is 16.5.  I want to know why the two-stage network and the single-stage network detection speed is basically the same.  Calculate the picture test time of all test sets by running the test command. Can I calculate the FPS in this way?  If not, what is the correct approach?

**Comment by yangxue0827** [comment]
`python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py YOUR_CFG YOUR_MODEL --launcher pytorch`

**Comment by houw0517** [comment]
![image](https://user-images.githubusercontent.com/86358057/163220272-8e08edf4-6205-4c79-9c7c-3e29549bc706.png)

**Comment by yangxue0827** [comment]
`YOUR_CFG`

**Comment by houw0517** [comment]
Thanks a lot. I got it . I also want to know how the parameter is calculated.

**Comment by yangxue0827** [comment]
Read the code yourself first.

**Comment by zjs210** [comment]
> Thanks a lot. I got it . I also want to know how the parameter is calculated.

Hello, did you solve this bug
