### ISSUE TITLE
add GWD loss to other models

### ISSUE THREAD

**Issue by AllieLan** [open-mmlab/mmrotate#219]
GWD loss is so useful that I want to use it to replace  SmoothL1Loss in the config  '/mmrotate/configs/oriented_rcnn/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py ' , which depend on
  '/mmrotate/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py'.

I tried to convert **the line 44** to  **loss_bbox=dict(type='GDLoss', loss_type='gwd', loss_weight=5.0),**,
but it failed, like following picture.
![gwd](https://user-images.githubusercontent.com/94182491/163217878-9c239473-bfb7-413a-8b14-d4c498595388.png)

I think perhaps there is somewhere still need to further revice. What else should I do?
Thanks!

**Comment by zytx121** [comment]
Please check the format of your config. it looks like missing parenthesis.
