### ISSUE TITLE
evaluation standard

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#220]
How to change the voc evaluation standard to the coco evaluation standard？

**Comment by yangxue0827** [comment]
Coco-style evaluation is not supported for now, you need to implement it yourself.

**Comment by yangxue0827** [comment]
By modifying the coco evaluation script.

**Comment by houw0517** [comment]
I try to do precision-recall curve plot with pkl file.It is found that pkl saves a 453*6 dimension of data，453 represents the size of the HRSC2016 test set，but what does the number 6 mean?
The first four data are on the order of 10*2.The latter two data are on the order of 10*(-1)

**Comment by Petros626** [comment]
@houw0517 What you mean by 6? 

To implement COCO evaluation metrics follow this code https://github.com/ultralytics/ultralytics/blob/e91a4969ea4440b02f052f3b15c0b279b5fa2af1/ultralytics/utils/metrics.py#L540
