### ISSUE TITLE
quesition about lr

### ISSUE THREAD

**Issue by zjutlouis1011** [open-mmlab/mmrotate#225]
hello,i want to train kld (r3det_tiny_kld_r50) with multi-scale, i use 4 gpu (2080ti) and i set sample_per_gpu = 2,  so what is the suitabke lr i should set?

**Comment by zytx121** [comment]
The lr should be 0.0025 *4 = 0.01.
However, limited by the size of the data set, it does not meet the linear scaling of the learning rate.
Refer to #59

**Comment by zjutlouis1011** [comment]
> The lr should be 0.0025 *4 = 0.01. However, limited by the size of the data set, it does not meet the linear scaling of the learning rate. Refer to #59

thank you for your reply,i will try it
