### ISSUE TITLE
Question about GWD distance calculation

### ISSUE THREAD

**Issue by ged0606** [open-mmlab/mmrotate#226]
Does GWD loss implementation in gaussian_dist_loss.py is same as origin paper? The result distance in gaussian_dist_loss.py line 148 has a sqrt() operation, that is different in the paper.

equation(3) in paper

![2022-04-15 10-44-12屏幕截图](https://user-images.githubusercontent.com/21331521/163509797-7f9f2b86-e304-45a2-9000-661a0d594aa7.png)

line 148
```
distance = (xy_distance + alpha * alpha * whr_distance).clamp(1e-7).sqrt()

```

**Comment by yangxue0827** [comment]
There two verson about gwd: [gaussian_dist_loss](https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/models/losses/gaussian_dist_loss.py) and [gaussian_dist_loss_v1](https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/models/losses/gaussian_dist_loss_v1.py). `gaussian_dist_loss_v1` is used by default. There are some differences in the implementation, as you pointed out.
You also can use the `gaussian_dist_loss`, which is the same as described in the paper. 
The following is the configuration file of `gaussian_dist_loss`, which can achieve the performance close to the current default version.

```
_base_ = ['../rotated_retinanet/rotated_retinanet_hbb_r50_fpn_1x_dota_oc.py']

model = dict(
    bbox_head=dict(
        reg_decoded_bbox=True,
        loss_bbox=dict(
            type='GDLoss',
            loss_type='gwd',
            normalize=False,
            loss_weight=0.5)))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal']),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
data = dict(train=dict(pipeline=train_pipeline))
```

**Comment by ged0606** [comment]
thanks

**Comment by yangxue0827** [comment]
Sorry, there was a mistake in the explanation just now, it has now been updated.

**Comment by ged0606** [comment]
Very much appreciated
