### ISSUE TITLE
Question about the target_stds value in bbox_coder

### ISSUE THREAD

**Issue by LiaoYujia** [open-mmlab/mmrotate#227]
Thank you very much to the author of mmrotate. In the process of using mmrotate, I compared mmrotate and redet detection framework, and found that the target_stds value in bbox_coder in the config is different between the two frameworks.

In mmrotate configs/roi_trans/roi_trans_r50_fpn_1x_dota_le90.py，the target_stds value of the first bbox_head is [0.1, 0.1, 0.2, 0.2, 1].
while in redet detection framework, the target_stds value of the first bbox_head is target_stds=[0.1, 0.1, 0.2, 0.2, 0.1].

For example,in configs/roi_trans/roi_trans_r50_fpn_1x_dota_le90.py
     
```
bbox_head=[
          dict(
              type='RotatedShared2FCBBoxHead',
              in_channels=256,
              fc_out_channels=1024,
              roi_feat_size=7,
              num_classes=15,
              bbox_coder=dict(
                  type='DeltaXYWHAHBBoxCoder',
                  angle_range=angle_version,
                  norm_factor=2,
                  edge_swap=True,
                  target_means=[0., 0., 0., 0., 0.],
                  **_### target_stds=[0.1, 0.1, 0.2, 0.2, 1])_**,
              reg_class_agnostic=True,
              loss_cls=dict(
                  type='CrossEntropyLoss',
                  use_sigmoid=False,
                  loss_weight=1.0),
              loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                             loss_weight=1.0)),
```

I want to ask why the target_stds value of the angle is 10 times worse? How did you get this value ？Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by yangxue0827** [comment]
Thanks for your question. I think it should be a small mistake on our part. Since we haven't conducted any relevant experiments, we can't tell how much of an impact this error has.

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/issues/202

**Comment by LiaoYujia** [comment]
Thank you for your answer, the target_stds value has a great impact on my experimental dataset.
