### ISSUE TITLE
运行demo.py,报错：warnings.warn('DeprecationWarning: anchor_generator is deprecated, '

### ISSUE THREAD

**Issue by Rocky-YU** [open-mmlab/mmrotate#229]
感谢您们提供的mmrotate, 推荐的安装配置方式都进行了尝试，最后还是运行demo.py报错，不知道怎么解决，错误如下，十分感谢您的帮助。
load checkpoint from local path: weights/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth
D:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior
_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '

**Comment by zytx121** [comment]
This is a warning caused by MMDetection, It does not affect the program. We need more error logs.

**Comment by Rocky-YU** [comment]
Thanks for reply. 

(openmmlab) E:\RotateDetection\mmrotate-main>python demo/image_demo.py demo/demo.jpg configs\rotated_faster_rcnn\rotated_faster_rcnn_r50_fpn_1x_dota_le90.py weights/rotated_faster_rcnn_
r50_fpn_1x_dota_le90-0393aa5c.pth demo/vis.jpg

D:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or a
lso use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: weights/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth
D:\ProgramData\Anaconda3\envs\openmmlab\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior
_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '

**Comment by zytx121** [comment]
Does the program stop? As I said above, This warning will not affect the running of the program.

**Comment by Rocky-YU** [comment]
It really did not affect the operation of the program. I'm sorry, I thought it would affect the program, thank you very much for replying.

**Comment by 123456hxh** [comment]
I'm having the same issue, I don't know what is the reason for this, I don't know how to fix it. Thank you
root@autodl-container-1350118f3c-0ef6eee1:~/mmrotate-main# python demo/image_demo.py demo/demo.jpg configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py weights/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth demo/1.jpg
/root/miniconda3/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
usage: image_demo.py [-h] [--out-file OUT_FILE] [--device DEVICE] [--palette {dota,sar,hrsc,hrsc_classwise,random}] [--score-thr SCORE_THR]
                     img config checkpoint
image_demo.py: error: unrecognized arguments: demo/1.jpg
