### ISSUE TITLE
more congfig results

### ISSUE THREAD

**Issue by lina926** [open-mmlab/mmrotate#230]
could you tell me the results of DOTA1.0 under the config  ''r3det_kfiou_ln_swin_tiny_adamw_fpn_1x_dota_ms_rr_oc.py '' and ''roi_trans_kfiou_ln_swin_tiny_fpn_1x_dota_ms_le90.py ? thank you very much

**Comment by yangxue0827** [comment]
you can refer to the [paper](https://arxiv.org/abs/2201.12558)

**Comment by lina926** [comment]
I want to know how much can be achieved on mmrotate,  is it consistent with the results in the paper?

**Comment by yangxue0827** [comment]
The results in the paper were tested by the code before mmrotate was released. As for this version, I'm not sure, so we don't give performance, weight and log in README.

**Comment by yangxue0827** [comment]
Results in paper: 
![image](https://user-images.githubusercontent.com/29257168/163708362-a42ddff6-df15-4615-97d9-35f438342b8d.png)

**Comment by lina926** [comment]
OK，i will try to run it

**Comment by lina926** [comment]
I run the  roi_trans_kfiou_ln_swin_tiny_fpn_1x_dota_ms_le90, however, the loss don't decreases and mAP is 0, is existing bug?

**Comment by yangxue0827** [comment]
Same issue about `roi_trans_kfiou_ln_swin_tiny_fpn_1x_dota_ms_le90`  as https://github.com/open-mmlab/mmrotate/issues/236

**Comment by yangxue0827** [comment]
We will discuss in https://github.com/open-mmlab/mmrotate/issues/236, so we close this issue.
