### ISSUE TITLE
Hello, is there any way to speed up the test process?

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#231]

**Comment by yangxue0827** [comment]
use `fp16`, reduce image size

**Comment by zytx121** [comment]
MMRotate will soon support onnxruntime and tensorRT!

**Comment by hust-lidelong** [comment]
The page is not found. How to use fp16? Thanks!
https://github.com/open-mmlab/mmrotate/blob/main/configs/oriented_rcnn_r50_fpn_fp16_1x_dota_le90.py
https://github.com/open-mmlab/mmrotate/blob/main/configs/redet_re50_refpn_fp16_1x_dota_le90.py

**Comment by DSPresearchlrj** [comment]
> MMRotate will soon support onnxruntime and tensorRT!
Isn't MMRotate support TensorRT now?

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmrotate.md
@DSPresearchlrj
