### ISSUE TITLE
[Bug] An error occurs in rotate_reppoints_head after modifying samples_per_gpu

### ISSUE THREAD

**Issue by tongalitong** [open-mmlab/mmrotate#232]
修改configs/_base_/datasets/dotav1.py
原samples_per_gpu=2
改为samples_per_gpu=8

报错：
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/focal_loss.py", line 40, in forward
    assert input.size(0) == target.size(0)

![image](https://user-images.githubusercontent.com/73646436/163715113-c8116a3e-578d-4f67-b6ea-9538ef770bb4.png)

**Comment by zytx121** [comment]
What version of mmrotate do you use？

**Comment by jiwei0731** [comment]
v0.2.0

**Comment by tongalitong** [comment]
issue config: mmrotate/cofigs/rotated_reppoints/rotated_reppoints_r50_fpn_1x_dota_oc.py

**Comment by qixiong-wang** [comment]
Change rotated_reppoints_head.py
`all_overlaps_rotate_list = [None] * 4`
to
`all_overlaps_rotate_list = [None] * len(proposals_list)`

**Comment by yangxue0827** [comment]
thx!

**Comment by tongalitong** [comment]
> Change rotated_reppoints_head.py `all_overlaps_rotate_list = [None] * 4` to `all_overlaps_rotate_list = [None] * len(proposals_list)`

helpful, thanks!
