### ISSUE TITLE
是否支持其他尺寸的图片输入而不用转化为DOTA类型1024*1024尺寸的图片？

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#237]
我的数据集图片尺寸是640 and 512，按照入门文档我利用**tools/data/dota/split/img_split.py**将其转化为了DOTA格式数据集，但是DOTA格式数据集图片尺寸是1024 and 1024的正方形，我的图片转化完只是左上角的一部分，其余部分都是填充像素，可以通过修改哪个文件支持640 and 512尺寸的输入图片吗？
此外，将640 and 512尺寸转化为1024*1024是否会影响检测的精度？我发现训练后的mAP只能达到60左右，我怀疑是不是填充的像素会干扰检测的结果。

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/blob/df125d7121d9d4074d1ccfdec60fd65ce58ff7d8/tools/data/dota/split/img_split.py#L55-L66

**Comment by hh123445** [comment]
> https://github.com/open-mmlab/mmrotate/blob/df125d7121d9d4074d1ccfdec60fd65ce58ff7d8/tools/data/dota/split/img_split.py#L55-L66

--gaps参数代表的什么意思？因为我的图片不是正方形，应该如何修改才能符合宽为640，高为512的输入呢？

**Comment by yangxue0827** [comment]
Maybe your dataset doesn't need to be cropped, just like the HRSC2016 dataset.

**Comment by hh123445** [comment]
我也是这么想的，如果不需要裁剪原来的数据集，我应当如何处理原有的数据集以适应mmrotate的训练数据集格式要求呢？是否有相关的介绍文档，我似乎没有找到，或者需要利用哪个文件进行转化呢？非常感谢您的回答！

**Comment by yangxue0827** [comment]
Refer to https://github.com/open-mmlab/mmrotate/tree/main/tools/data. 
Convert your annotations to one of the dataset formats. Or you can write a dataloader based on your own annotations.

**Comment by zytx121** [comment]
You can try https://github.com/ming71/toolbox/tree/master/converter/toDOTA

**Comment by hh123445** [comment]
> You can try https://github.com/ming71/toolbox/tree/master/converter/toDOTA

感谢你的答复！我解决了我的问题通过将tools/data/dota/split/split_configs/ss_trainval.json文件中的"sizes"设置为640，将"gaps"设置为512，将"no_padding"参数设置为true，这样就能保持原样了。
然而我训练的结果mAP没有得到提高仍然只能达到60左右，我还在寻找解决的方案。

**Comment by RS-Hong** [comment]
裁剪保持原样后，还需要做哪些设置可以使用这个尺度的数据集进行训练呢？你的所有数据都是640*512吗？

**Comment by hh123445** [comment]
> 裁剪保持原样后，还需要做哪些设置可以使用这个尺度的数据集进行训练呢？你的所有数据都是640*512吗？

还需要将网络config文件中所有1000尺度全部修改为你对应的尺度，是的，我的所有数据集都是640*512

**Comment by hh123445** [comment]
> 裁剪保持原样后，还需要做哪些设置可以使用这个尺度的数据集进行训练呢？你的所有数据都是640*512吗？

还需要将网络config文件中所有1024尺度全部修改为你对应的尺度，是的，我的所有数据集都是640*512
