### ISSUE TITLE
How to apply kfiou to an anchor free network？

### ISSUE THREAD

**Issue by JinYuannn** [open-mmlab/mmrotate#238]
I wanted to replace GIoU in TTFNet with kfiou to enable the detection of the rotated box, but the kfiou loss has been changing between 0.95-0.99 and will not go down. I use the real coordinates of the box to calculate the kfiou, not the offset.

I see that the regression equation in the paper requires the anchor box, but this doesn't exist in the anchor free detector.

In addition, when the anchor free network is just started training, Sigma_p.det() will get a negative number, so its sqrt() will be equal to nan, and it will need to be clamp(min=0).

Please give me some advice.

**Comment by yangxue0827** [comment]
In fact, the covariance of the Gaussian distribution corresponding to a bounding box should be positive definite, and the determinant should be greater than zero (`Sigma_p.det()>0`). The reason for the negative number may be that the predicted value is `inf`, so some restrictions may need to be added, such as `clamp(min=1e-5)` before using `sqrt()`.

**Comment by yangxue0827** [comment]
PR https://github.com/open-mmlab/mmrotate/pull/223 supports `FCOS+KLD`.

**Comment by JinYuannn** [comment]
Thank you for your reply and thank you for your work

**Comment by JinYuannn** [comment]
> PR #223 supports `FCOS+KLD`.

I verified that KLD is valid on anchor free detecoter (TTFNet), but why does KFIoU not work?

**Comment by yangxue0827** [comment]
There may be many reasons for this, and I can't make an deep analysis based on your description.
By the way, does KLD work on TTFNet?
