### ISSUE TITLE
GPU Memory Increase

### ISSUE THREAD

**Issue by ekarem** [open-mmlab/mmrotate#239]
Hello,

I think that there is a problem in the code to increase used memory of GPU.

I have custom data set and it's converted to DOTA format. When I'm trying to train Oriented R-CNN model (ResNET-50 backbone and 1 batch size) with my custom data, GPU memory is increasing unexpectedly starting from approx 5 GB to 16 GB and more. My GPU is Titan RTX. I haven't found which part of the code cause this problem yet.

![Screenshot from 2022-04-19 17-18-53](https://user-images.githubusercontent.com/3832397/164027623-97403f89-9f39-4b76-80da-dc0cc38cb0b9.png)

**Comment by KiaLAN** [comment]
Hi, have you fixed this problem? I met this problem too.
