### ISSUE TITLE
No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by Dami1126** [open-mmlab/mmrotate#24]
I run the demo and get the error:
No module named 'mmcv._ext'

**Comment by zytx121** [comment]
Hi @Dami1126 
This is because `mmcv-full` is not compiled. You can refer to MMCV [doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install the compiled version.

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/blob/main/docs/en/faq.md
