### ISSUE TITLE
HRSC reimplementations for other methods

### ISSUE THREAD

**Issue by xiaoyihit** [open-mmlab/mmrotate#240]
I wonder if there is an MMRotate reimplementation for HRSC with other methods aside from s2anet and rotated retinanet.
I tried to replace the code in line 54` loss_bbox=dict(type='L1Loss', loss_weight=1.0)),` in 
`configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_3x_hrsc_le90.py` with 
`loss_bbox=dict(type='GDLoss', loss_type='gwd', loss_weight=5.0)),`
` loss_bbox=dict(type='KFLoss', loss_weight=5.0)),`
```
loss_bbox=dict(
    type='GDLoss_v1',
    loss_type='kld',
    fun='log1p',
    tau=1,
    loss_weight=1.0)),
```
respectively, however none of them worked... 
Their loss goes nan.
Guess I could get some help here?

**Comment by yangxue0827** [comment]
Refer to https://github.com/open-mmlab/mmrotate/pull/183

**Comment by xiaoyihit** [comment]
Thx for the quick reply.
I get it for the stable kld case. How about GWD and KFLoss?
```
loss_bbox=dict(type='GDLoss', loss_type='gwd', loss_weight=5.0)),
loss_bbox=dict(type='KFLoss', loss_weight=5.0)),
```

**Comment by yangxue0827** [comment]
It has not been reproduced on hrsc yet, but I think it should be similar to kld. Someone in Issue https://github.com/open-mmlab/mmrotate/pull/203 ran successfully ran gwd on hrsc.

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/164042411-f73becf6-9063-4b6a-b945-4acd67bd8738.png)
copy from https://github.com/open-mmlab/mmrotate/issues/202
