### ISSUE TITLE
Hope to support the tool to transfer onnx.

### ISSUE THREAD

**Issue by xiaoshun1007** [open-mmlab/mmrotate#247]
将咱们的模型（如s2anet）转换为onnx格式,希望平台提供转换工具、文档指导。

**Comment by xiaoshun85** [comment]
I am a novice and can use our platform for model training through document support, but it is difficult for me to convert our model (such as s2anet) to onnx format. I hope the platform can provide conversion tools and document guidance

**Comment by yangxue0827** [comment]
MMRotate will soon support onnxruntime and tensorRT.

**Comment by yangxue0827** [comment]
Unofficial example:
https://itcn.blog/p/1649708301163974.html

**Comment by xiaoshun1007** [comment]
> Unofficial example: https://itcn.blog/p/1649708301163974.html

谢谢，我也注意到了类似的文章：https://blog.csdn.net/sxj731533730/article/details/124107625，包含了mnn部署和ncnn部署，正在研究中。

Thank you. I also noticed similar articles: https://blog.csdn.net/sxj731533730/article/details/124107625 , including MNN deployment and ncnn deployment, which I am studying.

**Comment by chandrakanth-gudavalli** [comment]
> Unofficial example: https://itcn.blog/p/1649708301163974.html

It is saying that the link is invalid

**Comment by yangxue0827** [comment]
@chandrakanth-gudavalli 
https://blog.csdn.net/sxj731533730/article/details/124107625
