### ISSUE TITLE
How does multi scale dataset proceed?

### ISSUE THREAD

**Issue by adonis-dym** [open-mmlab/mmrotate#250]
In splitting the DOTA dataset, to get multiscale dataset we are suggested to use the command `python tools/data/dota/split/img_split.py --base_json tools/data/dota/split/split_configs/ms_trainval.json`, where the paramenter `sizes` is set to `1024` and `rates` is set to `[0.5, 1.0, 1.5]` by default. So how does the model handle with the data images with different sizes? 
I observe that there is a `RResize` operation before training [(https://github.com/open-mmlab/mmrotate/blob/main/configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_ms_rr_le90.py#L10),](https://github.com/open-mmlab/mmrotate/blob/main/configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_ms_rr_le90.py#L10) is this the way that mmrotate unify images size before feeding into the models?

**Comment by zytx121** [comment]
Hi @adonis-dym 
It's really confusing here. In fact, we will resize the pictures before splitting, which can handle images of different sizes. It should be emphasized that the image size after splitting is uniform, which is `1024 * 1024`. This is a little different from the usual multi-scale, but related papers generally do so.
