### ISSUE TITLE
type of image and detect one image

### ISSUE THREAD

**Issue by Ashionnal** [open-mmlab/mmrotate#251]
hello:
  **Q1:**
     The type of input image is only '.png'? I use the DOTA config, it seems like only png picture
  **Q2:**
     'test.py' can only detect the directory pictures. Can i use one picture path to detect?

**Comment by liuyanyi** [comment]
I think other image formats are also supported, hsrc dataset use *.bmp. You can follow the `LoadImageFromFile` pipeline in mmdetection.

For single image inference you can follow scripts in demo https://github.com/open-mmlab/mmrotate/tree/main/demo

**Comment by Ashionnal** [comment]
> I think other image formats are also supported, hsrc dataset use *.bmp. You can follow the `LoadImageFromFile` pipeline in mmdetection.
> 
> For single image inference you can follow scripts in demo https://github.com/open-mmlab/mmrotate/tree/main/demo

ok  thank you
