### ISSUE TITLE
Question about test on custom dataset.

### ISSUE THREAD

**Issue by lo202ng** [open-mmlab/mmrotate#252]
我在训练成功后测试时没有结果，这是我的测试语句：
python tools/test.py run/redet_re50_refpn_1x_dota_ms_rr_le90.py run/epoch_12.pth --work-dir run/test

它的输出是这样：
MoTTY X11 proxy: Authorisation not recognised
/home/ljh/mmrotate/mmrotate/models/backbones/re_resnet.py:481: UserWarning: Deprecati
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/home/ljh/anaconda3/envs/mmrotate/lib/python3.7/site-packages/e2cnn/nn/modules/r2_conrch.bool instead. (Triggered internally at  /opt/conda/conda-bld/pytorch_161437812486
  full_mask[mask] = norms.to(torch.uint8)
/home/ljh/mmdetection/mmdet/models/dense_heads/anchor_head.py:116: UserWarning: Depre
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: run/epoch_12.pth
The model and loaded state dict do not match exactly

missing keys in source state_dict: backbone.conv1.filter, backbone.layer2.0.conv1.filr2.1.conv1.filter, backbone.layer2.1.conv2.filter, backbone.layer2.1.conv3.filter, bater, backbone.layer2.3.conv2.filter, backbone.layer2.3.conv3.filter, backbone.layer3.ckbone.layer3.1.conv1.filter, backbone.layer3.1.conv2.filter, backbone.layer3.1.conv33.conv1.filter, backbone.layer3.3.conv2.filter, backbone.layer3.3.conv3.filter, backb, backbone.layer3.5.conv2.filter, backbone.layer3.5.conv3.filter, backbone.layer4.0.cone.layer4.1.conv1.filter, backbone.layer4.1.conv2.filter, backbone.layer4.1.conv3.fi0.conv.expanded_bias, neck.lateral_convs.0.conv.filter, neck.lateral_convs.1.conv.expneck.lateral_convs.3.conv.expanded_bias, neck.lateral_convs.3.conv.filter, neck.fpn_cr, neck.fpn_convs.2.conv.expanded_bias, neck.fpn_convs.2.conv.filter, neck.fpn_convs.

completed: 0, elapsed: 0s(mmrotate) 

由于我的训练我修改了config涉及到的图片尺寸，所以我使用原本未改动的config与官网下model zoo里的checkpoint进行验证，输出依旧和上面一样没有检测结果。

我使用的是redet_re50_refpn_1x_dota_ms_rr_le90.py    ，这是我的训练语句：
CUDA_VISIBLE_DEVICES=3,4,5 bash tools/dist_train.sh 'configs/redet/redet_re50_refpn_1x_dota_ms_rr_le90.py' 2 --work-dir run
在训练时它有相关警告：
/home/ljh/mmrotate/mmrotate/models/backbones/re_resnet.py:481: UserWarning: Depr     ecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/home/ljh/anaconda3/envs/mmrotate/lib/python3.7/site-packages/e2cnn/nn/modules/r     2_conv/basisexpansion_singleblock.py:80: UserWarning: indexing with dtype torch.     uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered inter     nally at  /opt/conda/conda-bld/pytorch_1614378124864/work/aten/src/ATen/native/I     ndexingUtils.h:30.)
  full_mask[mask] = norms.to(torch.uint8)
/home/ljh/mmdetection/mmdet/models/dense_heads/anchor_head.py:116: UserWarning:      DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `nu     m_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
......
/home/ljh/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning:      DeprecationWarning: anchor_generator is deprecated, please use "prior_generator"      instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/home/ljh/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning:      DeprecationWarning: anchor_generator is deprecated, please use "prior_generator"      instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '

其中num_anchors和anchor_generator的问题我已经了解，但pretrained我不太确定是否有问题，但它依旧成功训练了:
MoTTY X11 proxy: Authorisation not recognised
MoTTY X11 proxy: Authorisation not recognised
MoTTY X11 proxy: Authorisation not recognised
MoTTY X11 proxy: Authorisation not recognised
2022-04-25 04:28:24,447 - mmrotate - INFO -
+-------------------------+-------+-------+--------+-------+
| class                   | gts   | dets  | recall | ap    |
+-------------------------+-------+-------+--------+-------+
| golffield               | 511   | 1058  | 0.863  | 0.797 |
| vehicle                 | 13723 | 27189 | 0.818  | 0.767 |
| Expressway-toll-station | 610   | 1058  | 0.902  | 0.879 |
| trainstation            | 501   | 1067  | 0.743  | 0.634 |
| chimney                 | 649   | 769   | 0.941  | 0.909 |
| storagetank             | 3042  | 5217  | 0.900  | 0.809 |
| ship                    | 27349 | 30493 | 0.941  | 0.904 |
| harbor                  | 2363  | 5245  | 0.642  | 0.541 |
| airplane                | 1888  | 2329  | 0.958  | 0.909 |
| tenniscourt             | 4898  | 5751  | 0.987  | 0.909 |
| groundtrackfield        | 1162  | 2081  | 0.978  | 0.898 |
| dam                     | 512   | 1182  | 0.545  | 0.385 |
| basketballcourt         | 1077  | 1403  | 0.940  | 0.906 |
| Expressway-Service-area | 1080  | 1760  | 0.957  | 0.902 |
| stadium                 | 595   | 916   | 0.982  | 0.909 |
| airport                 | 662   | 1183  | 0.636  | 0.503 |
| baseballfield           | 2384  | 2958  | 0.982  | 0.909 |
| bridge                  | 1366  | 3695  | 0.693  | 0.580 |
| windmill                | 2365  | 2726  | 0.857  | 0.770 |
| overpass                | 1328  | 2844  | 0.824  | 0.767 |
+-------------------------+-------+-------+--------+-------+
| mAP                     |       |       |        | 0.779 |
+-------------------------+-------+-------+--------+-------+
2022-04-25 04:28:24,509 - mmrotate - INFO - Exp name: redet_re50_refpn_1x_dota_ms_rr_le90.py
2022-04-25 04:28:24,510 - mmrotate - INFO - Epoch(val) [12][5863]       mAP: 0.7794

我想知道我的测试出现的问题是如何发生的呢，我该如何解决呢？非常感谢。

**Comment by lo202ng** [comment]
补充一下，我用demo引用训练后的文件夹里的py和pth可以成功infrence

**Comment by liuyanyi** [comment]
`tools/test.py` used to generate result for submit or calc mAP.
I guess you want to calc mAP or show all result, you can try:

Eval mAP
```
python ./tools/test.py  your-config.py your-ckpt.pth --eval=mAP
```
or show result
```
python ./tools/test.py  your-config.py your-ckpt.pth --show-dir work_dirs/vis
```

You can follow the doc. https://mmrotate.readthedocs.io/zh_CN/latest/get_started.html#

**Comment by lo202ng** [comment]
> `tools/test.py` used to generate result for submit or calc mAP. I guess you want to calc mAP or show all result, you can try:
> 
> Eval mAP
> 
> ```
> python ./tools/test.py  your-config.py your-ckpt.pth --eval=mAP
> ```
> 
> or show result
> 
> ```
> python ./tools/test.py  your-config.py your-ckpt.pth --show-dir work_dirs/vis
> ```
> 
> You can follow the doc. https://mmrotate.readthedocs.io/zh_CN/latest/get_started.html#

Thanks for your quick reply! Yes that's indeed what I want to do, I tried your code and the way in the doc but it still didn't work and it printed some new errors:
(1)CUDA_VISIBLE_DEVICES=3 python tools/test.py run/redet_re50_refpn_1x_dota_ms_rr_le90.py run/epoch_12.pth  --format-only --eval-options submission_dir=work_dirs/Task1_results

completed: 0, elapsed: 0s
Merging patch bboxes into full image!!!
Multiple processing
completed: 0, elapsed: 0s
Traceback (most recent call last):
  File "tools/test.py", line 238, in <module>
    main()
  File "tools/test.py", line 220, in main
    dataset.format_results(outputs, **kwargs)
  File "/home/ljh/mmrotate/mmrotate/datasets/dota.py", line 319, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
ValueError: not enough values to unpack (expected 2, got 0)
----------------------------------------------------------------------
(2)CUDA_VISIBLE_DEVICES=3 python tools/test.py run/redet_re50_refpn_1x_dota_ms_rr_le90.py run/epoch_12.pth --eval=mAP
 
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/test.py", line 238, in <module>
    main()
  File "tools/test.py", line 230, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/ljh/mmrotate/mmrotate/datasets/dota.py", line 200, in evaluate
    nproc=nproc)
  File "/home/ljh/mmrotate/mmrotate/core/evaluation/eval_map.py", line 169, in eval_rbbox_map
    num_classes = len(det_results[0])  # positive class num
IndexError: list index out of range

I have made changes on "num_classes" in config files and "CLASSES" in '/mmrotate/datasets/dota.py' before I trained, so is there anything else I need to check?

**Comment by zytx121** [comment]
It looks like you use your dataset, so you need to modify the `format_results` and `_results2submission` functions in mmrotate/datasets/dota.py by yourself.

**Comment by lo202ng** [comment]
> It looks like you use your dataset, so you need to modify the `format_results` and `_results2submission` functions in mmrotate/datasets/dota.py by yourself.

thx for your adviece! I use DIOR dataset, I convert it to DOTA formats follow customize_dataset.md and put them into files 'data/dior/trainval/annfiles/','data/dior/trainval/images/','data/dior/test/images/',the test images and ann_txt are mixed together in a folder.
So do I need to modify mmrotate/datasets/dota.py? since I thought I had convert them to DOTA format successfully...

**Comment by liuyanyi** [comment]
Maybe you should check your dataset config in your cfg file, by default dota dataset use image folder as ann folder in test dataset config. In custom dataset, please change that to ann folder.
https://github.com/open-mmlab/mmrotate/blob/382c06d993113de4f931aa99b983860871f1de7a/configs/_base_/datasets/dotav1.py#L45

**Comment by lo202ng** [comment]
> Maybe you should check your dataset config in your cfg file, by default dota dataset use image folder as ann folder in test dataset config. In custom dataset, please change that to ann folder.
> 
> https://github.com/open-mmlab/mmrotate/blob/382c06d993113de4f931aa99b983860871f1de7a/configs/_base_/datasets/dotav1.py#L45

thx, I noticed this before, my 'test/images/' are mixed with img and txt.
this is the configfile generated after train:

dataset_type = 'DOTADataset'
data_root = 'data/dior/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(800, 800)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(
        type='PolyRandomRotate',
        rotate_ratio=0.5,
        angles_range=180,
        auto_bound=False,
        rect_classes=[9, 11],
        version='le90'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(800, 800),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='DOTADataset',
        ann_file='data/dior/trainval/annfiles/',
        img_prefix='data/dior/trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize', img_scale=(800, 800)),
            dict(
                type='RRandomFlip',
                flip_ratio=[0.25, 0.25, 0.25],
                direction=['horizontal', 'vertical', 'diagonal'],
                version='le90'),
            dict(
                type='PolyRandomRotate',
                rotate_ratio=0.5,
                angles_range=180,
                auto_bound=False,
                rect_classes=[9, 11],
                version='le90'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        version='le90'),
    val=dict(
        type='DOTADataset',
        ann_file='data/dior/trainval/annfiles/',
        img_prefix='data/dior/trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(800, 800),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'),
    test=dict(
        type='DOTADataset',
        ann_file='data/dior/test/images/',
        img_prefix='data/dior/test/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(800, 800),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'))
evaluation = dict(interval=12, metric='mAP')
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=12)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
angle_version = 'le90'
model = dict(
    type='ReDet',
    backbone=dict(
        type='ReResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        pretrained='work_dirs/pretrain/re_resnet50_c8_batch256-25b16846.pth'),
    neck=dict(
        type='ReFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RotatedRPNHead',
        in_channels=256,
        feat_channels=256,
        version='le90',
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='RoITransRoIHead',
        version='le90',
        num_stages=2,
        stage_loss_weights=[1, 1],
        bbox_roi_extractor=[
            dict(
                type='SingleRoIExtractor',
                roi_layer=dict(
                    type='RoIAlign', output_size=7, sampling_ratio=0),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32]),
            dict(
                type='RotatedSingleRoIExtractor',
                roi_layer=dict(
                    type='RiRoIAlignRotated',
                    out_size=7,
                    num_samples=2,
                    num_orientations=8,
                    clockwise=True),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32])
        ],
        bbox_head=[
            dict(
                type='RotatedShared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=20,
                bbox_coder=dict(
                    type='DeltaXYWHAHBBoxCoder',
                    angle_range='le90',
                    norm_factor=2,
                    edge_swap=True,
                    target_means=[0.0, 0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.1, 0.1, 0.2, 0.2, 1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='RotatedShared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=20,
                bbox_coder=dict(
                    type='DeltaXYWHAOBBoxCoder',
                    angle_range='le90',
                    norm_factor=None,
                    edge_swap=True,
                    proj_xy=True,
                    target_means=[0.0, 0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.05, 0.05, 0.1, 0.1, 0.5]),
                reg_class_agnostic=False,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ]),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1,
                gpu_assign_thr=200),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='BboxOverlaps2D')),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='RBboxOverlaps2D')),
                sampler=dict(
                    type='RRandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            nms_pre=2000,
            min_bbox_size=0,
            score_thr=0.05,
            nms=dict(iou_thr=0.1),
            max_per_img=2000)))
work_dir = 'run'
auto_resume = False
gpu_ids = range(0, 2)

**Comment by lo202ng** [comment]
> Maybe you should check your dataset config in your cfg file, by default dota dataset use image folder as ann folder in test dataset config. In custom dataset, please change that to ann folder.
> 
> https://github.com/open-mmlab/mmrotate/blob/382c06d993113de4f931aa99b983860871f1de7a/configs/_base_/datasets/dotav1.py#L45

thx, I noticed this before, my 'test/images/' are mixed with img and txt.
this is the configfile generated after train:
dataset_type = 'DOTADataset'
data_root = 'data/dior/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(800, 800)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(
        type='PolyRandomRotate',
        rotate_ratio=0.5,
        angles_range=180,
        auto_bound=False,
        rect_classes=[9, 11],
        version='le90'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(800, 800),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='DOTADataset',
        ann_file='data/dior/trainval/annfiles/',
        img_prefix='data/dior/trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize', img_scale=(800, 800)),
            dict(
                type='RRandomFlip',
                flip_ratio=[0.25, 0.25, 0.25],
                direction=['horizontal', 'vertical', 'diagonal'],
                version='le90'),
            dict(
                type='PolyRandomRotate',
                rotate_ratio=0.5,
                angles_range=180,
                auto_bound=False,
                rect_classes=[9, 11],
                version='le90'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        version='le90'),
    val=dict(
        type='DOTADataset',
        ann_file='data/dior/trainval/annfiles/',
        img_prefix='data/dior/trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(800, 800),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'),
    test=dict(
        type='DOTADataset',
        ann_file='data/dior/test/images/',
        img_prefix='data/dior/test/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(800, 800),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'))
evaluation = dict(interval=12, metric='mAP')
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=12)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
angle_version = 'le90'
model = dict(
    type='ReDet',
    backbone=dict(
        type='ReResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        pretrained='work_dirs/pretrain/re_resnet50_c8_batch256-25b16846.pth'),
    neck=dict(
        type='ReFPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RotatedRPNHead',
        in_channels=256,
        feat_channels=256,
        version='le90',
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='RoITransRoIHead',
        version='le90',
        num_stages=2,
        stage_loss_weights=[1, 1],
        bbox_roi_extractor=[
            dict(
                type='SingleRoIExtractor',
                roi_layer=dict(
                    type='RoIAlign', output_size=7, sampling_ratio=0),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32]),
            dict(
                type='RotatedSingleRoIExtractor',
                roi_layer=dict(
                    type='RiRoIAlignRotated',
                    out_size=7,
                    num_samples=2,
                    num_orientations=8,
                    clockwise=True),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32])
        ],
        bbox_head=[
            dict(
                type='RotatedShared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=20,
                bbox_coder=dict(
                    type='DeltaXYWHAHBBoxCoder',
                    angle_range='le90',
                    norm_factor=2,
                    edge_swap=True,
                    target_means=[0.0, 0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.1, 0.1, 0.2, 0.2, 1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='RotatedShared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=20,
                bbox_coder=dict(
                    type='DeltaXYWHAOBBoxCoder',
                    angle_range='le90',
                    norm_factor=None,
                    edge_swap=True,
                    proj_xy=True,
                    target_means=[0.0, 0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.05, 0.05, 0.1, 0.1, 0.5]),
                reg_class_agnostic=False,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ]),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1,
                gpu_assign_thr=200),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='BboxOverlaps2D')),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='RBboxOverlaps2D')),
                sampler=dict(
                    type='RRandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            nms_pre=2000,
            min_bbox_size=0,
            score_thr=0.05,
            nms=dict(iou_thr=0.1),
            max_per_img=2000)))
work_dir = 'run'
auto_resume = False
gpu_ids = range(0, 2)

**Comment by lo202ng** [comment]
> Maybe you should check your dataset config in your cfg file, by default dota dataset use image folder as ann folder in test dataset config. In custom dataset, please change that to ann folder.
> 
> https://github.com/open-mmlab/mmrotate/blob/382c06d993113de4f931aa99b983860871f1de7a/configs/_base_/datasets/dotav1.py#L45

Thank you so so so much, I find my fault with your reminding, the reason is that I mixed txt and img but I put them in 'test/' not 'test/images/' by mistake......I am so sorry for wasting your time, and it can test now successfully.

**Comment by lo202ng** [comment]
> It looks like you use your dataset, so you need to modify the `format_results` and `_results2submission` functions in mmrotate/datasets/dota.py by yourself.

I fixed this problem. Thank you both very much for your patient reply~
