### ISSUE TITLE
test.py outputs format means?

### ISSUE THREAD

**Issue by Ashionnal** [open-mmlab/mmrotate#253]
hello:
  run test.py, return data 6 columns means what?

**Comment by zytx121** [comment]
[x,y,w,h,theta,score]

**Comment by Ashionnal** [comment]
ok, i got it, thank you process issue

**Comment by Ashionnal** [comment]
hello:
  Below are my predictions, the first value is the upper box, the second is the lower left box, and the third is the right box.
Theta = 1.5057 for the first value. The second detection box theta=1.2375. The third detection box theta=1.57. Can you help me draw a line to mark which angle is the included angle?
![2022-04-26 17-43-09](https://user-images.githubusercontent.com/23193694/165272140-fe20c87c-7b48-48d0-9df6-1838b9ce8743.png)
