### ISSUE TITLE
file 'dota_demo.py' detect device

### ISSUE THREAD

**Issue by Ashionnal** [open-mmlab/mmrotate#255]
hello:
  Using the algorithm redet, I use device=cuda:0 to make predictions, because my computer is a GPU graphics card, but when I change the configuration to cpu, an error is reported. But I use the model generated by the algorithm of rotated_retinanet to make predictions, and the correct predictions can be made using the device cpu configuration. Please how can I modify it. Below is my direct modification of 'cuda:0' to 'cpu'.
parser.add_argument(
     '--device', default='cpu', help='Device used for inference'
)
![1111](https://user-images.githubusercontent.com/23193694/165435016-c8aed14e-b8aa-45b4-b8d4-764fc0f9514d.png)

**Comment by zytx121** [comment]
ReDet doesn't support running on CPU now, but RotatedRetinaNet can.

**Comment by zytx121** [comment]
It is baceuse `import mmrotate  # noqa: F401`. We import all things of MMRotate, but there are some ops that don't support  CPU now.

**Comment by Ashionnal** [comment]
ok,thank you
