### ISSUE TITLE
HRSC2016 data introduce

### ISSUE THREAD

**Issue by lk137095576** [open-mmlab/mmrotate#257]
I see the classes in hrsc 
`    HRSC_CLASSES = ('ship', 'aircraft carrier', 'warcraft', 'merchant ship',
                    'Nimitz', 'Enterprise', 'Arleigh Burke', 'WhidbeyIsland',
                    'Perry', 'Sanantonio', 'Ticonderoga', 'Kitty Hawk',
                    'Kuznetsov', 'Abukuma', 'Austen', 'Tarawa', 'Blue Ridge',
                    'Container', 'OXo|--)', 'Car carrier([]==[])',
                    'Hovercraft', 'yacht', 'CntShip(_|.--.--|_]=', 'Cruise',
                    'submarine', 'lute', 'Medical', 'Car carrier(======|',
                    'Ford-class', 'Midway-class', 'Invincible-class')`

I would like to use it in real world, so I want to know what is "OXo|--)" "Car carrier([]==[])' and  'Car carrier(======|' , I don't find the instruction of this dataset in the HRSC2016 paper , It looks like Emoji :joy:
and other field in xlm like :

<Img_Rotation>090d</Img_Rotation>
  <Annotated>1</Annotated>
  <HRSC_Objects>
    <HRSC_Object>
      <Object_ID>100000001</Object_ID>
      <Class_ID>100000013</Class_ID>
      <Object_NO>100000001</Object_NO>
      <truncated>0</truncated>
      <difficult>0</difficult>
      <box_xmin>194</box_xmin>
      <box_ymin>243</box_ymin>
      <box_xmax>972</box_xmax>
      <box_ymax>507</box_ymax>
      <mbox_cx>582.9349</mbox_cx>
      <mbox_cy>353.2006</mbox_cy>
      <mbox_w>778.1303</mbox_w>
      <mbox_h>174.2541</mbox_h>
      <mbox_ang>-0.2144308</mbox_ang>
      <segmented>0</segmented>
      <seg_color>
      </seg_color>
      <header_x>964</header_x>
      <header_y>290</header_y>

I can't understand mbox_cx ,mbox_cy,mbox_w,mbox_h,mbox_ang,header_x,header_y,Img_Rotation 
Do you have the dataset documentation?

**Comment by liuyanyi** [comment]
All the classes infomation could be found in `sysdata.xml`.
The class name is indeed strange, but it is the class name provided in the xml.
```
    <HRSC_Class>
      <Class_ID>100000020</Class_ID>
      <HRS_Class_ID>100000004</HRS_Class_ID>
      <Class_Layer>2</Class_Layer>
      <Class_NO>100000020</Class_NO>
      <Class_Name>运输汽车船([]==[])</Class_Name>
      <Class_EngName>Car carrier([]==[])</Class_EngName>
      <Class_ShortName>Car carrier([]==[])</Class_ShortName>
      <Class_DisplayColor>160,102,211</Class_DisplayColor>
      <seg_color>160,102,211</seg_color>
      <edg_color>255,255,255</edg_color>
    </HRSC_Class>
```

mbox_cx ,mbox_cy,mbox_w,mbox_h,mbox_ang define a rotate bbox in le90
header_x, header_y annotated the head of a ship.

**Comment by lk137095576** [comment]
> All the classes infomation could be found in `sysdata.xml`. The class name is indeed strange, but it is the class name provided in the xml.
> 
> ```
>     <HRSC_Class>
>       <Class_ID>100000020</Class_ID>
>       <HRS_Class_ID>100000004</HRS_Class_ID>
>       <Class_Layer>2</Class_Layer>
>       <Class_NO>100000020</Class_NO>
>       <Class_Name>运输汽车船([]==[])</Class_Name>
>       <Class_EngName>Car carrier([]==[])</Class_EngName>
>       <Class_ShortName>Car carrier([]==[])</Class_ShortName>
>       <Class_DisplayColor>160,102,211</Class_DisplayColor>
>       <seg_color>160,102,211</seg_color>
>       <edg_color>255,255,255</edg_color>
>     </HRSC_Class>
> ```
> 
> mbox_cx ,mbox_cy,mbox_w,mbox_h,mbox_ang define a rotate bbox in le90 header_x, header_y annotated the head of a ship.

Good job. TKS
