### ISSUE TITLE
The output of 'rbbox_overlaps' is abnormal when bbox is too small

### ISSUE THREAD

**Issue by liuyanyi** [open-mmlab/mmrotate#26]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

I use `mmrotate.core.bbox.rbbox_overlaps` in my own model. In the early stages of training, the network output is not stable, so many very small detection boxes are generated. When calcuate iou between small predict bboxes and gt bboxes, the output of 'rbbox_overlap' is abnormal.

**Reproduction**

I write a piece of code to reproduce the problem

```
import torch

from mmrotate.core.bbox import rbbox_overlaps

predict = [[903.34, 1034.4, 1.81e-7, 1e-7, -0.312]]
gt = [[2.1525e+02, 7.5750e+01, 3.3204e+01, 1.2649e+01, 3.2175e-01],
      [3.0013e+02, 7.7144e+02, 4.9222e+02, 3.1368e+02, -1.3978e+00],
      [8.4887e+02, 6.9989e+02, 4.6854e+02, 3.0743e+02, -1.4008e+00],
      [8.5250e+02, 7.0250e+02, 7.6181e+02, 3.8200e+02, -1.3984e+00]]

predict_tensor = torch.tensor(predict, device='cuda')
gt_tensor = torch.tensor(gt, device='cuda')

iou = rbbox_overlaps(predict_tensor, gt_tensor)
print(iou)
```

the output of the code is:

```
tensor([[  371957.7500,  9881571.0000,           inf, -9312366.0000]],
       device='cuda:0')
```

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yangxue0827** [comment]
Thank you for your feedback, we will fix it as soon as possible.

**Comment by zytx121** [comment]
Hi @liuyanyi, thank you very much!
We believe that this is caused by the `box_iou_rotated` operator in `mmcv`. When the predicted box is too small, IoU cannot be calculated correctly. We consider fixing this bug by adding restrictions on the size of the prediction box and the value range of IOU in `rbbox_overlaps`.
