### ISSUE TITLE
confusion_matrix error 

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#262]
I run the command "python tools/analysis_tools/confusion_matrix.py configs/gliding_vertex/gliding_vertex_r50_fpn_3x_ucas_aod_le90.py  work_dirs/gliding_vertex_r50_fpn_3x_ucas_aod_le90/20220429_0015/gliding_vertex.pkl work_dirs/gliding_vertex_r50_fpn_3x_ucas_aod_le90/20220429_0015"

but it appear an error
the content of the error is TypeError: expected np.ndarray (got Tensor)

**Comment by zytx121** [comment]
Can other model's results run success?

**Comment by houw0517** [comment]
I know where the problem is. The data type of gt_bboxes should be numpy，but in the second round of the loop, the data type of gt_bboxes becomes tensor.（Because my dataset contains two classes of targets）
After I modify the data type in the loop, the result comes out

**Comment by wxggzz** [comment]
hello before , i run `python tools/test.py configs/oriented_rcnn/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py --out results.pkl`
But something went wrong  in `test.py: error: the following arguments are required: checkpoint`

**Comment by wxggzz** [comment]
Hello, I also have this problem. Can you ask how you modified it
my error:
```
  File "tools/analysis_tools/confusion_matrix.py", line 268, in <module>
    main()
  File "tools/analysis_tools/confusion_matrix.py", line 259, in main
    args.tp_iou_thr)
  File "tools/analysis_tools/confusion_matrix.py", line 92, in calculate_confusion_matrix
    score_thr, tp_iou_thr, nms_iou_thr)
  File "tools/analysis_tools/confusion_matrix.py", line 122, in analyze_per_img_dets
    gt_bboxes = torch.from_numpy(gt_bboxes).float()
TypeError: expected np.ndarray (got list)
```
my commad:
`ython tools/analysis_tools/confusion_matrix.py /workspace/mmrotate/work_dirs/ss/oriented_rcnn+swin/0222/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py ./results.pkl ./`
