### ISSUE TITLE
Does the mmrotate support online multi-scale training and multi-scale testing?

### ISSUE THREAD

**Issue by LiaoYujia** [open-mmlab/mmrotate#265]
At present, the remote sensing datasets, taking the DOTA data set as an example, is generally an offline multi-scale cropping map, which is cut into three scales of [0.5, 1.0, 1.5], and is uniformly resized to 1024*1024 during training. The mmrotate also implements this method. Thanks for your work.
But recently I have encountered problems when implementing online multi-scale training and testing. I would like to ask if mmrotate has realized online multi-scale training and online multi-scale testing? If implemented, how to use it? Hope to get your help.

**Comment by zytx121** [comment]
We don't online multi-scale test now. You can use online multi-scale training by setting
```
    dict(
        type='RResize',
        img_scale=[(1333, 640), (1333, 800)],
        multiscale_mode='range',
        keep_ratio=True),
```

**Comment by LiaoYujia** [comment]
Thank you for your answer, I hope this function can be added in the future version of mmrotate.

**Comment by yangxue0827** [comment]
`multiscale_mode='value'`?
@zytx121
