### ISSUE TITLE
Generate pkl file

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#271]
Is running the test file to generate the pkl file for the DOTA dataset by default?
I run the command that python tools/test.py configs/kfiou/r3det_kfiou_ln_r50_fpn_3x_hrsc_oc.py work_dirs/r3det_kfiou_ln_r50_fpn_3x_hrsc_oc/20220420_2301/epoch_36.pth --out work_dirs/r3det_kfiou_ln_r50_fpn_3x_hrsc_oc/result.pkl
The error message is “FileNotFoundError: HRSCDataset: [Errno 2] No such file or directory: 'data/hrsc/imgsets/test.txt'”

**Comment by zytx121** [comment]
If you use HRSCDataset, the ann_file is a required parameter, even for tests. If you don't have this file, you can generate one, or modify the Dataset class by yourself.

**Comment by houw0517** [comment]
By the way，can I draw a precision-recall curve by using COCOApi

**Comment by zytx121** [comment]
We don't support drawing the precision-recall curve now.

you can refer to [mmdet](https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/tools/analysis_tools/coco_error_analysis.py), PR is welcome!
