### ISSUE TITLE
如何利用dota数据集的测试集？

### ISSUE THREAD

**Issue by LowPassFilter-phil** [open-mmlab/mmrotate#273]
博主，您好，DOTA数据集中的测试集里面只有图片，没有标注文件.txt，这样的test能用于mmdetection的test.py测试吗？我看见论文里面好多都有dota数据集测试的结果，他们用的是测试集吗？还是验证集？为什么dota数据集的测试集没有标注文件官网还提供了生成测试集的json文件？生产的测试集的json文件真的有用吗？

**Comment by zytx121** [comment]
You can generate and submit the detection results on the DOTA's website for [online evalution](https://captain-whu.github.io/DOTA/evaluation.html)

**Comment by ijaypark** [comment]
DOTA's website for [online evalution](https://captain-whu.github.io/DOTA/evaluation.html) have some problem,(UnboundLocalError at /evaluation1/local variable 'res_flag' referenced before assignment),so how to get the result of test.thank u!

**Comment by xxxyyynnn** [comment]
@LowPassFilter-phil Hello, I have the same problem as you. If you have solved this, could you please help me tackle the problem?

**Comment by ijaypark** [comment]
sorry，I haven't found a solution yet, so I haven't used this dataset







-----原始邮件-----
发件人:YannanXie ***@***.***>
发送时间:2024-03-27 08:20:40 (星期三)
收件人: open-mmlab/mmrotate ***@***.***>
抄送: ijaypark ***@***.***>, Comment ***@***.***>
主题: Re: [open-mmlab/mmrotate] 如何利用dota数据集的测试集？ (Issue #273)






@LowPassFilter-phil Hello, I have the same problem as you. If you have solved this, could you please help me tackle the problem?

**Comment by tianbo321** [comment]
对dota测试集进行推理时，数据集路径怎么设置：
    test=dict(
        type=dataset_type,
        ann_file=data_root + '/val/annfiles/',
        img_prefix=data_root + 'val/images/',
        pipeline=test_pipeline))
