### ISSUE TITLE
Train with RGBA images

### ISSUE THREAD

**Issue by lo202ng** [open-mmlab/mmrotate#279]
I want to train with rgba images as input,  will it read all channels of images if I don't change any code? I only  change the in_channels of the backbone to 4.

**Comment by yangxue0827** [comment]
You also need to modify the corresponding image reading function. Modules like opencv do not support reading four-channel images.

**Comment by lo202ng** [comment]
谢谢大佬和群里另一位大佬帮助，总结下希望对其他人有点帮助（涉及到mmdet和mmcv的需要改虚拟环境，以下修改不影响mmrotate原本rgb训练等，英语撇脚就直接中文了）：
1，修改mmdet/datasets/pipelines/loading.py中的LoadImageFromFile类：color_type改为unchanged
2，改config中backbone输入通道数
3，mmcv/image/photometric.py里的imnormalize和imdenormalize函数，加判断语句实现根据mean参数来选择修改cv2.cvtColor的参数
4，修改mmrotate/models/backbones/reresnet第476行，加判断，rgba时参数为4

> You also need to modify the corresponding image reading function. Modules like opencv do not support reading four-channel images.

**Comment by yangxue0827** [comment]
Thx.
