### ISSUE TITLE
Multiple pictures test

### ISSUE THREAD

**Issue by zjs210** [open-mmlab/mmrotate#282]
How to test multiple pictures?

**Comment by yangxue0827** [comment]
An example:
`CUDA_VISIBLE_DEVICES=3 python tools/test.py configs/cfa/cfa_r50_fpn_40e_dota_oc.py work_dirs/cfa_r50_fpn_40e_dota_oc/cfa_r50_fpn_40e_dota_oc-2f387232.pth --show-dir work_dirs/cfa_r50_fpn_40e_dota_oc/vis`
