### ISSUE TITLE
Question about random seed.

### ISSUE THREAD

**Issue by HsLOL** [open-mmlab/mmrotate#291]
各位大佬好，用MMRotate跑实验的过程发现，设置了随机种子之后，用同样的配置文件，两次跑出来的验证集精度并不一样。
![image](https://user-images.githubusercontent.com/53011009/167754565-011c4c1c-c7cd-42c5-8ce0-d54a91841946.png)

我运行时的命令为：
`CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/ssdd/rotated_retinanet_hbb_r50_fpn_1x_ssdd_oc_noaug.py --gpu-id 0 --seed 42`

想问下各位大佬，这种实验过程中的随机性在MMRotate中应该怎么控制呢？

**Comment by zytx121** [comment]
Maybe you can try: 
`` CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/ssdd/rotated_retinanet_hbb_r50_fpn_1x_ssdd_oc_noaug.py --gpu-id 0 --seed 42 --deterministic``

**Comment by HsLOL** [comment]
问题已解决，谢谢大佬！

**Comment by 19990101lrk** [comment]
> 各位大佬好，用MMRotate跑实验的过程发现，设置了随机种子之后，用同样的配置文件，两次跑出来的验证集精度并不一样。 ![image](https://user-images.githubusercontent.com/53011009/167754565-011c4c1c-c7cd-42c5-8ce0-d54a91841946.png)
> 
> 我运行时的命令为： `CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/ssdd/rotated_retinanet_hbb_r50_fpn_1x_ssdd_oc_noaug.py --gpu-id 0 --seed 42`
> 
> 想问下各位大佬，这种实验过程中的随机性在MMRotate中应该怎么控制呢？

我能看下你的配置吗，我跑了6x，但是精度很低，官方有没有做过相关SAR图像数据集的实验

**Comment by 19990101lrk** [comment]
> Maybe you can try: ` CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/ssdd/rotated_retinanet_hbb_r50_fpn_1x_ssdd_oc_noaug.py --gpu-id 0 --seed 42 --deterministic`

Using the SSDD data set, I ran 6x, but the result is very low. I don’t know if the official has done an experiment on related SAR images.
