### ISSUE TITLE
RuntimeError: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by sinianGitHub** [open-mmlab/mmrotate#292]
使用镜像(非dockerfile创建)按照安装教程安装mmrotate成功（pytorch==1.7.1,torchvision==0.8..2,cuda==10.2,mmrotate==0.3.0,mmdet==2.24.1,mmcv-full==1.5.0），测试demo出现这个错误。

**Comment by zytx121** [comment]
It may be caused by the mismatch between mmcv and CUDA version.
