### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by zjs210** [open-mmlab/mmrotate#293]
HOW to test FPS?

**Comment by yangxue0827** [comment]
An example:
`python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py YOUR_CFG YOUR_MODEL --launcher pytorch`

**Comment by zjs210** [comment]
There are some errors in program
RuntimeError: Distributed package doesn't have NCCL built in
Killing subprocess 22388

subprocess.CalledProcessError: Command '['E:\\Anaconda\\envs\\mmrotate\\python.exe', '-u', 'tools/analysis_tools/benchmark.py', '--local_rank=0']' returned non-zero exit status 1.

**Comment by yangxue0827** [comment]
please refer to https://www.zhaoyabo.com/?p=8251

**Comment by zjs210** [comment]
> 请参考 https://www.zhaoyabo.com/?p=8251
There have another error
ZeroDivisionError：division by zero
Killing subprocess 9444

subprocess.CalledProcessError: Command '['E:\Anaconda\envs\mmrotate\python.exe', '-u', 'tools/analysis_tools/benchmark.py', '--local_rank=0']' returned non-zero exit status 1.

**Comment by zytx121** [comment]
We haven't tested FPS on Windows yet.

**Comment by SmallingCar** [comment]
> An example: `python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py YOUR_CFG YOUR_MODEL --launcher pytorch`

If I want to test different scale image,what should i do ?such as 1024*1024,and 800*800
