### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#295]
python tools/dist_train.sh configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py 2
    CONFIG=$1 
                   ^      
      SyntaxError: invalid syntax

**Comment by houw0517** [comment]
subprocess.CalledProcessError: Command '['/home/hw/anaconda3/envs/mmrotate/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_v1_5_le90.py', '--seed', '0', '--launcher', 'pytorch', '--work-dir=run']' died with <Signals.SIGSEGV: 11>.

**Comment by yangxue0827** [comment]
This is a syntax error, please double check.
