### ISSUE TITLE
rotated bbox resize issue

### ISSUE THREAD

**Issue by ucasqcz** [open-mmlab/mmrotate#298]
https://github.com/open-mmlab/mmrotate/blob/0edd2578743559b35bab23b45058211b85ecb82c/mmrotate/datasets/pipelines/transforms.py#L40

rotated rectangle after resize may not be rotated rectangle,  while rectange after rotated should be w * w_scale  h * h_scale, why did you 
choose np.sqrt(w_ratio * h_ratio)?

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/blob/0edd2578743559b35bab23b45058211b85ecb82c/mmrotate/datasets/pipelines/transforms.py#L29

`keep_ratio=True` is used.

**Comment by ucasqcz** [comment]
> 

so the h_scale and w_scale should be same?  did you do any anisotropy resize augmentation in rotated bbox detection domain?

**Comment by zytx121** [comment]
Yes, in the current version, mmrotate requires h_scale and w_scale should be the same. We will adjust it in future versions.
