### ISSUE TITLE
输入图片尺寸不一致问题

### ISSUE THREAD

**Issue by hllyzms** [open-mmlab/mmrotate#302]
你好，我在训练的时候把2048*2048的图片分割成了1024*1024大小，训练出来的模型对输入图片大小为1024*1024的图片检测很好，但是当输入原图片2048*2048时，检测不出来目标，是因为项目中没有使用数据增强对图片进行数据增强随机缩放的原因么？

**Comment by yangxue0827** [comment]
The image size of train and test should be the same.

**Comment by zytx121** [comment]
You can resize test images from 2048*2048 to 4096*4096.
