### ISSUE TITLE
After the image is segmented, the X coordinates of a large number of labels are negative, and the loss during model training is Nan

### ISSUE THREAD

**Issue by xiaoshun1007** [open-mmlab/mmrotate#303]
你好，由于我的检测目标都比较大，分割完图片后，右侧子图x坐标都是负数，模型训练时loss都是nan，所以，是否为负坐标导致
Hello, because my detection targets are relatively large, after the image is segmented, the X coordinates of the right subgraph are negative, and the loss during model training is Nan, So, is it caused by negative coordinates：

![image](https://user-images.githubusercontent.com/74587741/168788091-0921c650-158d-4211-93ef-3cec76d2eab7.png)

` mmrotate - INFO - Epoch [6][600/1300] lr: 2.500e-03, eta: 3:14:54, time: 0.286, data_time: 0.008, memory: 3678, s0.loss_cls: nan, s0.loss_bbox: nan, sr0.loss_cls: nan, sr0.loss_bbox: nan, loss: nan, grad_norm: nan`

**Comment by yangxue0827** [comment]
Image cropping is not a necessary step.

**Comment by xiaoshun1007** [comment]
您好，y坐标也是关联左侧子图的，我在想是不是我裁剪错了，还是本来就该如此
Hello, the Y coordinate is also associated with the subgraph on the left. I wonder if I cut it wrong, or it should have been so
