### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by LyoungOVO** [open-mmlab/mmrotate#307]
During the training process, the GPU memory gradually increases.How can I fix it?

**Comment by zytx121** [comment]
We need more information. Which model do you use?

**Comment by LyoungOVO** [comment]
Redet with polyloss.
I try it on anthor gpu server，it worked.,but in this gpu server the error occur.

**Comment by LyoungOVO** [comment]
I have anthor question.When each epoch trainning finished,the checkpoint will be save,but my work_dir doesn't save the checkpoint file when I break the trainning process.

**Comment by zytx121** [comment]
> 
You can change the save interval here.
https://github.com/open-mmlab/mmrotate/blob/0edd2578743559b35bab23b45058211b85ecb82c/configs/_base_/schedules/schedule_1x.py#L14

**Comment by zytx121** [comment]
> Redet with polyloss. I try it on anthor gpu server，it worked.,but in this gpu server the error occur.

It may be caused by the GPU's memory being too small.
