### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by wafa-bouzouita** [open-mmlab/mmrotate#309]
Hello,
I have a question regarding training a custom dataset.

    How can I transfer learning of some specific classes from the pre-trained weights (e.g. dota) to my custom training if my custom classes are different from the pre-trained classes? 

Best regards and Thank you

**Comment by vpeopleonatank** [comment]
I think you can try overriding `load_from` to pretrained weight path, change `num_classes` and `classes` and train on your custom dataset. May have some warnings about miss match parameters while loading pretrained weight.
