### ISSUE TITLE
delete the neck(FPN) from the modle or output the C2 layer in FPN

### ISSUE THREAD

**Issue by Proient** [open-mmlab/mmrotate#312]
when I train the model(roi_trans),the fpn may spend much time,so I just want to delete the FPN or get the specific layers(C2) in FPN to be output to head.
here is my config,I only know where to change the parameter,but after change the parameter ,I also met some error in the rotated_rpn_head.py
`model = dict(

    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        #out_indices=(0, 1, 2, 3),
        **_out_indices=(0,),_**
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        #in_channels=256, 
        **_in_channels=[256,],
        out_channels=256,
        start_level=0,
        #end_level=0,
        num_outs=1_**
        #add_extra_convs='on_input',
        #num_outs=5
        ),`

**Error**
 ```
warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 188, in main
    meta=meta)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/detectors/two_stage.py", line 142, in forward_train
    **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/dense_heads/rotated_rpn_head.py", line 330, in loss
    assert len(featmap_sizes) == self.anchor_generator.num_levels
AssertionError

```

**Comment by GamblerZSY** [comment]
> when I train the model(roi_trans),the fpn may spend much time,so I just want to delete the FPN or get the specific layers(C2) in FPN to be output to head. here is my config,I only know where to change the parameter,but after change the parameter ,I also met some error in the rotated_rpn_head.py `model = dict(
> 
> ```
> type='RotatedRetinaNet',
> backbone=dict(
>     type='ResNet',
>     depth=50,
>     num_stages=4,
>     #out_indices=(0, 1, 2, 3),
>     **_out_indices=(0,),_**
>     frozen_stages=1,
>     zero_init_residual=False,
>     norm_cfg=dict(type='BN', requires_grad=True),
>     norm_eval=True,
>     style='pytorch',
>     init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
> neck=dict(
>     type='FPN',
>     #in_channels=256, 
>     **_in_channels=[256,],
>     out_channels=256,
>     start_level=0,
>     #end_level=0,
>     num_outs=1_**
>     #add_extra_convs='on_input',
>     #num_outs=5
>     ),`
> ```
> 
> **Error**
> 
> ```
> warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
> Traceback (most recent call last):
>  File "tools/train.py", line 192, in <module>
>    main()
>  File "tools/train.py", line 188, in main
>    meta=meta)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/apis/train.py", line 141, in train_detector
>    runner.run(data_loaders, cfg.workflow)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>    epoch_runner(data_loaders[i], **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
>    self.run_iter(data_batch, train_mode=True, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
>    return self.module.train_step(*inputs[0], **kwargs[0])
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
>    losses = self(**data)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>    return forward_call(*input, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
>    return self.forward_train(img, img_metas, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/detectors/two_stage.py", line 142, in forward_train
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
>    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/dense_heads/rotated_rpn_head.py", line 330, in loss
>    assert len(featmap_sizes) == self.anchor_generator.num_levels
> AssertionError
> ```

The parameter 'strides' in 'anchor_generator' field should be changed to '4', here is my test config.
model = dict(
    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0,),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=None,
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[4, ]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range=angle_version,
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(.0, .0, .0, .0, .0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))

**Comment by GamblerZSY** [comment]
> when I train the model(roi_trans),the fpn may spend much time,so I just want to delete the FPN or get the specific layers(C2) in FPN to be output to head. here is my config,I only know where to change the parameter,but after change the parameter ,I also met some error in the rotated_rpn_head.py `model = dict(
> 
> ```
> type='RotatedRetinaNet',
> backbone=dict(
>     type='ResNet',
>     depth=50,
>     num_stages=4,
>     #out_indices=(0, 1, 2, 3),
>     **_out_indices=(0,),_**
>     frozen_stages=1,
>     zero_init_residual=False,
>     norm_cfg=dict(type='BN', requires_grad=True),
>     norm_eval=True,
>     style='pytorch',
>     init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
> neck=dict(
>     type='FPN',
>     #in_channels=256, 
>     **_in_channels=[256,],
>     out_channels=256,
>     start_level=0,
>     #end_level=0,
>     num_outs=1_**
>     #add_extra_convs='on_input',
>     #num_outs=5
>     ),`
> ```
> 
> **Error**
> 
> ```
> warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
> Traceback (most recent call last):
>  File "tools/train.py", line 192, in <module>
>    main()
>  File "tools/train.py", line 188, in main
>    meta=meta)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/apis/train.py", line 141, in train_detector
>    runner.run(data_loaders, cfg.workflow)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>    epoch_runner(data_loaders[i], **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
>    self.run_iter(data_batch, train_mode=True, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
>    return self.module.train_step(*inputs[0], **kwargs[0])
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
>    losses = self(**data)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>    return forward_call(*input, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
>    return self.forward_train(img, img_metas, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/detectors/two_stage.py", line 142, in forward_train
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
>    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/dense_heads/rotated_rpn_head.py", line 330, in loss
>    assert len(featmap_sizes) == self.anchor_generator.num_levels
> AssertionError
> ```

The parameter 'strides' in 'anchor_generator' field should be changed to '4', here is my test config.
`model = dict(
    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0,),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=None,
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[4, ]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range=angle_version,
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(.0, .0, .0, .0, .0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))`

**Comment by GamblerZSY** [comment]
> when I train the model(roi_trans),the fpn may spend much time,so I just want to delete the FPN or get the specific layers(C2) in FPN to be output to head. here is my config,I only know where to change the parameter,but after change the parameter ,I also met some error in the rotated_rpn_head.py `model = dict(
> 
> ```
> type='RotatedRetinaNet',
> backbone=dict(
>     type='ResNet',
>     depth=50,
>     num_stages=4,
>     #out_indices=(0, 1, 2, 3),
>     **_out_indices=(0,),_**
>     frozen_stages=1,
>     zero_init_residual=False,
>     norm_cfg=dict(type='BN', requires_grad=True),
>     norm_eval=True,
>     style='pytorch',
>     init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
> neck=dict(
>     type='FPN',
>     #in_channels=256, 
>     **_in_channels=[256,],
>     out_channels=256,
>     start_level=0,
>     #end_level=0,
>     num_outs=1_**
>     #add_extra_convs='on_input',
>     #num_outs=5
>     ),`
> ```
> 
> **Error**
> 
> ```
> warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
> Traceback (most recent call last):
>  File "tools/train.py", line 192, in <module>
>    main()
>  File "tools/train.py", line 188, in main
>    meta=meta)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/apis/train.py", line 141, in train_detector
>    runner.run(data_loaders, cfg.workflow)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>    epoch_runner(data_loaders[i], **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
>    self.run_iter(data_batch, train_mode=True, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
>    return self.module.train_step(*inputs[0], **kwargs[0])
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
>    losses = self(**data)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>    return forward_call(*input, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
>    return self.forward_train(img, img_metas, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/detectors/two_stage.py", line 142, in forward_train
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
>    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/dense_heads/rotated_rpn_head.py", line 330, in loss
>    assert len(featmap_sizes) == self.anchor_generator.num_levels
> AssertionError
> ```

### The parameter 'strides' in 'anchor_generator' field should be changed to '4', here is my test config.
`model = dict(
    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0,),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=None,
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[4, ]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range=angle_version,
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(.0, .0, .0, .0, .0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))`

**Comment by GamblerZSY** [comment]
> when I train the model(roi_trans),the fpn may spend much time,so I just want to delete the FPN or get the specific layers(C2) in FPN to be output to head. here is my config,I only know where to change the parameter,but after change the parameter ,I also met some error in the rotated_rpn_head.py `model = dict(
> 
> ```
> type='RotatedRetinaNet',
> backbone=dict(
>     type='ResNet',
>     depth=50,
>     num_stages=4,
>     #out_indices=(0, 1, 2, 3),
>     **_out_indices=(0,),_**
>     frozen_stages=1,
>     zero_init_residual=False,
>     norm_cfg=dict(type='BN', requires_grad=True),
>     norm_eval=True,
>     style='pytorch',
>     init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
> neck=dict(
>     type='FPN',
>     #in_channels=256, 
>     **_in_channels=[256,],
>     out_channels=256,
>     start_level=0,
>     #end_level=0,
>     num_outs=1_**
>     #add_extra_convs='on_input',
>     #num_outs=5
>     ),`
> ```
> 
> **Error**
> 
> ```
> warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
> Traceback (most recent call last):
>  File "tools/train.py", line 192, in <module>
>    main()
>  File "tools/train.py", line 188, in main
>    meta=meta)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/apis/train.py", line 141, in train_detector
>    runner.run(data_loaders, cfg.workflow)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>    epoch_runner(data_loaders[i], **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
>    self.run_iter(data_batch, train_mode=True, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
>    return self.module.train_step(*inputs[0], **kwargs[0])
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
>    losses = self(**data)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>    return forward_call(*input, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
>    return self.forward_train(img, img_metas, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/detectors/two_stage.py", line 142, in forward_train
>    **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
>    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
>    return old_func(*args, **kwargs)
>  File "/usr/local/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmrotate/models/dense_heads/rotated_rpn_head.py", line 330, in loss
>    assert len(featmap_sizes) == self.anchor_generator.num_levels
> AssertionError
> ```
The parameter 'strides' in 'anchor_generator' field should be changed to '4', here is my test config.

```python
model = dict(
    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0,),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=None,
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[4, ]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range=angle_version,
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(.0, .0, .0, .0, .0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))
```

**Comment by Agito555** [comment]
If you want to use the FPN architecture to get the P2 feature map only, I don't think your modification is consistent with your intention. Right?
If you gonna use the P2 feature map only in FPN ,  there is need to change the FPN architecture.
@Proient
