### ISSUE TITLE
The central point coordinates or angles of some prediction frames have deviation

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#313]
I trained the rotating retinanet network, and its map reached 91%, but in fact, there are deviations in the central point coordinates x, y or rotation angle of many prediction frames, resulting in inaccurate prediction frames.
What may be the reason for this? How should I modify it? Thank you in advance

**Comment by yangxue0827** [comment]
Please give some examples.

**Comment by zytx121** [comment]
The map is `mAP@0.5` here. This 91% mAP does not ensure that the results are completely accurate.

**Comment by hh123445** [comment]
> 请举一些例子。

Oh,I'm sorry I'm sorry to reply you so late.
In fact, this data set is a confidential data set. Please forgive me that I can only use one schematic diagram to show the problems I encounter. There are two main problems. One is that there is a deviation in the prediction of the rotation angle of the prediction box on the left in the figure. The other is that there is a deviation in the prediction of the center point of the prediction box on the right in the figure.
![deviation](https://user-images.githubusercontent.com/90760124/169934449-38bf35e6-49c8-40a9-9c91-b05894966761.png)

**Comment by hh123445** [comment]
> 地图在`mAP@0.5`这里。这个 91% 的 mAP 并不能确保结果完全准确。

Oh,thank you for your answer. I think I should take some tricks to continue to improve my mAP.

.
