### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#314]
我在 DOTA-1.0 数据集推理 RotatedRetinaNet 并生成压缩文件用于在线[提交](https://captain-whu.github.io/DOTA/evaluation.html) (首先请修改 [data_root](https://github.com/open-mmlab/mmrotate/tree/main/configs/_base_/datasets/dotav1.py))。的时候，使用了如下的命令
 Python ./tools/test.py configs\s2anet\costom_s2anet.py C:\D\APP\PyCharm\pythonProject\epoch_12.pth --format-only --eval-options submission
_dir=work_dirs/Task1
希望能得到对应的txt文件用于提交，可是出现了这个错误

Traceback (most recent call last):
  File "./tools/test.py", line 257, in <module>
    main()
  File "./tools/test.py", line 239, in main
    dataset.format_results(outputs, **kwargs)
  File "c:\d\app\pycharm\pythonproject\mmrotate-main\mmrotate\datasets\dota.py", line 326, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
  File "c:\d\app\pycharm\pythonproject\mmrotate-main\mmrotate\datasets\dota.py", line 229, in merge_det
    x_y_2 = re.findall(r'\d+', x_y[0])
IndexError: list index out of range

我已经将config里的dotav1文件的数据集修改了，请问为什么会报这个错？

**Comment by yangxue0827** [comment]
检查一下数据路径。

**Comment by milamiqi** [comment]
谢谢你的建议！我把数据集重新弄了一下，把训练集和验证集合并到了一起，结果出现了这个错误
Traceback (most recent call last):
  File "./tools/test.py", line 238, in <module>
    main()
  File "./tools/test.py", line 220, in main
    dataset.format_results(outputs, **kwargs)
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/datasets/dota.py", line 320, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
ValueError: not enough values to unpack (expected 2, got 0)
请问该如何解决

**Comment by milamiqi** [comment]
您好，我检查了一下数据路径，已经是和dotav1.py是一样的路径，但还是会报相同的错

**Comment by zytx121** [comment]
We need more error detail. By the way, it doesn't need to train again.

**Comment by milamiqi** [comment]
load checkpoint from local path: /home/dell/Research/zly/mmrotate-main/work_dirs/costom_s2anet/epoch_12.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fam_head.cls_convs.2.conv.weight, fam_head.cls_convs.2.conv.bias, fam_head.cls_convs.3.conv.weight, fam_head.cls_convs.3.conv.bias, fam_head.cls_convs.4.conv.weight, fam_head.cls_convs.4.conv.bias, fam_head.cls_convs.5.conv.weight, fam_head.cls_convs.5.conv.bias, fam_head.reg_convs.2.conv.weight, fam_head.reg_convs.2.conv.bias, fam_head.reg_convs.3.conv.weight, fam_head.reg_convs.3.conv.bias, fam_head.reg_convs.4.conv.weight, fam_head.reg_convs.4.conv.bias, fam_head.reg_convs.5.conv.weight, fam_head.reg_convs.5.conv.bias

completed: 0, elapsed: 0s
Merging patch bboxes into full image!!!
Multiple processing
completed: 0, elapsed: 0s
Traceback (most recent call last):
  File "./tools/test.py", line 238, in <module>
    main()
  File "./tools/test.py", line 220, in main
    dataset.format_results(outputs, **kwargs)
  File "/home/dell/Research/zly/mmrotate-main/mmrotate/datasets/dota.py", line 320, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by zytx121** [comment]
It seems like your test set path is wrong.

**Comment by milamiqi** [comment]
thank you!you are right!

**Comment by 1nancy23** [comment]
老哥为啥我改了路径还是有：
文件 “./tools/test.py”，第 220 行，在主
dataset.format_results（输出，**kwargs
） 文件 “/home/dell/Research/zly/mmrotate-main/mmrotate/datasets/dota.py”，第 320 行，在 format_results
id_list 中，dets_list = self.merge_det（results， nproc）
这个问题

**Comment by 3xiaoli33** [comment]
> 该错误是由错误图像文件名引起的。请确保测试图像是用我们的脚本裁剪的。https://github.com/open-mmlab/mmrotate/tree/main/tools/data/dota

Is there another solution? For the system I need to submit to, I can't make changes to the input data set
