### ISSUE TITLE
KeyError: "RotatedRetinaNet: 'xxx is not in the models registry'"

### ISSUE THREAD

**Issue by wjl0512** [open-mmlab/mmrotate#315]
I defined an improved CFPN based on FPN, using @ ROTATED_ NECKS. register_ module() and set from .cfpn import CFPN added to mmrotate / models / necks/__ init__. py, but still display keyerror: "rotatedretinanet: 'cfpn is not in the models registry'".

**Comment by yangxue0827** [comment]
It should be that you are not registered with `CFPN` that is designed by yourself. You need to understand the registration mechanism of mmdet first.

**Comment by zytx121** [comment]
Please make sure that the mmrotate you use and the mmrotate you modify are the same mmrotate.

**Comment by Nikhil-Kumar-Patel** [comment]
Hi @wjl0512, How did you solve it?
