### ISSUE TITLE
KFLoss疑惑

### ISSUE THREAD

**Issue by LUO77123** [open-mmlab/mmrotate#316]
作者您好，我在阅读FKLoss代码时，FKLoss函数中，正向传播输入的pred_decode=None, targets_decode=None,是什么喃（这两个应该是head输出的，是什么呀），（我准备将这个改到YOLO上，所以）请大佬解惑一下，谢谢
![image](https://user-images.githubusercontent.com/87272337/169695194-2a0f9083-2d78-4eb1-aae7-1f47cc1d99e9.png)

**Comment by 78Jarre** [comment]
Hello,brother.Do you solve it?
