### ISSUE TITLE
KFIoU损失疑问==KFIoU Loss doubt

### ISSUE THREAD

**Issue by LUO77123** [open-mmlab/mmrotate#317]
1.您好，我在阅读 FKLoss损失函数时，FKLoss 函数中的代码，正向传播输入的 pred_decode=None，targets_decode=None，是什么通话（这两个应该是 head 输出的，是什么呀），（我准备将这个改到YOLO上，所以）请大佬解惑一下，谢谢
Hello, when I read fkloss, the code in fkloss function propagates the input pred_decode=None，targets_decode=None, what call is it (these two should be output by head, what is it), (I'm going to change this to Yolo, so) please help me answer it, thank you
![image](https://user-images.githubusercontent.com/87272337/169695936-26c67268-ae46-4447-a342-54a6b0f7c248.png)
2.我不太理解这块’weight’的操作
I don't quite understand the operation of this ’weight’
![image](https://user-images.githubusercontent.com/87272337/169696031-6930acef-644e-43ed-b3aa-618ad2172997.png)

**Comment by yangxue0827** [comment]
`pred_decode` and `targets_decode` are pred box and gt box after decoding.

**Comment by zytx121** [comment]
The weight of the positive sample is 1,  and the weight of the negative sample is 0.

**Comment by LUO77123** [comment]
> `pred_decode` and `targets_decode` are pred box and gt box after decoding.

Hello, author. Thanks for your reply. I want to know what the decoding operation of pred box and gt box is and where the code segment is. Thank you.
大佬您好，感谢大佬回复，我想知道pred_decode和targets_decode的decoding操作是什么，代码段在哪里喃，谢谢大佬。

**Comment by zytx121** [comment]
https://github.com/open-mmlab/mmrotate/tree/main/mmrotate/core/bbox/coder
