### ISSUE TITLE
There was a problem generating confusion matrix

### ISSUE THREAD

**Issue by wxggzz** [open-mmlab/mmrotate#318]
1. Run the following command to generate a pkl file
` python tools/test.py /workspace/mmrotate/work_dirs/ss/oriented_rcnn+swin/0222/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py --out results.pkl /workspace/mmrotate/work_dirs/ss/oriented_rcnn+swin/0222/latest.pth  `

2. `python tools/analysis_tools/confusion_matrix.py /workspace/mmrotate/work_dirs/ss/oriented_rcnn+swin/0222/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py ./results.pkl ./ --show`
an error occurred  is 
```
  File "tools/analysis_tools/confusion_matrix.py", line 268, in <module>
    main()
  File "tools/analysis_tools/confusion_matrix.py", line 259, in main
    args.tp_iou_thr)
  File "tools/analysis_tools/confusion_matrix.py", line 92, in calculate_confusion_matrix
    score_thr, tp_iou_thr, nms_iou_thr)
  File "tools/analysis_tools/confusion_matrix.py", line 122, in analyze_per_img_dets
    gt_bboxes = torch.from_numpy(gt_bboxes).float()
TypeError: expected np.ndarray (got list)
``` 
and I modify the data type in the loop add       `  gt_bboxes = np.array(gt_bboxes)`   the result comes out
![confusion_matrix](https://user-images.githubusercontent.com/78011659/169698770-abde18d9-faef-4288-9670-de3e88181786.png)

Where are the problems in my process？

**Comment by wxggzz** [comment]
On DOTA dataset

**Comment by yangxue0827** [comment]
@akmalulkhairin

**Comment by liuyanyi** [comment]
Did you use test-set to generate confusion matrix? You can try it on val-set. There's no annotions for test-set on DOTA dataset.

**Comment by wxggzz** [comment]
OK . I'll give it a try. I trained the training set and the validation set together, now I re-train with the training set alone, and then use the validation set to test this function . TKS

> Did you use dota test-set to generate confusion matrix? You can try it on val-set. There's no annotions for test-set on DOTA dataset.
