### ISSUE TITLE
Can it generate the submission style of DOTA dataset test set?

### ISSUE THREAD

**Issue by Nankle** [open-mmlab/mmrotate#321]
How to generate the DOTA test set format in mmrotate?

**Comment by GamblerZSY** [comment]
> How to generate the DOTA test set format in mmrotate?

python tools/test.py {your config} {your model} --format-only --eval-options submission_dir={save path}

**Comment by GamblerZSY** [comment]
> How to generate the DOTA test set format in mmrotate?

python tools/test.py {your config} {your model} --format-only --eval-options submission_dir={save path}

**Comment by GamblerZSY** [comment]
> How to generate the DOTA test set format in mmrotate?

```python
python tools/test.py {your config} {your model} --format-only --eval-options submission_dir={save path}
```

**Comment by H1d30nbu3h** [comment]
> > How to generate the DOTA test set format in mmrotate?
> 
> ```python
> python tools/test.py {your config} {your model} --format-only --eval-options submission_dir={save path}
> ```
I split the test set with mmrorate. A split graph and label are generated. The current label is empty.  What am I supposed to do
