### ISSUE TITLE
Anchor ratios is for Horizontal detection box or Rotation detection box?

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#325]
I encountered a problem when modifying the ratios of the anchor. I'm not sure whether this aspect ratio is for the aspect ratio of the rotation detection box itself or for the aspect ratio of the smallest circumscribed rectangle of the rotation detection box？
![1](https://user-images.githubusercontent.com/90760124/170276507-d672dcd8-88d5-4d56-ad3f-9529ea61ddcf.png)

**Comment by GamblerZSY** [comment]
> I encountered a problem when modifying the ratios of the anchor. I'm not sure whether this aspect ratio is for the aspect ratio of the rotation detection box itself or for the aspect ratio of the smallest circumscribed rectangle of the rotation detection box？ ![1](https://user-images.githubusercontent.com/90760124/170276507-d672dcd8-88d5-4d56-ad3f-9529ea61ddcf.png)

I think it's just the aspect ratio of the horizontal box, since the initial angle is zero

**Comment by GamblerZSY** [comment]
> > > 我在修改锚的比率时遇到了问题。不知道这个纵横比是针对旋转检测框本身的纵横比还是针对旋转检测框最小外接矩形的纵横比？![1](https://user-images.githubusercontent.com/90760124/170276507-d672dcd8-88d5-4d56-ad3f-9529ea61ddcf.png)
> > 
> > 
> > 我认为这只是水平框的纵横比，因为初始角度为零
> 
> Oh,thanks for your answer. The object I need to detect is with high w/h ratio,do you think I set it to [0.1, 0.05, 10.0, 20.0] is suitable, as a matter of fact this is the result of KMeans clustering for original picture size.But I'm not sure whether to consider feature map scaling,and how to consider that?

I'm not sure whether the modified aspect ratio is appropriate, I'm afraid this requires several adjustments based on experiments to find the optimal solution. If it were me, I would first train with the original parameters, and then determine how to modify through the visualization of the error detection. By the way, does your dataset need slicing, if so, then K-Means should be performed on the sliced images.
As for the feature map scaling, I think RotatedAnchorGenerator has already considered it, because the anchor size on each level of features is 4(octave_base_scale)*stride*scales_per_octave(2**0,2**(1/3),2**(2/3)), 'stride' is related to feature map scaling.

**Comment by zytx121** [comment]
Yes, you need to adjust the anchor ratios according to the experiment results. KMeans maybe can't guarantee strong results.

**Comment by hh123445** [comment]
> > > > 不是这个横比是检测框的纵横比还是旋转检测框外接范围最窄![1](https://user-images.githubusercontent.com/90760124/170276507-d672dcd8-88d5-4d56-ad3f-9529ea61ddcf.png)
> > > 
> > > 
> > > 我认为这只是水平的纵横比，因为最初这只是水平的纵横比
> > 
> > 
> > 哦，谢谢你的回答。我需要检测的对象是具有高 w/h 比的，你认为我将它设置为 [0.1, 0.05, 10.0, 20.0] 是否合适，事实上这是对原始图片大小进行 KMeans 聚类的结果。但我不确定是否考虑特征图缩放，以及如何考虑？
> 
> 我不确定修改后的纵横比是否合适，恐怕这需要根据实验进行多次调整才能找到最佳解决方案。如果是我，我会先用原始参数进行训练，然后通过错误检测的可视化来确定如何修改。顺便说一句，您的数据集是否需要切片，如果需要，那么应该对切片图像执行 K-Means。 至于特征图缩放，我觉得RotatedAnchorGenerator已经考虑过了，因为每一层特征上的anchor size是4(octave_base_scale) _stride_ scales_per_octave(2 **0,2** (1/3),2**(2/3) )，“步幅”与特征图缩放有关。

Thank you for your answer,I have tried the original setting.its detect results is good,but some predict box have angle deviation,so I'm thinking that changing the ratio of anchor may make it easier to correct to the ground truth.
In addition,[0.1, 0.05, 10.0, 20.0] seem not to work.I'll try other ratios.
