### ISSUE TITLE
loss降不下来

### ISSUE THREAD

**Issue by Tian743** [open-mmlab/mmrotate#330]
您好，有个问题想请教，训练自己的数据集时，采用rotated_faster_rcnn训练map为0.64，比较正常，但换了其他方法训练多轮loss始终降不下来，精度一直很低，大佬请问可能是什么原因导致的呢？而且发现存在每个epoch都从头来过的问题。非常感谢！
[20220602_134637.log](https://github.com/open-mmlab/mmrotate/files/8821630/20220602_134637.log)
![problem](https://user-images.githubusercontent.com/78198512/171575367-6e890a51-ca7b-4444-a145-32decc4eb6bf.PNG)
![problem2](https://user-images.githubusercontent.com/78198512/171575645-1a43d2a7-fc46-498a-95a6-cf9eaaa70f4a.PNG)

**Comment by yangxue0827** [comment]
try lowering the learning rate.

**Comment by Tian743** [comment]
> try lowering the learning rate.

您好，我将学习率从原来的0.005降低为0.0001和0.0025，但loss和梯度出现了异常大的情况，请问该怎么办呢？祝您端午安康！
![problem](https://user-images.githubusercontent.com/78198512/171813933-5795418b-1e64-48d8-b1a0-820414f029ee.PNG)
![problem1](https://user-images.githubusercontent.com/78198512/171813949-c7982bd1-d744-46fe-bf56-9c51a6d4b013.PNG)

**Comment by zytx121** [comment]
Please don't modify the `norm_type`. By the way, `step` which is bigger than 20 in `lr_config` is useless, because your `max_epochs` is 20.

**Comment by zytx121** [comment]
It looks like your dataset is very small. What batch_size do you use?

**Comment by Tian743** [comment]
> Please don't modify the `norm_type`. By the way, `step` which is bigger than 20 in `lr_config` is useless, because your `max_epochs` is 20.

感谢！我也发现了这个问题，但是修改之后精度与官方还是差好多/(ㄒoㄒ)/~~

> It looks like your dataset is very small. What batch_size do you use?

我的数据集确实比较小。只有四百张图，batch size用的2，请问您有该情况下参数修改的建议吗？

**Comment by zytx121** [comment]
You can try to use the AdamW optimizer to replace SGD.
