### ISSUE TITLE
precision值

### ISSUE THREAD

**Issue by jytJYT8** [open-mmlab/mmrotate#338]
请问训练日志不输出precision值吗，怎么可以查看precision值呢

**Comment by zytx121** [comment]
The mAP is the average of precision so we don't support print precision in log. However, you can print it by yourself.
The precision is a list and you can get it at https://github.com/open-mmlab/mmrotate/blob/6eb7a277ed62f64952587c9e41498f8e3c0cfe63/mmrotate/core/evaluation/eval_map.py#L221
