### ISSUE TITLE
你好，请问模型占用显存和推理时间是怎么计算出来的呀

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#341]

**Comment by yangxue0827** [comment]
显存看log日志的`memory`，速度用`mmrotate/tools/analysis_tools/benchmark.py`

**Comment by 202004061408** [comment]
> 显存看log日志的，速度用`memory``mmrotate/tools/analysis_tools/benchmark.py`

hello,could benchmark.py run in windows?
