### ISSUE TITLE
How do I convert the R3DET model to ONNX format？

### ISSUE THREAD

**Issue by Jianchun-Huo** [open-mmlab/mmrotate#345]
How do I convert the R3DET model to ONNX format.

**Comment by yangxue0827** [comment]
Refer to https://github.com/open-mmlab/mmdeploy or https://blog.csdn.net/sxj731533730/article/details/124107625

**Comment by zytx121** [comment]
The  [rotated_feature_align ort op](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/onnxruntime/rotated_feature_align.h) is supported in mmcv.  So you don't need to custom ort op by yourself. All you need to do is to refer to:
- https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmrotate.html?highlight=mmrotate
- https://github.com/open-mmlab/mmdeploy/pull/277, 
- https://github.com/open-mmlab/mmdeploy/pull/312, 
- https://github.com/open-mmlab/mmdeploy/pull/422, 
- https://github.com/open-mmlab/mmdeploy/pull/450, 
- https://github.com/open-mmlab/mmdeploy/pull/428, 
- https://github.com/open-mmlab/mmdeploy/pull/473
