### ISSUE TITLE
您好，请问您用KFIOU和ROI Transformer做过实验吗？我自己的结果是KFIOU+ROI Transformer的精度是比不上ROI Transformer的

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#351]

**Comment by luoz66** [comment]
> 我也发现目前版本的mmrotate有你提出的问题，并且我发现类似GWD/KLD/KFIoU在二阶段的方法上都不奏效，而在单阶段方法比较奏效。 双阶段在reg分支预测输出通道数是5*(num_class+1)，而单阶段是5，因此单阶段上的一些超参数可能并不适用于二阶段方法，但是我目前也没有重新调work。

![image](https://user-images.githubusercontent.com/86155472/173372466-a74203c3-0e7b-4125-a953-5957a742cfcc.png)
您好，请问您的这个结果不是在mmrotate上做的实验吗

**Comment by yangxue0827** [comment]
这个结果是mmrotate开源前的结果

**Comment by yangxue0827** [comment]
而且你可以看到，差距不大，一般同个模型重跑后的性能浮动都可能比这个高。

**Comment by luoz66** [comment]
> 而且你可以看到，差距不大，一般同个模型重跑后的性能浮动都可能比这个高。

您好，我想请问，这个性能浮动是由什么原因引起的呢

**Comment by luoz66** [comment]
> 这个结果是mmrotate开源前的结果

您的这个结果也是trainval跑出来的吗

**Comment by luoz66** [comment]
>分割之后数据会变得非常多，用trainval跑的话是不是会很慢呢

**Comment by luoz66** [comment]
> 这个可以灵活设置，你完全可以只训练train，在val上验证。

好的，谢谢解答
