### ISSUE TITLE
如图所示（orient rcnn的配置文件），怎么理解bbox_coder中的proj_xy和edge_swap，看了源码没太明白，求大佬解答

### ISSUE THREAD

**Issue by dashanlidewa** [open-mmlab/mmrotate#352]
![image](https://user-images.githubusercontent.com/50894654/173512761-7820b108-b242-49ef-b46f-aa3672b72ba8.png)

**Comment by dashanlidewa** [comment]
As shown in the figure (the configuration file of orient rcnn), how to understand proj_xy and edge_swap in bbox_coder, I don understand the source code, please answer

**Comment by jbwang1997** [comment]
`proj_xy` means using the coordinate system of bboxes, which is rotated from the original coordinate system by bboxes angle, to calculate the dx and dy.
`edge_swap` means exchanging the w and h when the angle between priors and targets is larger than pi/4.

**Comment by dashanlidewa** [comment]
thanks

> `proj_xy` means using the coordinate system of bboxes, which is rotated from the original coordinate system by bboxes angle, to calculate the dx and dy. `edge_swap` means exchanging the w and h when the angle between priors and targets is larger than pi/4.
