### ISSUE TITLE
get the  boxes eight points  of each picture's object

### ISSUE THREAD

**Issue by Proient** [open-mmlab/mmrotate#364]
I want to get the coordinates of the eight points of the rotation box outside the predicted objects.
the format like the dota annotation ('x1 y1 x2 y2 x3 y3 x4 y4 class ') , each picture has a separate txt file
I try to use the '`tools/test.py --format-only --eval-options submission_dir=demo/result1',`but that format doesn't I want.
thanks

**Comment by zytx121** [comment]
Sorry, we don't support generating txt for each picture now. You need to modify this function yourself:
https://github.com/open-mmlab/mmrotate/blob/e22c8dfa3c309aa68ff18a5a03316f69c6eb2880/mmrotate/datasets/dota.py#L257
