### ISSUE TITLE
how to set the target_means and target_stds in bbox_coder?

### ISSUE THREAD

**Issue by TommyYangXP** [open-mmlab/mmrotate#365]
how to set the target_means and target_stds in bbox_coder for my model.  At [https://github.com/open-mmlab/mmrotate/issues/202#issue-1199296368](url), there may be a big influence on a model performance about how to set target_means and target_stds. Should I set the same target_means and target_stds in bbox_coder in every model for the same dataset?

**Comment by zytx121** [comment]
Usually, we can directly use the default value in the corresponding paper. We have not done any experiment to modify these two hyperparameters according to the dataset. You are welcome to try and share your experimental results.
