### ISSUE TITLE
用r3det_tiny_r50_fpn_1x_dota_oc.py训练后不显示map  用r3det_r50_fpn_1x_dota_oc.py可以显示

### ISSUE THREAD

**Issue by zongzizi** [open-mmlab/mmrotate#367]
这是用r3det_tiny_r50_fpn_1x_dota_oc.py 训练后显示的结果
![image](https://user-images.githubusercontent.com/42510035/174247088-170c8661-de3c-4a9b-8553-39cba4c4766a.png)
这是r3det_r50_fpn_1x_dota_oc.py 训练后显示的结果
![(G {8X D_M6 }3MCC2VV( 4](https://user-images.githubusercontent.com/42510035/174247425-5b5e2bf4-f4d2-437a-82ba-85dff8bfc38e.png)
用r3det_r50_fpn_1x_dota_oc.py先训练的，训练后没有改变相关东西，继续训练的r3det_tiny_r50_fpn_1x_dota_oc.py

**Comment by zytx121** [comment]
Please check your `num_classes` in `r3det_tiny_r50_fpn_1x_dota_oc.py`

**Comment by zongzizi** [comment]
> Please check your `num_classes` in `r3det_tiny_r50_fpn_1x_dota_oc.py`

Thank you for your reply. I found that the changes were only made locally, but not on the server.
