### ISSUE TITLE
Single Label/Class

### ISSUE THREAD

**Issue by tinly00** [open-mmlab/mmrotate#369]
Will this code suitable for Detecting Single class?

**Comment by zytx121** [comment]
Of course, we support it. You can set `num_classes=1` in the config and refer to https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/datasets/sar.py

**Comment by tinly00** [comment]
i tried some yolov5-rotation detection before， it did not suitable.
i will have a try with this code. thank you!



---- Replied Message ----
| From | Yue ***@***.***> |
| Date | 06/20/2022 09:27 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [open-mmlab/mmrotate] Single Label/Class (Issue #369) |

Of course, we support it. You can set num_classes=1 in the config and refer to https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/datasets/sar.py
