### ISSUE TITLE
The program crashed when I set the number of anchors to increase（S2aNet）

### ISSUE THREAD

**Issue by Nankle** [open-mmlab/mmrotate#373]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
python tools/train.py configs/s2anet/s2anet_r50_fpn_1x_dota_le135.py
```

**Environment**

Environment is runable when i set just 1 anchor with ratios=[1.0]

**Error traceback**
How to calculate offset in S2aNet ( Alignment Convolutional Layer) when the number of preset anchor is not 1?

**Comment by zytx121** [comment]
Sorry, S2ANet only supports preset anchors equal to 1 now.
