### ISSUE TITLE
Coordinates understanding

### ISSUE THREAD

**Issue by TekayaNidham** [open-mmlab/mmrotate#375]
this is the output of torchserve
```
  {
    "class_name": "APP",
    "bbox": [
      503.0770568847656,
      553.6226806640625,
      66.04365539550781,
      32.18748092651367,
      1.5016354322433472
    ],
    "score": 0.9999977350234985
  },
```
Can you please explain to me the last float and how can I use these coordinates to transform them into `x1y1..x4y4` format

**Comment by Agito555** [comment]
I think that the score represents the confidence of the output.
And you can refer to this link https://github.com/open-mmlab/mmrotate/blob/main/docs/en/intro.md to transform the output of $center_x center_y w h angle$ to $x_1 y_1 \dots x_4 y_4$

**Comment by zytx121** [comment]
You can find the convert function in https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/core/bbox/transforms.py
https://github.com/open-mmlab/mmrotate/blob/01439d1f2eab87e19f39cb2cb2a5b5c4afa3f6b6/mmrotate/core/bbox/transforms.py#L158
