### ISSUE TITLE
Trivial question about the coordinates in the DOTA dataset

### ISSUE THREAD

**Issue by Agito555** [open-mmlab/mmrotate#376]
I notice that there are some coordinates in the annotation of the DOTA dataset which are quadrilaterals instead of rotated rectangles

>i.e. 576.0 312.0 579.0 293.0 628.0 298.0 628.0 314.0 large-vehicle 0
>it represents a quadrilateral instead of rectangle

I wonder if there are codes or APIs in MMRotate to convert the quadrilateral to rectangle?

**Comment by zytx121** [comment]
Yes, you can find it at https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/core/bbox/transforms.py
