### ISSUE TITLE
how does rotated iou calculate?

### ISSUE THREAD

**Issue by AllieLan** [open-mmlab/mmrotate#377]
how does rotated iou calculate?
I am trying to write the process of rotate_iou by myself.
I have found the code in ./mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py, but it seems that the code doesn't clearly show how to calculate the intersection of two rotated bboxes, could you please tell me where to find the specific code?

**Comment by zytx121** [comment]
The related C++ code is in mmcv, and you can refer to:
- https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/box_iou_rotated.py
- https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/box_iou_rotated.cpp
- https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/common/cuda/box_iou_rotated_cuda.cuh
