### ISSUE TITLE
训练自制单类别数据集保错 FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'Aircraft_Carrier'

### ISSUE THREAD

**Issue by jsago** [open-mmlab/mmrotate#381]
I use the self-made data set for training. The single category is aircraft_carrier and the format is dota data set format. I modify the location, category and quantity of data sets in the source code and report errors ：”FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'Aircraft_Carrier'“，Then I modified it to a multi category dataset,report errors：“IndexError: DOTADataset: list index out of range”，Today, I used the public data set hrsc2016 to report an error：FileNotFoundError: HRSCDataset: [Errno 2] No such file or directory: 'D:/Moving/CV_and_DL/Datasets/ship_datasets/HRSC2016/my_test/FullDataSet/Annot
ations/.xml'
![QQ截图20220626220734](https://user-images.githubusercontent.com/24204254/175818192-6bfed8b8-9d27-4dfd-9d3f-9ae69e9165f4.jpg)
![QQ截图20220626220836](https://user-images.githubusercontent.com/24204254/175818198-fa59f511-b868-408d-8dc4-c13b03ec6688.jpg)
![QQ截图20220626220854](https://user-images.githubusercontent.com/24204254/175818202-5177e92b-41a2-4e4e-9ec2-47d7fe220ef8.jpg)

**Comment by zytx121** [comment]
Besides modifying the config, you also need to register a new Dataset just like [SARDataset](https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/datasets/sar.py).

Or you can just modify https://github.com/open-mmlab/mmrotate/blob/01439d1f2eab87e19f39cb2cb2a5b5c4afa3f6b6/mmrotate/datasets/sar.py#L9 to Aircraft_Carrier

**Comment by jsago** [comment]
I use the self-made data set for training. The single category is aircraft_carrier and the format is dota data set format.  I modify the location, category and quantity of data sets in the source code and report errors ：”FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'Aircraft_Carrier'“，Then I modified it to a multi category dataset,report errors：“IndexError: DOTADataset: list index out of range”，Today, I used the public data set hrsc2016 to report an error：FileNotFoundError: HRSCDataset: [Errno 2] No such file or directory: 'D:/Moving/CV_and_DL/Datasets/ship_datasets/HRSC2016/my_test/FullDataSet/Annot
ations/.xml'
![QQ截图20220627153934](https://user-images.githubusercontent.com/24204254/175887980-0057ca6c-eb00-4fce-bc86-144d625a0ff4.jpg)
![QQ截图20220626220836](https://user-images.githubusercontent.com/24204254/175887967-16e5e430-e590-4b9b-9af7-e4a0f3410a03.jpg)
![QQ截图20220626220854](https://user-images.githubusercontent.com/24204254/175887975-6ef78a78-6aa0-4ccd-970b-ff723ad8d7d7.jpg)
![QQ截图20220627154427](https://user-images.githubusercontent.com/24204254/175887983-06d2b87e-a32b-415c-8317-500dd81a907c.jpg)

**Comment by jsago** [comment]
> 

Yes, I did. I wrote a new script to inherit the source config and reported an error：“FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'Aircraft_Carrier'”. Then I tried to modify the source config and reported an error:"File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate"
![aa](https://user-images.githubusercontent.com/24204254/175888965-be934b97-8af8-4c38-8bd7-341ac48f23cf.jpg)

![zzz](https://user-images.githubusercontent.com/24204254/175888770-0e96e164-28ac-423f-9075-18064dc80c93.jpg)

**Comment by Pranav110500** [comment]
Hi there @zytx121, I am facing a similar issue, while using a different dataset (VALID dataset). I am getting the filenotfounderror as shown below in the image. I have sorted the images and the respective txt annotations in specific folders in the DOTA format also. Yet this error is popping, and I have no idea what split_config.json is supposed to be or why the error is occuring. Kindly help me out with anything on this.


![Screenshot from 2023-04-06 13-13-00](https://user-images.githubusercontent.com/104620839/230307758-99a2db1d-b907-42d9-a710-109d7b8b99a9.png)
