### ISSUE TITLE
A question about KFLoss

### ISSUE THREAD

**Issue by kuazhangxiaoai** [open-mmlab/mmrotate#383]
In kf_iou_loss function, what is the difference between pred_decode and pred?
Thanks for your answers.
![image](https://user-images.githubusercontent.com/54108453/176100551-c26854d7-62a6-4643-ba43-d8e4c268926a.png)

**Comment by zytx121** [comment]
The coder will decodes delta (dx, dy, dw, dh, da) back to original bbox (xc, yc, w, h, a). 
`pred_decode` means original bbox (xc, yc, w, h, a).
`pred` means delta (dx, dy, dw, dh, da).
