### ISSUE TITLE
How to expand the angle range to [0, 360) ?

### ISSUE THREAD

**Issue by JinYuannn** [open-mmlab/mmrotate#386]
as the title

**Comment by JinYuannn** [comment]
This is not unmeaningful, for example, to detect the exact orientation of the airplane's head.

**Comment by yangxue0827** [comment]
Heading detection (0-360) is not supported in mmrotate.

**Comment by zytx121** [comment]
> This is not unmeaningful, for example, to detect the exact orientation of the airplane's head.

You are right. We will add it to our backlogs.

**Comment by JinYuannn** [comment]
> 

Could you give me some advice for head detection based on mmrotate?

**Comment by JinYuannn** [comment]
> Heading detection (0-360) is not supported in mmrotate.

Could you give me some advice for head detection based on mmrotate?

**Comment by dashanlidewa** [comment]
Position Detection and Direction Prediction for Arbitrary-Oriented Ships via Multiscale Rotation Region Convolutional Neural Network
You can refer to this article.

**Comment by dashanlidewa** [comment]
> > Heading detection (0-360) is not supported in mmrotate.
> 
> Could you give me some advice for head detection based on mmrotate?

Position Detection and Direction Prediction for Arbitrary-Oriented Ships via Multiscale Rotation Region Convolutional Neural Network
You can refer to this article.

**Comment by JinYuannn** [comment]
> > > Heading detection (0-360) is not supported in mmrotate.
> > 
> > 
> > Could you give me some advice for head detection based on mmrotate?
> 
> Position Detection and Direction Prediction for Arbitrary-Oriented Ships via Multiscale Rotation Region Convolutional Neural Network You can refer to this article.

Thank you for the advice.

**Comment by qiuchun** [comment]
hi can you solived this  problem ?
i also have this problem ,can you  ask me some ways to solve this problem? thank you very much !

**Comment by JinYuannn** [comment]
> hi can you solived this problem ? i also have this problem ,can you ask me some ways to solve this problem? thank you very much !

I am studying

**Comment by qiuchun** [comment]
> 

ok,thankyou , i have solve it yesterday,i can expand the angle range to [0, 360),it can work my dataset but i dont no whether it also work in other dataset.

**Comment by JinYuannn** [comment]
wow，could i have your WeChat

**Comment by JinYuannn** [comment]
> > 
> 
> ok,thankyou , i have solve it yesterday,i can expand the angle range to [0, 360),it can work my dataset but i dont no whether it also work in other dataset.

could you briefly describe your method here, which can help more people? thanks

**Comment by qiuchun** [comment]
I think the detection frame has directions, and the rotation angle can be reconstructed according to the four points of the detection frame

**Comment by JinYuannn** [comment]
do you mean the bbox's corner points?

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/pull/1061
someone support this feature.
