### ISSUE TITLE
Question about KFIoU code

### ISSUE THREAD

**Issue by sjhong310** [open-mmlab/mmrotate#387]
This cod below is [KFIoU](https://arxiv.org/pdf/2201.12558v3.pdf)
https://github.com/open-mmlab/mmrotate/blob/01439d1f2eab87e19f39cb2cb2a5b5c4afa3f6b6/mmrotate/models/losses/kf_iou_loss.py#L38-L85

They calculate `Vb_p`, `Vb_t`, `Vb`.
When you get sqrt of negative number, it gives you `nan`.
So, they change all `nan` to `0` at L73 for `Vb`.

My question is that why don't they change `nan` to `0` for `Vb_p` and `Vb_t`?

If I change KFIoU code like this below, is this wrong?
I added `abs( )` to `Vb_p`, `Vb_t`, `Vb`

```
Vb_p = 4 * abs(Sigma_p.det()).sqrt() 
Vb_t = 4 * abs(Sigma_t.det()).sqrt() 
K = Sigma_p.bmm((Sigma_p + Sigma_t).inverse()) 
Sigma = Sigma_p - K.bmm(Sigma_p) 
Vb = 4 * abs(Sigma.det()).sqrt() 
KFIoU = Vb / (Vb_p + Vb_t - Vb + eps) 
```

**Comment by zytx121** [comment]
You can try it and see the effect. Welcome feedback.
