### ISSUE TITLE
--eval error

### ISSUE THREAD

**Issue by Rocky-YU** [open-mmlab/mmrotate#389]
For my own dataset, the model was tested after the training was completed, and an error was reported, and I didn't know how to correct it. The specific questions are as follows：
-------------------------------------------------------------------------------------------------------------------------------------------------

(rotate03) E:\RotateDetection\mmrotate-0.3.1>python tools/test.py configs/oriented_rcnn/custum.py tools/work_dirs/34-1/latest.pth --format-only --eval-options submission_dir=work_dirs/oriented/Task1_results
D:\ProgramData\Anaconda3\envs\rotate03\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or al
so use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: tools/work_dirs/34-1/latest.pth
completed: 0, elapsed: 0s
Merging patch bboxes into full image!!!
Multiple processing
completed: 0, elapsed: 0s
Traceback (most recent call last):
  File "tools/test.py", line 257, in <module>
    main()
  File "tools/test.py", line 239, in main
    dataset.format_results(outputs, **kwargs)
  File "e:\rotatedetection\mmrotate-0.3.1\mmrotate\datasets\dota.py", line 324, in format_results
    id_list, dets_list = self.merge_det(results, nproc)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by zytx121** [comment]
This is caused by the wrong data path. Please check the data path of your test set.

**Comment by Rocky-YU** [comment]
Thank you very much, the problem was solved.

**Comment by Pranav110500** [comment]
@zytx121 Hey there, could you let me know where exactly to change the data path that causes this error? I am doing this  and set the correct data_root in dotav1.py after splitting the dotav1 dataset, still I'm getting this unpacking error.

![Screenshot from 2023-02-07 18-46-40](https://user-images.githubusercontent.com/104620839/217254558-dc3ea147-7a3f-4279-b03c-d8160a19747a.png)

**Comment by getup201** [comment]
> @zytx121 Hey there, could you let me know where exactly to change the data path that causes this error? I am doing this and set the correct data_root in dotav1.py after splitting the dotav1 dataset, still I'm getting this unpacking error.
> 
> ![Screenshot from 2023-02-07 18-46-40](https://user-images.githubusercontent.com/104620839/217254558-dc3ea147-7a3f-4279-b03c-d8160a19747a.png)

hey buddy!  Did you solve this problem, I am also facing this problem, Thx.
