### ISSUE TITLE
Learning rate and min-batch: May I ask whats the mini_batch of the default learning rate in config files?

### ISSUE THREAD

**Issue by gys1287009045** [open-mmlab/mmrotate#39]
May I ask whats the mini_batch of the default learning rate in config files?

For example, the lr in roi_trans_r50_fpn_1x_dota_le90.py is 0.005, so whats the corresponding samples_per_gpu and gpus in other words the size of mini-batch?

Thanks for reply.

**Comment by zytx121** [comment]
Hi @gys1287009045  
`samples_per_gpu = 2`
You could check it at `configs/_base_/datasets/dotav1.py`
https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/configs/_base_/datasets/dotav1.py#L31
