### ISSUE TITLE
Changing .png to .jpg in dataset/dota.py

### ISSUE THREAD

**Issue by bgsuello** [open-mmlab/mmrotate#391]
Hello,

What could be the effect on changing the `.png` to `.jpg` in DOTA dataset during training? https://github.com/open-mmlab/mmrotate/blob/01439d1f2eab87e19f39cb2cb2a5b5c4afa3f6b6/mmrotate/datasets/dota.py#L72

**Comment by yangxue0827** [comment]
almost no influence. but you need save image as jpg format after data split step.

**Comment by bgsuello** [comment]
i see, thank you @yangxue0827
