### ISSUE TITLE
How to extract bounding box coordinates, confidance values and class in a readable format after inference?

### ISSUE THREAD

**Issue by VTrencsenyi** [open-mmlab/mmrotate#399]
I loaded the results with inference_detector_by_patches(), but instead of visualising the results, I want to save them in a dataframe/array/csv file or whatever. I looked in the contents of the 'results', but there seems to be too much data even for a single object. How can I export/compute the bounding box coordinates, confidance values and predicted classes??

**Comment by zytx121** [comment]
You can refer to https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/datasets/dota.py#L297

**Comment by VTrencsenyi** [comment]
> You can refer to
> 
> https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/datasets/dota.py#L297

Thanks, but the output of inference_detector_by patches() is not compatible with this function. I get the assertion "results must be a list", and what is have from the inference detector is a list of multi dim arrays

**Comment by zytx121** [comment]
We don't support exporting the results file of `inference_detector_by_patches` now, maybe you need to modify format_results by yourself.

**Comment by jbwang1997** [comment]
The results outputs by `inference_detector_by_patches` only use a score threshold of 0.05. You can filter out most objects by limiting the scores.

**Comment by VTrencsenyi** [comment]
> The results outputs by `inference_detector_by_patches` only use a score threshold of 0.05. You can filter out most objects by limiting the scores.

How can I limit that? The function only takes a treshold as input for merging the patches, I dont see a treshold for the scores.

**Comment by zytx121** [comment]
You can adjust the `test_cfg.score_thr` in your config file.

**Comment by jbwang1997** [comment]
> > The results outputs by `inference_detector_by_patches` only use a score threshold of 0.05. You can filter out most objects by limiting the scores.
> 
> How can I limit that? The function only takes a treshold as input for merging the patches, I dont see a treshold for the scores.

This function is in [imshow_det_rbboxes](https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/core/visualization/image.py#L77). If only using inference_detector_by_patches, you need to filter the low confidence objects by yourself.
