### ISSUE TITLE
KeyError: "DOTADataset: 'RMosaic is not in the pipeline registry'"

### ISSUE THREAD

**Issue by kimlia545** [open-mmlab/mmrotate#401]
```
train_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="LoadAnnotations", with_bbox=True),
    dict(type="RResize", img_scale=(1024, 1024)),
    dict(
        type="RRandomFlip",
        flip_ratio=[0.25, 0.25, 0.25],
        direction=["horizontal", "vertical", "diagonal"],
        version="le90",
    ),
    dict(
        type="RMosaic",
        img_scale=(640, 640),
        center_ratio_range=(0.5, 1.5),
        min_bbox_size=10,
        bbox_clip_border=True,
        skip_filter=True,
        pad_val=114,
        prob=1.0,
        version="le90",
    ),
    dict(
        type="Normalize",
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True,
    ),
    dict(type="Pad", size_divisor=32),
    dict(type="DefaultFormatBundle"),
    dict(type="Collect", keys=["img", "gt_bboxes", "gt_labels"]),
]
```
KeyError: 'RMosaic is not in the pipeline registry'
KeyError: "DOTADataset: 'RMosaic is not in the pipeline registry'"

```
dict(
        type="RandomCenterCropPad",
        crop_size=None,
        ratios=(0.9, 1.0, 1.1),
        border=128,
        mean=None,
        std=None,
        to_rgb=None,
        test_mode=False,
        test_pad_mode=("logical_or", 127),
        test_pad_add_pix=0,
        bbox_clip_border=True,
    ),
```
AssertionError: DOTADataset: RandomCenterCropPad:

**Comment by yangxue0827** [comment]
@heiyuxiaokai any suggestions?

**Comment by yangxue0827** [comment]
What version of mmrotate are you using? @kimlia545

**Comment by heiyuxiaokai** [comment]
@kimlia545 Here are some examples:

### 1. rotated_retinanet_obb_r50_fpn_1x_dota_rmo_le90.py
```
_base_ = [
    '../_base_/datasets/dotav1.py', '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]
dataset_type = 'DOTADataset'
data_root = ''
angle_version = 'le90'
model = dict(
    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5),
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range=angle_version,
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(.0, .0, .0, .0, .0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(
        type='RMosaic', 
        img_scale=(1024, 1024),
        min_bbox_size=5
    ),
    dict(
        type='RRandomCrop', 
        crop_size=(1024, 1024),
        version=angle_version
    ),
    # dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version=angle_version),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
train_dataset = dict(
    _delete_ = True,
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        version=angle_version
    ),
    pipeline=train_pipeline,
    max_refetch=50
)

data = dict(
    train=train_dataset,
    val=dict(
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        version=angle_version),
    test=dict(
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        version=angle_version))
```
### 2. rotated_retinanet_obb_r50_fpn_1x_dota_rmo_rr_le90.py
```
_base_ = [
    '../_base_/datasets/dotav1.py', '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]
dataset_type = 'DOTADataset'
data_root = ''
angle_version = 'le90'
model = dict(
    type='RotatedRetinaNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5),
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range=angle_version,
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(.0, .0, .0, .0, .0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(
        type='RMosaic', 
        img_scale=(1024, 1024),
        min_bbox_size=5
    ),
    dict(
        type='RRandomCrop', 
        crop_size=(1024, 1024),
        version=angle_version
    ),
    # dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version=angle_version),
    dict(
        type='PolyRandomRotate',
        rotate_ratio=0.5,
        angles_range=180,
        auto_bound=True,
        rect_classes=[9, 11],
        version=angle_version),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
train_dataset = dict(
    _delete_ = True,
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        version=angle_version
    ),
    pipeline=train_pipeline,
    max_refetch=50
)

data = dict(
    train=train_dataset,
    val=dict(
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        version=angle_version),
    test=dict(
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        version=angle_version))
```

**Comment by dou3516** [comment]
Hi, @heiyuxiaokai , How to use Mosaic in mmrotate 1.x? Since it use train_dataloader instead of train_dataset, and type='MultiImageMixDataset' is not supported in train_dataloader.

**Comment by nanhui69** [comment]
> @kimlia545 Here are some examples:
> 
> ### 1. rotated_retinanet_obb_r50_fpn_1x_dota_rmo_le90.py
> ```
> _base_ = [
>     '../_base_/datasets/dotav1.py', '../_base_/schedules/schedule_1x.py',
>     '../_base_/default_runtime.py'
> ]
> dataset_type = 'DOTADataset'
> data_root = ''
> angle_version = 'le90'
> model = dict(
>     type='RotatedRetinaNet',
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         zero_init_residual=False,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         style='pytorch',
>         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         start_level=1,
>         add_extra_convs='on_input',
>         num_outs=5),
>     bbox_head=dict(
>         type='RotatedRetinaHead',
>         num_classes=15,
>         in_channels=256,
>         stacked_convs=4,
>         feat_channels=256,
>         assign_by_circumhbbox=None,
>         anchor_generator=dict(
>             type='RotatedAnchorGenerator',
>             octave_base_scale=4,
>             scales_per_octave=3,
>             ratios=[1.0, 0.5, 2.0],
>             strides=[8, 16, 32, 64, 128]),
>         bbox_coder=dict(
>             type='DeltaXYWHAOBBoxCoder',
>             angle_range=angle_version,
>             norm_factor=None,
>             edge_swap=True,
>             proj_xy=True,
>             target_means=(.0, .0, .0, .0, .0),
>             target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
>         loss_cls=dict(
>             type='FocalLoss',
>             use_sigmoid=True,
>             gamma=2.0,
>             alpha=0.25,
>             loss_weight=1.0),
>         loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
>     train_cfg=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.5,
>             neg_iou_thr=0.4,
>             min_pos_iou=0,
>             ignore_iof_thr=-1,
>             iou_calculator=dict(type='RBboxOverlaps2D')),
>         allowed_border=-1,
>         pos_weight=-1,
>         debug=False),
>     test_cfg=dict(
>         nms_pre=2000,
>         min_bbox_size=0,
>         score_thr=0.05,
>         nms=dict(iou_thr=0.1),
>         max_per_img=2000))
> 
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(
>         type='RMosaic', 
>         img_scale=(1024, 1024),
>         min_bbox_size=5
>     ),
>     dict(
>         type='RRandomCrop', 
>         crop_size=(1024, 1024),
>         version=angle_version
>     ),
>     # dict(type='RResize', img_scale=(1024, 1024)),
>     dict(
>         type='RRandomFlip',
>         flip_ratio=[0.25, 0.25, 0.25],
>         direction=['horizontal', 'vertical', 'diagonal'],
>         version=angle_version),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
> ]
> train_dataset = dict(
>     _delete_ = True,
>     type='MultiImageMixDataset',
>     dataset=dict(
>         type=dataset_type,
>         ann_file=data_root + 'trainval/annfiles/',
>         img_prefix=data_root + 'trainval/images/',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='LoadAnnotations', with_bbox=True)
>         ],
>         version=angle_version
>     ),
>     pipeline=train_pipeline,
>     max_refetch=50
> )
> 
> data = dict(
>     train=train_dataset,
>     val=dict(
>         ann_file=data_root + 'trainval/annfiles/',
>         img_prefix=data_root + 'trainval/images/',
>         version=angle_version),
>     test=dict(
>         ann_file=data_root + 'test/images/',
>         img_prefix=data_root + 'test/images/',
>         version=angle_version))
> ```
> 
> ### 2. rotated_retinanet_obb_r50_fpn_1x_dota_rmo_rr_le90.py
> ```
> _base_ = [
>     '../_base_/datasets/dotav1.py', '../_base_/schedules/schedule_1x.py',
>     '../_base_/default_runtime.py'
> ]
> dataset_type = 'DOTADataset'
> data_root = ''
> angle_version = 'le90'
> model = dict(
>     type='RotatedRetinaNet',
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         zero_init_residual=False,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         style='pytorch',
>         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         start_level=1,
>         add_extra_convs='on_input',
>         num_outs=5),
>     bbox_head=dict(
>         type='RotatedRetinaHead',
>         num_classes=15,
>         in_channels=256,
>         stacked_convs=4,
>         feat_channels=256,
>         assign_by_circumhbbox=None,
>         anchor_generator=dict(
>             type='RotatedAnchorGenerator',
>             octave_base_scale=4,
>             scales_per_octave=3,
>             ratios=[1.0, 0.5, 2.0],
>             strides=[8, 16, 32, 64, 128]),
>         bbox_coder=dict(
>             type='DeltaXYWHAOBBoxCoder',
>             angle_range=angle_version,
>             norm_factor=None,
>             edge_swap=True,
>             proj_xy=True,
>             target_means=(.0, .0, .0, .0, .0),
>             target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
>         loss_cls=dict(
>             type='FocalLoss',
>             use_sigmoid=True,
>             gamma=2.0,
>             alpha=0.25,
>             loss_weight=1.0),
>         loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
>     train_cfg=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.5,
>             neg_iou_thr=0.4,
>             min_pos_iou=0,
>             ignore_iof_thr=-1,
>             iou_calculator=dict(type='RBboxOverlaps2D')),
>         allowed_border=-1,
>         pos_weight=-1,
>         debug=False),
>     test_cfg=dict(
>         nms_pre=2000,
>         min_bbox_size=0,
>         score_thr=0.05,
>         nms=dict(iou_thr=0.1),
>         max_per_img=2000))
> 
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(
>         type='RMosaic', 
>         img_scale=(1024, 1024),
>         min_bbox_size=5
>     ),
>     dict(
>         type='RRandomCrop', 
>         crop_size=(1024, 1024),
>         version=angle_version
>     ),
>     # dict(type='RResize', img_scale=(1024, 1024)),
>     dict(
>         type='RRandomFlip',
>         flip_ratio=[0.25, 0.25, 0.25],
>         direction=['horizontal', 'vertical', 'diagonal'],
>         version=angle_version),
>     dict(
>         type='PolyRandomRotate',
>         rotate_ratio=0.5,
>         angles_range=180,
>         auto_bound=True,
>         rect_classes=[9, 11],
>         version=angle_version),
>     dict(type='RResize', img_scale=(1024, 1024)),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
> ]
> train_dataset = dict(
>     _delete_ = True,
>     type='MultiImageMixDataset',
>     dataset=dict(
>         type=dataset_type,
>         ann_file=data_root + 'trainval/annfiles/',
>         img_prefix=data_root + 'trainval/images/',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='LoadAnnotations', with_bbox=True)
>         ],
>         version=angle_version
>     ),
>     pipeline=train_pipeline,
>     max_refetch=50
> )
> 
> data = dict(
>     train=train_dataset,
>     val=dict(
>         ann_file=data_root + 'trainval/annfiles/',
>         img_prefix=data_root + 'trainval/images/',
>         version=angle_version),
>     test=dict(
>         ann_file=data_root + 'test/images/',
>         img_prefix=data_root + 'test/images/',
>         version=angle_version))
> `






what does the max_refetch mean?
