### ISSUE TITLE
Lr changes differently between my own experiment and official training logs.

### ISSUE THREAD

**Issue by Nankle** [open-mmlab/mmrotate#402]
![image](https://user-images.githubusercontent.com/38069063/178022863-7b933f4b-2e14-47ab-bca3-7195d519a8b0.png)

The above is the training log of my own experiment, the lr will  remain unchanged from epoch 11 to 12, but the official training log of both s2anet and Retinanet-obb is quiet different ( Pic Below)

![image](https://user-images.githubusercontent.com/38069063/178023101-517cf6bb-0172-498a-b412-112995c6ae12.png)

The config is the same (schedule_1x.py) Why is that happend?

**Comment by zytx121** [comment]
You need to check your config in the printed log. It seems that you may have overwritten the config of `lr_config.step`.

**Comment by Nankle** [comment]
![1657598905254](https://user-images.githubusercontent.com/38069063/178406601-bbc5dfc2-e91a-4531-becd-6ed3be02de53.png)

but lr_config is exactly the same as the official

**Comment by Nankle** [comment]
How odd

**Comment by heiyuxiaokai** [comment]
You can compare `xxx.log` and `xxx.log.json` in the training dir. It seems the difference in output format between logs in the terminal and logs in log.json. `LR` in log.json may be under the rule of keeping one significant digit (from `2.500e-05` to `3e-5`).

**Comment by yangxue0827** [comment]
solved by wechat.

**Comment by Shmily-YH** [comment]
so how this happened? in my case, the learning rate did not decrease by ten...

**Comment by Shmily-YH** [comment]
so how this happened? in my case, the learning rate did not decrease by ten...
