### ISSUE TITLE
Why does it stop when it runs here?

### ISSUE THREAD

**Issue by fadaishaitaiyang** [open-mmlab/mmrotate#403]
![V5XK {P9EA$A DMR3{`GM(1](https://user-images.githubusercontent.com/63134541/178098087-48bb1154-293a-4420-bd5e-647bfec9c660.png)

**Comment by TekayaNidham** [comment]
can you provide your config file

**Comment by zytx121** [comment]
Does it print any error?
Our config is here:
herhttps://download.openmmlab.com/mmrotate/v0.1.0/roi_trans/roi_trans_r50_fpn_1x_dota_le90/roi_trans_r50_fpn_1x_dota_le90_20220130_132727.log

**Comment by liuyanyi** [comment]
you can add nproc=1 to eval-options, i think the multiprocess stucked.


```
python ./tools/test.py checkpoint.pth --format-only --eval-options submission_dir=work_dirs/Task1_results nproc=1
```

**Comment by fadaishaitaiyang** [comment]
Resolved, thank you

**Comment by JavierWei** [comment]
> Resolved, thank you！
