### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by HeuristicLU** [open-mmlab/mmrotate#406]
我测试时候一直加载数据集报错，后来看了下，可能是下面这两个配置文件有点问题，我改后可以正常训练和评估
（1）https://github.com/open-mmlab/mmrotate/blob/main/configs/kfiou/r3det_kfiou_ln_swin_tiny_adamw_fpn_1x_dota_ms_rr_oc.py
这个文件62-67行
    val=dict(
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/'),
    test=dict(
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/'))
这里的test 应该改为下面这个吧：
       ann_file=data_root + 'test/annfiles/',

（2）还有https://github.com/open-mmlab/mmrotate/blob/main/configs/_base_/datasets/dotav1.py
43-47行
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))
是不是也应该修改成ann_file=data_root + 'test/annfiles/'

**Comment by yangxue0827** [comment]
test没有标注文件，所以故意这么写的
