### ISSUE TITLE
How to do if I want to use mmrotate on COCO format dataset?

### ISSUE THREAD

**Issue by Lanxin1011** [open-mmlab/mmrotate#41]
Should I modify the code structure of mmrotate/datasets/dota.py or there is another way out? Thank you for your attention：）

**Comment by zytx121** [comment]
Sorry, we didn't support the COCO format dataset now. Do you want to train an open-source dataset? We can give priority to supporting it.

**Comment by Lanxin1011** [comment]
Thank u for your response:) I've been trying to train the model on GAOFEN and FAIR1M dataset, since there are OBB annotations in them, they might also suitable for rotated object detection tasks. Anyhow I will use the toolbox provided above and I believe you've solved my problem~
