### ISSUE TITLE
How to get the coordinates of the front part of an object from the model result?

### ISSUE THREAD

**Issue by kimlia545** [open-mmlab/mmrotate#413]
How do I get the coordinates corresponding to the head (for example, the front of a car)?
Annotation coordinate from Dota Dataset 
![anno](https://user-images.githubusercontent.com/72369991/180373376-f79b8748-0b92-47e3-80e7-53139a86d413.png)

Model prediction results (oriented_rcnn_r50_fpn_1x_dota_le90,  obb2poly_np_le90)
![P0007](https://user-images.githubusercontent.com/72369991/180373453-e36f1f70-3595-40dd-992f-f820ff2bf4bd.png)

**Comment by yangxue0827** [comment]
The DOTA dataset does not explicitly annotate header information.
