### ISSUE TITLE
A bug in mmrotate/models/dense_heads/oriented_reppoints_head.py

### ISSUE THREAD

**Issue by windyjunfeng** [open-mmlab/mmrotate#417]
The similar problem and solution to #100 and #232. 

**Problem**
When I train oriented reppoints and change the size of batch, the following error occurs.
assert input.size(0) == target.size(0)

**Solution** 
Modify mmrotate/models/dense_heads/oriented_reppoints_head.py
line 795
`all_overlaps_rotate_list = [None] * 4`
to
`all_overlaps_rotate_list = [None] * len(proposals_list)`

**Comment by yangxue0827** [comment]
@LiWentomng

**Comment by LiWentomng** [comment]
@windyjunfeng Thanks!  You are right.  When the `samples_per_gpu > 4` in the config, the target assigner can not work normally.  I will sumit a PR to solve this problem.
