### ISSUE TITLE
使用自己的数据集出现错误

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#427]
我从0.2版本的mmrotate升级到了最新版本的mmrotate，运行train.py时报错：FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'Insulator'
我使用自己的数据集进行训练，其中只有一个类Insulator，查看了最新的资料后，我在dotav1.py中新增加了classes，如下图所示
![image](https://user-images.githubusercontent.com/90760124/181151687-fb7f7873-79ec-4537-b31b-7c1f565e4862.png)
![image](https://user-images.githubusercontent.com/90760124/181151745-2f4841cf-0f30-4f7b-aabe-b6a8ae9747db.png)
但是好像还是不起作用，在之前的版本使用该数据集时可以正常运行，这个数据集是使用之前版本中tools文件夹下的img_split.py转换的，不知道是否新版本下不支持旧版本转换的数据集？或者我需要更改什么新的配置？
我需要您的帮助！

**Comment by hh123445** [comment]
我发现单类别的情况在类别后增加一个,可以解决这个问题，如下图所示
![image](https://user-images.githubusercontent.com/90760124/181189984-16143c38-785c-44bb-99db-76dc62e888ae.png)

**Comment by hh123445** [comment]
但是我还是不知道原因，如果可以的话请告诉我为什么增加，后可以解决此问题

**Comment by yangxue0827** [comment]
知道单类要这么设置就行，细节只能去看源码，没必要纠结。

**Comment by myheal000** [comment]
我遇到了相同的情况，类别上在在后面加上逗号了，如下
dataset_type = 'DOTADataset'
data_root = '/home/e1228/Desktop/Workspace/wmx/mmrotate-main/data/split_ss_dota'
classes = ('ship',) 
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(type='RRandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))
配置文件中的num_class也改成了1,报错如下，请问您知道该如何修改吗？
File "/home/e1228/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "DOTADataset: 'small-vehicle'"

**Comment by Royalbx** [comment]
> 我遇到了相同的情况，类别上在在后面加上逗号了，如下 dataset_type = 'DOTADataset' data_root = '/home/e1228/Desktop/Workspace/wmx/mmrotate-main/data/split_ss_dota' classes = ('ship',) img_norm_cfg = dict( mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True) train_pipeline = [ dict(type='LoadImageFromFile'), dict(type='LoadAnnotations', with_bbox=True), dict(type='RResize', img_scale=(1024, 1024)), dict(type='RRandomFlip', flip_ratio=0.5), dict(type='Normalize', **img_norm_cfg), dict(type='Pad', size_divisor=32), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']) ] test_pipeline = [ dict(type='LoadImageFromFile'), dict( type='MultiScaleFlipAug', img_scale=(1024, 1024), flip=False, transforms=[ dict(type='RResize'), dict(type='Normalize', **img_norm_cfg), dict(type='Pad', size_divisor=32), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img']) ]) ] data = dict( samples_per_gpu=2, workers_per_gpu=2, train=dict( type=dataset_type, classes=classes, ann_file=data_root + 'trainval/annfiles/', img_prefix=data_root + 'trainval/images/', pipeline=train_pipeline), val=dict( type=dataset_type, classes=classes, ann_file=data_root + 'trainval/annfiles/', img_prefix=data_root + 'trainval/images/', pipeline=test_pipeline), test=dict( type=dataset_type, classes=classes, ann_file=data_root + 'test/images/', img_prefix=data_root + 'test/images/', pipeline=test_pipeline)) 配置文件中的num_class也改成了1,报错如下，请问您知道该如何修改吗？ File "/home/e1228/anaconda3/envs/mmrotate/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') KeyError: "DOTADataset: 'small-vehicle'"

请问你解决这个问题了吗？我的多类别也报type(e)(f'{obj_cls.**name**}: {e}') KeyError: 这个错，不知道怎么解决
