### ISSUE TITLE
tensorrt推理oriented rcnn 时，如何从返回的结果得到框的类型，目前来看只得到一个得分，没有类型

### ISSUE THREAD

**Issue by bfdong** [open-mmlab/mmrotate#431]
tensorrt推理oriented rcnn 时，如何从返回的结果得到框的类型，目前来看只得到一个得分，没有类型，打印推理结果形状时，是1000*6

**Comment by zytx121** [comment]
The tensorrt can achieve 0.758 at the DOTA dataset.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/10410257/182327223-f4e1251b-9337-4190-992b-faae63848103.png">
So the results have the label information, of course.

The results are the same as with PyTorch version, and you can get the label by
https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/models/detectors/base.py#L69-L73

**Comment by bfdong** [comment]
thx, the reason is my wrong code, the second output tensor data type is int,but i seem it float32
