### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmrotate#432]
The following error occurs when calculating mAP in the test set, how to solve it
  File "tools/test.py", line 257, in <module>
    main()
  File "tools/test.py", line 249, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/root/autodl-tmp/code/mmrotate/mmrotate/datasets/dota.py", line 203, in evaluate
    mean_ap, _ = eval_rbbox_map(
  File "/root/autodl-tmp/code/mmrotate/mmrotate/core/evaluation/eval_map.py", line 177, in eval_rbbox_map
    cls_dets, cls_gts, cls_gts_ignore = get_cls_results(
  File "/root/autodl-tmp/code/mmrotate/mmrotate/core/evaluation/eval_map.py", line 114, in get_cls_results
    cls_gts.append(ann['bboxes'][gt_inds, :])
TypeError: list indices must be integers or slices, not tuple

**Comment by zytx121** [comment]
@19990101lrk 
The reason is we don't have the ground truth of the DOTA test set. They provide an [online evaluation platform](https://captain-whu.github.io/DOTA/evaluation.html).

**Comment by Pranav051100** [comment]
Hello  @zytx121  Sir,
I am trying this testing command "python ./tools/test.py configs/redet/redet_re50_refpn_fp16_1x_dota_le90.py checkpoints/redet_re50_refpn_fp16_1x_dota_le90-1e34da2d.pth --eval mAP" on the dota dataset.

I have changed the test folder to val (with 5297 images), however, I am still getting the issue of this TypeError. Please go through the screenshot given below and and help would be appreciated.

![Screenshot from 2023-02-14 01-22-56](https://user-images.githubusercontent.com/116499749/218561188-31fbeb55-9af2-4dec-92a3-f3819d0e186b.png)
