### ISSUE TITLE
Why rotatedRetinaNet can't use the RotatedIoULoss?

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#440]
I want to replace L1Loss with RotatedIoULoss during rotatedRetinaNet training, but when I train to the 10th epoch, loss_bbox becomes Nan. As shown in the following figure.

![image](https://user-images.githubusercontent.com/90760124/182284874-5b9df559-547a-4548-9e3b-3464d559bfc6.png)
![image](https://user-images.githubusercontent.com/90760124/182284973-a8d4ce94-4bec-4440-98a1-a61f2d3e91d1.png)

**Comment by yangxue0827** [comment]
`reg_decoded_bbox=True,`
should be added before
`loss_bbox=dict(`

**Comment by hh123445** [comment]
it is usefull,thank you!
