### ISSUE TITLE
oom error

### ISSUE THREAD

**Issue by Im-JimmyHu** [open-mmlab/mmrotate#442]
my device is win 10 with rtx3060(12gb)
when i try to train with [configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py](https://github.com/open-mmlab/mmrotate/blob/main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py) and dota v1.5 ,even i set the batch-szie to 1,it still run oom after 1000steps. after reading the faq,i set the `with_cp=true.`,but it not help .the other 2 parm like *gpu_assign_th* and `fp16`, i don't know where to set. can you give me some advice?

besides when i turn to hrsc, i find a typo and fix it 
https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/datasets/hrsc.py#L98
you may need to remove the `self.img_prefix`,or you will find the path error.

**Comment by zytx121** [comment]
You can use fp16 by adding one line command to your config:
https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/configs/redet/redet_re50_refpn_fp16_1x_dota_le90.py#L3

Or,  you can use  
https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/configs/redet/redet_re50_refpn_1x_dota_ms_rr_le90.py#L40

**Comment by zytx121** [comment]
Thanks! I will check it.
