### ISSUE TITLE
About img_norm_cfg

### ISSUE THREAD

**Issue by zhangchi621** [open-mmlab/mmrotate#443]
How to set img_norm_cfg if I want train my dataset? or how to calculate it?

img_norm_cfg = dict(                          
    mean=[123.675, 116.28, 103.53],        
    std=[58.395, 57.12, 57.375],           
    to_rgb=True)

**Comment by zytx121** [comment]
Normally, ` img_norm_cfg` will not be changed even if the dataset is different.

**Comment by zhangchi621** [comment]
> 

get it，thank you！
