### ISSUE TITLE
During the test of DOTA dataset, the checkpoint was loaded successfully, but it got stuck in Mutiple processing 

### ISSUE THREAD

**Issue by JavierWei** [open-mmlab/mmrotate#449]
During the test of DOTA dataset, the checkpoint was loaded successfully, but it got stuck in Mutiple processing.
I tried many times but couldn't solve it

load checkpoint from local path: work_dirs/rotated_faster_rcnn_swin_fpn_1x_dota_le90/epoch_12.pth
[                                                  ] 0/71888, elapsed: 0s, ETA:
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 71888/71888, 10.4 task/s, elapsed: 6892s, ETA:     0s
Merging patch bboxes into full image!!!
Multiple processing
[                                                  ] 1/937, 82.3 task/s, elapsed: 0s, ETA:    11s

How can this be solved? I tried many times, but none of them worked. I really hope to get your help Thank you!

**Comment by ShengqiWang** [comment]
I met the same problem！ It gets stuck during the merging process.

**Comment by liuyanyi** [comment]
Same with https://github.com/open-mmlab/mmrotate/issues/403 , you can add nproc=1 in eval-options.

**Comment by JavierWei** [comment]
> Same with #403 , you can add nproc=1 in eval-options.

Resolved, thank you！
