### ISSUE TITLE
I ran test after training but it was stuck to compute mAP 

### ISSUE THREAD

**Issue by DangChuong-DC** [open-mmlab/mmrotate#45]
**Describe the bug**
I finished the training of Rotated Faster-RCNN on Dota 1.5 train set. 
I tried to run test on Dota 1.5 validation set and it seems like it got stuck computing mAP.

**Reproduction**

1. What command or script did you run?

```
python tools/test.py \
    configs/rotated_faster_rcnn/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90.py \
    work_dirs/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90/latest.pth \
    --eval mAP
```
And
```
python tools/test.py \
    configs/rotated_faster_rcnn/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90.py \
    work_dirs/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90/latest.pth \
    --eval mAP \
    --eval-options nproc=1
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I did not change much. Except below to debug
![modification1](https://user-images.githubusercontent.com/40515271/156119966-a3863bb1-c543-4c95-a88a-140e79560864.png)

3. What dataset did you use?
DOTA 1.5

**Environment**
![env1](https://user-images.githubusercontent.com/40515271/156120096-e58a534a-faf7-4d9d-b42e-0c266c00c7eb.png)

**Error traceback**
![traceback](https://user-images.githubusercontent.com/40515271/156120337-2c4297c9-4b5e-41c9-a2a7-e7e45d5ce0e2.png)

Thank you in advanced!

**Comment by yangxue0827** [comment]
try
```
./tools/dist_test.sh  \
  configs/rotated_faster_rcnn/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90.py \
  work_dirs/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90/latest.pth 1 --eval mAP
```

**Comment by DangChuong-DC** [comment]
Hi @yangxue0827 and thank you for your response!
I confirmed that it is running fine with your suggested command:
```
./tools/dist_test.sh  \
  configs/rotated_faster_rcnn/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90.py \
  work_dirs/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90/latest.pth 1 --eval mAP
```

Moreover, I resolved the issue by these fixes. With the changes, now I can run the single test as normal:
```
python tools/test.py \
    configs/rotated_faster_rcnn/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90.py \
    work_dirs/DC_rotated_faster_rcnn_r50_fpn_1x_dota_le90/latest.pth \
    --eval mAP
```

Here are the fixes in `dota.py`:
+ Instead of `from multiprocessing import Pool` -> `from multiprocessing import get_context`
![import1](https://user-images.githubusercontent.com/40515271/156150975-490cef0a-47e0-40c6-94a1-4944691718db.png)

+ Then change init `Pool()` in `eval_map()` as below:
![eval_map](https://user-images.githubusercontent.com/40515271/156151384-760d5a09-b34a-4fed-ad19-fdf2a146a9c4.png)

I found this fix in this blog:
https://pythonspeed.com/articles/python-multiprocessing/

Cheer!

**Comment by yangxue0827** [comment]
Thanks. Great job!

**Comment by zytx121** [comment]
Hi @DangChuong-DC 
Thank you very much for your solution. Could you submit a PR to help us fix this bug?

**Comment by zytx121** [comment]
@jbwang1997 Do you think this solution is feasible?

**Comment by jbwang1997** [comment]
Yes, I think it also can solve the same deadlock problem in the `merge_det` function.
By the way, since 2.21, mmdetection started to use the `fork` method to set up multiprocess for speeding up training. https://github.com/open-mmlab/mmdetection/pull/6974.

**Comment by DangChuong-DC** [comment]
Ohm! #52 #53 haha =))
