### ISSUE TITLE
Model output

### ISSUE THREAD

**Issue by Shmily-YH** [open-mmlab/mmrotate#451]
Thanks for your wonderful work!
I have a question about the model output, for many rotated object detection works you have reimplemented in this project, but different  works tend to have different regression values such as (x, y, w, h, theta), (x1, y1, x2, y2, x3, y3, x4, y4) and so on. So i am wondering, during testing phase, **is that all models in this work output the same result (like polygons maybe...)? So for training is that so?** I am not finding out a clear description or bbox transform progresses in source code.
Thanks for anyone responding for this question!

**Comment by zytx121** [comment]
@Shmily-YH Thanks for your question!

During the testing phase, All models in this work output the result (x, y, w, h, theta) according to their configs. There are 3 kinds of ``angle_version`` you can choose: oc, le90, le135. And you can find their definition at [here](https://mmrotate.readthedocs.io/en/latest/intro.html#definition-of-rotated-box).  MMRotate use the coder to encode/decode rotated box, which you can find different coder [here](https://github.com/open-mmlab/mmrotate/tree/main/mmrotate/core/bbox/coder).

**Comment by Shmily-YH** [comment]
thanks for your reply!
