### ISSUE TITLE
ModuleNotFoundError: No module named 'model_archiver'

### ISSUE THREAD

**Issue by zgsxwsdxg** [open-mmlab/mmrotate#454]
python tools/deployment/mmrotate2torchserve.py ${CONFIG_FILE} ${CHECKPOINT_FILE} \
        --output-folder ${MODEL_STORE} \
        --model-name ${MODEL_NAME}

报错了，什么原因？我已安装torch-model-archiver

**Comment by zytx121** [comment]
Please give us more error information.

**Comment by nijkah** [comment]
You can check the Dockerfile for requirements. 
https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/docker/serve/Dockerfile#L27
Currently, requirements for deployment are not specified in the requirement file.
