### ISSUE TITLE
an error ''assert 'mix_results' in results"

### ISSUE THREAD

**Issue by 1343744768** [open-mmlab/mmrotate#456]
When i tried to use rmosaic in train_pipeline, as show as in the figure below. The following error will appear: ''assert 'mix_results' in results". I found the location and reason of the error in the transform.py, but I don't know how to improve it.
![image](https://user-images.githubusercontent.com/79694861/183445154-287aeb3d-2a77-4378-b848-5766fe1cf621.png)

**Comment by liuyanyi** [comment]
For mosaic and mixup, the pipeline must use with `MultiImageMixDataset`.

Here's an example in https://github.com/open-mmlab/mmrotate/issues/401#issuecomment-1178869962 .
You can also check YOLOX config in mmdetection, the usage of `Mosaic` is similar to `RMosaic`
