### ISSUE TITLE
convex_iou

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#46]
def convex_iou(pointsets, polygons): 
pointsets (torch.Tensor): It has shape (N, 18), indicating (x1, y1, x2, y2, ..., x9, y9) for each row.

**Comment by zytx121** [comment]
Hi @houw0517 
```
def convex_iou(pointsets, polygons):
    """Return intersection-over-union (Jaccard index) between point sets and
    polygons.
    Args:
        pointsets (torch.Tensor): It has shape (N, 18),
            indicating (x1, y1, x2, y2, ..., x9, y9) for each row.
        polygons (torch.Tensor): It has shape (K, 8),
            indicating (x1, y1, x2, y2, x3, y3, x4, y4) for each row.
    Returns:
        torch.Tensor: Return the ious between point sets and polygons with the
        shape (N, K).
    """
    N, K = pointsets.size(0), polygons.size(0)
    ious = pointsets.new_zeros((N, K))
    ext_module.convex_iou(pointsets, polygons, ious)
    return ious
```
You could refer mmcv:
https://github.com/open-mmlab/mmcv/blob/594ff3c0d3132bcbeb25e06eafb7e23b44a03ae3/mmcv/ops/convex_iou.py#L29-L46

**Comment by houw0517** [comment]
what is the pointsets？why it has shape(N,18)？

**Comment by zytx121** [comment]
You could refer: https://github.com/open-mmlab/mmrotate/tree/main/configs/cfa

**Comment by yangxue0827** [comment]
因为写这个函数的[原文](https://github.com/open-mmlab/mmrotate/tree/main/configs/cfa)是基于reppoints，所以输入就是9个点。如果你想要四个点也用的话，你通过插值或者复制扩充到9个点，比如Rotated_Faster_RCNN是四个点，你可以随机复制这些点增加到9个。

**Comment by zytx121** [comment]
只有 reppoints 系列方法才能使用 ConvexGIoULoss 和 BCConvexGIoULoss。

**Comment by houw0517** [comment]
想请教一下  Rotated_Faster_RCNN或者 Rotated_RetinaNet  还可以用哪些Loss函数  ，除了SmoothL1 和Focal Loss
