### ISSUE TITLE
A question about R3Det

### ISSUE THREAD

**Issue by kuazhangxiaoai** [open-mmlab/mmrotate#462]
1. 在R3Det的Feature interpolation中，是插入神经元吗？还是利用目标中心点C（x, y）周围的四个神经元共同输出其对应的C的偏移量？

2. 在下图中，蓝色点才是神经元，其四个一组共同输出其黄色点对应偏移量，对吗？既然黄色点不是具体的神经元，那红色点的位置如何输出呢？这张图看上去是要预测目标中心点和四个角点，并不是（x，y，w，h，angle）。
![2022-08-14 22-07-32](https://user-images.githubusercontent.com/54108453/184540970-8959fe2e-7eb8-4430-a318-640de6a5f6db.png)

3.整个detector只在refined-stage后计算loss，对吗？

谢谢！

**Comment by zytx121** [comment]
- It has 5 sample points (center point and four corner points).
- MMRotate uses the coder to encode/decode rotated box(x, y, w, h, angle), which you can find different coder [here](https://github.com/open-mmlab/mmrotate/tree/main/mmrotate/core/bbox/coder).
- r3det compute loss at every stage, not only at the refined stage.

**Comment by Acid-knight** [comment]
1.兄弟你这基础概念是不是有问题...，这是特征图上几种bounding box之间的示意图，为什么会牵扯到神经元...

**Comment by Acid-knight** [comment]
1.兄弟你这基础概念是不是有问题...，这是特征图上几种bounding box之间的示意图，为什么会牵扯到神经元...

**Comment by kuazhangxiaoai** [comment]
> * It has 5 sample points (center point and four corner points).
> * Rotated box(x, y, w, h, angle) will be converted to polygons at CUDA ops, which you can find [here](https://github.com/open-mmlab/mmcv/blob/595c2ebeb93c873ab2fc4af67a5b81640b7bc314/mmcv/ops/csrc/common/cuda/rotated_feature_align_cuda_kernel.cuh#L94).
> * r3det compute loss at every stage, not only at the refined stage.

For the 3rd answer, I'm confused about the way of loss backward whether loss of each stages back propagates respectively or summary of these losses back propagates to our detector.

**Comment by kuazhangxiaoai** [comment]
> * 1.兄弟你这基础概念是不是有问题...，这是特征图上几种bounding box之间的示意图，为什么会牵扯到神经元...
> * 2.这个绿色框点和红色框点的关系我倒是有疑惑：在论文的Figure4.(b)中展示了由于bounding box位置改变导致特征不对齐的问题，在下方有对其的说明“2”：“红点和绿点应该完全重叠在一起，而这里的红点被有意地抵消了，以区分地可视化整个过程。”这里图中的红点为GT（R），而绿色点为Anchor box，为什么它们应该“完全重叠在一起”呢？

1.牵扯到神经元，是因为实际模型输出的是点对于其对应神经元的偏移量。
2.没看明白，但我觉得绿色框和红色框不应该在重合

**Comment by zytx121** [comment]
Yes, we added up these losses.
