### ISSUE TITLE
R3Det result on DOTA1.0 error

### ISSUE THREAD

**Issue by Acid-knight** [open-mmlab/mmrotate#465]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**

I install mmrotate and use official DOTA1.0 dataset, only adjust "dataroot", "configs" to use R3Det to train, but the mAP on val appears just 63.62, I really don't know where the problem is!!!Please HELP!!! Here is the information:
2022-08-16 03:40:43,601 - mmrotate - INFO - Exp name: r3det_r50_fpn_1x_dota_oc.py
2022-08-16 03:40:43,601 - mmrotate - INFO - Epoch(val) [12][3066]	mAP: 0.6362

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-16GB
CUDA_HOME: /project/luojunwei/CUDA/10.0:
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMRotate: 0.3.2+unknown

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Acid-knight** [comment]
I just adjust "--config"  and "--work-dir" in train.py and "data_root" in dotav1.py, and split DOTA dataset to 1024*1024,like this
![image](https://user-images.githubusercontent.com/72430633/184785714-b61e5387-77b8-4959-9c75-55bd18f43aac.png)
,I really don't know what's problem result on offline mAP so low

**Comment by zytx121** [comment]
Do you only use the train-set to train? Normally, we use the trainval-set to train.

**Comment by Acid-knight** [comment]
> Do you only use the train-set to train r3det? Normally, we use the trainval-set to train the model and test on the test-set online.
> 
> We don't provide mAP which trains on train-set and test on val-set.

Yes, I divide train-set and val-set so I get offline mAP result of val set... I use official checkpoint downloaded in Github to get offline mAP(reach 75.8) and compare with my own mAP result(in val-set), because I can only submit 2 times of DOTA online evaluation ... Thank you for your reply, I will try it.

**Comment by jimuIee** [comment]
how many trainval data pictures in ur experiment? i have used the tool/data/dota/split/img_split.py to split the dataset, but i only get 12716 pictures, and i have found the official log the trainval data is 12800. i dont know why caused the problem
