### ISSUE TITLE
Mmrotate has poor detection effect for large targets

### ISSUE THREAD

**Issue by qiuchun** [open-mmlab/mmrotate#466]
When using my dataset for mmdetection and mmrotate training, when detecting large targets, mmdetection has a better detection effect and mmrotate has a worse detection effect. What is the reason？

Detection effect of mmdetection：
![image](https://user-images.githubusercontent.com/65998432/184787333-02636fa3-3c4a-4263-bd30-b5e11f9ba857.png)

Detection effect of mmrotate：
![image](https://user-images.githubusercontent.com/65998432/184790069-b7c14090-ca25-4533-9758-831948d7c4d6.png)

Is it because the images are segmented and merged in mmrotate, resulting in poor effect in large targets？

**Comment by zytx121** [comment]
The current parameters are set for remote sensing images, such as `nms_pre = 2000`, you need to adjust these parameters according to the configuration in mmdetection.
