### ISSUE TITLE
How to achieve each object only keep the results with the maximum confidence when use Image_demo.py?

### ISSUE THREAD

**Issue by zhangchi621** [open-mmlab/mmrotate#473]
How to achieve each object only keep the results with the maximum confidence when use Image_demo.py?

**Comment by zytx121** [comment]
https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/core/patch/merge_results.py#L102

The first item of  `dets_per_cls`  is what you need.
