### ISSUE TITLE
Urgent! Can mmrotate work with Python 3.6?

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#476]
I have an urgent project to deploy mmrotate on the docker of the edge side device. However, the docker of the edge side only supports Python 3.6.9. Therefore, I encountered a version restriction error when installing mmrotate. It requires that the minimum version is 3.7. Can I use some methods to remove this restriction so that I can install mmrotate through Python 3.6! Very urgent, thank you!

**Comment by zytx121** [comment]
The restriction  is introduced by e2cnn, and you can try to use https://github.com/QUVA-Lab/e2cnn/tree/legacy_py3.6

**Comment by hh123445** [comment]
> 限制是e2cnn引入的，可以尝试使用https://github.com/QUVA-Lab/e2cnn/tree/legacy_py3.6
Thank you for your answer！How can I successfully pass the version restriction when using the following command when installing mmrotate.
For example, modify a line of code in a file

![image](https://user-images.githubusercontent.com/90760124/186109415-f5e0aa71-9d8c-4ad5-9ee0-6a981df19989.png)

**Comment by zytx121** [comment]
Could you provide the error log?

**Comment by hh123445** [comment]
> Could you provide the error log?

I resolve this problem by install e2cnn through https://github.com/QUVA-Lab/e2cnn/tree/legacy_py3.6.
Next, open the requirements file in mmrotate, find the requirements related to e2cnn in the txt file mentioned in the requirements file, delete it, and compile through mmrotate with Python 3.6
![Uploading 11.png…]()

Thanks for your help!
