### ISSUE TITLE
After ROI Transformer replaces the backbone, the training accuracy is 0

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#477]

**Comment by zytx121** [comment]
Please give us more information.

**Comment by luoz66** [comment]
> Please give us more information.

我使用mmrotate中的roi Transformer跑模型，可以得到正常结果。我将backbone从resnet50换成MViTv2（CVPR2022）之后重新跑这个模型，得到的结果为0

**Comment by zytx121** [comment]
Have you modified the number of neck channels in the config?

**Comment by luoz66** [comment]
> Have you modified the number of neck channels in the config? BTW, you can try to use the AdamW optimizer just like Swin:
> 
> https://github.com/open-mmlab/mmrotate/blob/575a7577804441b556370d5450828f9b212d34ff/configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py#L33-L44

是的，我根据backbone的输出通道数修改了相应的neck部分的输入通道数，我使用AdamW试试，非常感谢

**Comment by luoz66** [comment]
> Have you modified the number of neck channels in the config? BTW, you can try to use the AdamW optimizer just like Swin:
> 
> https://github.com/open-mmlab/mmrotate/blob/575a7577804441b556370d5450828f9b212d34ff/configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py#L33-L44

![image](https://user-images.githubusercontent.com/86155472/188315751-84d7ea5a-27d2-4c59-b7c6-bba79f4b13fb.png)
