### ISSUE TITLE
reimplement an NMS

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmrotate#479]
I want to reimplement an NMS, how should I do it in mmrotate?

**Comment by nijkah** [comment]
You can check here. https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/core/post_processing/bbox_nms_rotated.py

**Comment by 19990101lrk** [comment]
> 您可以在此处查看。https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/core/post_processing/bbox_nms_rotated.py

Its core is still using from mmcv.ops import nms_rotated, I want to implement my own NMS

**Comment by zytx121** [comment]
What kind of NMS do you want to implement? The current NMS is implemented in C language to ensure speed. You can refer to the code in mmcv.

**Comment by 19990101lrk** [comment]
> 

I want to implement Rotated Adaptive NMS

**Comment by 19990101lrk** [comment]
> What kind of NMS do you want to implement? The current NMS is implemented in C language to ensure speed. You can refer to the code in mmcv.

I want to implement Rotated Adaptive NMS.

**Comment by zytx121** [comment]
Of course, you can implement it in mmcv.

**Comment by 19990101lrk** [comment]
> 你可以在这里查看。https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/core/post_processing/bbox_nms_rotated.py

After referring to your implementation of NMS, it shows not found when used in the configuration file

**Comment by 19990101lrk** [comment]
> Of course, you can implement it in mmcv. Could you give us a link to Rotated Adaptive NMS? Maybe we can help you.

NMS implemented under mmrotate.core.post_processing, shows not found when used in config file
