### ISSUE TITLE
Supported version does not match!

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmrotate#480]
**Motivation**
Currently, the below line imports `chamfer_distance` which is added after `mmcv>=1.5.3`.
https://github.com/open-mmlab/mmrotate/blob/d1d273b185b5906d1ca01c017b3d7b4e6a28e9fe/mmrotate/models/dense_heads/oriented_reppoints_head.py#L8

But current mmcv version requirement is set to 1.4.5. https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/__init__.py#L23

**Describe the feature**
Is it better to 'try and except' when import `chamfer_distance`?
or increase the minimum mmcv version to 1.5.3?

**Comment by zytx121** [comment]
Thanks for your suggestion! We have fixed this mismatch in the dev branch.
https://github.com/open-mmlab/mmrotate/blob/575a7577804441b556370d5450828f9b212d34ff/mmrotate/__init__.py#L23

**Comment by nijkah** [comment]
@zytx121 Thanks. I should check the `dev` branch next time. I found that it happens in the main branch.
