### ISSUE TITLE
Wrong names of two Redet models

### ISSUE THREAD

**Issue by RangeKing** [open-mmlab/mmrotate#486]
The model name of [redet_re50_refpn_1x_dota_le90.py](https://github.com/open-mmlab/mmrotate/blob/main/configs/redet/redet_re50_refpn_1x_dota_le90.py) is `redet_re50_fpn_1x_dota_le90-724ab2da.pth` missing `re` before `fpn`.
The same error in `redet_re50_fpn_1x_dota_ms_rr_le90-fc9217b5.pth`.

**Comment by zytx121** [comment]
Thanks, we will rename it in dev-1.x.
