### ISSUE TITLE
Why is the horizontal anchor generated in FasterRCNN, and the NMS is also horizontal? Thanks for answer.

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmrotate#489]
Why is the horizontal anchor generated in FasterRCNN, and the NMS is also horizontal? Thanks for answer.

**Comment by zytx121** [comment]
In the RPN stage of Rotated Faster RCNN, we use hbb anchor and hbb GT to learn the hbb proposals. In the RCNN stage, we use hbb proposals and rbb gt to learn the rbb prediction.

**Comment by 19990101lrk** [comment]
> In the RPN stage of Rotated Faster RCNN, we use hbb anchor and hbb GT to learn the hbb proposals. In the RCNN stage, we use hbb proposals and rbb gt to learn the rbb prediction.

After rbb prediction, the prediction box is rotated, why is the NMS still horizontal?

**Comment by zytx121** [comment]
In the RCNN stage, we use the rotated NMS not horizontal NMS.

**Comment by 19990101lrk** [comment]
test_cfg=dict(
rpn=dict(
nms_pre=2000,
max_per_img=2000,
nms=dict(type='nms', iou_threshold=0.7),
min_bbox_size=0),
rcnn=dict(
nms_pre=2000,
min_bbox_size=0,
score_thr=0.05,
nms=dict(iou_thr=0.1),
max_per_img=2000))) The nms in rcnn does not write a type. Is rotation used
by default?

Yue Zhou ***@***.***> 于2022年10月8日周六 08:55写道：

**Comment by zytx121** [comment]
Yes, rotated NMS is used by default
