### ISSUE TITLE
Training of FCOS+CSL seems to be unstable

### ISSUE THREAD

**Issue by yuyi1005** [open-mmlab/mmrotate#490]
Hey guys, thanks for this great project. I tried to train FCOS+CSL with this config file: rotated_fcos_csl_gaussian_r50_fpn_1x_dota_le90.py
And I found some strange phenomenon, as follows:

1. There is a chance that the loss_bbox is stuck at 1.0000 (from the beginning). I tried for 10 times, and this situation occurred 3 times. The logs are as follows:

Case 1:

- 2022-09-02 00:44:56,503 - mmrotate - INFO - Epoch [1][50/3200]  lr: 9.967e-04, eta: 7:25:03, time: 0.696, data_time: 0.262, memory: 6252, loss_cls: 0.9569, loss_bbox: 1.0003, loss_angle: 0.6602, loss_centerness: 0.7168, loss: 3.3342, grad_norm: 18.8347
- 2022-09-02 00:45:14,520 - mmrotate - INFO - Epoch [1][100/3200] lr: 1.163e-03, eta: 5:37:14, time: 0.360, data_time: 0.005, memory: 6562, loss_cls: 0.8084, loss_bbox: 1.0000, loss_angle: 0.2231, loss_centerness: 0.7089, loss: 2.7404, grad_norm: 9.3274

Case 2:

- 2022-09-02 00:54:20,809 - mmrotate - INFO - Epoch [1][50/3200]  lr: 9.967e-04, eta: 8:10:57, time: 0.768, data_time: 0.265, memory: 6262, loss_cls: 0.9850, loss_bbox: 1.0001, loss_angle: 0.6632, loss_centerness: 0.7243, loss: 3.3727, grad_norm: 22.8253
- 2022-09-02 00:54:40,581 - mmrotate - INFO - Epoch [1][100/3200] lr: 1.163e-03, eta: 6:11:21, time: 0.395, data_time: 0.007, memory: 6318, loss_cls: 0.8885, loss_bbox: 1.0000, loss_angle: 0.2193, loss_centerness: 0.6985, loss: 2.8062, grad_norm: 9.0997
- 2022-09-02 00:54:58,593 - mmrotate - INFO - Epoch [1][150/3200] lr: 1.330e-03, eta: 5:23:47, time: 0.360, data_time: 0.005, memory: 6318, loss_cls: 0.8684, loss_bbox: 1.0000, loss_angle: 0.2182, loss_centerness: 0.6967, loss: 2.7833, grad_norm: 7.9295

Case 3:

- 2022-09-02 01:05:04,687 - mmrotate - INFO - Epoch [1][50/6400]  lr: 9.967e-04, eta: 10:13:28, time: 0.480, data_time: 0.146, memory: 3570, loss_cls: 1.0720, loss_bbox: 1.0001, loss_angle: 0.6578, loss_centerness: 0.8049, loss: 3.5347, grad_norm: 20.8511
- 2022-09-02 01:05:15,766 - mmrotate - INFO - Epoch [1][100/6400] lr: 1.163e-03, eta: 7:28:09, time: 0.222, data_time: 0.003, memory: 3721, loss_cls: 1.0773, loss_bbox: 1.0000, loss_angle: 0.2298, loss_centerness: 0.7016, loss: 3.0087, grad_norm: 14.1250
- 2022-09-02 01:05:26,846 - mmrotate - INFO - Epoch [1][150/6400] lr: 1.330e-03, eta: 6:32:56, time: 0.222, data_time: 0.003, memory: 3721, loss_cls: 1.1154, loss_bbox: 1.0000, loss_angle: 0.2140, loss_centerness: 0.7022, loss: 3.0316, grad_norm: 9.4091

Afterwards, the loss_bbox is always 1.0000, and if I complete the training, the final mAP is 0.0.

2. Among those successful training, the final accuracy varies. I complete the training twice. In the first one, the mAP is 2.5 lower than that listed on the FCOS instruction page, and in the second one, 0.9 lower.

Looking forward to receiving any information, thanks!

**Comment by zytx121** [comment]
We trained this model on one GPU since we can't guarantee the effect on 2 GPUs. Unfortunately, the rotated FCOS is unstable, and failure is possible.

**Comment by liuyanyi** [comment]
It is normal for the loss to occasionally get stuck at 1.0 at the beginning. The Rotated FCOS model is unstable, i'll test the result and try to enhance the stability of the model.

I think the result won't varies too much, maybe #346 affect result a little.

**Comment by yuyi1005** [comment]
Thanks for your reply
