### ISSUE TITLE
How to use RMosaic?

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#491]
I'm trying to use RMosaic,but I have a problem. 

![image](https://user-images.githubusercontent.com/90760124/188044075-18ad8aab-3837-4fc4-aece-7ea718c5b4c8.png)

![image](https://user-images.githubusercontent.com/90760124/188044036-79963fe4-18d1-4416-97ea-057e0b956e3d.png)

assert 'mix_results' in results

I checked the instructions for the use of mosaic in mmdetection. It is mentioned that mosaic needs to be used with multiimagemixdataset. However, I am not sure how to add this setting in the configuration file in mmrotate, or is there any other solution?And can polyrandomrotate be used with Rmosaic?

**Comment by zytx121** [comment]
For mosaic and mixup, the pipeline must use with MultiImageMixDataset.

Here's an example in https://github.com/open-mmlab/mmrotate/issues/401#issuecomment-1178869962 .
You can also check YOLOX config in mmdetection, the usage of Mosaic is similar to RMosaic

**Comment by young169** [comment]
> For mosaic and mixup, the pipeline must use with MultiImageMixDataset.
> 
> Here's an example in [#401 (comment)](https://github.com/open-mmlab/mmrotate/issues/401#issuecomment-1178869962) . You can also check YOLOX config in mmdetection, the usage of Mosaic is similar to RMosaic

I still get the assertion error after wrapping the dataset with 'MultiImageMixDataset', can you give me some advice?

my config file is here:
[dota_bk.txt](https://github.com/open-mmlab/mmrotate/files/11973830/dota_bk.txt)
