### ISSUE TITLE
Question about boundary loss

### ISSUE THREAD

**Issue by Acid-knight** [open-mmlab/mmrotate#492]
大佬们，我有个问题：旋转框在回归时的角度会出现临界偏差，那这个问题是否可以在将5参数格式（cx,cy,w,h,theta）转化为DOTA4点格式时通过改变不同角度范围下第一个点(x1,y1)的位置来解决嘞？
I have a question: the angle of the rotated bounding box at regression will have a critical deviation, so can this problem be solved by changing the position of the first point (x1,y1) at different angle ranges when converting the 5 parameter format (cx, cy, w, h, theta) to the DOTA 4 point format when I make annotations?

**Comment by yangxue0827** [comment]
应该可以，五参数转四点会用到放射变换，这个过程不受具体角度定义的影响。

**Comment by Acid-knight** [comment]
> 应该可以，五参数转四点会用到放射变换，这个过程不受具体角度定义的影响。

多谢大佬解答！我的这个想法其实是转化rolabelImg的格式到DOTA时产生的：
![image](https://user-images.githubusercontent.com/72430633/188126660-326ba0f0-c56e-4e77-9b9d-228113b8c8c2.png)
在rolabelImg定义下，上图中width和x轴夹角θ为0<θ<pi/2，这时我设“左上角”为第一点；
![image](https://user-images.githubusercontent.com/72430633/188127119-2be6dde1-8722-42b1-aed5-b89fa43d67fa.png)
而当角度超过pi/2时，如上图，我想着设“右上角”为第一点，这样即使在回归时θ发生振荡，x1y1-x4y4四个点的位置不会突变，可能会减少一些损失。

不过我又找到了DOTA第一点的详细定义：以最靠近“top left”的点为“best point”，将其作为第一点，如下图：
![image](https://user-images.githubusercontent.com/72430633/188127708-9fba909c-32e8-4e34-b52c-7e006c3e5c13.png)

这样我自己先前的那个想法应该就不成立了哈哈)
