### ISSUE TITLE
Any plans to produce vision transformer backbone?

### ISSUE THREAD

**Issue by chagmgang** [open-mmlab/mmrotate#493]
Any plans to product vision transformer backbone?
There's not repository for rotated object detection with vision transformer.

**Comment by yangxue0827** [comment]
swin transformer: https://github.com/open-mmlab/mmrotate/blob/main/configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py

In fact, most backbones supported by mmdet can be used on mmrotate, because mmrotate directly call the backbone of mmdet.

**Comment by chagmgang** [comment]
However, mmdet only provides swin transformer not vision transformer.
https://github.com/open-mmlab/mmdetection/tree/master/mmdet/models/backbones

**Comment by zytx121** [comment]
In mmrotate-1.x, we will supoort more vision transformer.
