### ISSUE TITLE
AttributeError: 'RoIAlignRotated' object has no attribute 'out_size'

### ISSUE THREAD

**Issue by sihuo521** [open-mmlab/mmrotate#50]
1. shell:
   python demo/image_demo.py \
        demo/demo.jpg \
        configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
        configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth \
        demo/vis.jpg

2. env:
cuda 10.2
torch 1.10.2
mmcv 1.4.6
mmcv-full 1.4.6
mmdet 2.22.0

3.bug:

AttributeError: 'RoIAlignRotated' object has no attribute 'out_size'

**Comment by yangxue0827** [comment]
solution refer to https://github.com/open-mmlab/mmrotate/pull/51

**Comment by yangxue0827** [comment]
If this solution solves your problem, please provide feedback so we can merge this PR as soon as possible. @sihuo521

**Comment by sihuo521** [comment]
> If this solution solves your problem, please provide feedback so we can merge this PR as soon as possible. @sihuo521

it works.
like this
`  out_size = self.roi_layers[0].output_size
        num_levels = len(feats)
        expand_dims = (-1, self.out_channels * out_size[0] * out_size[1])
        if torch.onnx.is_in_onnx_export():
            # Work around to export mask-rcnn to onnx
            roi_feats = rois[:, :1].clone().detach()
            roi_feats = roi_feats.expand(*expand_dims)
            roi_feats = roi_feats.reshape(-1, self.out_channels, out_size[0],
                                          out_size[1])
            roi_feats = roi_feats * 0
        else:
            roi_feats = feats[0].new_zeros(
                rois.size(0), self.out_channels, out_size[0], out_size[1])`

**Comment by sihuo521** [comment]
> If this solution solves your problem, please provide feedback so we can merge this PR as soon as possible. @sihuo521
it works!
![1646213396(1)](https://user-images.githubusercontent.com/36940636/156334149-6f66ff16-8e5a-49eb-bd7f-625b0a9ce009.png)

**Comment by DangChuong-DC** [comment]
Hi @sihuo521 ,
Seems like you fixed code in downstream `mmcv` repo, hence you should add `torch.nn.modules._pair()` function, like in the link below:
https://github.com/open-mmlab/mmcv/blob/4e77382034c6906881249b92f658569b4328d2e8/mmcv/ops/roi_align_rotated.py#L161

Or follow this temporary fix:
<img width="1214" alt="Screen Shot 2022-03-02 at 23 29 37" src="https://user-images.githubusercontent.com/40515271/156381238-688aaff4-93fd-4ea2-8bc7-bb411b432c91.png">

**Comment by zytx121** [comment]
Hi @sihuo521 
It is a bug that has been merged to the dev branch but still not merged to main branch https://github.com/open-mmlab/mmrotate/pull/51
You could pull code from the dev branch and try again.
