### ISSUE TITLE
Reimplemented NMS under mmrotate.core.post_processing but shows not found when used in config file

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmrotate#504]
Reimplemented NMS under mmrotate.core.post_processing but shows not found when used in config file

**Comment by zytx121** [comment]
You need to replace https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/models/dense_heads/rotated_anchor_head.py#L685
with your new NMS in box head.
