### ISSUE TITLE
If it is available to use mmdet's algorithms in mmrotate?

### ISSUE THREAD

**Issue by HamPerdredes** [open-mmlab/mmrotate#505]
I've checked some issues and know that mmrotate can directly import backbones from mmdet, what about methods implemented in mmdet ? For example, some detectors in mmdet.

**Comment by zytx121** [comment]
We will supoort this in mmrotate-1.x.

**Comment by HamPerdredes** [comment]
Is there a rough timeline about the releasing of 1.x version ?

**Comment by zytx121** [comment]
Probably in October.
