### ISSUE TITLE
使用inference_detector_by_patches对huge image进行推断，在推断结果中，一个目标有多个检测结果，检测结果框基本是重合的

### ISSUE THREAD

**Issue by JinqingZhengTju** [open-mmlab/mmrotate#506]
使用inference_detector_by_patches对huge image进行推断，在推断结果中，一个目标有多个检测结果，检测结果框基本是重合的。不知道什么原因？设置哪个参数可以解决这个问题呢？

**Comment by JinqingZhengTju** [comment]
ok

**Comment by zytx121** [comment]
Is the detect results of a single image normal? Maybe you can try to use a smaller `iou_thr` in nms config.
