### ISSUE TITLE
When using inference_detector_by_patches to infer a huge image, in the inference results, some objects obtain several different detection results which are almost overlapping.

### ISSUE THREAD

**Issue by JinqingZhengTju** [open-mmlab/mmrotate#507]
When using inference_detector_by_patches to infer a huge image, in the inference results, some objects obtain several different detection results which are almost overlapping. I don't know the reason. Is it possible to solve this problem by setting parameters?

**Comment by JinqingZhengTju** [comment]
> Is the detect results of a single image normal? Maybe you can try to use a smaller `iou_thr` in nms config.

Thanks for your advice. The `iou_thr` in nms config is relatively small, 0.1. I learned that mmrotate uses intra-class nms. I don't know why it doesn't use inter-class nms like mmdet.

**Comment by zytx121** [comment]
Thanks for your suggestion! We will align the nms with mmdet in mmrotate-1.x.
