### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by shanhuhaifeng** [open-mmlab/mmrotate#511]
1. when i run the demo.py, an error is appeared as 'RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)'.

2. the configuration of my computer is listed following:

OS:  Windows 10
GPU: RTX3080Ti
CUDA driver: 11.7
Pytorch : Preview (Nightly)

i have installed mmrotate using conda virtual environment with pytorch version is Preview provided by its official webset, namely  '1.13.0.dev20220914 py3.9_cuda11.7_cudnn8_0    pytorch-nightly'

3. conda list is :
Name                    Version                   Build  Channel
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.6.15        py39haa95532_0
cffi                      1.15.1           py39h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cryptography              37.0.1           py39h21b164f_0
cuda                      11.7.1                        0    nvidia
cuda-cccl                 11.7.91                       0    nvidia
cuda-command-line-tools   11.7.1                        0    nvidia
cuda-compiler             11.7.1                        0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cuobjdump            11.7.91                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-cuxxfilt             11.7.91                       0    nvidia
cuda-demo-suite           11.7.91                       0    nvidia
cuda-documentation        11.7.91                       0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-memcheck             11.7.91                       0    nvidia
cuda-nsight-compute       11.7.1                        0    nvidia
cuda-nvcc                 11.7.99                       0    nvidia
cuda-nvdisasm             11.7.91                       0    nvidia
cuda-nvml-dev             11.7.91                       0    nvidia
cuda-nvprof               11.7.101                      0    nvidia
cuda-nvprune              11.7.91                       0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-nvvp                 11.7.101                      0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-sanitizer-api        11.7.91                       0    nvidia
cuda-toolkit              11.7.1                        0    nvidia
cuda-tools                11.7.1                        0    nvidia
cuda-visual-tools         11.7.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
e2cnn                     0.2.2                    pypi_0    pypi
fonttools                 4.37.1                   pypi_0    pypi
freetype                  2.10.4               hd328e21_0
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
jpeg                      9e                   h2bbff1b_0
kiwisolver                1.4.4                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libcublas                 11.10.3.66                    0    nvidia
libcublas-dev             11.10.3.66                    0    nvidia
libcufft                  10.7.2.124                    0    nvidia
libcufft-dev              10.7.2.124                    0    nvidia
libcurand                 10.2.10.91                    0    nvidia
libcurand-dev             10.2.10.91                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusolver-dev           11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libcusparse-dev           11.7.4.91                     0    nvidia
libdeflate                1.8                  h2bbff1b_5
libnpp                    11.7.4.75                     0    nvidia
libnpp-dev                11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libnvjpeg-dev             11.8.0.2                      0    nvidia
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.4.0                h8a3f274_0
libuv                     1.40.0               he774522_0
libwebp                   1.2.2                h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
markdown                  3.4.1                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
mmcv-full                 1.5.3                    pypi_0    pypi
mmdet                     2.25.1                   pypi_0    pypi
mmrotate                  0.3.2                     dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
nsight-compute            2022.2.1.3                    0    nvidia
numpy                     1.23.1           py39h7a0a035_0
numpy-base                1.23.1           py39hca35cd5_0
opencv-python             4.6.0.66                 pypi_0    pypi
openmim                   0.3.1                    pypi_0    pypi
openssl                   1.1.1q               h2bbff1b_0
ordered-set               4.1.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.4                    pypi_0    pypi
pillow                    9.2.0            py39hdc2b20a_1
pip                       22.1.2           py39haa95532_0
pycocotools               2.0.4                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.13.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39haa95532_0
python                    3.9.13               h6244533_1
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.13.0.dev20220914 py3.9_cuda11.7_cudnn8_0    pytorch-nightly
pytorch-cuda              11.7                 h67b0de4_0    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
pytz                      2022.2.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
regex                     2022.9.13                pypi_0    pypi
requests                  2.28.1           py39haa95532_0
rich                      12.5.1                   pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
setuptools                63.4.1           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.39.2               h2bbff1b_0
sympy                     1.11.1                   pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
torchaudio                0.13.0.dev20220914          pypi_0    pypi
torchvision               0.14.0.dev20220914          pypi_0    pypi
typing_extensions         4.3.0            py39haa95532_0
tzdata                    2022c                h04d1e81_0
urllib3                   1.26.11          py39haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
xz                        5.2.5                h8cc25b3_1
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h8cc25b3_3
zstd                      1.5.2                h19a0ad4_0

4. Run code is : 
python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg

5. Error detail is :
C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:116: UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
  warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
load checkpoint from local path: oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmdet\models\dense_heads\anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
Traceback (most recent call last):
  File "C:\D_disk\mmrotate\demo\image_demo.py", line 45, in <module>
    main(args)
  File "C:\D_disk\mmrotate\demo\image_demo.py", line 32, in main
    result = inference_detector(model, args.img)
  File "C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmdet\apis\inference.py", line 151, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmcv\runner\fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmdet\models\detectors\base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmdet\models\detectors\base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "c:\d_disk\mmrotate\mmrotate\models\detectors\two_stage.py", line 183, in simple_test
    return self.roi_head.simple_test(
  File "c:\d_disk\mmrotate\mmrotate\models\roi_heads\rotate_standard_roi_head.py", line 252, in simple_test
    det_bboxes, det_labels = self.simple_test_bboxes(
  File "c:\d_disk\mmrotate\mmrotate\models\roi_heads\oriented_standard_roi_head.py", line 178, in simple_test_bboxes
    det_bbox, det_label = self.bbox_head.get_bboxes(
  File "C:\Users\XXX\anaconda3\envs\mmrotate\lib\site-packages\mmcv\runner\fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "c:\d_disk\mmrotate\mmrotate\models\roi_heads\bbox_heads\rotated_bbox_head.py", line 418, in get_bboxes
    det_bboxes, det_labels = multiclass_nms_rotated(
  File "c:\d_disk\mmrotate\mmrotate\core\post_processing\bbox_nms_rotated.py", line 58, in multiclass_nms_rotated
    bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

did anyone ever meet this problem? i am wating for someone who can give me solution or  help, thanks!

**Comment by zytx121** [comment]
The Oriented RCNN doesn't support running on the CPU environment now.

**Comment by shanhuhaifeng** [comment]
i have solved this problem by re-install a suitable pytorch and mmcv-full. please note that, if your pytorch version is 1.12.1 and your cuda is 11.6, then you must install a mmcv-full with XXX_cu116_pytorch1.12.0.

**Comment by CrazyBrick** [comment]
> 



> The Oriented RCNN doesn't support running on the CPU environment now. Please check if the CUDA is available and mmcv compiled successfully.



> i have solved this problem by re-install a suitable pytorch and mmcv-full. please note that, if your pytorch version is 1.12.1 and your cuda is 11.6, then you must install a mmcv-full with XXX_cu116_pytorch1.12.0.

plz tell more about it, do you mean change the version of pytorch, or just download the file you mentioned when installing mmcv-full?
paste your code and solution may be better.
thanks in advance.

**Comment by zytx121** [comment]
Hi @CrazyBrick, maybe you need to check wheather installed the mmcv corresponding to CUDA version. And you can get the install command [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-mmcv).

<img width="894" alt="image" src="https://user-images.githubusercontent.com/10410257/201502135-2c6ed1ea-a702-4df6-aae4-6f5a4640d0fa.png">

**Comment by hahakid** [comment]
> > Luckily I haved find such solution before.
> > OS: ubuntu18.04
> > GPU: RTX3080
> > CUDA driver: 11.6
> > Pytorch : 1.13.0
> 
> I encountered the same problem, and I have tired to reinstall mmcv-full == 1.7.0 @zytx121 , not solved: The followings are my states: 1. python -c 'import torch;print(torch.**version**);print(torch.version.cuda)' 1.13.0 11.6
> 
> 
> pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13/index.html
> 
> 3. re-run
> 4. problem still exists. program stopped, no result image generated.

Problem solved.
I refer the https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3958
and check all the variables in multiclass_nms_rotated()
 during test, two places will cause the above problem:
1)
    inds = valid_mask.nonzero(as_tuple=False).squeeze(1)
    inds = inds.to('cpu')   # <--added
    bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]
2)
    if max_num > 0:
        keep = keep[:max_num]

    keep = keep.to('cpu')  # <--added
    bboxes = bboxes[keep]
    scores = scores[keep]
    labels = labels[keep]

So, I think the 'labels' and its index should placed on different devices.
Place labels to CPU may also solve the problem.
But my laptop only have one AMD CPU and a 3080 GPU, Both labels and index one GPU will trigger the problem, it is strange.

**Comment by hahakid** [comment]
> > > Luckily I haved find such solution before.
> > > OS: ubuntu18.04
> > > GPU: RTX3080
> > > CUDA driver: 11.6
> > > Pytorch : 1.13.0
> > 
> > 
> > I encountered the same problem, and I have tired to reinstall mmcv-full == 1.7.0 @zytx121 , not solved: The followings are my states: 1. python -c 'import torch;print(torch.**version**);print(torch.version.cuda)' 1.13.0 11.6
> > pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13/index.html
> > 
> > 3. re-run
> > 4. problem still exists. program stopped, no result image generated.
> 
> Problem solved. I refer the [AUTOMATIC1111/stable-diffusion-webui#3958](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3958) and check all the variables in multiclass_nms_rotated() during test, two places will cause the above problem: 1)
> 
> ```
> inds = valid_mask.nonzero(as_tuple=False).squeeze(1)
> inds = inds.to('cpu')   # <--added
> bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds]
> ```
> 
> 
> ```
> if max_num > 0:
>     keep = keep[:max_num]
> 
> keep = keep.to('cpu')  # <--added
> bboxes = bboxes[keep]
> scores = scores[keep]
> labels = labels[keep]
> ```
> 
> So, I think the 'labels' and its index should placed on different devices. Place labels to CPU may also solve the problem. But my laptop only have one AMD CPU and a 3080 GPU, Both labels and index one GPU will trigger the problem, it is strange.

Sorry for miss-understanding.

Based on the debug mode, the _labels_ are stored in **Memory** instead of CUDA:0, the _indexes_ are stored in CUDA:0, so the above problem involved.

labels = torch.arange(num_classes, dtype=torch.long)

Add labels = labels.to('cuda:0') after the above, will lead to all calculations on GPU. 
I am not sure if it works on multi-GPU device.

**Comment by hamdimina** [comment]
> > Hi @CrazyBrick, maybe you need to check wheather installed the mmcv corresponding to CUDA version. And you can get the install command [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-mmcv).
> 
> thank u so much. Luckily I haved find such solution before.

wich solution do you find can you help me i face this problem also: 
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by songyuc** [comment]
I met a similar error on Win11.

**Comment by CrazyBrick** [comment]
> > > Hi @CrazyBrick, maybe you need to check wheather installed the mmcv corresponding to CUDA version. And you can get the install command [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-mmcv).
> > 
> > 
> > thank u so much. Luckily I haved find such solution before.
> 
> wich solution do you find can you help me i face this problem also: RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

hi, **@hamdimina** , it depends on the version of torch and cuda which you've installed.
For your reference only:
in my computer(Ubuntu 22.04), I created an environment with
python 3.8.13
pytorch 1.8.2
cudatoolkit 11.1
then, I choose to download mmcv-full according [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-mmcv)
`pip install mmcv-full==1.6.1 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8/index.html`

**Comment by 2505928188** [comment]
I have solved this problem by lower CUDA and mmcv version.
my versiuon is:
cuda : 11.6.0
pytorch: 1.12.1
mmcv-full: 1.6.2

**Comment by BambaSpoid** [comment]
> I have solved this problem by lower CUDA and mmcv version. my versiuon is: cuda : 11.6.0 pytorch: 1.12.1 mmcv-full: 1.6.2

@2505928188 Thank you for your specification. I just want to be precise that when I installed with pip, for the mmcv installation, the error persisted, but mim install (instead of pip) solved my issues.
1.
```
!pip install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.html
```
2.
```
!pip3 install -U openmim
!mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.ht
!mim install mmdet
!pip install mmengine
```
3. result
<img width="493" alt="Screenshot 2023-02-26 at 13 45 56" src="https://user-images.githubusercontent.com/61390595/221414290-8cba2e11-4599-4d77-97eb-06c28bee94da.png">

**Comment by sowmyakavali** [comment]
> I met the same error before.Anyway,Python 3.8, CUDA 11.3, cuDNN 8, NVCC, Pytorch 1.11.0, torchvision 0.12.0, torchaudio 0.11.0 .Everything goes well.

This worked for me
