### ISSUE TITLE
The performance of rotated_reppoints_r50_fpn_1x_dota_oc model.

### ISSUE THREAD

**Issue by najingligong1111** [open-mmlab/mmrotate#513]
In the paper  "Oriented RepPoints for Aerial Object Detection Results on DOTA" , we report full experimental results
of single scale to make a fair comparison with the previous methods on DOTA dataset. With ResNet-50-FPN
and ResNet-101-FPN as the backbones, our method obtains 75.97% and 76.52% mAP, respectively.   The result of "rotated_reppoints_r50_fpn_1x_dota_oc " model  is 59.44 , why there is such a big gap?

**Comment by zytx121** [comment]
It becasue we don't use the same data augmentation with that paper, and use fewer training epochs. The current settings are to align with other models.
