### ISSUE TITLE
it was killed at some point when I was running the program，

### ISSUE THREAD

**Issue by ZehaoZhang-Uestc** [open-mmlab/mmrotate#521]
![1](https://user-images.githubusercontent.com/59605393/191752952-ad26bcea-fd12-438d-bac3-b5634f33af13.jpg)
I use command: python tools/train.py  configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_le90.py
Is it out of memory?

**Comment by zytx121** [comment]
It looks don't like out of memory. Maybe you can try 
```
./tools/dist_train.sh configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_le90.py 1
```
