### ISSUE TITLE
KFIoU make the feature be 'nan'

### ISSUE THREAD

**Issue by volcanolee4** [open-mmlab/mmrotate#541]
Hi！Thanks for your great work ! 
      My detector outputs bboxes' relative coordinate, which are relative to the whole image, so the range of bboxes' xywh is [0,1].
      I use the kfiou to replace L1 box loss and rotated iou loss, however, after two iterations (batchsize=2, lr = 1e-5) , the feature of backbone be 'Nan'. 
      I tried to convert the relative coordinate to the global coordinate by multiplying the image size.(global coordinate's range is [0,1024]), it didn't work.
      And I notice that it is because of the kfiou part of the kfiou loss , this error has no connection with the Smooth L1 loss of (x_c,yc) between GT and bboxes_pred.
      Looking forward to your reply!

**Comment by zytx121** [comment]
The inputs of KFIoU and L1 loss have a little difference.
The inputs of KFIoU loss are encoded boxes and decoded boxes.
The inputs of L1 loss are encoded boxes normally.

**Comment by volcanolee4** [comment]
Thanks for your reply!
      But I've noticed the difference you mentioned, and the inputs of my KFIoU loss are already the decoded boxes (x,y,w,h,a：center points and width&height | xywh = [0,1]).
      It is clearly that the total bbox loss （i.e KFLoss）is composed of the Smooth L1 loss of center points and a KFIoU loss:
                    KFLoss = Smooth L1((x_c,y_c),(x_c*,y_c*)) + (1-KFIoU).

      I've verified that the error has no connection with the Smooth L1 loss. If I only return the Smooth L1 loss，the error wouldn't occur. But if I add the KFIoU part, the error occured.

**Comment by volcanolee4** [comment]
I found this error can be fixed by change the code:
               Vb = 4 * Sigma.det().sqrt() ------>   -7b = 4*Sigma.det.clamp(1e7-).sqrt()

Maybe it is a same problm with this issue:
[BUG] Gaussian distance/divergence losses grad nan issue #205

 But I don't know why the area of intersection region can be negative:

**Comment by zytx121** [comment]
Thank you, we will fix this bug.
