### ISSUE TITLE
ImportError: cannot import name 'chamfer_distance' from 'mmcv.ops' 

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#542]
我在运行mmrotate的安装命令时遇到了以下问题，请问该如何解决
选项（a）：如果从源代码安装 mmrotate，只需运行以下命令。

python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg

**Comment by milamiqi** [comment]
我用之前3月配好的环境运行新的0。3。2的包时也会遇到如下问题

**Comment by liuyanyi** [comment]
please update your mmcv version, the min version of mmcv is 1.5.3 and min mmdet version is 2.25.1

**Comment by milamiqi** [comment]
谢谢
