### ISSUE TITLE
backbone 预训练权重加载

### ISSUE THREAD

**Issue by zhu011** [open-mmlab/mmrotate#549]
如果对backbone网络改动了一些，在加载原来预训练权重时，指令还可以是这个init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'))吗？如果需要改动，需要在哪里去改

**Comment by zytx121** [comment]
Yes, you can continue to use ResNet50 as your pre-training model. Because you have made changes to the backbone, some of the original parameters will not match. Usually, changes to the backbone network require us to use ImageNet or COCO dataset to train a model from scratch.

**Comment by Petros626** [comment]
@zytx121 I plan to train my own model on LiDAR data encoded as BEV image. Is training from scratch supported and how?
