### ISSUE TITLE
roi trans 模型总共可以识别多少个类别

### ISSUE THREAD

**Issue by yuki0707-new** [open-mmlab/mmrotate#553]
roi trans 模型总共可以识别多少个类别

**Comment by yuki0707-new** [comment]
in total the model can identify how many categories

**Comment by zytx121** [comment]
This depends on the data set used for the training. The default configuration of roi trans is trained on DOTA-v1.0, so 15 categories can be recognized.

**Comment by yuki0707-new** [comment]
> This depends on the data set used for the training. The default configuration of roi trans is trained on DOTA-v1.0, so 15 categories can be recognized.

thank you !
I mean, is there a limit to the number of recognizable categories? If I have 2000 categories of data, can it work normally?

**Comment by yangxue0827** [comment]
Theoretically, yes. However, the more categories, the greater the challenge to classification.
