### ISSUE TITLE
Papers for Rotated Faster R-CNN and Retina

### ISSUE THREAD

**Issue by TekayaNidham** [open-mmlab/mmrotate#575]
Hi, I was wondering on which papers the implementations are based for Rotated Faster RCNN an Retina detectors, the cited papers in the README are the original HBB papers the rotation/oriented variant doesn't exist there

**Comment by zytx121** [comment]
Hi @TekayaNidham Sorry to confuse you. We will improve the relevant content in the document.
Rotated RetinaNet came from [R3Det](https://arxiv.org/abs/1908.05612)
Rotated Faster RCNN came from [RRPN](https://arxiv.org/abs/1703.01086)
