### ISSUE TITLE
[Docs] why some classes,such as bridge，basketball-court，soccer-ball-field，helicopter，etc ，ap are low？

### ISSUE THREAD

**Issue by hu-wei-carrzy** [open-mmlab/mmrotate#584]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

This is your evaluation result for task 1 (VOC metrics):

mAP: 0.5997811018158722
ap of each class: plane:0.8320957170124519, baseball-diamond:0.6304746338534358, bridge:0.39845609455146797, ground-track-field:0.48713448887904914, small-vehicle:0.7157309973452733, large-vehicle:0.7555292309034217, ship:0.7909190807815281, tennis-court:0.9058976235535318, basketball-court:0.5963214766849744, storage-tank:0.7144218687120667, soccer-ball-field:0.16871720969962004, roundabout:0.45803273311924425, harbor:0.6005402089015192, swimming-pool:0.6153494771737905, helicopter:0.3270956860667081

**Comment by zytx121** [comment]
In general, the smaller the number of training samples, the worse the effect is, especially for helicopters.

**Comment by hu-wei-carrzy** [comment]
> 一般来说，训练样本数越少，效果越差，尤其是直升机。

I use horizontal and vertical flipping.
 oriented_rcnn_r50_fpn_1x_dota_le90.py
workers_per_gpu=2

Nothing else has change

**Comment by hu-wei-carrzy** [comment]
![IF}QAXDL~@VBKN14)HQ_A23](https://user-images.githubusercontent.com/116777202/199146696-2f74ef25-5380-4625-ae13-ef22521f0f37.jpg)

![PSD YDUQ6FZNN4`%3I2HQ3F](https://user-images.githubusercontent.com/116777202/199146735-d0ae10ed-1b1a-45f5-9f1c-8350740c546f.jpg)
I use horizontal and vertical flipping.
![PI5P~6@(59GT4)}X`W8DO{R](https://user-images.githubusercontent.com/116777202/199146779-d8c76a75-f6a7-4d02-a092-627f65870891.jpg)
![TKAL0PH18VA}WTKB9%9HGI](https://user-images.githubusercontent.com/116777202/199146762-60784f9a-d4bb-4884-b49c-92e5ae3a641d.jpg)

**Comment by hu-wei-carrzy** [comment]
![PSD YDUQ6FZNN4`%3I2HQ3F](https://user-images.githubusercontent.com/116777202/199146974-d6dfcfbd-87f9-442f-bd59-3d6a523abd1b.jpg)

**Comment by hu-wei-carrzy** [comment]
oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth

**Comment by hu-wei-carrzy** [comment]
Can you give me some advice, please
