### ISSUE TITLE
预训练权重加载问题

### ISSUE THREAD

**Issue by zhu011** [open-mmlab/mmrotate#600]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

如果对主干网络进行修改后，载入初始训练的权重，在哪里添加类似（strict=False）指令使网络兼容权重，希望得到解答，谢谢作者大大

### Suggest a potential alternative/fix

如果对主干网络进行修改后，载入初始训练的权重，在哪里添加类似（strict=False）指令使网络兼容权重，希望得到解答，谢谢作者大大

**Comment by zytx121** [comment]
Hi @zhu011 
Sorry, there is a bug when initializing mismatched pre-trained weights. We will notify you after the repair.

**Comment by zhu011** [comment]
ok,thank you
