### ISSUE TITLE
issues about ssdd  val  

### ISSUE THREAD

**Issue by xiaxiangyu** [open-mmlab/mmrotate#610]
### What's the feature?

各位大佬好，请问一下如何取消代码中SSDD数据集中的验证集部分，只按照8；2的比例划分为训练集和测试集。或者验证集（offshore）可以是测试集（offshore＋inshore）的一部分嘛。

**Comment by yangxue0827** [comment]
Modify the data path according your  requirement.

https://github.com/open-mmlab/mmrotate/blob/bc1ced4cafdc8d62305958512b0195d822ff6c7f/configs/_base_/datasets/ssdd.py#L30-L47

**Comment by xiaxiangyu** [comment]
Thanks for your reply。  Can i use val and test in this way 。val：inshore test ：inshore and offshore
data = dict(
    train=dict(
        pipeline=train_pipeline,
        ann_file=data_root + 'train/labelTxt/',
        img_prefix=data_root + 'train/images/'),
    val=dict(
        ann_file=data_root + 'test/inshore/labelTxt/',
        img_prefix=data_root + 'test/inshore/images/'),
    test=dict(
        ann_file=data_root + 'test/all/labelTxt/',
        img_prefix=data_root + 'test/all/images/'))``

**Comment by yangxue0827** [comment]
yes, you can.

**Comment by xiaxiangyu** [comment]
Thanks for your patient answer 。Besides，I have some questions about [r3det_kfiou_ln_swin_tiny_adamw_fpn_2x_dota_ms_rr_oc.py]。Could you provide an experiment using this in SSDD . I want to  compare the config and results with my experiment .  I Would appreciate it if you could provide  a baseline .

**Comment by xiaxiangyu** [comment]
Here is my resuls. But in some essays about SSDD,their maps are far higher than mine.
{"config": "run_r3det_swin_kfiou_lpu_newd/r3det_kfiou_ln_swin_tiny_adamw_fpn_2x_dota_ms_rr_oc.py", "metric": {"mAP": 0.904013991355896}}
![屏幕截图 2022-11-11 163739](https://user-images.githubusercontent.com/104504570/201300257-ad534ca1-636c-419e-b92e-5aacc88b10a0.png)

**Comment by yangxue0827** [comment]
The default eval metric of mmrotate is 07, the results in your image is measured by 12.

**Comment by yangxue0827** [comment]
Set `use_07_metric=False` in the function `evaluation` at mmrotate/datasets/xxxx.py

**Comment by xiaxiangyu** [comment]
Does mmrotate support coco eval metric .

**Comment by yangxue0827** [comment]
MMRotate dev-1.x branch have supported it.

**Comment by xiaxiangyu** [comment]
Thanks for your help ，the question has been done！
