### ISSUE TITLE
[Bug] AssertionError: Box type qbox hasn't been registered in box_types.

### ISSUE THREAD

**Issue by VersifierL** [open-mmlab/mmrotate#612]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: win32
Python: 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1650
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30037 版
GCC: n/a
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.6.0
MMEngine: 0.3.1
MMRotate: 1.0.0rc0+

### Reproduces the problem - code sample

oriented-reppoints-qbox_r50_fpn_1x_dota.py

### Reproduces the problem - command or script

This problem occurs when I train the model on the ssdd dataset, such as oriented-reppoints.

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 122, in <module>
    main()
  File "tools/train.py", line 118, in main
    runner.train()
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1658, in train
    model = self.train_loop.run()  # type: ignore
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 90, in run
    self.run_epoch()
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 105, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 789, in prepare_data
    return self.pipeline(data_info)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 58, in __call__
    data = t(data)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmdet\datasets\transforms\loading.py", line 390, in transform
    self._load_bboxes(results)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmdet\datasets\transforms\loading.py", line 271, in _load_bboxes
    _, box_type_cls = get_box_type(self.box_type)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmdet\structures\bbox\box_type.py", line 176, in get_box_type
    assert type_name in box_types, \
AssertionError: Box type qbox hasn't been registered in box_types.

### Additional information

When there are several config file training SSDD datasets, they all appear

**Comment by zytx121** [comment]
Please provide your modified config file for us. We will check it.

**Comment by VersifierL** [comment]
> Hi@VersifierLPlease provide your modified config file for us. We will check it.BTW,`DOTADataset`don't support SSDD datasets now, please tryhttps://github.com/open-mmlab/mmrotate/blob/1.x/configs/_base_/datasets/ssdd.pyand you can download ssdd with coco annotation at[here](https://github.com/open-mmlab/mmrotate/tree/1.x/tools/data/ssdd) .

Thanks for your teplay. In fact, I had used the ssdd.py and coco annotation which you point. My config file as follow
""""""I only adjust some channel in "oriented-reppoints-qbox_r50_fpn_1x_dota.py", because my computer performtion is poor.

_base_ = [
    '../_base_/datasets/ssdd.py', '../_base_/schedules/schedule_x1.py',
    '../_base_/default_runtime.py'
]
norm_cfg = dict(type='GN', num_groups=32, requires_grad=True)

model = dict(
    type='mmdet.RepPointsDetector',
    data_preprocessor=dict(
        type='mmdet.DetDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_size_divisor=32),
    backbone=dict(
        type='mmdet.ResNet',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet18')),
    neck=dict(
        type='mmdet.FPN',
        in_channels=[64, 128, 256, 512],
        out_channels=128,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5,
        norm_cfg=norm_cfg),
    bbox_head=dict(
        type='OrientedRepPointsHead',
        num_classes=1,
        in_channels=128,
        feat_channels=128,
        point_feat_channels=128,
        stacked_convs=3,
        num_points=9,
        gradient_mul=0.3,
        point_strides=[8, 16, 32, 64, 128],
        point_base_scale=2,
        norm_cfg=norm_cfg,
        loss_cls=dict(
            type='mmdet.FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox_init=dict(type='ConvexGIoULoss', loss_weight=0.375),
        loss_bbox_refine=dict(type='ConvexGIoULoss', loss_weight=1.0),
        loss_spatial_init=dict(type='SpatialBorderLoss', loss_weight=0.05),
        loss_spatial_refine=dict(type='SpatialBorderLoss', loss_weight=0.1),
        init_qua_weight=0.2,
        top_ratio=0.4),
    # training and testing settings
    train_cfg=dict(
        init=dict(
            assigner=dict(type='ConvexAssigner', scale=4, pos_num=1),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        refine=dict(
            assigner=dict(
                type='MaxConvexIoUAssigner',
                pos_iou_thr=0.1,
                neg_iou_thr=0.1,
                min_pos_iou=0,
                ignore_iof_thr=-1),
            allowed_border=-1,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms_rotated', iou_threshold=0.4),
        max_per_img=2000))
file_client_args = dict(backend='disk')
train_pipeline = [
    dict(
        type='mmdet.LoadImageFromFile',
        file_client_args={{_base_.file_client_args}}),
    dict(type='mmdet.LoadAnnotations', with_bbox=True, box_type='qbox'),
    dict(type='mmdet.Resize', scale=(640, 640), keep_ratio=True),
    dict(
        type='mmdet.RandomFlip',
        prob=0.75,
        direction=['horizontal', 'vertical', 'diagonal']),
    dict(type='mmdet.PackDetInputs')
]

train_dataloader = dict(dataset=dict(pipeline=train_pipeline))
