### ISSUE TITLE
[Feature] Can you concat when features are fused？

### ISSUE THREAD

**Issue by zhuixingfu121** [open-mmlab/mmrotate#623]
### What's the feature?

I would like to ask if the add mode is supported in feature fusion, does it support the concat mode? When I tried splicing using torch.cat, TypeError: expected Tensor as element 0 in argument 0, but got GeometricTensor.

**Comment by zytx121** [comment]
Hi @zhuixingfu121 Which model to you use? We need more information to help you.

**Comment by zhuixingfu121** [comment]
Now, the model I'm using is ReDet, and I want to try multiscale fusion. Under this framework, you can only add, not concat. How do you concat?

**Comment by zytx121** [comment]
You can refer https://github.com/QUVA-Lab/e2cnn/blob/1145b558b4fcbb1dc05f4d90d3cfc0df7c6335b3/e2cnn/nn/geometric_tensor.py#L660 and implement the `concat` function of GeometricTensor by yourself.
