### ISSUE TITLE
[Bug] is the "tools/test.py" `add_dump_metric` api should be changed to DumpResults

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmrotate#632]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

No change

### Reproduces the problem - code sample

- 

### Reproduces the problem - command or script

No change

### Reproduces the problem - error message

No change

### Additional information

mmdet.util seems didn't have the add_dump_metric api.
is it changed to `from mmengine.evaluator import DumpResults`?

https://github.com/open-mmlab/mmrotate/blob/dev-1.x/tools/test.py

**Comment by vansin** [comment]
I meet the same problem
```shell

(mmrotate) ➜  mmrotate git:(dev-1.x) ✗ python tools/test.py work_dirs/gliding-vertex-qbox_r50_fpn_1x_dota/gliding-vertex-qbox_r50_fpn_1x_dota.py work_dirs/gliding-vertex-qbox_r50_fpn_1x_dota/epoch_3.pth      
Traceback (most recent call last):
  File "tools/test.py", line 6, in <module>
    from mmdet.utils import add_dump_metric
ImportError: cannot import name 'add_dump_metric' from 'mmdet.utils' (/home/elaine/miniconda3/envs/mmrotate/lib/python3.8/site-packages/mmdet/utils/__init__.py)
```

**Comment by zytx121** [comment]
Hi @sanbuphy 
Thank you for your feedback, You can refer to #636 to fix it.
