### ISSUE TITLE
[Bug] ReDet: ReResNet: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by rkinas** [open-mmlab/mmrotate#638]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

I used demo notebook.
I changed only cfg file and checkpoint for ReDet.
When calling:

```python
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
```

error: ReDet: ReResNet: Expected all tensors to be on the same device appears

### Reproduces the problem - code sample

```python

DS_HOME = 'dataset/'

# Modify dataset type and path
cfg.dataset_type = 'TinyDataset'
cfg.data_root = DS_HOME

cfg.data.test.type = 'TinyDataset'
cfg.data.test.data_root = DS_HOME
cfg.data.test.ann_file = 'val'
cfg.data.test.img_prefix = 'images'

cfg.data.train.type = 'TinyDataset'
cfg.data.train.data_root = DS_HOME
cfg.data.train.ann_file = 'train'
cfg.data.train.img_prefix = 'images'

cfg.data.val.type = 'TinyDataset'
cfg.data.val.data_root = DS_HOME
cfg.data.val.ann_file = 'val'
cfg.data.val.img_prefix = 'images'
cfg.data.samples_per_gpu = 8
cfg.data.workers_per_gpu = 8

cfg.model.roi_head.bbox_head[0].num_classes = 1
cfg.model.roi_head.bbox_head[1].num_classes = 1

# We can still use the pre-trained Mask RCNN model though we do not need to
# use the mask branch
cfg.load_from = 'redet_re50_fpn_1x_dota_ms_rr_le90-fc9217b5.pth'

# Set up working dir to save files and logs.
cfg.work_dir = './redet_exp'

cfg.optimizer.lr = 0.004 

cfg.lr_config.warmup = None
cfg.runner.max_epochs = 5
cfg.log_config.interval = 100

# Change the evaluation metric since we use customized dataset.
cfg.evaluation.metric = 'mAP'
# We can set the evaluation interval to reduce the evaluation times
cfg.evaluation.interval = 1
# We can set the checkpoint saving interval to reduce the storage cost
cfg.checkpoint_config.interval = 1

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)
cfg.device='cuda'

# We can also use tensorboard to log the training process
cfg.log_config.hooks = [
    dict(type='TextLoggerHook'),
    dict(type='TensorboardLoggerHook')]

# We can initialize the logger for training and have a look
# at the final config used for training
print(f'Config:\n{cfg.pretty_text}')


# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True) 
```

### Reproduces the problem - command or script

Error from demo notebook.

### Reproduces the problem - error message

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_bmm)

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)

RuntimeError: ReResNet: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_bmm)

### Additional information

I uploaded ReResnet checkpoint to work_dirs/pretrain/

**Comment by zytx121** [comment]
Hi @rkinas Could you provide more enviroment information for us?

**Comment by gfreund123** [comment]
@rkinas Any luck since then?

**Comment by NilakshanKunananthaseelan** [comment]
I got the same error, my environmet


Package                       Version      Editable project location
----------------------------- ------------ ------------------------------------------------
absl-py                       1.4.0
addict                        2.4.0
asttokens                     2.2.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.11.2
cachetools                    5.3.0
certifi                       2022.12.7
charset-normalizer            3.1.0
click                         8.1.3
colorama                      0.4.6
contourpy                     1.0.7
cycler                        0.11.0
debugpy                       1.5.1
decorator                     5.1.1
e2cnn                         0.2.3
entrypoints                   0.4
executing                     1.2.0
filelock                      3.9.1
fonttools                     4.39.0
future                        0.18.3
gdown                         4.6.4
google-auth                   2.16.2
google-auth-oauthlib          0.4.6
grpcio                        1.51.3
huggingface-hub               0.13.2
idna                          3.4
importlib-metadata            6.0.0
importlib-resources           5.12.0
ipykernel                     6.15.0
ipython                       8.11.0
jedi                          0.18.2
jupyter-client                7.0.6
jupyter_core                  5.2.0
kiwisolver                    1.4.4
Markdown                      3.4.1
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
matplotlib                    3.4.2
matplotlib-inline             0.1.6
mdurl                         0.1.2
mmcv-full                     1.7.1
mmdet                         2.28.2
mmrotate                      0.3.4        /hxxxx/mmrotate
model-index                   0.1.11
mpmath                        1.3.0
nest-asyncio                  1.5.6
numpy                         1.24.2
oauthlib                      3.2.2
opencv-python                 4.7.0.72
openmim                       0.3.6
ordered-set                   4.1.0
packaging                     23.0
pandas                        1.5.3
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.0.1
platformdirs                  3.1.1
prettytable                   3.6.0
prompt-toolkit                3.0.38
protobuf                      4.22.1
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycocotools                   2.0.6
Pygments                      2.14.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2022.7.1
PyYAML                        6.0
pyzmq                         19.0.2
regex                         2022.10.31
requests                      2.28.2
requests-oauthlib             1.3.1
rich                          13.3.2
rsa                           4.9
scipy                         1.10.1
seaborn                       0.12.2
setuptools                    65.6.3
shapely                       2.0.1
six                           1.16.0
soupsieve                     2.4
stack-data                    0.6.2
sympy                         1.11.1
tabulate                      0.9.0
tensorboard                   2.12.0
tensorboard-data-server       0.7.0
tensorboard-plugin-wit        1.8.1
terminaltables                3.1.10
timm                          0.6.12
tokenizers                    0.13.2
torch                         1.13.1+cu116
torchaudio                    0.13.1+cu116
torchvision                   0.14.1+cu116
tornado                       6.1
tqdm                          4.65.0
traitlets                     5.9.0
transformers                  4.26.1
typing_extensions             4.5.0
urllib3                       1.26.15
wcwidth                       0.2.6
Werkzeug                      2.2.3
wheel                         0.38.4
yapf                          0.32.0
zipp                          3.15.0
