### ISSUE TITLE
[Docs] Is there a way to visualize the structure of the model?

### ISSUE THREAD

**Issue by zhou233-33** [open-mmlab/mmrotate#650]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

Is there a way to visualize the structure of the model? I did not find a way to convert the model to onnx as in mmdetection.

**Comment by zytx121** [comment]
You can convert the model to onnx by mmdeploy. Please refer to https://github.com/open-mmlab/mmdeploy/pull/1401.
