### ISSUE TITLE
请问您在使用Rotated_Fcos时，裁剪DOTA数据集用的是ms_trainval还是ss_trainval，里面具体的参数是怎么样的？谢谢您的工作！

### ISSUE THREAD

**Issue by zhangleigood** [open-mmlab/mmrotate#664]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

请问您在使用Rotated_Fcos时，裁剪DOTA数据集用的是ms_trainval还是ss_trainval，里面具体的参数是怎么样的？谢谢您的工作！

**Comment by zytx121** [comment]
Hi @zhangleigood We use ``ss_trainval`` by default. The specific parameters are consistent with the configuration files provided by us.
