### ISSUE TITLE
how to obtain the bounding box coordinates and class type of one single image? 

### ISSUE THREAD

**Issue by 137ck** [open-mmlab/mmrotate#666]
### What's the feature?

Hello, all!
I have finished the training of my model and want to detect one certain picture and obtained the bounding box coordinates and class type from the certain picture above.  I find that image_demo.py doesn't have the function of restore the coordinates of the bounding box and the also the class type. How should I do?

**Comment by curiosity2** [comment]
It seems that th author doesn't implement it, here is  my implementation.

![image](https://user-images.githubusercontent.com/11660784/208641720-4a9cff6e-71e8-42d1-8b29-77eea040fa3c.png)

**Comment by 137ck** [comment]
Thanks! It works
