### ISSUE TITLE
warnings when I run the demo

### ISSUE THREAD

**Issue by wyc259** [open-mmlab/mmrotate#67]
when I run the demo，two warnings appear
UserWarning: DeprecationWarning: `num_anchors` is deprecated, for consistency or also use `num_base_priors` instead
warnings.warn('DeprecationWarning: `num_anchors` is deprecated, '
UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
I hope to be helped

**Comment by zytx121** [comment]
Hi @wyc259 
You can just ignore these warnings. They do not affect the use of MMRotate.
