### ISSUE TITLE
可视化正样本anchor

### ISSUE THREAD

**Issue by shenhaibb** [open-mmlab/mmrotate#675]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

我选择anchor[pos_inds]的结果进行可视化，得到的图像如下
![myplot](https://user-images.githubusercontent.com/64736467/209925133-4535fb4a-b9da-480f-affe-33596a6612e3.png)
anchor都是水平形式存在，如果我想得到下面这种可视化的结果，应该怎么做呢
<img width="298" alt="image" src="https://user-images.githubusercontent.com/64736467/209925233-6d3e8ed8-8910-40cd-bb83-7a15e5f134bf.png">

还有另外我想再问一下，为什么可视化出来一个目标的anchor这么少，而下面那张图的anchor能显示出那么多
我使用的assigner是默认的MaxIoUAssigner

十分感谢大佬百忙之中回复我的疑惑！

**Comment by zytx121** [comment]
Hi @shenhaibb
MMRotate only support generate horizontal anchors for all anchor-based models.
