### ISSUE TITLE
'RoIAlignRotated' object has no attribute 'out_size'，官网好像也没有相关的文档

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#68]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yangxue0827** [comment]
It is a bug that has been merged to the dev branch but still not merged to main branch https://github.com/open-mmlab/mmrotate/pull/51

**Comment by luoz66** [comment]
> It is a bug that has been merged to the dev branch but still not merged to main branch #51

请问怎么解决这个问题呢
我拉取dev的代码也是这个问题

**Comment by luoz66** [comment]
> It is a bug that has been merged to the dev branch but still not merged to main branch #51

感谢大佬，这个问题已经解决

**Comment by ZXiaoheng** [comment]
> It is a bug that has been merged to the dev branch but still not merged to main branch #51
How to fix it?

**Comment by so-bright** [comment]
> > 这是一个已合并到 dev 分支但仍未合并到主分支的错误#51
> 
> 感谢大佬，这个问题已经解决了


> > It is a bug that has been merged to the dev branch but still not merged to main branch #51
> 
> 感谢大佬，这个问题已经解决
你好，你是怎么解决的，我修改了outsize>outputsize, 出现了新的问题expand_dims = (-1, self.out_channels * out_size * out_size)
TypeError: can't multiply sequence by non-int of type 'tuple'

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/158043637-c34b2384-7da2-4f34-ba99-92c3b7a5c90d.png)
@so-bright

**Comment by so-bright** [comment]
> ![image](https://user-images.githubusercontent.com/29257168/158043637-c34b2384-7da2-4f34-ba99-92c3b7a5c90d.png) @so-bright

感谢大佬！
