### ISSUE TITLE
How to visualization when I use rmosaic

### ISSUE THREAD

**Issue by QAQTATQAQTAT** [open-mmlab/mmrotate#686]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

![Environment](https://user-images.githubusercontent.com/37134602/210500868-91d7e93e-98b9-4b98-bd13-025ef129ee22.png)

### Reproduces the problem - code sample

![parameter](https://user-images.githubusercontent.com/37134602/210500924-badbb00f-7f2e-479a-9093-42a0238ab26a.png)
I also want to know why I use rmosaic，it make my task worse.

### Reproduces the problem - command or script

/bin/bash tools/dist_train.sh configs/s2anet/s2anet_r50_fpn_3x_dota_rmo_le90.py 4 --work-dir work_dir/s2anet_rmo

### Reproduces the problem - error message

![s2anet_note](https://user-images.githubusercontent.com/37134602/210501968-6e35a221-7a77-4614-88cf-a75cf16d037d.png)

**Comment by zytx121** [comment]
Hi @QAQTATQAQTAT, you can use `demo/image_demo.py` to visualization the output of rmosaic. You can refer https://github.com/open-mmlab/mmrotate/blob/dev-1.x/configs/rotated_rtmdet/rotated_rtmdet_tiny-300e-aug-hrsc.py. 
```
train_pipeline = [
    dict(
        type='mmdet.LoadImageFromFile',
        file_client_args={{_base_.file_client_args}}),
    dict(type='mmdet.LoadAnnotations', with_bbox=True, box_type='qbox'),
    dict(type='ConvertBoxType', box_type_mapping=dict(gt_bboxes='rbox')),
    dict(
        type='mmdet.CachedMosaic',
        img_scale=(800, 800),
        pad_val=114.0,
        max_cached_images=20,
        random_pop=False),
    dict(
        type='mmdet.RandomResize',
        resize_type='mmdet.Resize',
        scale=(1600, 1600),
        ratio_range=(0.5, 2.0),
        keep_ratio=True),
    dict(type='RandomRotate', prob=0.5, angle_range=180),
    dict(type='mmdet.RandomCrop', crop_size=(800, 800)),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        type='mmdet.RandomFlip',
        prob=0.75,
        direction=['horizontal', 'vertical', 'diagonal']),
    dict(type='mmdet.Pad', size=(800, 800), pad_val=dict(img=(114, 114, 114))),
    dict(
        type='mmdet.CachedMixUp',
        img_scale=(800, 800),
        ratio_range=(1.0, 1.0),
        max_cached_images=10,
        random_pop=False,
        pad_val=(114, 114, 114),
        prob=0.5),
    dict(type='mmdet.PackDetInputs')
]
```

**Comment by QAQTATQAQTAT** [comment]
Thanks！I try it and it worked！
