### ISSUE TITLE
[Bug] boxes dimension on SRSDD  and RSDD

### ISSUE THREAD

**Issue by Jiang-Yidi** [open-mmlab/mmrotate#687]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

totally follow the mmrotate document to install environment.

### Reproduces the problem - code sample

python tools/train.py ./configs/gwd/rotated-retinanet-hbox-oc_r50_fpn_gwd_1x_dota.py --work-dir ./work_dir/gwd_srsdd/

### Reproduces the problem - command or script

python tools/train.py ./configs/gwd/rotated-retinanet-hbox-oc_r50_fpn_gwd_1x_dota.py --work-dir ./work_dir/gwd_srsdd/

### Reproduces the problem - error message

![1672829390607](https://user-images.githubusercontent.com/85482606/210539305-675a43d7-a778-4419-b8c2-f137493adccf.png)

### Additional information

I use the SRSDD dataset mmrotate provided based on dev-1.x version, there will be an error.
AssertionError: The boxes dimension must >= 2 and the length of the last dimension must be 8, but got boxes with shape torch.Size([2, 4]).

**Comment by zytx121** [comment]
Please refer https://github.com/open-mmlab/mmrotate/blob/dev-1.x/configs/_base_/datasets/srsdd.py  
![image](https://user-images.githubusercontent.com/10410257/211714380-30b1056e-0156-4cf8-84e4-cccc7cfe007b.png)
