### ISSUE TITLE
about HRSID dataset

### ISSUE THREAD

**Issue by VersifierL** [open-mmlab/mmrotate#695]
### What's the feature?

hi，I read HRSID paper. It say that the number of images is 5604.
But I calculate the dataset that you offer. It lacks some images, the total images is 5578

**Comment by zytx121** [comment]
Please try to use mmrotate 1.x. You can directly train the HRSID dataset with coco style annotations in 1.x 
https://github.com/open-mmlab/mmrotate/blob/1.x/configs/_base_/datasets/hrsid.py
