### ISSUE TITLE
[Docs] 训练时显存溢出的问题。

### ISSUE THREAD

**Issue by 18735549442** [open-mmlab/mmrotate#696]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

在文档FAQ的GPU out of memory栏目中，找不到设置batch_size参数的方法。

### Suggest a potential alternative/fix

只能在apis/inference.py找到bs=1的参数，希望在FAQ中给出训练代码里设置batch_size参数的方法。

**Comment by 18735549442** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的邮件。我将尽快给您回复。

**Comment by 18735549442** [comment]
during training, i cant find change batch_size, but apis/inference.py can do it. i hope you can give the method about change batch_size. i cant find the method in any configs/datasets and schedules you presented and docment FAQs.

**Comment by yzbx** [comment]
> during training, i cant find change batch_size, but apis/inference.py can do it. i hope you can give the method about change batch_size. i cant find the method in any configs/datasets and schedules you presented and docment FAQs.

view your config file, change the dataloader config, for 1.x
```
train_dataloader = dict(batch_size=2,
                        num_workers=2,
                        persistent_workers=True,
                        sampler=dict(type='DefaultSampler', shuffle=True),
                        batch_sampler=None,
                        dataset=dict(type=dataset_type,
                                     metainfo=metainfo,
                                     data_root=data_root,
                                     ann_file='/out/ymir_dataset/ymir_train.json',
                                     data_prefix=dict(img='/in/assets'),
                                     filter_cfg=dict(filter_empty_gt=True),
                                     pipeline=train_pipeline))
```

for mmrotate 0.x 
```
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'trainval/annfiles/',
        img_prefix=data_root + 'trainval/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'test/images/',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))
```
