### ISSUE TITLE
visualization codes

### ISSUE THREAD

**Issue by heiyuxiaokai** [open-mmlab/mmrotate#70]
It seems miss
`labels = labels[inds]`
after
https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/mmrotate/core/visualization/image.py#L68

**Comment by zytx121** [comment]
Hi @heiyuxiaokai 
Thanks for catching this bug! 
PR is welcome!

**Comment by gillsin** [comment]
Tv info books tv written books amen .🙏🏻 all books have codes. 


So xeprxex thinking
