### ISSUE TITLE
[Bug] Cannot download RTMDet configs

### ISSUE THREAD

**Issue by pascalewalters** [open-mmlab/mmrotate#701]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070
CUDA_HOME: None
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.7.0
MMEngine: 0.4.0
MMRotate: 1.0.0rc0+5d0491c

### Reproduces the problem - code sample

```
mim download mmrotate --config rotated_rtmdet_l-100e-aug-dota --dest .
```

### Reproduces the problem - command or script

```
mim download mmrotate --config rotated_rtmdet_l-100e-aug-dota --dest .
```

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/home/pascale/miniconda3/envs/blah1/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/mim/commands/download.py", line 57, in cli
    download(package, configs, dest_root, check_certificate)
  File "/home/pascale/miniconda3/envs/blah1/lib/python3.8/site-packages/mim/commands/download.py", line 100, in download
    raise ValueError(
ValueError: Expected configs: dict_keys(['cfa-qbox_r50_fpn_1x_dota', 'cfa-qbox_r50_fpn_40e_dota', 'rotated-retinanet-rbox-le90_r50_fpn_csl-gaussian_amp-1x_dota', 'gliding-vertex-rbox_r50_fpn_1x_dota', 'rotated-retinanet-hbox-oc_r50_fpn_gwd_1x_dota', 'rotated-retinanet-hbox-le90_r50_fpn_kfiou_1x_dota', 'rotated-retinanet-hbox-oc_r50_fpn_kfiou_1x_dota', 'rotated-retinanet-hbox-le135_r50_fpn_kfiou_1x_dota', 'r3det-oc_r50_fpn_kfiou-ln_1x_dota', 'rotated-retinanet-hbox-oc_r50_fpn_kld_1x_dota', 'rotated-retinanet-hbox-oc_r50_fpn_kld-stable_1x_dota', 'rotated-retinanet-rbox-le90_r50_fpn_kld-stable_1x_dota', 'r3det-oc_r50_fpn_kld-stable_1x_dota', 'r3det-tiny-oc_r50_fpn_kld_1x_dota', 'rotated-retinanet-hbox-oc_r50_fpn_kld-stable_rr-6x_hrsc', 'rotated-retinanet-rbox-le90_r50_fpn_kld-stable_rr-6x_hrsc', 'rotated-retinanet-rbox-le90_r50_fpn_kld-stable_adamw-1x_dota', 'oriented-rcnn-le90_r50_fpn_amp-1x_dota', 'oriented-rcnn-le90_r50_fpn_1x_dota', 'r3det-oc_r50_fpn_1x_dota', 'r3det-tiny-oc_r50_fpn_1x_dota', 'redet-le90_re50_refpn_amp-1x_dota', 'redet-le90_re50_refpn_1x_dota', 'redet-le90_re50_refpn_rr-1x_dota-ms', 'redet-le90_re50_refpn_3x_hrsc', 'roi-trans-le90_r50_fpn_amp-1x_dota', 'roi-trans-le90_r50_fpn_1x_dota', 'roi-trans-le90_swin-tiny_fpn_1x_dota', 'roi-trans-le90_r50_fpn_1x_dota-ms', 'rotated_atss_hbb_r50_fpn_1x_dota_oc', 'rotated_atss_obb_r50_fpn_1x_dota_le90', 'rotated_atss_obb_r50_fpn_1x_dota_le135', 'rotated-faster-rcnn-le90_r50_fpn_1x_dota', 'rotated-fcos-hbox-le90_r50_fpn_1x_dota', 'rotated-fcos-le90_r50_fpn_1x_dota', 'rotated-fcos-hbox-le90_r50_fpn_csl-gaussian_1x_dota', 'rotated-fcos-le90_r50_fpn_kld_1x_dota', 'rotated-reppoints-qbox_r50_fpn_1x_dota', 'rotated-retinanet-hbox-oc_r50_fpn_1x_dota', 'rotated-retinanet-rbox-le90_r50_fpn_1x_dota', 'rotated-retinanet-rbox-le90_r50_fpn_amp-1x_dota', 'rotated-retinanet-rbox-le135_r50_fpn_1x_dota', 'rotated-retinanet-rbox-le90_r50_fpn_rr-1x_dota-ms', 'rotated-retinanet-hbox-oc_r50_fpn_rr-6x_hrsc', 'rotated-retinanet-rbox-le90_r50_fpn_rr-6x_hrsc', 's2anet-le135_r50_fpn_1x_dota', 's2anet-le135_r50_fpn_amp-1x_dota', 'sasm-reppoints-qbox_r50_fpn_1x_dota']), but got {'rotated_rtmdet_l-100e-aug-dota'}

### Additional information

I am able to download other config files, but I get this error for the RTMDet files

**Comment by liuyanyi** [comment]
That's a bug, you can manualy add this line in `model-index.yml`, mim will work fine

```
  - configs/rotated_rtmdet/metafile.yml
```
