### ISSUE TITLE
[Docs] How to submit with `dev-1.x`

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmrotate#706]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

For submission, `mmrotate==0.x` uses `tools/test.py` with `--format-only  --eval-options submission_dir=work_dirs/Task1_results`.
But in `mmrotate==1.x`, it seems not to have this kind of feature.

Is there any existing feature that is not explained in the documentation? or is it the feature to be supported?

**Comment by nijkah** [comment]
Answer by myself. 😂 
This is explained in below;
https://github.com/open-mmlab/mmrotate/blob/5d0491c826ad52b7490a7c1146fb65a7d78e2347/configs/_base_/datasets/dota.py#L69

**Comment by AllieLan** [comment]
Hello, I have found the code, but I still can't output the format results and the submission_dir.    Could you please share the code you run the test.py with me?  Thx a lot!

> Answer by myself. 😂 This is explained in below;
> 
> https://github.com/open-mmlab/mmrotate/blob/5d0491c826ad52b7490a7c1146fb65a7d78e2347/configs/_base_/datasets/dota.py#L69

**Comment by nijkah** [comment]
Hi @AllieLan , all you have to do is uncomment as below;
```python
# test_dataloader = val_dataloader

val_evaluator = dict(type='DOTAMetric', metric='mAP')
# test_evaluator = val_evaluator

# inference on test dataset and format the output results
# for submission. Note: the test set has no annotation.
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path='test/images/'),
        img_shape=(1024, 1024),
        test_mode=True,
        pipeline=test_pipeline))
test_evaluator = dict(
    type='DOTAMetric',
    format_only=True,
    merge_patches=True,
    outfile_prefix='./work_dirs/dota/Task1')
```

**Comment by AllieLan** [comment]
> Hi @AllieLan , all you have to do is uncomment as below;
> 
> ```python
> # test_dataloader = val_dataloader
> 
> val_evaluator = dict(type='DOTAMetric', metric='mAP')
> # test_evaluator = val_evaluator
> 
> # inference on test dataset and format the output results
> # for submission. Note: the test set has no annotation.
> test_dataloader = dict(
>     batch_size=1,
>     num_workers=2,
>     persistent_workers=True,
>     drop_last=False,
>     sampler=dict(type='DefaultSampler', shuffle=False),
>     dataset=dict(
>         type=dataset_type,
>         data_root=data_root,
>         data_prefix=dict(img_path='test/images/'),
>         img_shape=(1024, 1024),
>         test_mode=True,
>         pipeline=test_pipeline))
> test_evaluator = dict(
>     type='DOTAMetric',
>     format_only=True,
>     merge_patches=True,
>     outfile_prefix='./work_dirs/dota/Task1')
> ```

It works! So thankful.
