### ISSUE TITLE
[Docs] Which architectures support instance segmentation? Does RTMDet support both instance segmentation and rotated bboxes?

### ISSUE THREAD

**Issue by FabianSchuetze** [open-mmlab/mmrotate#708]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

Thanks for this wonderful repo! It is a pleasure to work with it. 

I am wondering if RTMDet supports instance segmentation predicted rotated bboxes? I presume it is possible, but it is not clear to me which flags to use in the config to enable this or whether I would have to adjust the code.  

In general, is there an example for a detector predicting rotated bounding boxes and instance segmentation? Reading the docs for [two stage detectors](https://mmrotate.readthedocs.io/en/latest/_modules/mmrotate/models/detectors/two_stage.html?highlight=segmentation) suggests that some archiectures support this, but also the #164 might suggest that it is not implemented yet.

**Comment by liuyanyi** [comment]
Currently, none of the model in MMRotate support both rbox and instance segmentation.

For two-stage model, currently `BaseInstanceMasks` in mmdet doesn't support rbox, more changes may be needed. 

For RTMDet-ins and RTMDet-R, I've tested a version to merge them, and works fine on roof segmentation. You can copy all code of `RTMDetInsHead` to mmrotate and change the base class to `RotatedRTMDetHead`, then manually merge changes from `RotatedRTMDetHead`. 

My code is still in draft and I will probably submit it when it is complete, but not recently.

![test001](https://user-images.githubusercontent.com/11705038/215431618-b4f973bd-7755-4a1c-8ec8-9ffa76c5f057.jpg)

**Comment by FabianSchuetze** [comment]
Thanks a lot for the informative answer. That is very helpful indeed
