### ISSUE TITLE
g-rep is not available

### ISSUE THREAD

**Issue by ShawJoey** [open-mmlab/mmrotate#709]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

KeyError: 'KLDRepPointsHead is not in the models registry'

sorry, i cannot find the KLDRepPointsHead code. does it still have some problem?  
I'm curious about the result of g-rep. 
I would appreciate it if g-rep could run correctly.

**Comment by yangxue0827** [comment]
For some reasons, MMRotate does not support G-Rep. We have deleted its relevant information in the latest version. You can consult the first author by email.
