### ISSUE TITLE
cannot import name 'points_in_polygons' from 'mmcv.ops'

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#71]
在windows10系统上 运行训练命令报错 cannot import name 'points_in_polygons' from 'mmcv.ops'
请问大佬们 这个怎么解决啊

**Comment by zytx121** [comment]
Please try:
```
# Check Pytorch installation
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

# Check MMRotate installation
import mmrotate
print(mmrotate.__version__)

# Check MMDetection installation
import mmdet
print(mmdet.__version__)

# Check mmcv installation
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())
```
and give us your logs.

**Comment by houw0517** [comment]
torch.__version ：1.10.2
torch.cuda.is_available()  true

![PWXLD`LLJ 5P$6W}L 6@Q$G](https://user-images.githubusercontent.com/86358057/156886617-f956f745-dac1-44dc-9257-c182e9a19655.png)

**Comment by houw0517** [comment]
mmdet.__version__  2.22.0
get_compiling_cuda_version()  11.3
get_compiler_version()  MSVC 191627045

**Comment by zytx121** [comment]
Please install mmrotate.

**Comment by houw0517** [comment]
I pip install mmrotate 
ERROR: Could not find a version that satisifies the requirement mmcv(from mmrotate) (from versions:none)
ERROR: No matching distribution found for mmcv

**Comment by zytx121** [comment]
We need install mmcv before install mmrotate. Maybe read our docs can help you.

**Comment by houw0517** [comment]
Assertion Error： points-in-polygons-forward miss in module-ext

**Comment by zytx121** [comment]
Hi @houw0517 
This error is because mmcv is not installed correctly. (Operators are not compiled.)
But don't worry. Installing mmcv is probably the most challenging step in MMRotate‘s installation process.
You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install `mmcv-full` which have been compiled. So you don't have to compile it yourself.

After that, you could test whether mmcv is installed successfully through the following command
```
# Check mmcv installation
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())
```
If no error is reported, the mmcv installation is successful.

**Comment by 2793145003** [comment]
> Hi @houw0517 This error is because mmcv is not installed correctly. (Operators are not compiled.) **But don't worry. Installing mmcv is probably the most challenging step in MMRotate‘s installation process.** You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install `mmcv-full` which have been compiled. So you don't have to compile it yourself.
> 
> After that, you could test whether mmcv is installed successfully through the following command
> 
> ```
> # Check mmcv installation
> from mmcv.ops import get_compiling_cuda_version, get_compiler_version
> print(get_compiling_cuda_version())
> print(get_compiler_version())
> ```
> 
> If no error is reported, the mmcv installation is successful.

hi, I have same problem. I get
```
11.3
GCC 7.3
```
running the command but still get `ImportError: cannot import name 'points_in_polygons' from 'mmcv.ops' (/usr/local/lib/python3.8/site-packages/mmcv/ops/__init__.py)
from mmcv import Config, DictAction` running test.py

**Comment by zytx121** [comment]
> > Hi @houw0517 This error is because mmcv is not installed correctly. (Operators are not compiled.) **But don't worry. Installing mmcv is probably the most challenging step in MMRotate‘s installation process.** You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install `mmcv-full` which have been compiled. So you don't have to compile it yourself.
> > After that, you could test whether mmcv is installed successfully through the following command
> > ```
> > # Check mmcv installation
> > from mmcv.ops import get_compiling_cuda_version, get_compiler_version
> > print(get_compiling_cuda_version())
> > print(get_compiler_version())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If no error is reported, the mmcv installation is successful.
> 
> hi, I have same problem. I get
> 
> ```
> 11.3
> GCC 7.3
> ```
> 
> running the command but still get `ImportError: cannot import name 'points_in_polygons' from 'mmcv.ops' (/usr/local/lib/python3.8/site-packages/mmcv/ops/__init__.py) from mmcv import Config, DictAction` running test.py

This is because you did not successfully install the compiled mmcv-full. You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install mmcv-full which have been compiled.

**Comment by 2793145003** [comment]
> Hi @2793145003 This is because you did not successfully install the compiled mmcv-full. You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install mmcv-full which have been compiled.

Thanks for reply. It's because I installed mmcv-full with wrong CUDA version.

**Comment by Aliciawangyu** [comment]
I have successfully installed the compiled mmcv-full, 

and I get 10.2 and GCC 7.3 running the commond
`from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())` ,  

but still have a problem of 
`File "/amax/home/wangyu/Large-Selective-Kernel-Network/mmrotate/core/bbox/assigners/atss_kld_assigner.py", line 3, in <module> from mmcv.ops import points_in_polygons`
` File "/amax/home/wangyu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/points_in_polygons.py", line 6, in <module> ext_module = ext_loader.load_ext('_ext', ['points_in_polygons_forward'])`
`File "/amax/home/wangyu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext assert hasattr(ext, fun), f'{fun} miss in module {name}'`
`AssertionError: points_in_polygons_forward miss in module _ext`

**Comment by Aliciawangyu** [comment]
> > > Hi @houw0517 This error is because mmcv is not installed correctly. (Operators are not compiled.) **But don't worry. Installing mmcv is probably the most challenging step in MMRotate‘s installation process.** You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install `mmcv-full` which have been compiled. So you don't have to compile it yourself.
> > > After that, you could test whether mmcv is installed successfully through the following command
> > > ```
> > > # Check mmcv installation
> > > from mmcv.ops import get_compiling_cuda_version, get_compiler_version
> > > print(get_compiling_cuda_version())
> > > print(get_compiler_version())
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If no error is reported, the mmcv installation is successful.
> > 
> > 
> > hi, I have same problem. I get
> > ```
> > 11.3
> > GCC 7.3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > running the command but still get `ImportError: cannot import name 'points_in_polygons' from 'mmcv.ops' (/usr/local/lib/python3.8/site-packages/mmcv/ops/__init__.py) from mmcv import Config, DictAction` running test.py
> 
> Hi @2793145003 This is because you did not successfully install the compiled mmcv-full. You could refer [mmcv doc](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) to install mmcv-full which have been compiled.

I have successfully installed the compiled mmcv-full,

and I get 10.2 and GCC 7.3 running the commond
from mmcv.ops import get_compiling_cuda_version, get_compiler_version print(get_compiling_cuda_version()) print(get_compiler_version()) ,

but still have a problem of
File "/amax/home/wangyu/Large-Selective-Kernel-Network/mmrotate/core/bbox/assigners/atss_kld_assigner.py", line 3, in <module> from mmcv.ops import points_in_polygons
 File "/amax/home/wangyu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/points_in_polygons.py", line 6, in <module> ext_module = ext_loader.load_ext('_ext', ['points_in_polygons_forward'])
File "/amax/home/wangyu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: points_in_polygons_forward miss in module _ext
