### ISSUE TITLE
[Docs] https://mmrotate.readthedocs.io/en/1.x/user_guides/train_test.html

### ISSUE THREAD

**Issue by Adlith** [open-mmlab/mmrotate#710]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

How to format the result to a specific format and submit it to the test server in mmrotate1.x?
the command
```
python ./tools/test.py  \
  configs/rotated_retinanet/rotated-retinanet-rbox-le90_r50_fpn_1x_dota.py \
  checkpoints/SOME_CHECKPOINT.pth --format-only \
  --eval-options submission_dir=work_dirs/Task1_results
```
can not be used.

**Comment by vansin** [comment]
please show the  error log

**Comment by Adlith** [comment]
> please show the error log

val-options submission_dir=work_dirs/Task1_results
usage: test.py [-h] [--work-dir WORK_DIR] [--out OUT] [--show] [--show-dir SHOW_DIR] [--wait-time WAIT_TIME] [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
               [--launcher {none,pytorch,slurm,mpi}] [--local_rank LOCAL_RANK]
               config checkpoint
test.py: error: unrecognized arguments: --format-only --eval-options submission_dir=work_dirs/Task1_results

**Comment by liuyanyi** [comment]
You can follow follow the config in 

https://github.com/open-mmlab/mmrotate/blob/5d0491c826ad52b7490a7c1146fb65a7d78e2347/configs/_base_/datasets/dota.py#L69-L88

output dir can be modify in test_evaluator

**Comment by Adlith** [comment]
> You can follow the config in
> 
> https://github.com/open-mmlab/mmrotate/blob/5d0491c826ad52b7490a7c1146fb65a7d78e2347/configs/_base_/datasets/dota.py#L69-L88
> 
> output-dir can be modified in test_evaluator


Thank you.
I finally generated results by 
```
python ./tools/test.py configs/rotated_rtmdet/rotated_rtmdet_l-3x-dota.py work_dirs/rtmdet/epoch_36.pth
```
with the config you mentioned.

**Comment by CrazyBrick** [comment]
> 
Hi, I have the same problem as you, but I'm not sure what changes need to be made in **dota.py.**

At present, I have replaced val with test, but it will report an error as follows:
`Traceback (most recent call last):
  File "./tools/test.py", line 127, in <module>
    main()
  File "./tools/test.py", line 109, in main
    runner = Runner.from_cfg(cfg)
  File "/xxx/environment/openmmlab_1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/xxx/environment/openmmlab_1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 315, in __init__
    raise ValueError(
ValueError: val_dataloader, val_cfg, and val_evaluator should be either all None or not None, but got val_dataloader=None, val_cfg={'type': 'ValLoop'}, val_evaluator=None`

Can you share your specific modifications? Thanks in advance.

**Comment by xsxyh** [comment]
> python ./tools/test.py configs/rotated_rtmdet/rotated_rtmdet_l-3x-dota.py work_dirs/rtmdet/epoch_36.pth

How do you solve this issue? I have encountered the same problem.

**Comment by xsxyh** [comment]
> > 
> 
> Hi, I have the same problem as you, but I'm not sure what changes need to be made in **dota.py.**
> 
> At present, I have replaced val with test, but it will report an error as follows: `Traceback (most recent call last): File "./tools/test.py", line 127, in <module> main() File "./tools/test.py", line 109, in main runner = Runner.from_cfg(cfg) File "/xxx/environment/openmmlab_1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg runner = cls( File "/xxx/environment/openmmlab_1/lib/python3.8/site-packages/mmengine/runner/runner.py", line 315, in __init__ raise ValueError( ValueError: val_dataloader, val_cfg, and val_evaluator should be either all None or not None, but got val_dataloader=None, val_cfg={'type': 'ValLoop'}, val_evaluator=None`
> 
> Can you share your specific modifications? Thanks in advance.

Hello, How do you solve this issue? I have encountered the same problem.
