### ISSUE TITLE
backbone--ResNet

### ISSUE THREAD

**Issue by yechao-prog** [open-mmlab/mmrotate#711]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

R3det的backbone ResNet 以及FPN在哪儿可以找到呢？

**Comment by yangxue0827** [comment]
You can find them in mmdetection. mmrotate imports resnet and fpn from mmdetection.

**Comment by yechao-prog** [comment]
ok，thank you very much。I find them！！！

**Comment by SmallingCar** [comment]
> You can find them in mmdetection. mmrotate imports resnet and fpn from mmdetection.

i register a new backbone in mmdetection,and use it in mmrotate ,but it appears a bug ,what should i do ?

**Comment by SmallingCar** [comment]
> > You can find them in mmdetection. mmrotate imports resnet and fpn from mmdetection.
> 
> i register a new backbone in mmdetection,and use it in mmrotate ,but it appears a bug ,what should i do ?

the new backbone in mmdetection is nice ,but there is bug in mmrotate
