### ISSUE TITLE
pipeline transforms in 1.x branch

### ISSUE THREAD

**Issue by yuvalgrossman** [open-mmlab/mmrotate#749]
### What's the feature?

Hi, 
I'm working on training RTMDet to my data (so must use the 1.x or dev-1.x branch), and I wish to implement a multi-scale resize transform. 
I notice that in the main branch this is implemented in [RResize() class](https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/datasets/pipelines/transforms.py), however in the 1.x branch it does not exist, and the transforms are different. 
This transform also implemented in the main branch in mmdet in [Resize() class](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py) however, I'm forced to work with mmdet>=3.0.0, which don't include that. 

Generally, this project is awesome. However, I find it very difficult to understand the versioning of the whole open-mmlab. Is there a place where the compatibility specified for the **dev branch**es? Where can I find the future release schedule? 
Thanks

**Comment by liuyanyi** [comment]
We provide a sample config for more augmentation, please check 

https://github.com/open-mmlab/mmrotate/blob/5d0491c826ad52b7490a7c1146fb65a7d78e2347/configs/rotated_rtmdet/rotated_rtmdet_l-100e-aug-dota.py#L85-L90

In 1.x we can use most of the augmentations in mmdet without modification.
For source code you can check [mmcv.transforms](https://github.com/open-mmlab/mmcv/tree/2.x/mmcv/transforms) and https://github.com/open-mmlab/mmdetection/tree/3.x/mmdet/datasets/transforms

**Comment by yuvalgrossman** [comment]
great, thanks!
