### ISSUE TITLE
[Feature] about RoIPoolRotated

### ISSUE THREAD

**Issue by Ariyl** [open-mmlab/mmrotate#750]
### What's the feature?

Thank you for providing such great work!

In the rotated object detection task, the common feature pooling method is RoIAlignRotated. If there is a max pooling, i.e. RoIPoolRotated method. If not how should I modify it?

In the RoIAlign implementation, there is a parameter pool_mode that controls whether the pooling method is max pooling or avg pooling, is there a similar parameter in RotatedRoIAlign?

**Comment by zytx121** [comment]
Hi @Ariyl, we don't support RoPoolRotated and pool_mode in RotatedRoIAlign now. If you want to modify it yourself, please refer `to https://github.com/open-mmlab/mmcv/blob/2.x/mmcv/ops/roi_align_rotated.py`. Frankly speaking, it will involve the modification of the C++/CUDA operator, which is quite tricky.

**Comment by Ariyl** [comment]
> Hi @Ariyl, we don't support RoPoolRotated and pool_mode in RotatedRoIAlign now. If you want to modify it yourself, please refer `to https://github.com/open-mmlab/mmcv/blob/2.x/mmcv/ops/roi_align_rotated.py`. Frankly speaking, it will involve the modification of the C++/CUDA operator, which is quite tricky.

Thanks for your reply! I think I should approach this problem in a different way
