### ISSUE TITLE
添加自己的模块遇到问题

### ISSUE THREAD

**Issue by mkzhcak** [open-mmlab/mmrotate#756]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

我在mmrotate/mmrotate/models/dense_heads/rotated_rtmdet_head.py中写入了自己的模块，该模块继承RotatedRTMDetHead，用@MODELS.register_module()注册，然后在__init__中加入了该模块，之后pip install -e .然后在我的配置文件中调用，但是在train的时候报错，报错如下：TypeError: class `RTMDet` in mmdet/models/detectors/rtmdet.py: class `RotatedRTMDetSepBNHead` in mmrotate/models/dense_heads/rotated_rtmdet_head.py: __init__() got an unexpected keyword argument 'num_block
下面是我的配置文件：
_base_ = './rotated_rtmdet_l-3x-dota_ms.py'

checkpoint = 'https://download.openmmlab.com/mmdetection/v3.0/rtmdet/cspnext_rsb_pretrain/cspnext-s_imagenet_600e.pth'  # noqa

model = dict(
    backbone=dict(
        deepen_factor=0.33,
        widen_factor=0.5,
        init_cfg=dict(
            type='Pretrained', prefix='backbone.', checkpoint=checkpoint)),
    neck=dict(in_channels=[128, 256, 512], out_channels=128, num_csp_blocks=1),
    bbox_head=dict(
        num_block=2,
        window_size=[7,7],
        shift=[3,3],
        drop=0.3,
        num_head=8,
        dim=128,           
        in_channels=128,
        feat_channels=128,
        exp_on_reg=False,
        loss_bbox=dict(type='RotatedIoULoss', mode='linear', loss_weight=2.0),
    ))

# batch_size = (1 GPUs) x (8 samples per GPU) = 8
train_dataloader = dict(batch_size=8, num_workers=4)

**Comment by 1shenhui** [comment]
Please did you solve it
