### ISSUE TITLE
[Bug] Wrongly labelled bounding box with a 90 degree malposition (or long/short edges mislabel) - RSDD dataset

### ISSUE THREAD

**Issue by RoyLJH** [open-mmlab/mmrotate#764]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.7.15 (default, Nov 24 2022, 21:12:53) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: TITAN RTX
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.10
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.7.0
MMEngine: 0.4.0
MMRotate: 1.0.0rc1+5d0491c

### Reproduces the problem - code sample

Trained several detectors on RSDD dataset but the performances are quite low, while on HRSID and SRSDD the performance seems ok. 

Therefore I visualize the RSDD dataset to see the bounding box and find that  bounding boxes are 90 degrees deviated from the real object (or the long edges and short edges are accidentally switched)?  See the following image samples.

![image](https://user-images.githubusercontent.com/38347064/223942636-14826873-53a3-4570-9f64-f9c82053dffc.png)

I use `tools/analysis_tools/browse_dataset.py` to visualize the dataset. The config file is  `configs/_base_/datasets/rsdd.py` with two additional lines of code:

`
vis_backends = [dict(type='LocalVisBackend')]

visualizer = dict(type='RotLocalVisualizer', vis_backends=vis_backends, name='visualizer')
`

### Reproduces the problem - command or script

See the previous section.

### Reproduces the problem - error message

No error message but the bounding boxes are clearly mislabeled. More examples:

![image](https://user-images.githubusercontent.com/38347064/223947126-ed58d84d-1b81-4408-baf2-54b2b579fb5e.png)
 
![image](https://user-images.githubusercontent.com/38347064/223947193-45ca625c-90af-42bc-a763-21a174881ada.png)

### Additional information

It's either a rotation angle error or long/short edge confusion. (Each bounding box is nearly perpendicular to the original object)

**Comment by zytx121** [comment]
Hi @RoyLJH! Thank you for your feedback. We will check and fix this bug as soon as possible!

**Comment by zytx121** [comment]
[rsdd_annotation.zip](https://github.com/open-mmlab/mmrotate/files/10963874/rsdd_annotation.zip)
Please try this new annotation.

**Comment by RoyLJH** [comment]
Hi @zytx121, thank you for your response. I also tried my way to fix this issue.

The key problem is: MMRotate uses [long edge definition](https://mmrotate.readthedocs.io/en/latest/intro.html#definition-of-rotated-box) where `width > height`. However,  the original repository [RSDD repo](https://github.com/makabakasu/RSDD-SAR-OPEN) of RSDD has larger value in height than weight.


![image](https://user-images.githubusercontent.com/38347064/224888571-3ef08da1-1ed6-47f3-9341-65d05690aa25.png)
(from 0_0_5.xml for example)

By multiplying the angle by -1 can solve this issue. 

The RSDD dataset has both coco format and voc format annotations. I hereby paste my script of re-generating COCO format annotation from VOC format XML files.

**Comment by RoyLJH** [comment]
Put this file at root in the RSDD folder:
```
import xml.etree.ElementTree as ET
import os
import json
import math
 
coco = dict()
coco['images'] = []
coco['type'] = 'instances'
coco['annotations'] = []
coco['categories'] = []
 
train_file_list = []
test_file_list = []

category_set = dict()
image_set = set()
 
category_item_id = -1
image_id = 0
annotation_id = 0

def get_train_test_file_list():
    global train_file_list, test_file_list
    with open('ImageSets/train.txt', 'r') as f:
        lines = f.readlines()
        for line in lines:
            train_file_list.append(line.strip())
    with open('ImageSets/test.txt', 'r') as f:
        lines = f.readlines()
        for line in lines:
            test_file_list.append(line.strip())
    print(len(test_file_list))
    print(len(train_file_list))
    print(test_file_list[0])

def addCatItem(name):
    global category_item_id
    category_item = dict()
    category_item['supercategory'] = 'none'
    category_item_id += 1
    category_item['id'] = category_item_id
    category_item['name'] = name
    coco['categories'].append(category_item)
    category_set[name] = category_item_id
    return category_item_id
 
def addImgItem(file_name, size):
    global image_id
    if file_name is None:
        raise Exception('Could not find filename tag in xml file.')
    if size['width'] is None:
        raise Exception('Could not find width tag in xml file.')
    if size['height'] is None:
        raise Exception('Could not find height tag in xml file.')
    image_id += 1
    image_item = dict()
    image_item['id'] = image_id
    image_item['file_name'] = file_name
    image_item['width'] = size['width']
    image_item['height'] = size['height']
    coco['images'].append(image_item)
    image_set.add(file_name)
    return image_id

def addRotAnnoItem(object_name, image_id, category_id, bbox):
    global annotation_id
    
    annotation_item = dict()
    annotation_item['segmentation'] = []
    seg = []
    # bbox[] is cx,cy,w,h,angle
    cos_a = math.cos(-1*bbox[4])
    sin_a = math.sin(-1*bbox[4])

    dx = bbox[2] / 2
    dy = bbox[3] / 2
    offsets = [(dx, dy), (dx, -dy), (-dx, -dy), (-dx, dy)]

    for offset in offsets:
        x = offset[0] * cos_a + offset[1] * sin_a + bbox[0]
        y = -offset[0] * sin_a + offset[1] * cos_a + bbox[1]
        seg.append(round(x))
        seg.append(round(y))
    print(seg)

    annotation_item['segmentation'].append(seg)
 
    annotation_item['area'] = bbox[2] * bbox[3]
    annotation_item['iscrowd'] = 0
    annotation_item['ignore'] = 0
    annotation_item['image_id'] = image_id
    annotation_item['bbox'] = bbox[:4]
    annotation_item['category_id'] = category_id
    annotation_id += 1
    annotation_item['id'] = annotation_id
    coco['annotations'].append(annotation_item)

"""直接从xml文件夹中生成"""
def parseXmlFiles_rsdd_train(xml_path,json_save_path):
    for f in os.listdir(xml_path):
        if not f.endswith('.xml'):
            continue
        if f.split('.')[0] not in train_file_list:
            continue
        bndbox = dict()
        size = dict()
        current_image_id = None
        current_category_id = None
        file_name = None
        size['width'] = 512
        size['height'] = 512
        size['depth'] = 3
 
        xml_file = os.path.join(xml_path, f)
 
        tree = ET.parse(xml_file)
        root = tree.getroot()
        if root.tag != 'annotation':
            raise Exception('pascal voc xml root element should be annotation, rather than {}'.format(root.tag))
 
        for elem in root:
            if elem.tag == 'filename':
                file_name = elem.text
                if file_name in category_set:
                    raise Exception('file_name duplicated')
            elif elem.tag == 'size':
                current_image_id = addImgItem(file_name.replace('.xml', '.jpg'), size)
                print('add image with {} and {}'.format(file_name, size))
            elif elem.tag == 'object':
                for subelem in elem:
                    if subelem.tag == 'name':
                        object_name = subelem.text
                        if object_name not in category_set:
                            current_category_id = addCatItem(object_name)
                        else:
                            current_category_id = category_set[object_name]
                    elif subelem.tag == 'robndbox':
                        for option in subelem:
                            bndbox[option.tag] = float(option.text)
                bbox = []
                bbox.append(bndbox['cx'])
                # cy
                bbox.append(bndbox['cy'])
                # h
                bbox.append(bndbox['h'])
                # w
                bbox.append(bndbox['w'])
                # angle
                bbox.append(bndbox['angle'])
                print('add annotation with {},{},{},{}'.format(object_name, current_image_id, current_category_id,
                                                                   bbox))
                addRotAnnoItem(object_name, current_image_id, current_category_id, bbox)
    print(f"Load {current_image_id} images in train set.")      
    json.dump(coco, open(json_save_path, 'w'))

"""直接从xml文件夹中生成"""
def parseXmlFiles_rsdd_test(xml_path,json_save_path):
    for f in os.listdir(xml_path):
        if not f.endswith('.xml'):
            continue
        if f.split('.')[0] not in test_file_list:
            continue
        bndbox = dict()
        size = dict()
        current_image_id = None
        current_category_id = None
        file_name = None
        size['width'] = 512
        size['height'] = 512
        size['depth'] = 3
 
        xml_file = os.path.join(xml_path, f)
 
        tree = ET.parse(xml_file)
        root = tree.getroot()
        if root.tag != 'annotation':
            raise Exception('pascal voc xml root element should be annotation, rather than {}'.format(root.tag))
 
        for elem in root:
            if elem.tag == 'filename':
                file_name = elem.text
                if file_name in category_set:
                    raise Exception('file_name duplicated')
            elif elem.tag == 'size':
                current_image_id = addImgItem(file_name.replace('.xml', '.jpg'), size)
                print('add image with {} and {}'.format(file_name, size))
            elif elem.tag == 'object':
                for subelem in elem:
                    if subelem.tag == 'name':
                        object_name = subelem.text
                        if object_name not in category_set:
                            current_category_id = addCatItem(object_name)
                        else:
                            current_category_id = category_set[object_name]
                    elif subelem.tag == 'robndbox':
                        for option in subelem:
                            bndbox[option.tag] = float(option.text)
                bbox = []
                bbox.append(bndbox['cx'])
                # cy
                bbox.append(bndbox['cy'])
                # h
                bbox.append(bndbox['h'])
                # w
                bbox.append(bndbox['w'])
                # angle
                bbox.append(bndbox['angle'])
                print('add annotation with {},{},{},{}'.format(object_name, current_image_id, current_category_id,
                                                                   bbox))
                addRotAnnoItem(object_name, current_image_id, current_category_id, bbox)
    print(f"Load {current_image_id} images in test set.")      
    json.dump(coco, open(json_save_path, 'w'))
 
 
 
if __name__ == '__main__':
    get_train_test_file_list()

    #通过文件夹生成
    ann_path="./Annotations"
    json_save_path="./ImageSets/train_rot.json"
    parseXmlFiles_rsdd_train(ann_path,json_save_path)


    category_set = dict()
    image_set = set()
    
    category_item_id = -1
    image_id = 0
    annotation_id = 0
    json_save_path="./ImageSets/test_rot.json"
    parseXmlFiles_rsdd_test(ann_path,json_save_path)
```

Run the script and use `ImageSets/train_rot.json` and `ImageSets/test_rot.json` as new annotation files. The bounding box will be normal.
