### ISSUE TITLE
When training s2anet, the precision is too low

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmrotate#765]
When I was using s2anet, I only modified the angle_version, num_class and img_scale of the config file. The data set used was DOTAv1.5, and only one class of ship was used. The recall of the test result was 0.908, but the precision was only 0.324. What is the reason? Had the same problem in sasm_reppoints.

**Comment by zytx121** [comment]
Hi @19990101lrk! As far as we know, this is caused by the extremely small target in DOTAv1.5, which have a fatal impact on the single-stage detector. You can filter out these tiny boxes in `train_pipeline`, just like:
```
dict(type='mmdet.FilterAnnotations', min_gt_bbox_wh=(1e-2, 1e-2)),
```

**Comment by zytx121** [comment]
We do not support this feature yet, welcome to PR!
