### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fredO13** [open-mmlab/mmrotate#773]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

# Name                    Version                   Build  Channel
addict                    2.4.0                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0    anaconda
argon2-cffi-bindings      21.2.0           py37h2bbff1b_0    anaconda
attrs                     21.4.0             pyhd3eb1b0_0    anaconda
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
beautifulsoup4            4.11.1           py37haa95532_0    anaconda
blas                      1.0                         mkl    anaconda
bleach                    4.1.0              pyhd3eb1b0_0    anaconda
ca-certificates           2022.4.26            haa95532_0    anaconda
certifi                   2022.6.15        py37haa95532_0    anaconda
cffi                      1.15.0           py37h2bbff1b_1    anaconda
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cudatoolkit               10.1.243             h74a9793_0    anaconda
cycler                    0.11.0                   pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
debugpy                   1.5.1            py37hd77b12b_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
defusedxml                0.7.1              pyhd3eb1b0_0    anaconda
e2cnn                     0.2.3                    pypi_0    pypi
entrypoints               0.4              py37haa95532_0    anaconda
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.10.4                   vc14_3  [vc14]  esri
future                    0.18.3                   pypi_0    pypi
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0    anaconda
importlib_resources       5.2.0              pyhd3eb1b0_1    anaconda
intel-openmp              2021.4.0          haa95532_3556    anaconda
ipykernel                 6.9.1            py37haa95532_0    anaconda
ipython                   7.31.1           py37haa95532_0    anaconda
ipython_genutils          0.2.0              pyhd3eb1b0_1    anaconda
ipywidgets                7.6.5              pyhd3eb1b0_1    anaconda
jedi                      0.18.1           py37haa95532_1    anaconda
jinja2                    3.0.3              pyhd3eb1b0_0    anaconda
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
jsonschema                4.4.0            py37haa95532_0    anaconda
jupyter                   1.0.0                    py37_7    anaconda
jupyter_client            7.2.2            py37haa95532_0    anaconda
jupyter_console           6.4.3              pyhd3eb1b0_0    anaconda
jupyter_core              4.10.0           py37haa95532_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    anaconda
kiwisolver                1.4.4                    pypi_0    pypi
libpng                    1.6.32           vc14h5163883_3  [vc14]  anaconda
libtiff                   4.2.0                hd0e1b90_0    anaconda
libuv                     1.40.0               he774522_0    anaconda
libwebp                   1.2.2                h2bbff1b_0    anaconda
lz4-c                     1.9.3                h2bbff1b_1    anaconda
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.1            py37h2bbff1b_0    anaconda
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
mdurl                     0.1.2                    pypi_0    pypi
mistune                   0.8.4           py37hfa6e2cd_1001    anaconda
mkl                       2021.4.0           haa95532_640    anaconda
mkl-service               2.4.0            py37h2bbff1b_0    anaconda
mkl_fft                   1.3.1            py37h277e83a_0    anaconda
mkl_random                1.2.2            py37hf11a4ad_0    anaconda
mmcv-full                 1.7.1                    pypi_0    pypi
mmdet                     2.28.2                   pypi_0    pypi
mmrotate                  0.3.4                    pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
nbclient                  0.5.13           py37haa95532_0    anaconda
nbconvert                 6.4.4            py37haa95532_0    anaconda
nbformat                  5.3.0            py37haa95532_0    anaconda
nest-asyncio              1.5.5            py37haa95532_0    anaconda
ninja                     1.10.2               haa95532_5    anaconda
ninja-base                1.10.2               h6d14046_5    anaconda
notebook                  6.4.11           py37haa95532_0    anaconda
numpy                     1.21.5           py37h7a0a035_3    anaconda
numpy-base                1.21.5           py37hca35cd5_3    anaconda
opencv                    4.0.1.24                 py37_0    esri
openmim                   0.3.6                    pypi_0    pypi
openssl                   1.0.2u               he774522_0    anaconda
ordered-set               4.1.0                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0    anaconda
parso                     0.8.3              pyhd3eb1b0_0    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    9.0.1            py37hdc2b20a_0    anaconda
pip                       21.2.4           py37haa95532_0    anaconda
prometheus_client         0.13.1             pyhd3eb1b0_0    anaconda
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
prompt_toolkit            3.0.20               hd3eb1b0_0    anaconda
pycocotools               2.0.6                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pygments                  2.14.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyqt                      5.6.0            py37ha878b3d_6    anaconda
pyrsistent                0.18.0           py37h196d8e1_0    anaconda
python                    3.7.1                h33f27b4_4    anaconda
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python-fastjsonschema     2.15.1             pyhd3eb1b0_0    anaconda
pytorch                   1.7.0           py3.7_cuda101_cudnn7_0    pytorch
pytz                      2022.7.1                 pypi_0    pypi
pywin32                   302              py37h2bbff1b_2    anaconda
pywinpty                  2.0.2            py37h5da7b33_0    anaconda
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0           py37hd77b12b_2    anaconda
qt                        5.6.2           vc14h6f8c307_12  [vc14]  anaconda
qtconsole                 5.3.0              pyhd3eb1b0_0    anaconda
qtpy                      2.0.1              pyhd3eb1b0_0    anaconda
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rich                      13.3.2                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1    anaconda
setuptools                61.2.0           py37haa95532_0    anaconda
sip                       4.18.1           py37hd77b12b_2    anaconda
six                       1.16.0             pyhd3eb1b0_1    anaconda
soupsieve                 2.3.1              pyhd3eb1b0_0    anaconda
sqlite                    3.38.5               h2bbff1b_0    anaconda
sympy                     1.10.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
terminado                 0.13.1           py37haa95532_0    anaconda
terminaltables            3.1.10                   pypi_0    pypi
testpath                  0.6.0            py37haa95532_0    anaconda
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
torchvision               0.8.1                py37_cu101    pytorch
tornado                   6.1              py37h2bbff1b_0    anaconda
traitlets                 5.1.1              pyhd3eb1b0_0    anaconda
typing-extensions         4.1.1                hd3eb1b0_0    anaconda
typing_extensions         4.1.1              pyh06a4308_0    anaconda
urllib3                   1.26.15                  pypi_0    pypi
vc                        14.2                 h21ff451_1    anaconda
vs2015_runtime            14.27.29016          h5e58377_2    anaconda
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
wheel                     0.37.1             pyhd3eb1b0_0    anaconda
widgetsnbextension        3.5.2            py37haa95532_0    anaconda
wincertstore              0.2              py37haa95532_2    anaconda
winpty                    0.4.3                         4    anaconda
xz                        5.2.5                h8cc25b3_1    anaconda
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda
zstd                      1.4.5                h04227a9_0    anaconda

### Reproduces the problem - code sample

python demo/image_demo.py demo/demo.jpg configs/oriented_rcnn_r50_fpn_1x_dota_le90.py --weights oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth demo/vis.jpg

### Reproduces the problem - command or script

see above

### Reproduces the problem - error message

the error arises when trying to load extension module. Bellow is the trace I added to see what is tries to load
import_module(mmcv._ext, None)

this is the call stack

Traceback (most recent call last):
  File "demo/image_demo.py", line 4, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File "\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "\lib\site-packages\mmdet\apis\inference.py", line 8, in <module>
    from mmcv.ops import RoIPool
  File "\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "\lib\site-packages\mmcv\utils\ext_loader.py", line 15, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "\lib\importlib\__init__.py", line 128, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by zytx121** [comment]
Hi @fredO13 please reinstall the mmcv-full by 
```
pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7/index.html
```
