### ISSUE TITLE
[Docs] how to perform rotation augmentation during testing

### ISSUE THREAD

**Issue by SustechcsKing** [open-mmlab/mmrotate#774]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

I couldn't find the test rotation augmentation method in doc, thank you

**Comment by zytx121** [comment]
Hi @SustechcsKing!
Sorry, we don't support this feature. Welcome to PR!

**Comment by SustechcsKing** [comment]
@zytx121 Thank you, I try to implement it.

**Comment by fdy61** [comment]
i want ask the same question,The test.py of mmrotate does't have --tta
