### ISSUE TITLE
首先感谢这一出色的工作，我用ssdd的数据加oriented_rcnn配置文件训练并测试了，效果很好，现在想把自己的数据处理成dota形式的，请问我该怎么做啊，有什么做标签的工具吗

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmrotate#78]

**Comment by zytx121** [comment]
Hi @happy20200 
Thanks for your use. You could refer to https://github.com/ming71/toolbox/tree/master/converter/toDOTA to convert your datasets to DOTA style.
