### ISSUE TITLE
[Error] CUDA error: an illegal memory access was encountered 

### ISSUE THREAD

**Issue by yang326922943** [open-mmlab/mmrotate#780]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

训练过程中，会时不时地出现CUDA error: an illegal memory access was encountered，而且在已经完成一个epoch的train和val

**Comment by yangxue0827** [comment]
1. For reppoints based detector, close validation during training.
2. If the same error occurs during testing, try some potentially useful solutions mentioned in https://github.com/open-mmlab/mmrotate/issues/405.
