### ISSUE TITLE
eval_map()got an unexpected keyword argument"version"

### ISSUE THREAD

**Issue by ga546** [open-mmlab/mmrotate#79]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I train my own dataset and evaluation it but it return eval_map()got an unexpected keyword argument"version"
**Reproduction**

1. What command or script did you run?
python tool/train.py
A placeholder for the command.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
in dota.py 
Comment line 205 : version=self.version

**Comment by happy20200** [comment]
请问你自己的数据及是怎么做的啊，另外你这个问题我也遇到了，我直接注释掉出问题的行倒是临时跑通了

**Comment by ga546** [comment]
就把自己数据集改成dota的格式就好了，嗯嗯，我也是注释掉了

**Comment by ga546** [comment]
> 请问你自己的数据及是怎么做的啊，另外你这个问题我也遇到了，我直接注释掉出问题的行倒是临时跑通了

**Comment by ga546** [comment]
我是把自己的数据集改成dota数据集的格式，嗯嗯，注释掉确实跑通了，就是不知道实际上那个参数有没有用

**Comment by happy20200** [comment]
> 我是把自己的数据集改成dota数据集的格式，嗯嗯，注释掉确实跑通了，就是不知道实际上那个参数有没有用

那请问是用什么工具标注的呢，刚刚入门目标检测，实在没有经验

**Comment by zytx121** [comment]
@ga546 This bug has been fixed in the dev branch, and you could switch to the dev branch.

**Comment by zytx121** [comment]
> 



> 请问你自己的数据及是怎么做的啊，另外你这个问题我也遇到了，我直接注释掉出问题的行倒是临时跑通了

Thank you for answering our issue. We have already answered your questions in #78

**Comment by ga546** [comment]
labelme

**Comment by ga546** [comment]
> 
I use labelme

**Comment by ga546** [comment]
> > 我是把自己的数据集改成dota数据集的格式，嗯嗯，注释掉确实跑通了，就是不知道实际上那个参数有没有用
> 
> 那请问是用什么工具标注的呢，刚刚入门目标检测，实在没有经验

I use labelme

**Comment by ga546** [comment]
> @ga546 This bug has been fixed in #37, and you could refer to it (just delete it). Or you could switch to the dev branch.
thanks
