### ISSUE TITLE
Comparison of L1, L2, Smooth L1 Loss on Rotated RetinaNet

### ISSUE THREAD

**Issue by hh123445** [open-mmlab/mmrotate#793]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

TorchVision: 0.10.1+cu111
OpenCV: 4.5.3
MMCV: 1.6.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.4
MMRotate: 0.3.2+

### Reproduces the problem - code sample

I am comparing the impact of L1, L2, smooth L1 Loss as box regression losses on rotated RetinaNet on my own dataset。
However, I found that the effect of L1 Loss (mAP50=0.9, mAP @ [. 5:.95]=0.58) was significantly greater than that of L2 Loss (mAP50=0.791, mAP @ [. 5:.95]=0.45) and smooth L1 Loss (mAP50=0.786, mAP @ [. 5:.95]=0.43),

**"I can't understand why smooth L1 Loss has a worse effect than L1 Loss on rotated RetinaNet, or why the training results of L2 Loss and L1 Loss differ so much.". One of my guesses is that the rotation detection box needs to regress the rotation angle, and there are more outliers for the rotation angle than for the four parameters in the horizontal detection, so using L1 Loss would be better? However, it is still difficult to explain why smooth L1 Loss is less effective than L1 Loss?**

The following is my config file. Is my configuration correct?  What is the more appropriate setting for beta and loss_weight in smooth L1 Loss ? In addition to making changes at the loss_bbox, do I need to make changes elsewhere to enable rotated RetinaNet to use L2 Loss and smooth L1 Loss for training?

L1 Loss config:
````
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=1,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range='le135',
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0))

      evaluation = dict(interval=10, metric='mAP')
      optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
      optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
      lr_config = dict(
          policy='step',
          warmup='linear',
          warmup_iters=500,
          warmup_ratio=0.3333333333333333,
          step=[20, 30])
````
L2 Loss(MSE Loss) config:
````
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=1,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range='le135',
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='MSELoss', loss_weight=1.0)),

        evaluation = dict(interval=5, metric='mAP')
        optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
        optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
        lr_config = dict(
            policy='step',
            warmup='linear',
            warmup_iters=500,
            warmup_ratio=0.3333333333333333,
            step=[20, 30]) 
````
smooth L1 Loss:
````
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=1,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        assign_by_circumhbbox=None,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range='le135',
            norm_factor=None,
            edge_swap=True,
            proj_xy=True,
            target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),

      evaluation = dict(interval=5, metric='mAP')
      optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
      optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
      lr_config = dict(
          policy='step',
          warmup='linear',
          warmup_iters=500,
          warmup_ratio=0.3333333333333333,
          step=[20, 30])
````

Thank you very much!

### Reproduces the problem - command or script

Reference Above

### Reproduces the problem - error message

Reference Above

### Additional information

Reference Above

**Comment by yangxue0827** [comment]
Resolved through private message.
