### ISSUE TITLE
您好，你们公布的模型库中还有许多的配置文件没有涉及，请问这些模型会陆续公布吗

### ISSUE THREAD

**Issue by luoz66** [open-mmlab/mmrotate#80]

**Comment by zytx121** [comment]
All models in our model library provide configuration files. Could you please tell us which model is missing?

**Comment by luoz66** [comment]
> All models in our model library provide configuration files. Could you please tell us which model is missing?

例如这个配置文件r3det_kfiou_ln_swin_tiny_adamw_fpn_1x_dota_ms_rr_oc.py，在model library中没有相应的记录
你们项目中很多配置文件在model library中是没有的

**Comment by zytx121** [comment]
We will release them later. And you could train it by yourself.

**Comment by luoz66** [comment]
> Sorry, we will release them later. And you could train it by yourself.

好的，你们的工作对我的研究起到了很大的作用，很感谢你们
