### ISSUE TITLE
MMRotate colab does not works[Bug] 

### ISSUE THREAD

**Issue by Nicolaing** [open-mmlab/mmrotate#824]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

# Check nvcc version
!nvcc -V
# Check GCC version
!gcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Reproduces the problem - code sample

import mmrotate
print(mmrotate.__version__)

### Reproduces the problem - command or script

from mmcv import collect_env
collect_env()

# Check MMRotate installation
import mmrotate
print(mmrotate.__version__)

# Check MMDetection installation
import mmdet
print(mmdet.__version__)

# Check mmcv installation
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-6-f1ca9e5d2a56>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from mmcv import collect_env
      2 collect_env()
      3 
      4 # Check MMRotate installation
      5 import mmrotate

ImportError: cannot import name 'collect_env' from 'mmcv' (/usr/local/lib/python3.9/dist-packages/mmcv/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Reproduces the problem - error message

mmcv==2.0.0 is used but incompatible. please install mmcv>=1.3.17, <=1.8.0.

### Additional information

I may think that the Google colabs Cuda version is newer than what the MMRotate is taking as maximum. How can i solve this?

**Comment by erennaltunn** [comment]
I have the same problem. MMRotate_Tutorial.ipynb should be checked.

**Comment by zytx121** [comment]
Hi @Nicolaing and @erennaltunn, you're right. We will update the `MMRotate_Tutorial.ipynb` for 1.x branch ASAP.

**Comment by erennaltunn** [comment]
Hi, thank you for consideration. May I ask how long do you think it will take approximately? I am willing to use it for a project.

**Comment by BambaSpoid** [comment]
> Hi @Nicolaing and @erennaltunn, you're right. We will update the `MMRotate_Tutorial.ipynb` for the 1.x branch ASAP.

I've been trying to update the [notebook](https://colab.research.google.com/drive/14QQU5QUnPSvsZkZTgmKW6EUuHZeYQoxN?usp=sharing) by myself based on the previous, but it doesn't work. I'll really appreciate your help

**Comment by Nicolaing** [comment]
> > Hi @Nicolaing and @erennaltunn, you're right. We will update the `MMRotate_Tutorial.ipynb` for the 1.x branch ASAP.
> 
> I've been trying to update the [notebook](https://colab.research.google.com/drive/14QQU5QUnPSvsZkZTgmKW6EUuHZeYQoxN?usp=sharing) by myself based on the previous, but it doesn't work. I'll really appreciate your help

You have to change the bbox_nms_rotated.txt with:
[bbox_nms_rotated (1).txt](https://github.com/open-mmlab/mmrotate/files/11364208/bbox_nms_rotated.1.txt)

**I have installed mmcv as followed:**
# Install MMCV and MMDetection using MIM.
!pip3 install -U openmim
!mim install mmcv
!mim install mmdet

# Install MMRotate from the source.
!git clone https://github.com/open-mmlab/mmrotate.git

**Change the bbox_nms_rotated.txt before you install:**
%cd mmrotate
!pip install -e .

**Then you can see if you it works by:**
from mmcv import collect_env
collect_env()

# Check MMRotate installation
import mmrotate
print(mmrotate.__version__)

# Check MMDetection installation
import mmdet
print(mmdet.__version__)

# Check mmcv installation
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())

**Comment by Nicolaing** [comment]
> Hi, thank you for consideration. May I ask how long do you think it will take approximately? I am willing to use it for a project.

It took my about 50-60 min to install all the things in Google colab. But in colab it do not save your work, so you have to run all the installations again if you are not doing it on your own pc.
