### ISSUE TITLE
 how to convert inferred results to DOTA format

### ISSUE THREAD

**Issue by jsxyhelu** [open-mmlab/mmrotate#827]
From the demo i know show_result_pyplot can plot the inferred results, I would like to ask how to convert inferred results to DOTA format, is there a related function? Or do you need to handle the result directly?
thanks!

show_result_pyplot能够绘制出推断的结果，想请教一下如何将这里推断的结果转换为dota的格式，有相关的函数吗？还是需要直接对result进行处理？
感谢！

**Comment by zytx121** [comment]
Hi @jsxyhelu, we did not provide the corresponding script to the user. You need to convert the results to DOTA format by yourself. Welcome to submit your script to help more people.

**Comment by jsxyhelu** [comment]
get it.

**Comment by jsxyhelu** [comment]
[如何将MMrotate的识别结果转换为dota和fair1m格式](https://www.cnblogs.com/jsxyhelu/p/17366114.html)
