### ISSUE TITLE
SASM训练过程出现的问题

### ISSUE THREAD

**Issue by lalalagogogochong** [open-mmlab/mmrotate#83]
为什么input和target维度不一样呢，然后会报这个错误assert input.size(0) == target.size(0)  AssertionError
![image](https://user-images.githubusercontent.com/44855506/157199702-14938553-8d1c-4129-b357-db04652e4545.png)
![image](https://user-images.githubusercontent.com/44855506/157199776-16eab82b-724e-4b91-b45f-f0acb9bc92c1.png)

**Comment by zytx121** [comment]
Hi @lalalagogogochong 
We will check it, could you use the issue template to provide more information?

**Comment by lalalagogogochong** [comment]
> Hi @lalalagogogochong We will check it, could you use the issue template to provide more information?

使用SASM训练自己的数据集需要修改哪些地方呢，我修改了配置文件中的类别，数据集路径。数据是按照DOTA的数据格式整理的，然后训练的时候会出现这个维度报错的问题

**Comment by yangxue0827** [comment]
same as issue https://github.com/open-mmlab/mmrotate/issues/94
