### ISSUE TITLE
train mydataset,  labeltxt looks like this, acc is always 100

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmrotate#84]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
![image](https://user-images.githubusercontent.com/59427046/157201283-b123a07d-579e-46d8-a291-4846bad4e17e.png)

**Comment by happy20200** [comment]
![image](https://user-images.githubusercontent.com/59427046/157201381-3deb5210-ce3d-4a7c-947a-735692f4940e.png)

**Comment by yangxue0827** [comment]
Is the final performance and visualization normal?

**Comment by happy20200** [comment]
> Is the final performance and visualization normal?
no，there is nothing

**Comment by yangxue0827** [comment]
I speculate that the training failed, and the 100% accuracy may be caused by the background that is all easy to classify. You may need to adjust parameters.

**Comment by happy20200** [comment]
> Please check whether CLASSES is changed to text, just like this:
> 
> https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/mmrotate/datasets/sar.py#L6-L9
> 
> Maybe you need to create a new dataset, or just modify `mmrotate/datasets/sar.py`

thanks~, i have change the sar.py like this, but there is still a mistake, what  should i do

**Comment by happy20200** [comment]
![image](https://user-images.githubusercontent.com/59427046/157353489-2e0e2cc9-ad72-422b-8a91-185c2094cb66.png)

**Comment by happy20200** [comment]
![image](https://user-images.githubusercontent.com/59427046/157353547-22186465-06c2-439a-bf18-a2f5561bf80c.png)

**Comment by liuyanyi** [comment]
maybe you should add a comma like `CLASSES = ('text', )`
