### ISSUE TITLE
When does mmrotate support mmcv>=2.00rc1 and mmdet>=3.0.0?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmrotate#843]
### What's the feature?

Hello, dear authors!
Thank you for your amazing job!
I want to unify the environment of mmdet, mmyolo and mmrotate. When I "pip/conda" them, I found mmdet and mmyolo have supported mmcv>=2.00rc1 and mmdet>=3.0.0 already, but mmrotate still supports the old version (mmcv-full and mmdet<3.0.0). 
When I ignored these gaps of mmrotate and mmdet/mmyolo and continued to install mmrotate (after installing mmcv2.0.0rc4 and mmdet3.0.0), I found mmrotate would rollback mmcv2.0.0rc4 to mmcv-full and rollback mmdet3.0.0 to mmdet2.xx.xx, which made the installation of mmdet3.0.0 for nothing. Moreover, without mmrotate, mmyolo will install mmrotate automatically and this thing will happen again...
It seemly like a trouble to unify their environment.
How do I fix it? Or when does mmrotate support mmcv>=2.00rc1 and mmdet>=3.0.0?
Thank you!

### Any other context?

Anconda 2023+CUDA11.3+CUDNN8.2.1+PyTorch1.12.0

**Comment by liuyanyi** [comment]
Please check the [1.x](https://github.com/open-mmlab/mmrotate/tree/1.x) or [dev-1.x](https://github.com/open-mmlab/mmrotate/tree/dev-1.x) branch.

**Comment by zhongqiu1245** [comment]
Thx！
