### ISSUE TITLE
可以出一些参数说明的文档么，配置文件里面许多参数意义不是很了解

### ISSUE THREAD

**Issue by lalalagogogochong** [open-mmlab/mmrotate#85]

**Comment by zytx121** [comment]
Good suggestion, we will add these doc. BTW, You could check the meaning of these parameters in the class or function definition. Each class or function has a docstring.
https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/mmrotate/core/bbox/coder/delta_xywha_rbbox_coder.py#L18-L34
