### ISSUE TITLE
[Docs] Wrong link in the Gliding Vertex README.md

### ISSUE THREAD

**Issue by vavanade** [open-mmlab/mmrotate#853]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

The first link here
[https://github.com/open-mmlab/mmrotate/tree/1.x/configs/gliding_vertex#results-and-models](https://github.com/open-mmlab/mmrotate/tree/1.x/configs/gliding_vertex#results-and-models)

is to [rotated-faster-rcnn-le90_r50_fpn_1x_dota](https://github.com/open-mmlab/mmrotate/blob/1.x/configs/rotated_faster_rcnn/rotated-faster-rcnn-le90_r50_fpn_1x_dota.py), not Gliding Vertex config.

**Comment by yangxue0827** [comment]
The first row in table is the baseline of Gliding Vertex, i.e. rotated-faster-rcnn.
