### ISSUE TITLE
[Docs] Changing classes names of a dataset on 1.x version does not work the way it is mentioned in the Customize dataset tutorial

### ISSUE THREAD

**Issue by vavanade** [open-mmlab/mmrotate#862]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

Changing class names in an existing dataset according to [this tutorial](https://github.com/open-mmlab/mmrotate/blob/main/docs/en/tutorials/customize_dataset.md) does not work in the `1.x` versions.

I created a pull request to fix that.

### Suggest a potential alternative/fix

[https://github.com/open-mmlab/mmrotate/pull/861](https://github.com/open-mmlab/mmrotate/pull/861)

**Comment by JielinYang** [comment]
I met the same problem. There isn't any tutorial about mmrotate 1.0. When I try to install, there always has the version incompatibility between mmcv, mmdet and mmengine.
