### ISSUE TITLE
类别识别准确度不高

### ISSUE THREAD

**Issue by yuki0707-new** [open-mmlab/mmrotate#87]
这个怎么设置自己的classes,总共可以预测多少类别。为什么我训练出来的，框的对象全部正确，但是类别都是乱的。

**Comment by zytx121** [comment]
This may be caused by a bug. You could fix it refer to this PR #81

**Comment by yuki0707-new** [comment]
@yangxue0827 @yangxue0827 非常感谢你们的回答。
 问题得到了解决
