### ISSUE TITLE
About gliding vertex

### ISSUE THREAD

**Issue by ga546** [open-mmlab/mmrotate#88]
论文中的gliding vertex 似乎可以实现任意四边形的检测，而mmrotate中的gliding vertex算法只能检测规则的矩形框吗

**Comment by yangxue0827** [comment]
这里的gliding vertex 也是四边形的，有可能是在可视化或者输出前将四边形转换成了对应的旋转矩形，你可以注释这一操作。 @ga546 @zytx121

**Comment by zytx121** [comment]
Hi @ga546 
You are right, the input and output of all MMRotate detectors are OBBs, so the Gliding Vertex we reproduce is not the real  Gliding Vertex. However, we are considering adding the pipeline of quadrilateral bounding boxes (QBBs).

**Comment by ga546** [comment]
@zytx121 @yangxue0827  thanks for your answers ! I get it

**Comment by yangxue0827** [comment]
目前mmrotate输入是obb的形式，在搭建Gliding Vertex时将obb转成qbb进行操作，Gliding Vertex的最后解码输出是qbb但是我们最后[转成了obb输出](https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/mmrotate/core/bbox/coder/gliding_vertex_coder.py#L93)。
其实输入是qbb会更合理，yangxue0827/RotationDetection就是这样，但是可能会影响速度，后续我们会考虑这个问题，感谢反馈。

**Comment by ga546** [comment]
@yangxue0827 
您好，我还有一个疑问。我输入的数据集标注是8参数形式的，但是其实他的形状并非规则矩形，那输入mmrotate时是如何将它转换成obb形式的呢？这样会实际上带来较大误差对吗？

**Comment by yangxue0827** [comment]
qbb转obb是取最小外接矩形，opencv有相应的函数。当目标非常不规则的时候，这种转换是会有较大误差的。
