### ISSUE TITLE
about test.py

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmrotate#90]
Does the test dataset also need the label file? If I only want to crop out the positioned text, how do I get the positioned coordinates?
![image](https://user-images.githubusercontent.com/59427046/157385991-202406cf-5c11-4085-aadf-78a115d56403.png)

**Comment by yangxue0827** [comment]
No annotation files are required. The model will output predicted coordinates, which you can use for clipping operations.
Also, isn't the purple bounding box in the image drawn by the model's predictions?

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/blob/main/demo/image_demo.py#L35

**Comment by happy20200** [comment]
the purple bounding box in the image is drawn by the model's predictions.  but where can I find this coordinate? image_demo.py is for single picture?

**Comment by yangxue0827** [comment]
`result` in https://github.com/open-mmlab/mmrotate/blob/main/demo/image_demo.py#L35
You can take it to operate according to your own needs.

**Comment by happy20200** [comment]
你好，我在image_demo.py上测试过了，但是有两个参数不是很明白它们的含义，就是下面红线标出来的这两个，另外为什么测试出来的框明明不是很准，但绿色的这个都是1啊
![image](https://user-images.githubusercontent.com/59427046/157437690-6695b48f-7fb6-45b3-ae5d-5e2f401c7c7e.png)
![image](https://user-images.githubusercontent.com/59427046/157437756-2096c918-9a8d-4c5b-9b21-2e7f0ddd22aa.png)

**Comment by yangxue0827** [comment]
脚本都有参数介绍的，demo.jpg是测试的图片，vis.jpg是测试完保存的图片。
分数是分类的置信度，表示是text类别的概率是100%，但不代表框是准的。你这个不准的问题明显是由文字中间截断造成的，

**Comment by happy20200** [comment]
哦，明白了，不过这个文字中间有截断有什么改进方法吗

**Comment by yangxue0827** [comment]
这个你就得看相关文字检测的研究了。

**Comment by happy20200** [comment]
哦，明白了，不过这个文字中间有截断有什么改进方法吗
