### ISSUE TITLE
[bug] when i try to pr, get ci error, mmcv has no member `__version__`

### ISSUE THREAD

**Issue by CSberlin** [open-mmlab/mmrotate#901]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.7.0
MMEngine: 0.7.4
MMRotate: 1.0.0rc1+25204ec

- Install pytorch : conda install pytorch==1.8.0 torchvision==0.9.0 cudatoolkit=10.2 -c pytorch -y
- Install mmcv : mim install "mmcv>=2.0.0rc2"
- Install mmdet: mim install 'mmdet>=3.0.0rc2'
- other: cd mmrotate&&pip install -v -e . ; mim install mmengine

### Reproduces the problem - code sample

```python
import mmcv
# Check mmcv installation
print(mmcv.__version__) # noqa E1101
```

when i use nbqa pylint tutorial.ipy in shell, i got mmcv has no member `__version__`

### Reproduces the problem - command or script

```python
import mmcv
# Check mmcv installation
print(mmcv.__version__) # noqa E1101
```

```shell
nbqa pylint tutorial.ipy
```

### Reproduces the problem - error message

```
E1101: Module 'mmcv' has no 'version'member  (no-member)
```

### Additional information

[pr link]https://github.com/open-mmlab/mmrotate/pull/899
maybe in ci, the error is not cause by this problem, i'm not quite sure...

**Comment by zytx121** [comment]
Hi @CSberlin, CI error is not caused by this problem. It was caused by you modifying the version in [.pre-commit-config-zh-cn.yaml](https://github.com/open-mmlab/mmrotate/pull/899/files#diff-0adf65b22f6072134cc05b74fe21183471d76acc75dd3f3bf801ead750df659d).

Are these modifications necessary? What problems will occur if not modified?

**Comment by CSberlin** [comment]
> Hi @CSberlin, CI error is not caused by this problem. It was caused by you modifying the version in [.pre-commit-config-zh-cn.yaml](https://github.com/open-mmlab/mmrotate/pull/899/files#diff-0adf65b22f6072134cc05b74fe21183471d76acc75dd3f3bf801ead750df659d).
> 
> Please check： Are these modifications necessary? What problems will occur if not modified?

i got the problem when i not modify the isort version in .yaml file, and mmyolo is not adapt for mmrotate in yaml...
in wechat group king member answer me that from the result of ci, is the md format promblem... but i not modify md config in yaml, and i can't get md error information using `nbqa pylint xxx` in my shell

**Comment by CSberlin** [comment]
finish, find that is pre-commit cause a md file , not commit to github, cause the problem.
