### ISSUE TITLE
[Bug] install error

### ISSUE THREAD

**Issue by lina926** [open-mmlab/mmrotate#906]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

collect_env.py  ：ModuleNotFoundError: No module named 'mmcv._ext'
cuda 11.6
torch 1.13.1
python 3.10
mmdet 2.28.2
mmcv-full 1.7.1
mmcv 1.7.1

### Reproduces the problem - code sample

  python .\tools\train.py .\configs\redet\redet_re50_refpn_1x_dota_le90.py --work-dir results/

### Reproduces the problem - command or script

  python .\tools\train.py .\configs\redet\redet_re50_refpn_1x_dota_le90.py --work-dir results/

### Reproduces the problem - error message

ImportError: cannot import name 'print_log' from 'mmcv' (C:\anaconda3\envs\mmrotate\lib\site-packages\mmcv\__init__.py)

### Additional information

I think it should be the version issue, can you tell me what version about mmdet and mmcv I should install for 4070, cu11.6?

**Comment by Zzzxi** [comment]
Hello, I also encountered this situation, how did you solve it?
