### ISSUE TITLE
KeyError: "RotatedFasterRCNN: 'FPN_v1 is not in the models registry'"

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#92]
windows系统
在init里初始化，在necks里添加这个FPN_v1，并且在RotatedFasterRCNN的neck=dict(type=FPN_v1)
为什么还会报错

**Comment by zytx121** [comment]
Could you provide your file?

**Comment by houw0517** [comment]
I can't upload a Python file

**Comment by houw0517** [comment]
Can we communicate with the mailbox ？

**Comment by zytx121** [comment]
Sure, sjtu_zy@sjtu.edu.com

**Comment by houw0517** [comment]
Mail has been bounced. I also choose to send it online
[fpn.txt](https://github.com/open-mmlab/mmrotate/files/8219878/fpn.txt)

**Comment by zytx121** [comment]
Because you use @NECKS. In MMRotate we use @ROTATED_NECKS

**Comment by houw0517** [comment]
After I change  @necks into @ROTATED_NECKS. It also appear error

**Comment by zytx121** [comment]
Could you provide your file after modified?

**Comment by houw0517** [comment]
[fpn.txt](https://github.com/open-mmlab/mmrotate/files/8242513/fpn.txt)

**Comment by houw0517** [comment]
On windows systems，add a new component is not used. I think the reason is that compile command cannot be performed successfully.  There is also a phenomenon when I comment out the original component in the initialization file ，such as GDLoss，procedure can perform properly. Could you explain the reasons for it？

**Comment by zytx121** [comment]
It looks like the MMRotate you use is not the MMRotate you installed. Please check it.

**Comment by zytx121** [comment]
> On windows systems，add a new component is not used. I think the reason is that compile command cannot be performed successfully. There is also a phenomenon when I comment out the original component in the initialization file ，such as GDLoss，procedure can perform properly. Could you explain the reasons for it？

When you comment out the original component in the initialization file, the procedure should perform properly. We think this is right.

**Comment by houw0517** [comment]
After I change @NECKS to @ROTATED_NECKS，it  is still an error “'FPN_v1 is not in the models registry'”

**Comment by zytx121** [comment]
Could you provide your file after modified?
