### ISSUE TITLE
按照官方教程转换Torchserve模型时报错：AttributeError: 'Namespace' object has no attribute 'config_file' [Bug] 

### ISSUE THREAD

**Issue by Gaofan666** [open-mmlab/mmrotate#932]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

sys.platform: linux
Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1650
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 1.8.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1+cu101
OpenCV: 4.8.0
MMCV: 1.7.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMRotate: 0.3.4+

### Reproduces the problem - code sample

python tools/deployment/mmrotate2torchserve.py configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py checkpoint/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth \
--output-folder /home/hhh/myprojects/mmrotate/model_store \
--model-name rotated_faster_rcnn

### Reproduces the problem - command or script

python tools/deployment/mmrotate2torchserve.py configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py checkpoint/rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth \
--output-folder /home/hhh/myprojects/mmrotate/model_store \
--model-name rotated_faster_rcnn

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/deployment/mmrotate2torchserve.py", line 109, in <module>
    mmrotate2torchserve(args.config, args.checkpoint, args.output_folder,
  File "tools/deployment/mmrotate2torchserve.py", line 66, in mmrotate2torchserve
    manifest = ModelExportUtils.generate_manifest_json(args)
  File "/home/hhh/anaconda3/envs/openmmlab/lib/python3.8/site-packages/model_archiver/model_packaging_utils.py", line 129, in generate_manifest_json
    model = ModelExportUtils.generate_model(args)
  File "/home/hhh/anaconda3/envs/openmmlab/lib/python3.8/site-packages/model_archiver/model_packaging_utils.py", line 117, in generate_model
    config_file=modelargs.config_file,
AttributeError: 'Namespace' object has no attribute 'config_file'

**Comment by pacificlion** [comment]
It is compatibility issue starting with pytorch serve 0.80 -[link](https://github.com/pytorch/serve/blob/2f1f52f553e83703b5c380c2570a36708ee5cafa/docs/configuration.md?plain=1#L267). You can use 0.7.1 like below or create a config yaml as per new docs and also include attribute in tools\deployment\mmrotate2torchserve.py
```
conda unistall torchserve torch-model-archiver
conda config --add channels pytorch
conda install torchserve=0.7.1 torch-model-archiver=0.7.1

```

**Comment by Gaofan666** [comment]
> It is compatibility issue starting with pytorch serve 0.80 -[link](https://github.com/pytorch/serve/blob/2f1f52f553e83703b5c380c2570a36708ee5cafa/docs/configuration.md?plain=1#L267). You can use 0.7.1 like below or create a config yaml as per new docs and also include attribute in tools\deployment\mmrotate2torchserve.py
> 
> ```
> conda unistall torchserve torch-model-archiver
> conda config --add channels pytorch
> conda install torchserve=0.7.1 torch-model-archiver=0.7.1
> ```

thank you very much!
