### ISSUE TITLE
Installation on Google Colab

### ISSUE THREAD

**Issue by shinnakayama** [open-mmlab/mmrotate#934]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

Hi, 

I followed the official documentation of installing mmrotate on Google Colab:
```
!pip3 install -U openmim
!mim install mmcv-full
!mim install mmdet
```
, which took about 35 minutes. Then
```
!git clone https://github.com/open-mmlab/mmrotate.git
%cd mmrotate
!pip install -e .
```
But I get an error when I run `import mmrotate`:

> AssertionError: MMCV==2.0.1 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.

Any solutions? I would really like to use mmrotate on Google Colab. Torch 2.0.1+cu118 on Python 3.10.12

### Reproduces the problem - code sample

```
!pip3 install -U openmim
!mim install mmcv-full
!mim install mmdet
!git clone https://github.com/open-mmlab/mmrotate.git
%cd mmrotate
!pip install -e .
import mmrotate
```

### Reproduces the problem - command or script

```
!pip3 install -U openmim
!mim install mmcv-full
!mim install mmdet
!git clone https://github.com/open-mmlab/mmrotate.git
%cd mmrotate
!pip install -e .
import mmrotate
```

### Reproduces the problem - error message

AssertionError                            Traceback (most recent call last)
[<ipython-input-14-3f3ffa800e61>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import mmrotate

1 frames
[/content/mmrotate/mmrotate/__init__.py](https://localhost:8080/#) in <module>
      1 # Copyright (c) OpenMMLab. All rights reserved.
      2 import mmcv
----> 3 import mmdet
      4 
      5 from .core import *  # noqa: F401, F403

[/usr/local/lib/python3.10/dist-packages/mmdet/__init__.py](https://localhost:8080/#) in <module>
     23 
     24 assert (mmcv_version >= digit_version(mmcv_minimum_version)
---> 25         and mmcv_version <= digit_version(mmcv_maximum_version)), \
     26     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     27     f'Please install mmcv>={mmcv_minimum_version}, <={mmcv_maximum_version}.'

AssertionError: MMCV==2.0.1 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.

**Comment by corydambach** [comment]
I am also running into this
