### ISSUE TITLE
[Bug] Problems encountered during program operation

### ISSUE THREAD

**Issue by milamiqi** [open-mmlab/mmrotate#938]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

TorchVision: 0.11.1+cu113
OpenCV: 4.5.4
MMCV: 1.7.1
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: 11.3
MMRotate: 0.3.4+9ea1aee

### Reproduces the problem - code sample

# the new config inherits the base configs to highlight the necessary modification
_base_ = './s2anet_r50_fpn_1x_dota_le135.py'

# 1. dataset settings
dataset_type = 'DOTADataset'
classes = ('plane', 'ship', 'storage-tank', 'baseball-diamond', 'tennis-court',
           'basketball-court', 'ground-track-field', 'harbor', 'bridge', 'small-vehicle',
           'large-vehicle', 'helicopter', 'roundabout', 'soccer-ball-field', 'swimming-pool', 'container-crane')

data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='C:\D\APP\PyCharm\pythonProject\mmrotate-main\datasets\dota/trainsplit/annfiles',
        img_prefix='C:\D\APP\PyCharm\pythonProject\mmrotate-main\datasets\dota/trainsplit\images'),
    val=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='C:\D\APP\PyCharm\pythonProject\mmrotate-main\datasets\dota/valsplit/annfiles',
        img_prefix='C:\D\APP\PyCharm\pythonProject\mmrotate-main\datasets\dota/valsplit\images'),
    test=dict(
        type=dataset_type,
        # explicitly add your class names to the field `classes`
        classes=classes,
        ann_file='C:\D\APP\PyCharm\pythonProject\mmrotate-main\datasets\dota/test\images',
        img_prefix='C:\D\APP\PyCharm\pythonProject\mmrotate-main\datasets\dota/test\images'))

### Reproduces the problem - command or script

python tools/test.py C:\D\APP\PyCharm\pythonProject\mmrotate\configs\s2anet\s2anet_r50_fpn_1x_dota_le135.py

### Reproduces the problem - error message

PS C:\D\APP\PyCharm\pythonProject\mmrotate>  python tools/test.py C:\D\APP\PyCharm\pythonProject\mmrotate\configs\s2anet\costom_s2anet.py
 process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/do
cs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "tools/test.py", line 19, in <module>
    from mmrotate.utils import (build_ddp, build_dp, compat_cfg, get_device,
ImportError: cannot import name 'build_ddp' from 'mmrotate.utils' (C:\D\APP\anaconda\envs\PyTorch\lib\site-packages\mmrotate\utils\__init__.py)
PS C:\D\APP\PyCharm\pythonProject\mmrotate> python tools/test.py C:\D\APP\PyCharm\pythonProject\mmrotate\configs\s2anet\s2anet_r50_fpn_1x_dota_le135.py
C:\D\APP\anaconda\envs\PyTorch\lib\site-packages\mmcv\__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training
 process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/do
cs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "tools/test.py", line 19, in <module>
    from mmrotate.utils import (build_ddp, build_dp, compat_cfg, get_device,
ImportError: cannot import name 'build_ddp' from 'mmrotate.utils' (C:\D\APP\anaconda\envs\PyTorch\lib\site-packages\mmrotate\utils\__init__.py)

**Comment by ldjsvater** [comment]
l've got the same problrm. It's the key that wo need to find a new version of 3 functions (build_ddp, build_dp, get_device).

**Comment by puffcarol** [comment]
> l've got the same problrm. It's the key that wo need to find a new version of 3 functions (build_ddp, build_dp, get_device).

how to find them？

**Comment by WangSuhang123** [comment]
> > l've got the same problrm. It's the key that wo need to find a new version of 3 functions (build_ddp, build_dp, get_device).
> 
> how to find them？

I solved this problem
Specific solution steps:
1.Uninstall the currently installed mmrotate package (if installed via pip):
`pip uninstall mmrotate`
2.Install the locally cloned mmrotate source code (make sure the code is consistent with the installed package version):
Execute in the mmrotate-main directory:
`pip install -e . # Install local source code in editable mode to ensure that code modifications take effect in real time`
3.Re-run the training command:


It is likely that you cloned the mmrotate source code (mmrotate-main directory) from GitHub, but the actual installed mmrotate package is an older version (or mismatched version) installed through pip. As a result, tools/train.py in the source code calls the get_device function that is only available in the newer version, but the installed package does not have this function.
