### ISSUE TITLE
请问SASM的训练流程和KFIOU这些训练流程都是一样的吗，需要额外改哪些参数吗

### ISSUE THREAD

**Issue by lalalagogogochong** [open-mmlab/mmrotate#94]
同样的数据集数据格式，用KFIOU训练可以，但是用SASM训练一直不成功

**Comment by yangxue0827** [comment]
是一样的，可能存在bug，还在调试，你可以试一下源码[houliping/SASM](https://github.com/houliping/SASM)

**Comment by yangxue0827** [comment]
如果发现bug，欢迎提PR，谢谢！

**Comment by lalalagogogochong** [comment]
> 如果发现bug，欢迎提PR，谢谢！

好的，我再调试调试看一下，谢谢了

**Comment by lalalagogogochong** [comment]
> 如果发现bug，欢迎提PR，谢谢！

你好，我发现两个地方有点问题，然后修改之后现在可以训练了，怎么提个PR呢，有个参数是给固定成4了，应该是batchsize，修改之后tensor维度就没问题了

**Comment by yangxue0827** [comment]
solution: https://github.com/open-mmlab/mmrotate/pull/100
