### ISSUE TITLE
[Docs] RuntimeError: RuntimeError"index_reduce_func_cuda_exclude_input_init" not implemented for 'Long': 

### ISSUE THREAD

**Issue by clin-fu** [open-mmlab/mmrotate#941]
### Branch

1.x branch https://mmrotate.readthedocs.io/en/1.x/

### 📚 The doc issue

when i run h2rboxv2 
RuntimeError: RuntimeError"index_reduce_func_cuda_exclude_input_init" not implemented for 'Long': 
"index_reduce_func_cuda_exclude_input_init" not implemented for 'Long'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 78423) of binary: /home/fuchenlin/anaconda3/envs/mmr1x/bin/python
Traceback (most recent call last):

How can i fix it??

**Comment by yangxue0827** [comment]
Integer index_reduce is not supported before torch version 1.13.

https://github.com/pytorch/pytorch/commit/f668b7ecb02d881e9585ff2276f7c4f54a323e7d

**Comment by yangxue0827** [comment]
![image](https://github.com/open-mmlab/mmrotate/assets/29257168/716b8c34-ab21-470a-b1f8-1be6fb14bfb5)
