### ISSUE TITLE
how to convert rolabelImg format to trainning format 

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmrotate#95]
I want to use roLabelImg for annotations,it is xml format,xml file contain cx,cy,width,heights,angle.so how convert xml to trainning format,like dota format

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/core/bbox/transforms.py#L116 may help you.

**Comment by zytx121** [comment]
https://github.com/ming71/toolbox/blob/master/converter/toDOTA/HRSC2016/HRSC2DOTA.py  may help you.
