### ISSUE TITLE
[Bug] h2rboxV2一些代码只适用于torch2.x以上版本，希望适配一下

### ISSUE THREAD

**Issue by qqq1521902442** [open-mmlab/mmrotate#951]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

System environment:
    sys.platform: linux
    Python: 3.9.16 (main, Jan 11 2023, 16:05:54) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 809818192
    GPU 0: GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.0, V11.0.221
    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    PyTorch: 1.8.0
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.9.0
    OpenCV: 4.7.0
    MMEngine: 0.6.0

### Reproduces the problem - code sample

bid, idx = torch.unique(pos_bid_targets, return_inverse=True)
             compacted_bid_targets = torch.empty_like(bid).index_reduce_(
                0, idx, pos_bid_targets, 'mean', include_self=False)
              

以及torch.pi

### Reproduces the problem - command or script

CUDA_VISIBLE_DEVICES=2 PORT=29505 tools/dist_train.sh configs/h2rbox_v2/h2rbox_v2-le90_r50_fpn-1x_dv2_ss_cedg.py 1 --cfg-options randomness.seed=809818192 --work-dir work_dirs/h2rboxV2_cedg

### Reproduces the problem - error message

mmrotate-1.x/mmrotate/models/dense_heads/h2rbox_v2_head.py", line 320, in loss_by_feat
    compacted_bid_targets = torch.empty_like(bid).index_reduce_(
AttributeError: 'Tensor' object has no attribute 'index_reduce_'

**Comment by qqq1521902442** [comment]
补充一下，mmrotate1.x的install似乎依然是1.x版本的torch支持，自行适配2.x版本的torch后会出现错误
`/data/czl/anaconda3/envs/new_mmrotate/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions
 File "/data/czl/anaconda3/envs/new_mmrotate/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
[2023-10-11 10:45:48,804] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 799382) of binary: /data/czl/anaconda3/en
vs/new_mmrotate/bin/python
  File "/data/czl/anaconda3/envs/new_mmrotate/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/czl/anaconda3/envs/new_mmrotate/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-11_10:45:48
  host      : amax
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 799382)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`
不知道是哪些环境需要一起做升级适配

**Comment by zhu011** [comment]
请问您的问题AttributeError: 'Tensor' object has no attribute 'index_reduce_'是如何解决的

**Comment by 2597883929** [comment]
请问您有没有遇到“RuntimeError: expected scalar type Long but found Float ”的问题，是怎么解决的？

**Comment by guoxxxxxxx** [comment]
请问一下，最后如何解决的？我也遇到了这个问题

**Comment by qqq1521902442** [comment]
最后更新为1.11还是啥版本，然后就解决了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月23日 09:03 |
| 收件人 | open-mmlab/mmrotate ***@***.***> |
| 抄送人 | qqq1521902442 ***@***.***>,
State ***@***.***> |
| 主题 | Re: [open-mmlab/mmrotate] [Bug] h2rboxV2一些代码只适用于torch2.x以上版本，希望适配一下 (Issue #951) |

请问一下，最后如何解决的？我也遇到了这个问题

**Comment by yangxue0827** [comment]
pytorch≥1.13

**Comment by Petros626** [comment]
@yangxue0827 Hey, is `mmrotate` compatible with PyTorch  2 or only PyTorch 1?

**Comment by Petros626** [comment]
@qqq1521902442 could you tell me how to train the rotated segmentation models (H2RBoxv2, SAMRBox) with `mmrotate`. Would be an imense help :)
