### ISSUE TITLE
About the sequence of 4 points of the polygon in the detection results.

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmrotate#97]
请问检测到的四个点坐标顺序是什么
     p1 = (xc - wx - hx, yc - wy - hy)
        p2 = (xc + wx - hx, yc + wy - hy)
        p3 = (xc + wx + hx, yc + wy + hy)
        p4 = (xc - wx + hx, yc - wy + hy)
        ps = np.int0(np.array([p1, p2, p3, p4]))

**Comment by zytx121** [comment]
Which file does this code come from? We need more information.

**Comment by happy20200** [comment]
![image](https://user-images.githubusercontent.com/59427046/157780206-8cdee117-06bb-48dd-9c70-9ca261700cb2.png)

**Comment by zytx121** [comment]
Please refer to
https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/mmrotate/core/bbox/transforms.py#L780
