### ISSUE TITLE
Does mmrotate support the detection of general quadrilateral objects？

### ISSUE THREAD

**Issue by daigang896** [open-mmlab/mmrotate#99]
Hello.
Does mmrotate support the detection of general quadrilateral objects? For example, four vertices of an arbitrary quadrilateral object?

**Comment by yangxue0827** [comment]
refer to https://github.com/open-mmlab/mmrotate/issues/88

**Comment by daigang896** [comment]
Thank you. Due to the need to deal with general quadrilateral. It may be more accurate to use gliding vertex directly without converting it into a rotating rectangle.

**Comment by yangxue0827** [comment]
You may need to make some modifications based on this repo, or you can use the official gliding vertex or RSDet from yangxue0827/RotationDetection.

**Comment by daigang896** [comment]
Okay, thank you.
