### ISSUE TITLE
[Bug] How to infer the trained model on the DOTA-1.0 dataset using the MMrotate dev1.x branch, and generate a compressed file for online submission?

### ISSUE THREAD

**Issue by fadaishaitaiyang** [open-mmlab/mmrotate#999]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmrotate/tree/1.x

### Environment

1.x

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

？

### Reproduces the problem - error message

？

**Comment by Atlantisming** [comment]
https://github.com/open-mmlab/mmrotate/blob/1.x/configs/_base_/datasets/dota.py
```
# inference on test dataset and format the output results
# for submission. Note: the test set has no annotation.
# test_dataloader = dict(
#     batch_size=1,
#     num_workers=2,
#     persistent_workers=True,
#     drop_last=False,
#     sampler=dict(type='DefaultSampler', shuffle=False),
#     dataset=dict(
#         type=dataset_type,
#         data_root=data_root,
#         data_prefix=dict(img_path='test/images/'),
#         test_mode=True,
#         pipeline=test_pipeline))
# test_evaluator = dict(
#     type='DOTAMetric',
#     format_only=True,
#     merge_patches=True,
#     outfile_prefix='./work_dirs/dota/Task1')
```

**Comment by fadaishaitaiyang** [comment]
thank you
